TemplateSynth Class Reference
Implements a template-based synthesis using a QBF solver.
#include <TemplateSynth.h>
Public Member Functions
TemplateSynth (CNFImplExtractor *impl_extractor)
Constructor.
virtual ~TemplateSynth ()
Destructor.
virtual bool run ()
Executes this back-end.
Protected Member Functions
bool computeWinningRegion ()
Computes the winning region as instantiation of a generic template.
bool computeWinningRegionCNF ()
Computes the winning region as instantiation of a CNF template.
bool computeWinningRegionAndNet ()
Computes the winning region as instantiation of a network of AND-Gates.
bool findWinRegCNFTempl (size_t nr_of_clauses)
Computes the winning region as instantiation of a generic CNF template.
bool findWinRegANDNetwork (size_t nr_of_gates)
Computes the winning region as instantiation of a generic AIGER template.
bool syntQBF (const CNF &win_constr, int w1, int w2, vector< int > &solution)
Resolves the template by calling a QBF solver.
bool syntSAT (const CNF &win_constr, int w1, int w2, vector< int > &solution)
Resolves the template by calling a SAT solver in a CEGIS loop.
void exclude (const vector< int > &ce, const CNF &gen)
A helper for the CEGIS loop of syntSAT(), eliminating a counterexample.
bool check (const vector< int > &cand, const CNF &win_constr, int w1, int w2, vector< int > &ce)
A helper for the CEGIS loop of syntSAT(), checking if a candidate solution works.
Protected Attributes
CNF winning_region_
The resulting winning region.
CNF neg_winning_region_
The negation of the resulting winning region.
QBFSolver * qbf_solver_
The QBF-solver to use for solving the queries.
SatSolver * sat_solver_
The SAT-solver to use if we resolve the template using the CEGIS loop.
CNFImplExtractor * impl_extractor_
The engine to use for circuit extraction.
Detailed Description
Implements a template-based synthesis using a QBF solver.
We are searching for a winning region W(x) such that:
I(x) => W(x): every initial state is contained in the winning region
W(x) => P(x): every state of the winning region is safe
forall x,i: exists c,x': W(x) => (T(x,i,c,x') & W(x')): from every state in the winning region we can enforce to stay in the winning region by setting the c-signals appropriately.
In this class, we encode the search for such a winning region symbolically. We define a template W(x,k) for the winning region. The variables k are template parameters. Their values define a concrete function W(x). Then we simply solve the query
   exists k: forall x,i: exists c,x': I(x) => W(x,k) & W(x,k) => P(x) & W(x,k) => (T(x,i,c,x') & W(x',k))
 with a single QBF-solver call. We ask the solver for a satisfying assignment to the variables k. These values define a concrete function W(x), which is our winning region. The difficult question is how to define a generic template W(x,k) for the winning region. At the moment, only two possibility is implemented:
defining W(x,k) as a parameterized CNF over the state variables x with parameters k.
defining W(x,k) as a parameterized AIGER graph over the state variables x with parameters k
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 73 of file TemplateSynth.h.
Constructor & Destructor Documentation
TemplateSynth::TemplateSynth (CNFImplExtractor * impl_extractor)
Constructor.
Parameters
impl_extractor The engine to use for circuit extraction. It will be deleted by this class.
Definition at line 44 of file TemplateSynth.cpp.
TemplateSynth::~TemplateSynth () [virtual]
Destructor.
Definition at line 54 of file TemplateSynth.cpp.
References impl_extractor_, qbf_solver_, and sat_solver_.
Member Function Documentation
bool TemplateSynth::check (const vector< int > & cand, const CNF & win_constr, int w1, int w2, vector< int > & ce) [protected]
A helper for the CEGIS loop of syntSAT(), checking if a candidate solution works.
Parameters
cand A canidate solution in the form of concrete values for the template parameters.
win_constr CNF constraints that constitute a correct solution for the winning region using the generic template. Essentially, three constraints are encoded in this CNF:
I(x) => W(x): every initial state is contained in the winning region
W(x) => P(x): every state of the winning region is safe
forall x,i: exists c,x': W(x) => (T(x,i,c,x') & W(x')): from every state in the winning region we can enforce to stay in the winning region by setting the c-signals appropriately.
w1 The literal that represents the present-state copy of the winning region in win_constr.
w2 The literal that represents the next-state copy of the winning region in win_constr.
ce An empty vector. If the candidate solution is incorrect, a counterexample in the form of concrete values for state and input variables for which we fall out of the winning region is stored in this vector.
Returns
True if the candidate solution is correct, False otherwise.
Definition at line 659 of file TemplateSynth.cpp.
References CNF::add1LitClause(), CNF::addCNF(), VarInfo::CTRL, Options::getSATSolver(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incIsSatModelOrCore(), VarInfo::INPUT, VarManager::instance(), Options::instance(), AIG2CNF::instance(), MASSERT, VarInfo::PRES_STATE, CNF::setVarValue(), and SatSolver::startIncrementalSession().
Referenced by syntSAT().
bool TemplateSynth::computeWinningRegion () [protected]
Computes the winning region as instantiation of a generic template.
This works as explained in the description of the class.
Returns
True if the specification was realizable, false otherwise.
Definition at line 93 of file TemplateSynth.cpp.
References computeWinningRegionAndNet(), computeWinningRegionCNF(), and Options::instance().
Referenced by run().
bool TemplateSynth::computeWinningRegionAndNet () [protected]
Computes the winning region as instantiation of a network of AND-Gates.
This works as explained in the description of the class using a AIGER graph template W(x,k) for the winning region W(x), where k are template parameters defining how the winning region really looks like. The AIGER template fixes a maximum number N of AND-gates. For the first AND-gate we have template parameters saying (a) which state variables x are an input for the AND gate, and (b) which state variables are connected in negated and unnegated form. The second AND gate is similar but has the output of the first AND gate as additional input. The third AND gate has the outputs of the previous two as inputs, and so on. One final template parameter defines whether or not the output of the last AND gate forms W(x) or the negation of W(x).
Returns
True if the specification was realizable, false otherwise.
Definition at line 132 of file TemplateSynth.cpp.
References findWinRegANDNetwork(), VarManager::getVarsOfType(), VarManager::instance(), L_INF, L_LOG, VarInfo::PRES_STATE, and VarManager::resetToLastPush().
Referenced by computeWinningRegion().
bool TemplateSynth::computeWinningRegionCNF () [protected]
Computes the winning region as instantiation of a CNF template.
This works as explained in the description of the class using a CNF template W(x,k) for the winning region W(x), where k are template parameters defining how the winning region really looks like. The CNF template fixes a maximum number N of clauses. It has three groups of parameters.
The parameters kc[i] (with 1 <= i <= N) define if clause i occurs in the CNF or not.
The parameters kv[i][j] (with 1 <= i <= N, 1 <= j <= |x|) define if state variable xj occurs in clause i or not.
The parameters kn[i][j] (with 1 <= i <= N, 1 <= j <= |x|) define if state variable xj occurs in clause i only negated or unnegated. If kv[i][j]=false, then kn[i][j] is irrelevant.
The union of all these parameters forms k. Concrete values for all k define a concrete CNF formula over the state variables x (i.e., a concrete winning region). We chose N in the following way: we start with N=1. On failure, we increase N (multiply by 4).
Returns
True if the specification was realizable, false otherwise.
Definition at line 102 of file TemplateSynth.cpp.
References findWinRegCNFTempl(), VarManager::getVarsOfType(), VarManager::instance(), L_INF, L_LOG, VarInfo::PRES_STATE, and VarManager::resetToLastPush().
Referenced by computeWinningRegion().
void TemplateSynth::exclude (const vector< int > & ce, const CNF & gen) [protected]
A helper for the CEGIS loop of syntSAT(), eliminating a counterexample.
Parameters
ce A counterexample that has been computed previously by calling check(). A counterexample is simply a set of values for state variables and input variables for which we fall out of the winning region.
gen The CNF containing the constraints for a correct winning region. We simply add constraints here saying that the winning region must now also work for the counterexample.
Definition at line 734 of file TemplateSynth.cpp.
References CNF::appendVarsTo(), VarManager::createFreshTmpVar(), VarManager::getInfo(), VarInfo::getKind(), SatSolver::incAddCNF(), VarManager::instance(), CNF::renameVars(), sat_solver_, CNF::setVarValue(), and VarInfo::TEMPL_PARAMS.
Referenced by syntSAT().
bool TemplateSynth::findWinRegANDNetwork (size_t nr_of_gates) [protected]
Computes the winning region as instantiation of a generic AIGER template.
This works as explained in the description of computeWinningRegionAndNet().
Parameters
nr_of_gates The number N of gates to use in the template. Choosing a good value for this parameter is difficult. If it is chosen to low, then we may not find a solution even if one exists. If it is chosen to high, then we waste computational resources.
Returns
True if a solution is found with the given number of clauses, false otherwise. If this method returns false, then this does not mean that the specification is unrealizable. It may be that nr_of_gates has been chosen too low.
Definition at line 335 of file TemplateSynth.cpp.
References CNF::add1LitClause(), CNF::add2LitClause(), CNF::add4LitClause(), CNF::addClause(), VarManager::createFreshTemplParam(), VarManager::createFreshTmpVar(), VarManager::getNextErrorStateVar(), VarManager::getPresErrorStateVar(), VarManager::getVarsOfType(), VarManager::instance(), Options::instance(), neg_winning_region_, Utils::negateLiterals(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, VarManager::resetToLastPush(), syntQBF(), syntSAT(), VarInfo::TEMPL_PARAMS, and winning_region_.
Referenced by computeWinningRegionAndNet().
bool TemplateSynth::findWinRegCNFTempl (size_t nr_of_clauses) [protected]
Computes the winning region as instantiation of a generic CNF template.
This works as explained in the description of computeWinningRegionCNF().
Parameters
nr_of_clauses The number N of clauses to use in the template. Choosing a good value for this parameter is difficult. If it is chosen to low, then we may not find a solution even if one exists. If it is chosen to high, then we waste computational resources.
Returns
True if a solution is found with the given number of clauses, false otherwise. If this method returns false, then this does not mean that the specification is unrealizable. It may be that nr_of_clauses has been chosen too low.
Definition at line 162 of file TemplateSynth.cpp.
References CNF::add1LitClause(), CNF::add2LitClause(), CNF::add4LitClause(), CNF::addClause(), VarManager::createFreshTemplParam(), VarManager::createFreshTmpVar(), VarManager::getMaxCNFVar(), VarManager::getNextErrorStateVar(), VarManager::getPresErrorStateVar(), VarManager::getVarsOfType(), VarManager::instance(), Options::instance(), neg_winning_region_, CNF::negate(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, VarManager::resetToLastPush(), syntQBF(), syntSAT(), and winning_region_.
Referenced by computeWinningRegionCNF().
bool TemplateSynth::run () [virtual]
Executes this back-end.
The back-end works as explained in the description of the class.
Returns
True if the specification was realizable, false otherwise.
Implements BackEnd.
Definition at line 67 of file TemplateSynth.cpp.
References computeWinningRegion(), Utils::debugCheckWinReg(), CNFImplExtractor::extractCircuit(), impl_extractor_, VarManager::instance(), Options::instance(), L_INF, L_RES, CNFImplExtractor::logStatistics(), neg_winning_region_, VarManager::push(), and winning_region_.
bool TemplateSynth::syntQBF (const CNF & win_constr, int w1, int w2, vector< int > & solution) [protected]
Resolves the template by calling a QBF solver.
Parameters
win_constr CNF constraints that constitute a correct solution for the winning region using the generic template. Essentially, three constraints are encoded in this CNF:
I(x) => W(x): every initial state is contained in the winning region
W(x) => P(x): every state of the winning region is safe
forall x,i: exists c,x': W(x) => (T(x,i,c,x') & W(x')): from every state in the winning region we can enforce to stay in the winning region by setting the c-signals appropriately.
w1 The literal that represents the present-state copy of the winning region in win_constr.
w2 The literal that represents the next-state copy of the winning region in win_constr.
solution An empty vector. If a solution exists, then the corresponding template parameter values are written into this vector.
Returns
True if a solution exists, false otherwise.
Definition at line 575 of file TemplateSynth.cpp.
References QBFSolver::A, CNF::addCNF(), VarInfo::CTRL, QBFSolver::E, AIG2CNF::getT(), AIG2CNF::getTransEqT(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), AIG2CNF::instance(), QBFSolver::isSatModel(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, qbf_solver_, VarInfo::TEMPL_PARAMS, and VarInfo::TMP.
Referenced by findWinRegANDNetwork(), and findWinRegCNFTempl().
bool TemplateSynth::syntSAT (const CNF & win_constr, int w1, int w2, vector< int > & solution) [protected]
Resolves the template by calling a SAT solver in a CEGIS loop.
Parameters
win_constr CNF constraints that constitute a correct solution for the winning region using the generic template. Essentially, three constraints are encoded in this CNF:
I(x) => W(x): every initial state is contained in the winning region
W(x) => P(x): every state of the winning region is safe
forall x,i: exists c,x': W(x) => (T(x,i,c,x') & W(x')): from every state in the winning region we can enforce to stay in the winning region by setting the c-signals appropriately.
w1 The literal that represents the present-state copy of the winning region in win_constr.
w2 The literal that represents the next-state copy of the winning region in win_constr.
solution An empty vector. If a solution exists, then the corresponding template parameter values are written into this vector.
Returns
True if a solution exists, false otherwise.
Definition at line 607 of file TemplateSynth.cpp.
References CNF::addCNF(), check(), exclude(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incIsSatModelOrCore(), VarInfo::INPUT, VarManager::instance(), AIG2CNF::instance(), Utils::negateLiterals(), VarInfo::PRES_STATE, sat_solver_, SatSolver::startIncrementalSession(), and VarInfo::TEMPL_PARAMS.
Referenced by findWinRegANDNetwork(), and findWinRegCNFTempl().
Member Data Documentation
CNFImplExtractor* TemplateSynth::impl_extractor_ [protected]
The engine to use for circuit extraction.
It will be deleted by this class (in the destructor).
Definition at line 290 of file TemplateSynth.h.
Referenced by run(), and ~TemplateSynth().
CNF TemplateSynth::neg_winning_region_ [protected]
The negation of the resulting winning region.
Definition at line 273 of file TemplateSynth.h.
Referenced by findWinRegANDNetwork(), findWinRegCNFTempl(), and run().
QBFSolver* TemplateSynth::qbf_solver_ [protected]
The QBF-solver to use for solving the queries.
Definition at line 278 of file TemplateSynth.h.
Referenced by syntQBF(), and ~TemplateSynth().
SatSolver* TemplateSynth::sat_solver_ [protected]
The SAT-solver to use if we resolve the template using the CEGIS loop.
Definition at line 283 of file TemplateSynth.h.
Referenced by exclude(), syntSAT(), and ~TemplateSynth().
CNF TemplateSynth::winning_region_ [protected]
The resulting winning region.
Definition at line 268 of file TemplateSynth.h.
Referenced by findWinRegANDNetwork(), findWinRegCNFTempl(), and run().
The documentation for this class was generated from the following files:
src/TemplateSynth.h
src/TemplateSynth.cpp