LearnSynthQBFInd Class Reference
Implements a learning-based synthesis with inductive reachability reasoning.
#include <LearnSynthQBFInd.h>
Public Member Functions
LearnSynthQBFInd ()
Constructor.
virtual ~LearnSynthQBFInd ()
Destructor.
virtual bool run ()
Executes this back-end.
Protected Member Functions
bool computeWinningRegion ()
Computes the winning region and stores the result in winning_region_.
bool computeWinningRegionOne ()
Uses the standard method to compute the winning region, with inductive reasoning.
bool computeWinningRegionAll ()
Computes the winning region, always computing all counterexample generalizations.
bool computeCounterexampleQBF (vector< int > &ce)
Computes a counterexample-state using a QBF-solver with inductive reasoning.
bool computeBlockingClause (vector< int > &ce, vector< int > &blocking_clause)
Computes a blocking clause for a counterexample.
bool computeAllBlockingClauses (vector< int > &ce, vector< vector< int > > &blocking_clauses)
Computes all minimal blocking clauses for a counterexample.
void reduceExistingClauses ()
Tries to drop literals from clauses in the winning region.
void recomputeCheckCNF (bool take_small_win=true)
Recomputes the CNF (of the QBF) that is used for computing counterexamples.
void recomputeGenCNF (bool take_small_win=true)
Recomputes the CNF (of the QBF) that is used for generalizing counterexamples.
void restrictToStates (vector< int > &vec) const
Restricts a vector of literals (a cube or clause) to state-variables only.
bool generalizeCounterexample (vector< int > &ce, bool check_sat=true) const
Generalizes a counterexample-state by dropping literals.
int presentToPrevious (int literal) const
Returns the previous-state copy of a literal.
void presentToPrevious (vector< int > &cube_or_clause) const
Computes the previous-state copy of a cube or clause.
void presentToPrevious (CNF &cnf) const
Computes the previous-state copy of a CNF.
void debugCheckWinRegReach () const
Checks a winning region computed with optimization RC for correctness.
Protected Attributes
CNF winning_region_
The current over-approximation of the winning region.
CNF winning_region_large_
The current over-approximation of the winning region in an uncompressed form.
LearnStatisticsQBF statistics_
Stores and maintains statistics and performance measures.
QBFSolver * qbf_solver_
The QBF-solver used for all queries.
vector< pair< VarInfo::VarKind,
*
QBFSolver::Quant > > check_quant_
The quantifier prefix of the QBF for computing counterexamples.
CNF check_cnf_
The CNF matrix of the QBF for computing counterexamples.
vector< pair< VarInfo::VarKind,
*
QBFSolver::Quant > > gen_quant_
The quantifier prefix of the QBF for generalizing counterexamples.
CNF generalize_clause_cnf_
The CNF matrix of the QBF for generalizing counterexamples.
vector< int > current_to_previous_map_
A map from present-state variables to their previous-state copy.
int current_state_is_initial_
A literal that is true if the current state is initial and false otherwise.
CNF prev_trans_or_initial_
Says: the current state is initial or the previous transition relation holds.
CNF check_reach_
Says: prev_trans_or_initial_ and the current state is different from the previous.
bool do_reach_check_
Enables or disables optimization RC.
Private Member Functions
LearnSynthQBFInd (const LearnSynthQBFInd &other)
Copy constructor.
LearnSynthQBFInd & operator= (const LearnSynthQBFInd &other)
Assignment operator.
Detailed Description
Implements a learning-based synthesis with inductive reachability reasoning.
This class is almost an exact copy of LearnSynthQBF. Hence, we refer to the documentation of LearnSynthQBF for an explanation of the basic working principle. The main difference is that this class uses a reachability optimization that is inspired by the concept of inductiveness relative to a certain clause set used in IC3. Refer to the VMCAI'14 publication `SAT-Based Synthesis Methods for Safety Specs` for a detailed explanation how (and why) this works. The class LearnSynthQBF computes counterexamples by solving: exists x,i: forall c: exists x',tmp: F(x) & T(x,i,c,x') & !F(x')
 and generalizes them by checking exists x: forall i: exists c,x',tmp: s & F(x) & T(x,i,c,x') & F(x')
 repeatedly, where s is the counterexample and F is the current over-approximation of the winning region.
We know that F(x) is never left by the final implementation. Hence, F is an over-approximation of the reachable states. Now if a state s is not initial and !s & F & T => !s', then we know by induction that the state s is unreachable. We can disregard unreachable states both in the computation of counterexamples as well as during the generalization. This is done by gluing the constraints !s & F & T => !s' and !I(s) to the generalization and check queries as following. The check query becomes:
   exists x*,i*,c*,x,i: forall c: exists x',tmp: (I(x) | (x* != x) & F(x*) & T(x*, i*, c*, x)) & F(x) & T(x,i,c,x') & !F(x')
 where x*, i* and c* are the previous-state copy of x,i,c. The query now says: find a counterexample-state x that is either initial or has a predecessor x* in F such that x* is different from x. (Otherwise the counterexample-state is unreachable.) The generalization query becomes:
   exists x*,i*,c*,x: forall i: exists c,x',tmp: (I(x) | F(x*) & !s* & T(x*, i*, c*, x)) & s & F(x) & T(x,i,c,x') & F(x')
 where x*, i* and c* are the previous-state copy of x,i,c. The query now says: a state that prevents generalization must be either initial or have a predecessor in F & !s. Otherwise it is unreachable and we do not care. This means that we can remove states that are winning for the protagonist from the winning region of they are unreachalbe in the final implementation.
The modification of the generalization is called optimization RG in the VMCAI paper. The modification of the counterexample-computation is called optimization RC. Depending on the command-line parameters (--mode) this class performs either just one or both optimizations. Experiments suggest that optimization RG is often beneficial, while optimization RC is usually not. Optimization RC leads to a winning region which cannot be turned into a circuit with the standard method.
Todo
Todo Turning a winning region that was computed with optimization RC into a circuit is not yet implemented. However, since optimization RC does not increase the performance in our experiments (in contrast to optimization RG), this is not a severe issue at the moment. We can consider optimization RC as experiment that did not work out well.
Note
This class is experimental.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.0.0
Definition at line 98 of file LearnSynthQBFInd.h.
Constructor & Destructor Documentation
LearnSynthQBFInd::LearnSynthQBFInd ()
Constructor.
Definition at line 40 of file LearnSynthQBFInd.cpp.
References QBFSolver::A, CNF::add2LitClause(), CNF::add3LitClause(), CNF::addClause(), CNF::addCNF(), check_quant_, check_reach_, VarManager::createFreshPrevVar(), VarManager::createFreshTmpVar(), VarInfo::CTRL, current_state_is_initial_, current_to_previous_map_, do_reach_check_, QBFSolver::E, gen_quant_, CNF::getClauses(), VarManager::getMaxCNFVar(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), Options::instance(), AIG2CNF::instance(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, presentToPrevious(), VarInfo::PREV, prev_trans_or_initial_, CNF::swapWith(), and VarInfo::TMP.
LearnSynthQBFInd::~LearnSynthQBFInd () [virtual]
Destructor.
Definition at line 136 of file LearnSynthQBFInd.cpp.
References qbf_solver_.
LearnSynthQBFInd::LearnSynthQBFInd (const LearnSynthQBFInd & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
bool LearnSynthQBFInd::computeAllBlockingClauses (vector< int > & ce, vector< vector< int > > & blocking_clauses) [protected]
Computes all minimal blocking clauses for a counterexample.
This method works like LearnSynthQBF::computeAllBlockingClauses() but using inductive reasoning regarding reachable states as an optimization. That is, instead of solving
   exists x: forall i: exists c,x',tmp: s & F(x) & T(x,i,c,x') & F(x')
 where s is the counterexample-state to generalize, we solve
   exists x*,i*,c*,x: forall i: exists c,x',tmp: (I(x) | F(x*) & !s* & T(x*, i*, c*, x)) & s & F(x) & T(x,i,c,x') & F(x')
 The query now says: a state that prevents generalization must be either initial or have a predecessor in F & !s. Otherwise it is unreachable and we do not care. This means that we can remove states that are winning for the protagonist from the winning region of they are unreachable in the final implementation.
Parameters
ce The counterexample to block. It is a full or partial cube over the state variables.
blocking_clauses An empty vector. It is used to store the computed blocking clauses. The counterexample falsifies all blocking clauses in this vector.
Returns
False if one of the blocking clauses blocks the initial state. This means that the initial state is removed from the winning region, i.e., the specification is unrealizable. True is returned otherwise.
Definition at line 362 of file LearnSynthQBFInd.cpp.
References CNF::addClause(), Utils::containsInit(), generalize_clause_cnf_, generalizeCounterexample(), Utils::intersectionEmpty(), Utils::negateLiterals(), LearnStatisticsQBF::notifyAfterCubeMin(), LearnStatisticsQBF::notifyBeforeCubeMin(), LearnStatisticsQBF::notifyCubeMin(), presentToPrevious(), Utils::remove(), statistics_, and Utils::swapPresentToNext().
Referenced by computeWinningRegionAll().
bool LearnSynthQBFInd::computeBlockingClause (vector< int > & ce, vector< int > & blocking_clause) [protected]
Computes a blocking clause for a counterexample.
This method works like LearnSynthQBF::computeBlockingClause() but using inductive reasoning regarding reachable states as an optimization. That is, instead of solving
   exists x: forall i: exists c,x',tmp: s & F(x) & T(x,i,c,x') & F(x')
 where s is the counterexample-state to generalize, we solve
   exists x*,i*,c*,x: forall i: exists c,x',tmp: (I(x) | F(x*) & !s* & T(x*, i*, c*, x)) & s & F(x) & T(x,i,c,x') & F(x')
 The query now says: a state that prevents generalization must be either initial or have a predecessor in F & !s. Otherwise it is unreachable and we do not care. This means that we can remove states that are winning for the protagonist from the winning region of they are unreachable in the final implementation.
Parameters
ce The counterexample to block. It is a full or partial cube over the state variables.
blocking_clause An empty vector. It is used to store the computed blocking clause. The counterexample falsifies the blocking clause.
Returns
False if the blocking clause blocks the initial state. This means that the initial state is removed from the winning region, i.e., the specification is unrealizable. True is returned otherwise.
Definition at line 344 of file LearnSynthQBFInd.cpp.
References Utils::containsInit(), generalizeCounterexample(), L_DBG, Utils::negateLiterals(), LearnStatisticsQBF::notifyAfterCubeMin(), LearnStatisticsQBF::notifyBeforeCubeMin(), Utils::randomize(), and statistics_.
Referenced by computeWinningRegionOne().
bool LearnSynthQBFInd::computeCounterexampleQBF (vector< int > & ce) [protected]
Computes a counterexample-state using a QBF-solver with inductive reasoning.
This method works like LearnSynthQBF::computeCounterexampleQBF() but using inductive reasoning regarding reachable states as an optimization. That is, instead of solving
   exists x,i: forall c: exists x',tmp: F(x) & T(x,i,c,x') & !F(x')
 we solve
   exists x*,i*,c*,x,i: forall c: exists x',tmp: (I(x) | (x* != x) & F(x*) & T(x*, i*, c*, x)) & F(x) & T(x,i,c,x') & !F(x')
 to obtain a counterexample. The query now says: find a counterexample-state x that is either initial or has a predecessor x* in F such that x* is different from x. (Otherwise the counterexample-state is unreachable.)
If optimization RC is disabled (do_reach_check_ is false), then counterexamples are computed in the standard way.
Parameters
ce An empty vector. The computed counterexample is stored in this vector in form of a cube over the state variables. The cube does not necessarily contain all state variables. If some state variables are irrelevant, then they may be omitted.
Returns
True if a counterexample was found, false if no counterexample exists.
Definition at line 333 of file LearnSynthQBFInd.cpp.
References check_cnf_, check_quant_, QBFSolver::isSatModel(), LearnStatisticsQBF::notifyAfterComputeCube(), LearnStatisticsQBF::notifyBeforeComputeCube(), qbf_solver_, restrictToStates(), and statistics_.
Referenced by computeWinningRegionAll(), and computeWinningRegionOne().
bool LearnSynthQBFInd::computeWinningRegion () [protected]
Computes the winning region and stores the result in winning_region_.
Depending on the command-line parameters (--mode) this method calls one of
computeWinningRegionOne()
computeWinningRegionAll()
Returns
True if the specification was realizable, false otherwise.
Definition at line 176 of file LearnSynthQBFInd.cpp.
References computeWinningRegionAll(), computeWinningRegionOne(), Utils::debugCheckWinReg(), debugCheckWinRegReach(), do_reach_check_, Options::getBackEndMode(), Options::instance(), and winning_region_.
Referenced by run().
bool LearnSynthQBFInd::computeWinningRegionAll () [protected]
Computes the winning region, always computing all counterexample generalizations.
This method works like LearnSynthQBF::computeWinningRegionOne() but using inductive reasoning regarding reachable states as an optimization (as explained in the description of the class).
Returns
True if the specification was realizable, false otherwise.
Definition at line 267 of file LearnSynthQBFInd.cpp.
References CNF::addClauseAndSimplify(), check_cnf_, CNF::clear(), Utils::compressStateCNF(), computeAllBlockingClauses(), computeCounterexampleQBF(), VarInfo::CTRL, Logger::DBG, Utils::debugPrint(), generalize_clause_cnf_, CNF::getNrOfClauses(), CNF::getNrOfLits(), AIG2CNF::getSafeStates(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), Logger::instance(), AIG2CNF::instance(), Logger::isEnabled(), L_DBG, LearnStatisticsQBF::logStatistics(), VarInfo::PRES_STATE, recomputeCheckCNF(), recomputeGenCNF(), reduceExistingClauses(), statistics_, winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
bool LearnSynthQBFInd::computeWinningRegionOne () [protected]
Uses the standard method to compute the winning region, with inductive reasoning.
This method works like LearnSynthQBF::computeWinningRegionOne() but using inductive reasoning regarding reachable states as an optimization (as explained in the description of the class).
Returns
True if the specification was realizable, false otherwise.
Definition at line 195 of file LearnSynthQBFInd.cpp.
References CNF::addClauseAndSimplify(), check_cnf_, CNF::clear(), Utils::compressStateCNF(), computeBlockingClause(), computeCounterexampleQBF(), VarInfo::CTRL, Logger::DBG, Utils::debugPrint(), generalize_clause_cnf_, CNF::getNrOfClauses(), CNF::getNrOfLits(), AIG2CNF::getSafeStates(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), Logger::instance(), AIG2CNF::instance(), Logger::isEnabled(), L_DBG, LearnStatisticsQBF::logStatistics(), VarInfo::PRES_STATE, presentToPrevious(), recomputeCheckCNF(), recomputeGenCNF(), statistics_, Utils::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
void LearnSynthQBFInd::debugCheckWinRegReach () const [protected]
Checks a winning region computed with optimization RC for correctness.
We usually check the correctness of the winning region in debug-mode by calling Utils::debugCheckWinReg(). However, this method of Utils does not work for winning regions that have been computed with optimization RC enabled. In such cases we this method.
Definition at line 631 of file LearnSynthQBFInd.cpp.
References QBFSolver::A, CNF::addCNF(), CNF::clear(), VarInfo::CTRL, QBFSolver::E, VarInfo::INPUT, AIG2CNF::instance(), LingelingApi::isSat(), QBFSolver::isSat(), L_DBG, MASSERT, CNF::negate(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, presentToPrevious(), VarInfo::PREV, prev_trans_or_initial_, qbf_solver_, CNF::swapPresentToNext(), VarInfo::TMP, and winning_region_.
Referenced by computeWinningRegion().
bool LearnSynthQBFInd::generalizeCounterexample (vector< int > & ce, bool check_sat = true) const [protected]
Generalizes a counterexample-state by dropping literals.
This method works like LearnSynthQBF::generalizeCounterexample() but using inductive reasoning regarding reachable states as an optimization. That is, instead of solving
   exists x: forall i: exists c,x',tmp: s & F(x) & T(x,i,c,x') & F(x')
 where s is the counterexample-state to generalize, we solve
   exists x*,i*,c*,x: forall i: exists c,x',tmp: (I(x) | F(x*) & !s* & T(x*, i*, c*, x)) & s & F(x) & T(x,i,c,x') & F(x')
 The query now says: a state that prevents generalization must be either initial or have a predecessor in F & !s. Otherwise it is unreachable and we do not care. This means that we can remove states that are winning for the protagonist from the winning region of they are unreachable in the final implementation.
Parameters
ce The counterexample to generalize (it will be overwritten by its own generalization). This is a complete or partial cube over the present state variables.
check_sat False if ce is a counterexample (for which a generalization exists) for sure. False if this may not be the case and needs to be checked.
Returns
True if the passed vector is a valid (generalization of a) counterexample, false otherwise.
Definition at line 567 of file LearnSynthQBFInd.cpp.
References CNF::addCube(), CNF::addNegCubeAsClause(), current_state_is_initial_, gen_quant_, generalize_clause_cnf_, QBFSolver::isSat(), presentToPrevious(), qbf_solver_, Utils::remove(), Utils::sort(), and Utils::swapPresentToNext().
Referenced by computeAllBlockingClauses(), and computeBlockingClause().
LearnSynthQBFInd& LearnSynthQBFInd::operator= (const LearnSynthQBFInd & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
int LearnSynthQBFInd::presentToPrevious (int literal) const [protected]
Returns the previous-state copy of a literal.
Parameters
literal The literal to transform.
Returns
The previous-state copy of a literal.
Definition at line 601 of file LearnSynthQBFInd.cpp.
References current_to_previous_map_.
Referenced by computeAllBlockingClauses(), computeWinningRegionOne(), debugCheckWinRegReach(), generalizeCounterexample(), LearnSynthQBFInd(), presentToPrevious(), recomputeCheckCNF(), recomputeGenCNF(), and reduceExistingClauses().
void LearnSynthQBFInd::presentToPrevious (vector< int > & cube_or_clause) const [protected]
Computes the previous-state copy of a cube or clause.
Parameters
cube_or_clause A cube or clause (in form of a vector of literals) over the present state variables. This vector is overwritten by the corresponding cube of clause over the previous-state literals (i.e., all literals are replaced by their previous-state copy).
Definition at line 611 of file LearnSynthQBFInd.cpp.
References presentToPrevious().
void LearnSynthQBFInd::presentToPrevious (CNF & cnf) const [protected]
Computes the previous-state copy of a CNF.
Parameters
cnf A CNF formula over the present state variables. This CNF is overwritten by the corresponding CNF over the previous-state literals (i.e., all literals are replaced by their previous-state copy).
Definition at line 618 of file LearnSynthQBFInd.cpp.
References CNF::addClause(), CNF::clear(), CNF::getClauses(), and presentToPrevious().
void LearnSynthQBFInd::recomputeCheckCNF (bool take_small_win = true) [protected]
Recomputes the CNF (of the QBF) that is used for computing counterexamples.
The CNF used for computing counterexamples is F & T & !F' if optimization RC is disabled (check_reach_ = false) , or (I | (x* != x) & F* & T*) & F & T & !F' if optimization RC in enabled (check_reach_ = true). Here F is the current over-approximation of the winning region (in winning_region_). This formula is put into check_cnf_ by this method.
Parameters
take_small_win If this parameter is true (or omitted) the winning_region_ is used to compute the check_cnf_. Otherwise, the winning_region_large_ is used. The difference between these two winning region versions is as follows. From time to we remove redundant clauses (clauses implied by other clauses) from winning_region_ but not from winning_region_large_. Hence, winning_region_ is often smaller, but winning_region_large_ may contain clauses the solver may have to learn when using winning_region_.
Definition at line 488 of file LearnSynthQBFInd.cpp.
References CNF::addCNF(), check_cnf_, check_reach_, CNF::clear(), do_reach_check_, AIG2CNF::instance(), CNF::negate(), presentToPrevious(), VarManager::resetToLastPush(), CNF::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegionAll(), and computeWinningRegionOne().
void LearnSynthQBFInd::recomputeGenCNF (bool take_small_win = true) [protected]
Recomputes the CNF (of the QBF) that is used for generalizing counterexamples.
The CNF used for generalizing counterexamples is (I | F* & T*) & F & T & F' where F is the current over-approximation of the winning region (in winning_region_).
Parameters
take_small_win If this parameter is true (or omitted) the winning_region_ is used to compute the check_cnf_. Otherwise, the winning_region_large_ is used. The difference between these two winning region versions is as follows. From time to we remove redundant clauses (clauses implied by other clauses) from winning_region_ but not from winning_region_large_. Hence, winning_region_ is often smaller, but winning_region_large_ may contain clauses the solver may have to learn when using winning_region_.
Definition at line 520 of file LearnSynthQBFInd.cpp.
References CNF::addCNF(), CNF::clear(), generalize_clause_cnf_, AIG2CNF::instance(), presentToPrevious(), prev_trans_or_initial_, CNF::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegionAll(), and computeWinningRegionOne().
void LearnSynthQBFInd::reduceExistingClauses () [protected]
Tries to drop literals from clauses in the winning region.
This method examines all clauses (in winning_region_) that have already been computed and checks if more literals can be dropped. This is done in the same way as for dropping literals when generalizing a counterexample.
The intuition behind this method is that, even if a literal could not be dropped before, it could be dropped at a later point in time because the winning region has been refined in the meantime. However, in practice, typically only very few additional literals can be dropped, so this method often does not pay off.
Definition at line 450 of file LearnSynthQBFInd.cpp.
References CNF::addClause(), CNF::addClauseAndSimplify(), CNF::addNegClauseAsCube(), current_state_is_initial_, gen_quant_, generalize_clause_cnf_, CNF::getClauses(), CNF::getNrOfClauses(), CNF::getNrOfLits(), QBFSolver::isSat(), L_DBG, LearnStatisticsQBF::notifyAfterCubeMin(), LearnStatisticsQBF::notifyBeforeCubeMin(), presentToPrevious(), qbf_solver_, Utils::remove(), statistics_, winning_region_, and winning_region_large_.
Referenced by computeWinningRegionAll().
void LearnSynthQBFInd::restrictToStates (vector< int > & vec) const [protected]
Restricts a vector of literals (a cube or clause) to state-variables only.
That is, all literals that do not talk about present state variables are removed.
Parameters
vec The vector of literals (the cube or clause) to restricts to state-variables only.
Definition at line 548 of file LearnSynthQBFInd.cpp.
References VarManager::getInfo(), VarInfo::getKind(), VarManager::getPresErrorStateVar(), VarManager::instance(), and VarInfo::PRES_STATE.
Referenced by computeCounterexampleQBF().
bool LearnSynthQBFInd::run () [virtual]
Executes this back-end.
In contrast to the corresponding method of LearnSynthQBF, this method applies some inductive reachability reasoning as an optimization (attempt). The reachability optimization is inspired by the concept of inductiveness relative to a certain clause set used in IC3. Refer to the VMCAI'14 publication `SAT-Based Synthesis Methods for Safety
Specs` for a detailed explanation how (and why) this works. The method LearnSynthQBF::run() computes counterexamples by solving:
   exists x,i: forall c: exists x',tmp: F(x) & T(x,i,c,x') & !F(x')
 and generalizes them by checking
   exists x: forall i: exists c,x',tmp: s & F(x) & T(x,i,c,x') & F(x')
 repeatedly, where s is the counterexample and F is the current over-approximation of the winning region.
We know that F(x) is never left by the final implementation. Hence, F is an over-approximation of the reachable states. Now if a state s is not initial and !s & F & T => !s', then we know by induction that the state s is unreachable. We can disregard unreachable states both in the computation of counterexamples as well as during the generalization. This is done by gluing the constraints !s & F & T => !s' and !I(s) to the generalization and check queries as following. The check query becomes:
   exists x*,i*,c*,x,i: forall c: exists x',tmp: (I(x) | (x* != x) & F(x*) & T(x*, i*, c*, x)) & F(x) & T(x,i,c,x') & !F(x')
 where x*, i* and c* are the previous-state copy of x,i,c. The query now says: find a counterexample-state x that is either initial or has a predecessor x* in F such that x* is different from x. (Otherwise the counterexample-state is unreachable.) The generalization query becomes:
   exists x*,i*,c*,x: forall i: exists c,x',tmp: (I(x) | F(x*) & !s* & T(x*, i*, c*, x)) & s & F(x) & T(x,i,c,x') & F(x')
 where x*, i* and c* are the previous-state copy of x,i,c. The query now says: a state that prevents generalization must be either initial or have a predecessor in F & !s. Otherwise it is unreachable and we do not care. This means that we can remove states that are winning for the protagonist from the winning region of they are unreachable in the final implementation.
The modification of the generalization is called optimization RG in the VMCAI paper. The modification of the counterexample-computation is called optimization RC. Depending on the command-line parameters (--mode) this class performs either just one or both optimizations. Experiments suggest that optimization RG is often beneficial, while optimization RC is usually not.
Note
When optimization RC in enabled, we cannot extract a circuit from the winning region at the moment.
Returns
True if the specification was realizable, false otherwise.
Implements BackEnd.
Definition at line 143 of file LearnSynthQBFInd.cpp.
References computeWinningRegion(), do_reach_check_, QBFCertImplExtractor::extractCircuit(), VarManager::instance(), Options::instance(), L_INF, L_RES, LearnStatisticsQBF::logStatistics(), MASSERT, LearnStatisticsQBF::notifyRelDetEnd(), LearnStatisticsQBF::notifyRelDetStart(), LearnStatisticsQBF::notifyWinRegEnd(), LearnStatisticsQBF::notifyWinRegStart(), VarManager::push(), statistics_, and winning_region_.
Member Data Documentation
CNF LearnSynthQBFInd::check_cnf_ [protected]
The CNF matrix of the QBF for computing counterexamples.
If optimization RC in enabled (do_reach_check_ is true), then this CNF is
   (I | (x* != x) & F* & T*) & F & T & !F'
 otherwise (if do_reach_check_ is false) it is
   F & T & !F'
 where F is the current over-approximation of the winning region (store in winning_region_).
Definition at line 450 of file LearnSynthQBFInd.h.
Referenced by computeCounterexampleQBF(), computeWinningRegionAll(), computeWinningRegionOne(), and recomputeCheckCNF().
vector<pair<VarInfo::VarKind, QBFSolver::Quant> > LearnSynthQBFInd::check_quant_ [protected]
The quantifier prefix of the QBF for computing counterexamples.
If optimization RC in enabled (do_reach_check_ is true), then this quantifier prefix is
   exists x*,i*,c*,x,i: forall c: exists x',tmp:
 otherwise (if do_reach_check_ is false) it is
   exists x,i: forall c: exists x',tmp:
Definition at line 438 of file LearnSynthQBFInd.h.
Referenced by computeCounterexampleQBF(), and LearnSynthQBFInd().
CNF LearnSynthQBFInd::check_reach_ [protected]
Says: prev_trans_or_initial_ and the current state is different from the previous.
If the optimization RC is disabled (do_reach_check_ is false) then this CNF is simply TRUE. This CNF is an important building block for check_cnf_ (the part that stays constant over all iterations). Hence, it is computed once and copied whenever needed.
Definition at line 498 of file LearnSynthQBFInd.h.
Referenced by LearnSynthQBFInd(), and recomputeCheckCNF().
int LearnSynthQBFInd::current_state_is_initial_ [protected]
A literal that is true if the current state is initial and false otherwise.
The clauses assigning the literal are part of prev_trans_or_initial_. Since prev_trans_or_initial_ is part of check_cnf_ and generalize_clause_cnf_, this literal is also assigned by check_cnf_ (if optimization RC is enabled, i.e., if do_reach_check_ is true) and generalize_clause_cnf_.
Definition at line 480 of file LearnSynthQBFInd.h.
Referenced by generalizeCounterexample(), LearnSynthQBFInd(), and reduceExistingClauses().
vector<int> LearnSynthQBFInd::current_to_previous_map_ [protected]
A map from present-state variables to their previous-state copy.
Definition at line 470 of file LearnSynthQBFInd.h.
Referenced by LearnSynthQBFInd(), and presentToPrevious().
bool LearnSynthQBFInd::do_reach_check_ [protected]
Enables or disables optimization RC.
Optimization RC (inductive reachability checks during the computation of counterexamples) is enabled if this flag is true, otherwise it is disabled.
Definition at line 506 of file LearnSynthQBFInd.h.
Referenced by computeWinningRegion(), LearnSynthQBFInd(), recomputeCheckCNF(), and run().
vector<pair<VarInfo::VarKind, QBFSolver::Quant> > LearnSynthQBFInd::gen_quant_ [protected]
The quantifier prefix of the QBF for generalizing counterexamples.
This quantifier prefix is always exists x*,i*,c*,x: forall i: exists c,x',tmp:
Definition at line 458 of file LearnSynthQBFInd.h.
Referenced by generalizeCounterexample(), LearnSynthQBFInd(), and reduceExistingClauses().
CNF LearnSynthQBFInd::generalize_clause_cnf_ [protected]
The CNF matrix of the QBF for generalizing counterexamples.
This CNF is always (I | F* & T*) & F & T & F', where F is the winning_region_.
Definition at line 465 of file LearnSynthQBFInd.h.
Referenced by computeAllBlockingClauses(), computeWinningRegionAll(), computeWinningRegionOne(), generalizeCounterexample(), recomputeGenCNF(), and reduceExistingClauses().
CNF LearnSynthQBFInd::prev_trans_or_initial_ [protected]
Says: the current state is initial or the previous transition relation holds.
This CNF expresses that the current state is initial or the previous-state copy of the transition relation holds. This is an important building block for both check_cnf_ and generalize_clause_cnf_.
Definition at line 489 of file LearnSynthQBFInd.h.
Referenced by debugCheckWinRegReach(), LearnSynthQBFInd(), and recomputeGenCNF().
QBFSolver* LearnSynthQBFInd::qbf_solver_ [protected]
The QBF-solver used for all queries.
The type of solver is selected with command-line arguments.
Definition at line 428 of file LearnSynthQBFInd.h.
Referenced by computeCounterexampleQBF(), debugCheckWinRegReach(), generalizeCounterexample(), reduceExistingClauses(), and ~LearnSynthQBFInd().
LearnStatisticsQBF LearnSynthQBFInd::statistics_ [protected]
Stores and maintains statistics and performance measures.
Definition at line 421 of file LearnSynthQBFInd.h.
Referenced by computeAllBlockingClauses(), computeBlockingClause(), computeCounterexampleQBF(), computeWinningRegionAll(), computeWinningRegionOne(), reduceExistingClauses(), and run().
CNF LearnSynthQBFInd::winning_region_ [protected]
The current over-approximation of the winning region.
Only when computeWinningRegion() is done, this field will store the correct winning region.
Definition at line 404 of file LearnSynthQBFInd.h.
Referenced by computeWinningRegion(), computeWinningRegionAll(), computeWinningRegionOne(), debugCheckWinRegReach(), recomputeCheckCNF(), recomputeGenCNF(), reduceExistingClauses(), and run().
CNF LearnSynthQBFInd::winning_region_large_ [protected]
The current over-approximation of the winning region in an uncompressed form.
This CNF is logically equivalent to winning_region_. However, winning_region_ is 'compressed' from time to time by removing redundant clauses (clauses that are implied by other clauses in the winning region). This field stores the uncompressed version of the winning region. Having the uncompressed winning region can be good because throwing away redundant clauses is not always beneficial. The CNF get smaller, but the solver may have to re-discover the removed clauses.
Definition at line 416 of file LearnSynthQBFInd.h.
Referenced by computeWinningRegionAll(), computeWinningRegionOne(), recomputeCheckCNF(), recomputeGenCNF(), and reduceExistingClauses().
The documentation for this class was generated from the following files:
src/LearnSynthQBFInd.h
src/LearnSynthQBFInd.cpp