MiniSatApi Class Reference
Interfaces the MiniSat SAT-solver via its API.
#include <MiniSatApi.h>
Public Member Functions
MiniSatApi (bool rand_models=false, bool min_cores=true)
Constructor.
virtual ~MiniSatApi ()
Destructor.
virtual bool isSat (const CNF &cnf)
Checks if a CNF is satisfiable.
virtual bool isSatModelOrCore (const CNF &cnf, const vector< int > &assumptions, const vector< int > &vars_of_interest, vector< int > &model_or_core)
Checks if a CNF is satisfiable and extracts a model or an unsatisfiable core.
virtual void startIncrementalSession (const vector< int > &vars_to_keep, bool use_push=true)
Starts a new incremental session.
virtual void clearIncrementalSession ()
Deletes the solver instance that is used in the incremental session.
virtual void incAddCNF (const CNF &cnf)
Adds a new CNF to the current incremental session.
virtual void incAddClause (const vector< int > &clause)
Adds a new clause to the current incremental session.
virtual void incAddUnitClause (int lit)
Adds a new unit clause to the current incremental session.
virtual void incAdd2LitClause (int lit1, int lit2)
Adds a new clause consisting of 2 literals to the current incremental session.
virtual void incAdd3LitClause (int lit1, int lit2, int lit3)
Adds a new clause consisting of 3 literals to the current incremental session.
virtual void incAddCube (const vector< int > &cube)
Adds a new cube to the current incremental session.
virtual void incAddNegCubeAsClause (const vector< int > &cube)
Adds the negation of a given cube (which is a clause) to the incremental session.
virtual bool incIsSat ()
Checks if a the CNF in the incremental session is satisfiable.
virtual bool incIsSat (const vector< int > &assumptions)
Checks if a the CNF in the incremental session is satisfiable under assumptions.
virtual bool incIsSatModelOrCore (const vector< int > &assumptions, const vector< int > &vars_of_interest, vector< int > &model_or_core)
Checks the CNF in the incremental session and computes a model or unsat core.
virtual bool incIsSatModelOrCore (const vector< int > &core_assumptions, const vector< int > &more_assumptions, const vector< int > &vars_of_interest, vector< int > &model_or_core)
Computes a satisfying assignment or core using additional assumptions.
virtual void incPush ()
Stores the current state of the incremental session on a stack.
virtual void incPop ()
Restores the incremental session back to the point where incPush() was called.
void doMinCores (bool min_cores=true)
Enables or disables the computation of MINIMAL unsatisfiable cores.
void doRandModels (bool rand_models=true)
Enables or disables the randomization of satisfying assignments.
Protected Types
typedef list< Minisat::Solver * >
*
::const_iterator StackConstIter
A type for a const-iterator over the incremental session stack.
typedef list< Minisat::Solver * >
*
::iterator StackIter
A type for an iterator over the incremental session stack.
typedef list< CNF * >
*
::const_iterator StackCNFConstIter
A type for a const-iterator over the CNFs of the incremental sessions.
typedef list< CNF * >::iterator StackCNFIter
A type for an iterator over the CNFs of the incremental sessions.
Protected Attributes
list< Minisat::Solver * > incr_stack_
A stack of incremental session contexts.
list< CNF * > incr_stack_cnfs_
A CNFs that are stored in the incremental session contexts.
bool use_push_
A flag indicating if incPush() and incPop() are ever going to be used.
bool min_cores_
Indicates if the unsat cores returned by the solver should be minimized further.
bool rand_models_
Indicates if satisfying assignments should be randomized.
Private Member Functions
MiniSatApi (const MiniSatApi &other)
Copy constructor.
MiniSatApi & operator= (const MiniSatApi &other)
Assignment operator.
Detailed Description
Interfaces the MiniSat SAT-solver via its API.
This class represents an interface to the SAT-solver Minisat (see http://minisat.se). It is a concrete implementation of the SatSolver interface. For a given CNF, this class is able to determine satisfiability. Furthermore, in case of satisfiability, it can extract satisfying assignments. In case of unsatisfiability, it can compute an unsatisfiable core. It can be used in two different ways. In the incremental usage scenario, all information the solver has learned so far is retained. Methods for incremental solving start with 'inc'. Other methods (like isSat() or isSatModelOrCore()) instantiate a fresh solver instance for every call.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.1.0
Definition at line 58 of file MiniSatApi.h.
Member Typedef Documentation
list< CNF * >::const_iterator MiniSatApi::StackCNFConstIter [protected]
A type for a const-iterator over the CNFs of the incremental sessions.
Definition at line 432 of file MiniSatApi.h.
list< CNF * >::iterator MiniSatApi::StackCNFIter [protected]
A type for an iterator over the CNFs of the incremental sessions.
Definition at line 438 of file MiniSatApi.h.
list< Minisat::Solver * >::const_iterator MiniSatApi::StackConstIter [protected]
A type for a const-iterator over the incremental session stack.
Definition at line 420 of file MiniSatApi.h.
list< Minisat::Solver * >::iterator MiniSatApi::StackIter [protected]
A type for an iterator over the incremental session stack.
Definition at line 426 of file MiniSatApi.h.
Constructor & Destructor Documentation
MiniSatApi::MiniSatApi (bool rand_models = false, bool min_cores = true)
Constructor.
Parameters
rand_models A flag indicating if satisfying assignments should be randomized. This is done in a post-processing step (values are flipped randomly and then we check if this still constitutes a satisfying assignment). This is expensive. If this parameter is skipped, then satisfying assignments are not randomized.
min_cores A flag indicating if unsatisfiable cores returned by the solver should be minimized further by trying to drop one literal after the other. This makes the calls slower but produces potentially smaller cubes.
Definition at line 38 of file MiniSatApi.cpp.
MiniSatApi::~MiniSatApi () [virtual]
Destructor.
Definition at line 46 of file MiniSatApi.cpp.
References clearIncrementalSession().
MiniSatApi::MiniSatApi (const MiniSatApi & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void MiniSatApi::clearIncrementalSession () [virtual]
Deletes the solver instance that is used in the incremental session.
Implements SatSolver.
Definition at line 218 of file MiniSatApi.cpp.
References incr_stack_, and incr_stack_cnfs_.
Referenced by startIncrementalSession(), and ~MiniSatApi().
void SatSolver::doMinCores (bool min_cores = true) [inherited]
Enables or disables the computation of MINIMAL unsatisfiable cores.
Parameters
min_cores A flag indicating if unsatisfiable cores returned by the solver should be minimized further by trying to drop one literal after the other. This makes the calls slower but produces potentially smaller cubes. If the parameter is skipped the computation of minimal cores is enabled.
Definition at line 47 of file SatSolver.cpp.
References SatSolver::min_cores_.
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), and LearningImplExtractor::runLearningJiangSATTmpCtrlInc2().
void SatSolver::doRandModels (bool rand_models = true) [inherited]
Enables or disables the randomization of satisfying assignments.
Parameters
rand_models A flag indicating if satisfying assignments should be randomized. This is done in a post-processing step (values are flipped randomly and then we check if this still constitutes a satisfying assignment). This is expensive. If this parameter is skipped, then randomization is enabled.
Definition at line 53 of file SatSolver.cpp.
References SatSolver::rand_models_.
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), and LearnSynthSAT::computeWinningRegionRGRC().
void MiniSatApi::incAdd2LitClause (int lit1, int lit2) [virtual]
Adds a new clause consisting of 2 literals to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
lit1 The first literal of the clause to add to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed literal talks about a variables that have been mentioned in vars_to_keep when calling startIncrementalSession(). Actually, the implementation in THIS class does not care, but other implementations of the SatSolver interface do. Hence, you should not violate this property to have the solver instances exchangeable.
lit2 The second literal of the clause to add to the currently open incremental session (must be contained in vars_to_keep as well).
Implements SatSolver.
Definition at line 269 of file MiniSatApi.cpp.
References c2m(), incr_stack_, incr_stack_cnfs_, MASSERT, and use_push_.
void MiniSatApi::incAdd3LitClause (int lit1, int lit2, int lit3) [virtual]
Adds a new clause consisting of 3 literals to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
lit1 The first literal of the clause to add to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed literal talks about a variables that have been mentioned in vars_to_keep when calling startIncrementalSession(). Actually, the implementation in THIS class does not care, but other implementations of the SatSolver interface do. Hence, you should not violate this property to have the solver instances exchangeable.
lit2 The second literal of the clause to add to the currently open incremental session (must be contained in vars_to_keep as well).
lit3 The third literal of the clause to add to the currently open incremental session (must be contained in vars_to_keep as well).
Implements SatSolver.
Definition at line 279 of file MiniSatApi.cpp.
References c2m(), incr_stack_, incr_stack_cnfs_, MASSERT, and use_push_.
void MiniSatApi::incAddClause (const vector< int > & clause) [virtual]
Adds a new clause to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
clause The clause (a disjunction of literals) to add (conjunct) to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed clause talks only about variables that have been mentioned in vars_to_keep when calling startIncrementalSession(). Actually, the implementation in THIS class does not care, but other implementations of the SatSolver interface do. Hence, you should not violate this property to have the solver instances exchangeable.
Implements SatSolver.
Definition at line 246 of file MiniSatApi.cpp.
References c2m(), incr_stack_, incr_stack_cnfs_, MASSERT, and use_push_.
void MiniSatApi::incAddCNF (const CNF & cnf) [virtual]
Adds a new CNF to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
cnf The CNF to add to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed CNF talks only about variables that have been mentioned in vars_to_keep when calling startIncrementalSession(). Actually, the implementation in THIS class does not care, but other implementations of the SatSolver interface do. Hence, you should not violate this property to have the solver instances exchangeable.
Implements SatSolver.
Definition at line 229 of file MiniSatApi.cpp.
References c2m(), CNF::getClauses(), incr_stack_, incr_stack_cnfs_, MASSERT, and use_push_.
void MiniSatApi::incAddCube (const vector< int > & cube) [virtual]
Adds a new cube to the current incremental session.
That is, all literals of the cube are added as unit clauses to the current incremental session. For instance, if the cube [2, -4, 8] is passed as argument, then this method adds the three unit clauses [2], [-4], [8].
Precondition
startIncrementalSession() must have been called before.
Parameters
cube The cube (a conjunction of literals) to add (conjunct) to the currently open incremental session. All literals of this cube will be added as unit clauses. If this method is called after solving for the first time, be sure that the passed clause talks only about variables that have been mentioned in vars_to_keep when calling startIncrementalSession(). Actually, the implementation in THIS class does not care, but other implementations of the SatSolver interface do. Hence, you should not violate this property to have the solver instances exchangeable.
Implements SatSolver.
Definition at line 289 of file MiniSatApi.cpp.
References c2m(), incr_stack_, incr_stack_cnfs_, MASSERT, and use_push_.
void MiniSatApi::incAddNegCubeAsClause (const vector< int > & cube) [virtual]
Adds the negation of a given cube (which is a clause) to the incremental session.
For instance, if the cube [2, -4, 8] is passed as argument, then this method adds the clauses [-2, 4, -8] to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
cube The cube (a conjunction of literals) to negate and add (conjunct) to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed cube talks only about variables that have been mentioned in vars_to_keep when calling startIncrementalSession(). Actually, the implementation in THIS class does not care, but other implementations of the SatSolver interface do. Hence, you should not violate this property to have the solver instances exchangeable.
Implements SatSolver.
Definition at line 300 of file MiniSatApi.cpp.
References c2m(), incr_stack_, incr_stack_cnfs_, MASSERT, and use_push_.
void MiniSatApi::incAddUnitClause (int lit) [virtual]
Adds a new unit clause to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
lit The (one and only) literal of the unit clause to add to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed literal talks about a variables that have been mentioned in vars_to_keep when calling startIncrementalSession(). Actually, the implementation in THIS class does not care, but other implementations of the SatSolver interface do. Hence, you should not violate this property to have the solver instances exchangeable.
Implements SatSolver.
Definition at line 259 of file MiniSatApi.cpp.
References c2m(), incr_stack_, incr_stack_cnfs_, MASSERT, and use_push_.
bool MiniSatApi::incIsSat () [virtual]
Checks if a the CNF in the incremental session is satisfiable.
Precondition
startIncrementalSession() must have been called before.
Returns
True in case of satisfiability, false otherwise.
Implements SatSolver.
Definition at line 313 of file MiniSatApi.cpp.
References incr_stack_, and MASSERT.
bool MiniSatApi::incIsSat (const vector< int > & assumptions) [virtual]
Checks if a the CNF in the incremental session is satisfiable under assumptions.
This method checks if the CNF in the incremental session is satisfiable given that all literals passed in the vector 'assumptions' are true. The assumptions are not persistently added to the CNF of the incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
assumptions A vector of literals. This method then checks if the CNF of the incremental session is satisfiable given that all literals passed in this vector are true. The assumptions are not persistently added to the CNF. The assumptions must be a subset of the vars_to_keep passed to startIncrementalSession().
Returns
True in case of satisfiability, false otherwise.
Implements SatSolver.
Definition at line 320 of file MiniSatApi.cpp.
References c2m(), incr_stack_, and MASSERT.
bool MiniSatApi::incIsSatModelOrCore (const vector< int > & assumptions, const vector< int > & vars_of_interest, vector< int > & model_or_core) [virtual]
Checks the CNF in the incremental session and computes a model or unsat core.
This method checks if the CNF of the incremental session is satisfiable given that all literals passed in the vector 'assumptions' is true. If this is the case, then a satisfying assignment will be written into model_or_core. You can specify which variables you want to have in the satisfying assignment using the vars_of_interest vector. The reason is that your CNF may contain thousands of temporary variables stemming from some Tseitin encoding, but usually one in only interested in the value of a few variables. In case of unsatisfiability, an unsatisfiable core is stored in model_or_core. The unsatisfiable core is a subset of the literals passed in 'assumptions' such that the CNF is still unsatisfiable when these literals hold.
Parameters
assumptions A vector of literals. This method then checks if the CNF of the incremental session is satisfiable given that all literals passed in this vector are true. The assumptions are not persistently added to the CNF. The assumptions must be a subset of the vars_to_keep passed to startIncrementalSession().
vars_of_interest The variables for which you want to have a value in case of satisfiability. vars_of_interest must be a subset of the vars_to_keep passed to startIncrementalSession().
model_or_core An empty vector. Depending on the outcome of the call, either a satisfying assignment (a cube over the variables passed in vars_of_interest) or an unsatisfiable core (a subset of the literals passed in 'assumptions') will be written into this vector.
Returns
True in case of satisfiability (of the CNF of the incremental session in conjunction conjuncted with all assumptions), false otherwise.
Implements SatSolver.
Definition at line 331 of file MiniSatApi.cpp.
References c2m(), incr_stack_, m2c(), MASSERT, SatSolver::min_cores_, SatSolver::rand_models_, randModel(), and Utils::remove().
bool MiniSatApi::incIsSatModelOrCore (const vector< int > & core_assumptions, const vector< int > & more_assumptions, const vector< int > & vars_of_interest, vector< int > & model_or_core) [virtual]
Computes a satisfying assignment or core using additional assumptions.
In contrast to the previous method, this one allows to define two sets of assumptions. The core_assumptions are used as basis for extracting an unsatisfiable core in case of unsatisfiability. The more_assumptions are assumed but not considered for the computation of unsatisfiable cores. This is convenient to avoid calls to incPush() and incPop() when temporarily working under assumptions that should not be minimized for the unsatisfiable core.
Parameters
core_assumptions A vector of literals. This method then checks if the CNF of the incremental session is satisfiable given that all literals passed in this vector and all literals passed in more_assumptions are true. However, for computing the the unsatisfiable core, only the core_assumptions will be minimized and the more_assumptions stay as they are. That is, in case of unsatisfiability, model_or_core will contain a subset X of the core_assumptions such that X & more_assumptions & incremental_cnf is still unsatisfiable. core_assumptions must be a subset of the vars_to_keep passed to startIncrementalSession().
more_assumptions A vector of assumptions that are assumed, but not minimized when an unsatisfiable core is computed. That is, in case of unsatisfiability, model_or_core will contain a subset X of the core_assumptions such that X & more_assumptions & incremental_cnf is still unsatisfiable. more_assumptions must be a subset of the vars_to_keep passed to startIncrementalSession().
vars_of_interest The variables for which you want to have a value in case of satisfiability. vars_of_interest must be a subset of the vars_to_keep passed to startIncrementalSession().
model_or_core An empty vector. Depending on the outcome of the call, either a satisfying assignment (a cube over the variables passed in vars_of_interest) or an unsatisfiable core (a subset of the literals passed in 'core_assumptions') will be written into this vector.
Returns
True in case of satisfiability (of the CNF of the incremental session in conjunction conjuncted with all assumptions), false otherwise.
Implements SatSolver.
Definition at line 389 of file MiniSatApi.cpp.
References c2m(), incr_stack_, m2c(), MASSERT, SatSolver::min_cores_, SatSolver::rand_models_, randModel(), and Utils::remove().
void MiniSatApi::incPop () [virtual]
Restores the incremental session back to the point where incPush() was called.
Implements SatSolver.
Definition at line 483 of file MiniSatApi.cpp.
References incr_stack_, incr_stack_cnfs_, and MASSERT.
void MiniSatApi::incPush () [virtual]
Stores the current state of the incremental session on a stack.
The state can be restored later by calling incPop(). MiniSat does not support push and pop natively. Also, MiniSat does not allow to copy a a solver instance. Hence, we do a workaround: we create a new solver instance and feed it with the CNF that has been fed into the original solver instance. Clauses learned by the original solver are not transferred. For this to work, we track all clauses that are added to the original solver. This means some computational overhead. We can save this overhead if we tell startIncrementalSession() that incPush() will never be called.
Todo
Todo Try to improve this workaround with activation variables or by extracting the learned clauses from the original solver instance or by implementing a copy-function for MiniSat solver instances.
Implements SatSolver.
Definition at line 463 of file MiniSatApi.cpp.
References c2m(), incr_stack_, incr_stack_cnfs_, MASSERT, and use_push_.
bool MiniSatApi::isSat (const CNF & cnf) [virtual]
Checks if a CNF is satisfiable.
This method is not incremental. At aver call to this method, a new solver instance is created and deleted afterwards. This method does not interfere with an incremental session that may be open in parallel.
Parameters
cnf The CNF formula for which we want to know if it is satisfiable.
Returns
True in case of satisfiability, false otherwise.
Implements SatSolver.
Definition at line 129 of file MiniSatApi.cpp.
References c2m(), and CNF::getClauses().
Referenced by isSatModelOrCore().
bool MiniSatApi::isSatModelOrCore (const CNF & cnf, const vector< int > & assumptions, const vector< int > & vars_of_interest, vector< int > & model_or_core) [virtual]
Checks if a CNF is satisfiable and extracts a model or an unsatisfiable core.
This method is not incremental. At aver call to this method, a new solver instance is created and deleted afterwards. This method does not interfere with an incremental session that may be open in parallel. This method checks if the passed CNF is satisfiable given that all literals passed in the vector 'assumptions' is true. If this is the case, then a satisfying assignment will be written into model_or_core. You can specify which variables you want to have in the satisfying assignment using the vars_of_interest vector. The reason is that you CNF may contain thousands of temporary variables stemming from some Tseitin encoding, but usually one in only interested in the value of a few variables. In case of unsatisfiability, an unsatisfiable core is stored in model_or_core. The unsatisfiable core is a subset of the literals passed in 'assumptions' such that the CNF is still unsatisfiable when these literals hold.
Parameters
cnf The CNF formula for which we want to know if it is satisfiable (in conjunction with the assumptions).
assumptions A vector of literals. These literals are conjuncted to the CNF before solving. If you do not have any assumptions but want to decide the satisfiability of the cnf only, then simply leave this vector empty.
vars_of_interest The variables for which you want to have a value in case of satisfiability.
model_or_core An empty vector. Depending on the outcome of the call, either a satisfying assignment (a cube over the variables passed in vars_of_interest) or an unsatisfiable core (a subset of the literals passed in 'assumptions') will be written into this vector.
Returns
True in case of satisfiability (of the CNF conjuncted with all assumptions), false otherwise.
Implements SatSolver.
Definition at line 144 of file MiniSatApi.cpp.
References CNF::add1LitClause(), c2m(), CNF::getClauses(), isSat(), m2c(), SatSolver::min_cores_, SatSolver::rand_models_, randModel(), and Utils::remove().
MiniSatApi& MiniSatApi::operator= (const MiniSatApi & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
void MiniSatApi::startIncrementalSession (const vector< int > & vars_to_keep, bool use_push = true) [virtual]
Starts a new incremental session.
Every instance of this class can have at most one open incremental session. If there is an old open incremental session it will be closed before. An incremental session allows you to execute sequences of calls, where the information the solver learned in previous calls is retained and may speedup later calls. You can add new clauses between calls, but you cannot remove clauses.
Parameters
vars_to_keep A set of variables the solver should not optimize away. Clauses added later in an incremental session can only talk about variables contained in this vector. The MiniSatApi actually completely ignores these variables. However, other SatSolver implementations require this information, so it must be provided in any case (otherwise we could not exchange one SatSolver implementation by another one).
use_push A hint to the solver if you are ever going to use incPush() or incPop(). This information is particularly important for the MiniSatApi (other implementations of the SatSolver interface may ignore this information). The reason is that MiniSat does not support push and pop natively. Also, one cannot easily copy the entire solver. Therefore, we do a workaround to support push and pop. However, this workaround is expensive and we can safe some computation time if we skip it when we will not need it.
Implements SatSolver.
Definition at line 206 of file MiniSatApi.cpp.
References clearIncrementalSession(), incr_stack_, incr_stack_cnfs_, and use_push_.
Member Data Documentation
list<Minisat::Solver*> MiniSatApi::incr_stack_ [protected]
A stack of incremental session contexts.
The incremental session is store on a stack to support incPush() and incPop(). The current session is always at the top of the stack (the end of the list).
Definition at line 398 of file MiniSatApi.h.
Referenced by clearIncrementalSession(), incAdd2LitClause(), incAdd3LitClause(), incAddClause(), incAddCNF(), incAddCube(), incAddNegCubeAsClause(), incAddUnitClause(), incIsSat(), incIsSatModelOrCore(), incPop(), incPush(), and startIncrementalSession().
list<CNF*> MiniSatApi::incr_stack_cnfs_ [protected]
A CNFs that are stored in the incremental session contexts.
This is used for our workaround to support incPush() and incPop(). The current CNF is always at the top of the stack (the end of the list).
Definition at line 406 of file MiniSatApi.h.
Referenced by clearIncrementalSession(), incAdd2LitClause(), incAdd3LitClause(), incAddClause(), incAddCNF(), incAddCube(), incAddNegCubeAsClause(), incAddUnitClause(), incPop(), incPush(), and startIncrementalSession().
bool SatSolver::min_cores_ [protected], [inherited]
Indicates if the unsat cores returned by the solver should be minimized further.
Definition at line 428 of file SatSolver.h.
Referenced by SatSolver::doMinCores(), LingelingApi::incIsSatModelOrCore(), PicoSatApi::incIsSatModelOrCore(), incIsSatModelOrCore(), LingelingApi::isSatModelOrCore(), PicoSatApi::isSatModelOrCore(), and isSatModelOrCore().
bool SatSolver::rand_models_ [protected], [inherited]
Indicates if satisfying assignments should be randomized.
Definition at line 433 of file SatSolver.h.
Referenced by SatSolver::doRandModels(), LingelingApi::incIsSatModelOrCore(), PicoSatApi::incIsSatModelOrCore(), incIsSatModelOrCore(), LingelingApi::isSatModelOrCore(), PicoSatApi::isSatModelOrCore(), and isSatModelOrCore().
bool MiniSatApi::use_push_ [protected]
A flag indicating if incPush() and incPop() are ever going to be used.
If this flag is set to false, we do not track the CNFs in the incremental solver instances in incr_stack_cnfs_.
Definition at line 414 of file MiniSatApi.h.
Referenced by incAdd2LitClause(), incAdd3LitClause(), incAddClause(), incAddCNF(), incAddCube(), incAddNegCubeAsClause(), incAddUnitClause(), incPush(), and startIncrementalSession().
The documentation for this class was generated from the following files:
src/MiniSatApi.h
src/MiniSatApi.cpp