QBFSolver Class Reference
An abstract interface for all QBF-solver implementations.
#include <QBFSolver.h>
Public Types
enum Quant { E,
A
 }
A type for the different kinds of quantifiers.
Public Member Functions
QBFSolver ()
Constructor.
virtual ~QBFSolver ()
Destructor.
virtual bool isSat (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)=0
Checks if a given QBF is satisfiable (with quantification over variable kinds).
virtual bool isSat (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)=0
Checks if a given QBF is satisfiable (with quantification over variable sets).
virtual bool isSatModel (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf, vector< int > &model)=0
Checks satisfiability and extracts a model (quantifying over variable kinds).
virtual bool isSatModel (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf, vector< int > &model)=0
Checks satisfiability and extracts a model (quantifying over variable sets).
Private Member Functions
QBFSolver (const QBFSolver &other)
Copy constructor.
QBFSolver & operator= (const QBFSolver &other)
Assignment operator.
Detailed Description
An abstract interface for all QBF-solver implementations.
This class represents an abstract interface all QBF-solver instances. You cannot instantiate objects of this class. You need to instantiate objects of one of the derived classes (e.g., DepQBFApi, DepQBFExt, QuBEExt) instead. For a given Quantified Boolean formula (a CNF with a quantifier prefix), a QBFSolver is able to determine satisfiability. Furthermore, in case of satisfiability, it can extract satisfying assignments for variables quantified existentially on the outermost level.
Definition at line 49 of file QBFSolver.h.
Member Enumeration Documentation
enum QBFSolver::Quant
A type for the different kinds of quantifiers.
Enumerator:
E
 The value for existential quantification.
A
 The value for universal quantification.
Definition at line 56 of file QBFSolver.h.
Constructor & Destructor Documentation
QBFSolver::QBFSolver ()
Constructor.
Definition at line 33 of file QBFSolver.cpp.
QBFSolver::~QBFSolver () [virtual]
Destructor.
Definition at line 39 of file QBFSolver.cpp.
QBFSolver::QBFSolver (const QBFSolver & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
virtual bool QBFSolver::isSat (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [pure virtual]
Checks if a given QBF is satisfiable (with quantification over variable kinds).
The QBF consists of a quantifier prefix and a Boolean formula in CNF. The quantifier prefix assigns an existential or universal quantifier to every kind of variable.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Returns
True if the QBF is satisfiable, false otherwise.
Implemented in DepQBFApi, and ExtQBFSolver.
Referenced by Utils::debugCheckWinReg(), LearnSynthQBFInd::debugCheckWinRegReach(), LearnSynthQBF::generalizeCounterexample(), LearnSynthQBFInd::generalizeCounterexample(), ClauseMinimizerQBF::minimizeClauses(), LearnSynthQBF::reduceExistingClauses(), LearnSynthQBFInd::reduceExistingClauses(), and LearningImplExtractor::runLearningQBF().
virtual bool QBFSolver::isSat (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [pure virtual]
Checks if a given QBF is satisfiable (with quantification over variable sets).
The QBF consists of a quantifier prefix and a Boolean formula in CNF. The quantifier prefix assigns an existential or universal quantifier to different sets variable.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Returns
True if the QBF is satisfiable, false otherwise.
Implemented in DepQBFApi, and ExtQBFSolver.
virtual bool QBFSolver::isSatModel (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf, vector< int > & model) [pure virtual]
Checks satisfiability and extracts a model (quantifying over variable kinds).
Just like isSat() , this method checks a quantified Boolean formula for satisfiability. If the QBF is satisfiable, this method also extracts a model (a satisfying assignment) for all variables which are quantified existentially on the outermost level. The model is provided as cube: negated variables in the cube are FALSE, unnegated ones are TRUE.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
model The resulting model in form of a cube in case of satisfiability. Negated variables in the cube are FALSE, unnegated ones are TRUE. If the formula is unsatisfiable (this method returns false) then this parameter is not modified.
Returns
True if the QBF is satisfiable, false otherwise.
Implemented in DepQBFApi, and ExtQBFSolver.
Referenced by LearnSynthQBF::computeCounterexampleQBF(), LearnSynthQBFInd::computeCounterexampleQBF(), TemplateSynth::findWinRegCNFTempl(), and LearningImplExtractor::runLearningQBF().
virtual bool QBFSolver::isSatModel (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf, vector< int > & model) [pure virtual]
Checks satisfiability and extracts a model (quantifying over variable sets).
Just like isSat() , this method checks a quantified Boolean formula for satisfiability. If the QBF is satisfiable, this method also extracts a model (a satisfying assignment) for all variables which are quantified existentially on the outermost level. The model is provided as cube: negated variables in the cube are FALSE, unnegated ones are TRUE.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
model The resulting model in form of a cube in case of satisfiability. Negated variables in the cube are FALSE, unnegated ones are TRUE. If the formula is unsatisfiable (this method returns false) then this parameter is not modified.
Returns
True if the QBF is satisfiable, false otherwise.
Implemented in DepQBFApi, and ExtQBFSolver.
QBFSolver& QBFSolver::operator= (const QBFSolver & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
The documentation for this class was generated from the following files:
src/QBFSolver.h
src/QBFSolver.cpp