FileUtils Class Reference
Contains utility functions for access to files.
#include <FileUtils.h>
Public Member Functions
virtual ~FileUtils ()
Destructor.
Static Public Member Functions
static bool fileExists (const string &file_name)
Checks if a file exists.
static bool readFile (const string &file_name, string &file_content)
Reads the content of a file into a string.
static bool writeFile (const string &file_name, const string &file_content)
Writes the content of a string into a file.
Private Member Functions
FileUtils ()
Constructor.
FileUtils (const FileUtils &other)
Copy constructor.
FileUtils & operator= (const FileUtils &other)
Assignment operator.
Detailed Description
Contains utility functions for access to files.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.0.0
Definition at line 42 of file FileUtils.h.
Constructor & Destructor Documentation
FileUtils::~FileUtils () [virtual]
Destructor.
Definition at line 85 of file FileUtils.cpp.
FileUtils::FileUtils () [private]
Constructor.
The constructor is private and not implemented. Use the static methods.
FileUtils::FileUtils (const FileUtils & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
bool FileUtils::fileExists (const string & file_name) [static]
Checks if a file exists.
Parameters
file_name The name of the file to check.
Returns
True if the file exists (and could be opened), false otherwise.
Definition at line 33 of file FileUtils.cpp.
FileUtils& FileUtils::operator= (const FileUtils & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
bool FileUtils::readFile (const string & file_name, string & file_content) [static]
Reads the content of a file into a string.
Parameters
file_name The name of the file to read.
file_content The read file content is appended to this string.
Returns
True if file reading was successful, false otherwise (e.g. because the file does not exist, could not be opened, etc.)
Definition at line 42 of file FileUtils.cpp.
References MASSERT.
Referenced by ExtQBFSolver::parseModel(), DepQBFExt::qbfCert(), and EPRSynthesizer::run().
bool FileUtils::writeFile (const string & file_name, const string & file_content) [static]
Writes the content of a string into a file.
If the file already exists, it is overwritten. The directory into which the file should be written must exist.
Parameters
file_name The name of the file to write.
file_content The content to write into this file.
Returns
True if writing was successful, false otherwise.
Definition at line 71 of file FileUtils.cpp.
Referenced by EPRSynthesizer::run().
The documentation for this class was generated from the following files:
src/FileUtils.h
src/FileUtils.cpp