CounterGenSAT Class Reference
Takes counterexamples found by other threads and computes all generalizations.
#include <ParallelLearner.h>
Public Member Functions
CounterGenSAT (ParallelLearner &coordinator)
Constructor if optimization RG is disabled.
CounterGenSAT (ParallelLearner &coordinator, const CNF &prev_trans_or_initial, const vector< int > &current_to_previous_map, int current_state_is_initial)
Constructor if optimization RG is enabled.
virtual ~CounterGenSAT ()
Destructor.
void generalizeCounterexamples ()
The work-horse of this class.
void notifyNewWinRegClause (const vector< int > &clause, int src)
Notifies this worker about a new winning region clause.
const LearnStatisticsSAT & getStatistics () const
Returns the statistics and performance measures computed by this object.
Protected Member Functions
bool generalizeCounterexample (vector< int > &state_cube, const vector< int > &in_cube)
Generalizes a counterexample.
void generalizeCeFuther (vector< int > &core, const vector< int > &in_cube)
Generalizes a generalized counterexample further using optimization RG.
void bored ()
Called if there are no more counterexamples to generalize.
void compressBored ()
Reduces the counterexample that are considered for further generalization.
void considerNewInfoFromOthers ()
Considers new winning region clauses that have been found by other threads.
int presentToPrevious (int literal) const
Returns the previous-state copy of a literal.
void presentToPrevious (vector< int > &cube_or_clause) const
Computes the previous-state copy of a cube or clause.
void presentToPrevious (CNF &cnf) const
Computes the previous-state copy of a CNF.
Protected Attributes
bool use_ind_
A flag indicating if optimization RG should be used.
ParallelLearner & coordinator_
A reference to the coordinator.
CNF new_win_reg_clauses_
All new winning region clauses that have not been considered yet.
mutex new_win_reg_clauses_lock_
A lock that protects the new_win_reg_clauses_ from race-conditions.
vector< int > vars_to_keep_
A set of variables the solver should not optimize by the SAT-solver.
SatSolver * solver_ctrl_
The solver for checking counterexample-candidates.
SatSolver * solver_win_
An incremental SatSolver containing the winning region.
CNF prev_trans_or_initial_
Says: the current state is initial or the previous transition relation holds.
vector< int > current_to_previous_map_
A map from present-state variables to their previous-state copy.
int current_state_is_initial_
Says: the current state is initial or the previous transition relation holds.
SatSolver * solver_ctrl_ind_
The solver for generalizing counterexamples if optimization RG is enabled.
int prev_safe_
A literal saying that the previous-state is safe.
LearnStatisticsSAT statistics_
Stores and maintains statistics and performance measures.
vector< pair< vector< int >
*
, vector< int > > > do_if_bored_
The counterexamples to generalize further whenever we are bored.
size_t next_bored_index_
The index (in do_if_bored_) of the next item to process if bored.
size_t last_bored_compress_size_
The size of do_if_bored_ when we compressed it the last time.
Private Member Functions
CounterGenSAT (const CounterGenSAT &other)
Copy constructor.
CounterGenSAT & operator= (const CounterGenSAT &other)
Assignment operator.
Detailed Description
Takes counterexamples found by other threads and computes all generalizations.
A counterexample is a state-input combination with which the antagonist can enforce to leave the winning region. A generalization is a state-cube from which the antagonist can enforce to leave the winning region with this input. This class takes counterexamples found by other threads and computes all minimal generalizations. The negation of a generalization is a clause over the state-variables, which is added to the winning region. The counterexamples to generalize are read out of the ParallelLearner's database. If there are no more counterexamples left in this database (this class removes counterexamples after processing them), then this class is bored. When this class is bored, it takes counterexample generalizations that have been computed earlier and tries to generalize them further by dropping even more literals.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.1.0
Definition at line 852 of file ParallelLearner.h.
Constructor & Destructor Documentation
CounterGenSAT::CounterGenSAT (ParallelLearner & coordinator)
Constructor if optimization RG is disabled.
Parameters
coordinator A reference to the coordinator. All communication to other worker-threads is done via the coordinator.
Definition at line 873 of file ParallelLearner.cpp.
References do_if_bored_.
CounterGenSAT::CounterGenSAT (ParallelLearner & coordinator, const CNF & prev_trans_or_initial, const vector< int > & current_to_previous_map, int current_state_is_initial)
Constructor if optimization RG is enabled.
Parameters
coordinator A reference to the coordinator. All communication to other worker-threads is done via the coordinator.
prev_trans_or_initial A CNF that says: the current state is initial or the previous transition relation holds. This is an important building block for the CNF to generalize counterexamples if optimization RG is enabled. This CNF is computed only once by the ParallelLearner and passed to all CounterGenSAT instances.
current_to_previous_map A map from present-state variables to their previous-state copy. This map is computed only once by the ParallelLearner and passed to all CounterGenSAT instances.
current_state_is_initial A literal that is true if the current state is initial and false otherwise. The clauses assigning the literal are part of prev_trans_or_initial.
Definition at line 889 of file ParallelLearner.cpp.
References do_if_bored_.
CounterGenSAT::~CounterGenSAT () [virtual]
Destructor.
Definition at line 910 of file ParallelLearner.cpp.
References solver_ctrl_, solver_ctrl_ind_, and solver_win_.
CounterGenSAT::CounterGenSAT (const CounterGenSAT & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void CounterGenSAT::bored () [protected]
Called if there are no more counterexamples to generalize.
We want to do something useful with the computation time nevertheless. And what this function does is the following: it takes counterexamples that have been generalized before and tries to generalize them further. This could be possible because the winning region has been refined in the meantime.
Definition at line 1123 of file ParallelLearner.cpp.
References CE_GEN, compressBored(), coordinator_, do_if_bored_, generalizeCeFuther(), SatSolver::incIsSat(), last_bored_compress_size_, Utils::negateLiterals(), next_bored_index_, ParallelLearner::notifyNewWinRegClause(), ParallelLearner::result_, solver_win_, and UNKNOWN.
Referenced by generalizeCounterexamples().
void CounterGenSAT::compressBored () [protected]
Reduces the counterexample that are considered for further generalization.
The counterexamples considered for further generalization are stored in do_if_bored_. Similar to Utils::compressStateCNF() we remove all counterexamples that are implied by others anyway.
Definition at line 1152 of file ParallelLearner.cpp.
References coordinator_, do_if_bored_, Options::getSATSolver(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incIsSat(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), last_bored_compress_size_, next_bored_index_, VarInfo::PRES_STATE, ParallelLearner::result_, SatSolver::startIncrementalSession(), and UNKNOWN.
Referenced by bored().
void CounterGenSAT::considerNewInfoFromOthers () [protected]
Considers new winning region clauses that have been found by other threads.
Definition at line 1210 of file ParallelLearner.cpp.
References CNF::clear(), CNF::getNrOfClauses(), SatSolver::incAddCNF(), new_win_reg_clauses_, new_win_reg_clauses_lock_, presentToPrevious(), solver_ctrl_, solver_ctrl_ind_, solver_win_, CNF::swapPresentToNext(), and use_ind_.
Referenced by generalizeCeFuther(), and generalizeCounterexample().
void CounterGenSAT::generalizeCeFuther (vector< int > & core, const vector< int > & in_cube) [protected]
Generalizes a generalized counterexample further using optimization RG.
Optimization RG is explained in LearnSynthQBFInd.
Parameters
core The state-part of the counterexample. This is a state-cube (representing a set of states) for which the input in in_cube ensures that the winning region is left. It will be overwritten by its own generalization. The result will be a subset of the state-literals such that in_cube still ensures that the winning region is left, for all states in the generalized cube, or the state is unreachable.
in_cube The input vector which ensures that the winning region is left when starting from state_cube.
Definition at line 1080 of file ParallelLearner.cpp.
References considerNewInfoFromOthers(), current_state_is_initial_, SatSolver::incAddCube(), SatSolver::incAddNegCubeAsClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), SatSolver::incPop(), SatSolver::incPush(), MASSERT, presentToPrevious(), Utils::remove(), solver_ctrl_, solver_ctrl_ind_, Utils::swapPresentToNext(), and use_ind_.
Referenced by bored(), generalizeCounterexample(), and generalizeCounterexamples().
bool CounterGenSAT::generalizeCounterexample (vector< int > & state_cube, const vector< int > & in_cube) [protected]
Generalizes a counterexample.
This method may call generalizeCeFuther() if optimization RG is enabled.
Parameters
state_cube The state-part of the counterexample. This is a state for which the input in in_cube ensures that the winning region is left. It will be overwritten by its own generalization. The result will be a subset of the state-literals such that in_cube still ensures that the winning region is left, for all states in the generalized cube.
in_cube The input vector which ensures that the winning region is left when starting from state_cube.
Returns
True if in_cube ensures that the winning region is left from all states of state_cube (if this is a counterexample, i.e., if a generalization exists). False otherwise.
Definition at line 1065 of file ParallelLearner.cpp.
References considerNewInfoFromOthers(), generalizeCeFuther(), SatSolver::incIsSatModelOrCore(), solver_ctrl_, and use_ind_.
Referenced by generalizeCounterexamples().
void CounterGenSAT::generalizeCounterexamples ()
The work-horse of this class.
It Takes counterexamples found by other threads and computes all generalizations. A counterexample is a state-input combination with which the antagonist can enforce to leave the winning region. A generalization is a state-cube from which the antagonist can enforce to leave the winning region with this input. This class takes counterexamples found by other threads and computes all minimal generalizations. The negation of a generalization is a clause over the state-variables, which is added to the winning region. The counterexamples to generalize are read out of the ParallelLearner's database. If there are no more counterexamples left in this database (this class removes counterexamples after processing them), then this class is bored. When this class is bored, it takes counterexample generalizations that have been computed earlier and tries to generalize them further by dropping even more literals. In every iteration, this method also considers all new incoming clauses found by others. If it finds out that the specification is realizable or unrealizable, it sets the flag ParallelLearner::result_ accordingly. It also polls this flag regularly. If it has been set by some other thread, it quits.
Definition at line 921 of file ParallelLearner.cpp.
References bored(), CE_GEN, Utils::containsInit(), coordinator_, ParallelLearner::counterexamples_, ParallelLearner::counterexamples_lock_, do_if_bored_, Utils::extract(), generalizeCeFuther(), generalizeCounterexample(), AIG2CNF::getNextSafeStates(), AIG2CNF::getSafeStates(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddUnitClause(), SatSolver::incIsSat(), VarInfo::INPUT, VarManager::instance(), AIG2CNF::instance(), Utils::intersectionEmpty(), Utils::negateLiterals(), LearnStatisticsSAT::notifyAfterCheckCandidateFailed(), LearnStatisticsSAT::notifyAfterCheckCandidateFound(), LearnStatisticsSAT::notifyBeforeCheckCandidate(), ParallelLearner::notifyNewWinRegClause(), VarInfo::PRES_STATE, prev_safe_, prev_trans_or_initial_, Utils::remove(), ParallelLearner::result_, solver_ctrl_, solver_ctrl_ind_, solver_win_, SatSolver::startIncrementalSession(), statistics_, UNKNOWN, UNREALIZABLE, use_ind_, and vars_to_keep_.
Referenced by ParallelLearner::run().
const LearnStatisticsSAT & CounterGenSAT::getStatistics () const
Returns the statistics and performance measures computed by this object.
It is used by the ParallelLearner to merge the statistics of the different workers.
Returns
The statistics and performance measures computed by this object.
Definition at line 1059 of file ParallelLearner.cpp.
References statistics_.
void CounterGenSAT::notifyNewWinRegClause (const vector< int > & clause, int src)
Notifies this worker about a new winning region clause.
Parameters
clause The new clause that has been discovered.
src An integer number defining which kind of worker-thread discovered the clause. At the moment, this information is ignored.
Definition at line 1051 of file ParallelLearner.cpp.
References CNF::addClause(), new_win_reg_clauses_, and new_win_reg_clauses_lock_.
CounterGenSAT& CounterGenSAT::operator= (const CounterGenSAT & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
int CounterGenSAT::presentToPrevious (int literal) const [protected]
Returns the previous-state copy of a literal.
Parameters
literal The literal to transform.
Returns
The previous-state copy of a literal.
Definition at line 1235 of file ParallelLearner.cpp.
References current_to_previous_map_.
Referenced by considerNewInfoFromOthers(), generalizeCeFuther(), and presentToPrevious().
void CounterGenSAT::presentToPrevious (vector< int > & cube_or_clause) const [protected]
Computes the previous-state copy of a cube or clause.
Parameters
cube_or_clause A cube or clause (in form of a vector of literals) over the present state variables. This vector is overwritten by the corresponding cube of clause over the previous-state literals (i.e., all literals are replaced by their previous-state copy).
Definition at line 1245 of file ParallelLearner.cpp.
References presentToPrevious().
void CounterGenSAT::presentToPrevious (CNF & cnf) const [protected]
Computes the previous-state copy of a CNF.
Parameters
cnf A CNF formula over the present state variables. This CNF is overwritten by the corresponding CNF over the previous-state literals (i.e., all literals are replaced by their previous-state copy).
Definition at line 1252 of file ParallelLearner.cpp.
References CNF::addClause(), CNF::clear(), CNF::getClauses(), and presentToPrevious().
Member Data Documentation
ParallelLearner& CounterGenSAT::coordinator_ [protected]
A reference to the coordinator.
All communication to other worker-threads is done via the coordinator.
Definition at line 1030 of file ParallelLearner.h.
Referenced by bored(), compressBored(), and generalizeCounterexamples().
int CounterGenSAT::current_state_is_initial_ [protected]
Says: the current state is initial or the previous transition relation holds.
This CNF expresses that the current state is initial or the previous-state copy of the transition relation holds. This is an important building block for the CNF to generalize counterexamples if optimization RG is enabled. If optimization RG is disabled, then this field is meaningless.
Definition at line 1092 of file ParallelLearner.h.
Referenced by generalizeCeFuther().
vector<int> CounterGenSAT::current_to_previous_map_ [protected]
A map from present-state variables to their previous-state copy.
If optimization RG is disabled, then this CNF is empty.
Definition at line 1082 of file ParallelLearner.h.
Referenced by presentToPrevious().
vector<pair<vector<int>, vector<int> > > CounterGenSAT::do_if_bored_ [protected]
The counterexamples to generalize further whenever we are bored.
We are bored whenever the counterexample-database of the ParallelLearner does not contain any new counterexamples. All counterexample generalizations found by this class are written into this field. If we are bored, we try to generalize one of these counterexamples further. This is to utilize our computation time.
The first item of the pairs stored in this vectors is always the state-cube of the counterexample. The second item of the pair is the corresponding input-cube witnessing the fact that the successor state will be outside of the winning region.
Definition at line 1130 of file ParallelLearner.h.
Referenced by bored(), compressBored(), CounterGenSAT(), and generalizeCounterexamples().
size_t CounterGenSAT::last_bored_compress_size_ [protected]
The size of do_if_bored_ when we compressed it the last time.
This is just tracked for a heuristic that decides when to call compressBored() the next time.
Definition at line 1143 of file ParallelLearner.h.
Referenced by bored(), and compressBored().
CNF CounterGenSAT::new_win_reg_clauses_ [protected]
All new winning region clauses that have not been considered yet.
Definition at line 1035 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), and notifyNewWinRegClause().
mutex CounterGenSAT::new_win_reg_clauses_lock_ [protected]
A lock that protects the new_win_reg_clauses_ from race-conditions.
Many worker-threads modify the new_win_reg_clauses_ (add new ones). This lock ensures that only one thread is modifying or reading the new_win_reg_clauses_ at one time.
Definition at line 1043 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), and notifyNewWinRegClause().
size_t CounterGenSAT::next_bored_index_ [protected]
The index (in do_if_bored_) of the next item to process if bored.
Definition at line 1135 of file ParallelLearner.h.
Referenced by bored(), and compressBored().
int CounterGenSAT::prev_safe_ [protected]
A literal saying that the previous-state is safe.
We store this literal here and do not read it out of the VarManager again and again to avoid a concurrency issue. The VarManager is sometimes modified (new temporary variables are created). This does not affect the literal defining safe states. However, we do not want to lock reading-accesses to the variable manager and we do not want to read out the variable manager in an inconsistent state. Hence, we read it out once and store it. If optimization RG is disabled, then this field is meaningless.
Definition at line 1109 of file ParallelLearner.h.
Referenced by generalizeCounterexamples().
CNF CounterGenSAT::prev_trans_or_initial_ [protected]
Says: the current state is initial or the previous transition relation holds.
This CNF expresses that the current state is initial or the previous-state copy of the transition relation holds. This is an important building block for the CNF to generalize counterexamples if optimization RG is enabled. If optimization RG is disabled, then this CNF is empty.
Definition at line 1075 of file ParallelLearner.h.
Referenced by generalizeCounterexamples().
SatSolver* CounterGenSAT::solver_ctrl_ [protected]
The solver for checking counterexample-candidates.
It is also used to generalize counterexamples if optimization RG is disabled.
Definition at line 1057 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), generalizeCeFuther(), generalizeCounterexample(), generalizeCounterexamples(), and ~CounterGenSAT().
SatSolver* CounterGenSAT::solver_ctrl_ind_ [protected]
The solver for generalizing counterexamples if optimization RG is enabled.
Definition at line 1097 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), generalizeCeFuther(), generalizeCounterexamples(), and ~CounterGenSAT().
SatSolver* CounterGenSAT::solver_win_ [protected]
An incremental SatSolver containing the winning region.
It is mainly used to check if new clauses found by this class are already implied by other clauses in the winning region. If so, then the new clauses are not added.
Definition at line 1065 of file ParallelLearner.h.
Referenced by bored(), considerNewInfoFromOthers(), generalizeCounterexamples(), and ~CounterGenSAT().
LearnStatisticsSAT CounterGenSAT::statistics_ [protected]
Stores and maintains statistics and performance measures.
Basically, this is a merge of the statistics from all worker-threads.
Definition at line 1116 of file ParallelLearner.h.
Referenced by generalizeCounterexamples(), and getStatistics().
bool CounterGenSAT::use_ind_ [protected]
A flag indicating if optimization RG should be used.
See LearnSynthQBFInd for an explanation.
Definition at line 1023 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), generalizeCeFuther(), generalizeCounterexample(), and generalizeCounterexamples().
vector<int> CounterGenSAT::vars_to_keep_ [protected]
A set of variables the solver should not optimize by the SAT-solver.
These are all variables except for temporary ones (type VarInfo::TMP).
Definition at line 1050 of file ParallelLearner.h.
Referenced by generalizeCounterexamples().
The documentation for this class was generated from the following files:
src/ParallelLearner.h
src/ParallelLearner.cpp