LearnSynthSAT Class Reference
Implements a learning-based synthesis using two SAT solvers.
#include <LearnSynthSAT.h>
Public Member Functions
LearnSynthSAT ()
Constructor.
virtual ~LearnSynthSAT ()
Destructor.
virtual bool run ()
Executes this back-end.
Protected Member Functions
bool computeWinningRegion ()
Computes the winning region and stores the result in winning_region_.
bool computeWinningRegionPlain ()
Uses the standard method to compute a winning region.
bool computeWinningRegionRG ()
Compute a winning region with optimization RG when generalizing counterexamples.
bool computeWinningRegionRGRC ()
Compute a winning region with optimization RG and RC enabled.
int presentToPrevious (int literal) const
Returns the previous-state copy of a literal.
void presentToPrevious (vector< int > &cube_or_clause) const
Computes the previous-state copy of a cube or clause.
void presentToPrevious (CNF &cnf) const
Computes the previous-state copy of a CNF.
void debugCheckWinReg ()
Checks a winning region computed with optimization RC for correctness.
Protected Attributes
LearnStatisticsSAT statistics_
Stores and maintains statistics and performance measures.
CNF winning_region_
The current over-approximation of the winning region.
CNF winning_region_large_
The current over-approximation of the winning region in an uncompressed form.
CNF prev_trans_or_initial_
Says: the current state is initial or the previous transition relation holds.
vector< int > current_to_previous_map_
A map from present-state variables to their previous-state copy.
int current_state_is_initial_
A literal that is true if the current state is initial and false otherwise.
CNF different_from_prev_or_initial_
Says: the current state is different from the previous one.
SatSolver * solver_i_
The solver for computing counterexample-candidates if optimization RC is disabled.
SatSolver * solver_ctrl_
The solver for checking counterexample-candidates.
SatSolver * solver_i_ind_
The solver for computing counterexample-candidates if optimization RC is enabled.
SatSolver * solver_ctrl_ind_
The solver for generalizing counterexamples if optimization RG is endabled.
Private Member Functions
LearnSynthSAT (const LearnSynthSAT &other)
Copy constructor.
LearnSynthSAT & operator= (const LearnSynthSAT &other)
Assignment operator.
Detailed Description
Implements a learning-based synthesis using two SAT solvers.
The working principle of the algorithm implemented in this class is very similar to LearnSynthQBF: We start by setting the winning region F to the set of all safe states P. In a loop, we first compute a counterexample to the correctness of this guess in form of a state from which the antagonist (controlling the uncontrollable inputs i) can enforce to leave F. The state is represented as a cube over all state-variables. Next, this state-cube is generalized into a larger region of states by dropping literals as long as the cube contains only states that are winning for the antagonist (and hence must be removed or have already been removed from F). Finally, the generalized cube is removed from F. The next iteration checks for counterexample-state on the refined F. This is repeated until no more counterexample-states exist (then the specification is realizable and F is a winning region) or the initial state has been removed from F (in which case the specification is unrealizable).
The difference to LearnSynthQBF is that this class uses two competing SAT-solvers to compute a counterexample. First, solver solver_i_ finds some input values i that could be chosen by the antagonist in order to leave the winning_region_. Next, solver_ctrl_ checks if there exists a response of the protagonist to chose control values c such that the winning region is not left. If no such response exists, then we have found a counterexample. Otherwise, we exclude the state-input combination found by solver_i_ (after generalizing it into a larger set of state-input pairs) and try again. There is also an optimization which allows to use solver_i_ incrementally: The next state-copy of the winning region is updated only lazily. Also the generalization of counterexamples is implemented with a QBF-solver instead of a SAT solver. Details and background can be found in the VMCAI'14 paper `SAT-Based
Synthesis Methods for Safety Specs`.
The procedure outlined above is implemented in computeWinningRegionPlain(). Some variants of this procedure are implemented in other methods of this class. The method computeWinningRegionRG() also uses inductive reachability reasoning in the generalization of counterexamples, just like LearnSynthQBFInd. The method computeWinningRegionRGRC() uses inductive reachability reasoning also during the computation or counterexamples. These extensions are described as optimization RG and optimization RC in the VMCAI'14 paper. Command-line parameters (--mode) decide which of these methods to use.
Finally the QBFCertImplExtractor is used to extract a circuit.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.0.0
Definition at line 84 of file LearnSynthSAT.h.
Constructor & Destructor Documentation
LearnSynthSAT::LearnSynthSAT ()
Constructor.
Definition at line 41 of file LearnSynthSAT.cpp.
References CNF::add2LitClause(), CNF::add3LitClause(), CNF::addClause(), VarManager::createFreshPrevVar(), VarManager::createFreshTmpVar(), VarInfo::CTRL, current_state_is_initial_, current_to_previous_map_, different_from_prev_or_initial_, CNF::getClauses(), VarManager::getMaxCNFVar(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), AIG2CNF::instance(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, presentToPrevious(), prev_trans_or_initial_, CNF::swapWith(), and VarInfo::TMP.
LearnSynthSAT::~LearnSynthSAT () [virtual]
Destructor.
Definition at line 104 of file LearnSynthSAT.cpp.
References solver_ctrl_, solver_ctrl_ind_, solver_i_, and solver_i_ind_.
LearnSynthSAT::LearnSynthSAT (const LearnSynthSAT & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
bool LearnSynthSAT::computeWinningRegion () [protected]
Computes the winning region and stores the result in winning_region_.
Depending on the command-line parameters (--mode) this method calls one of
computeWinningRegionPlain()
computeWinningRegionRG()
computeWinningRegionRGRC()
Returns
True if the specification was realizable, false otherwise.
Definition at line 152 of file LearnSynthSAT.cpp.
References computeWinningRegionPlain(), computeWinningRegionRG(), computeWinningRegionRGRC(), debugCheckWinReg(), Options::getBackEndMode(), Options::instance(), and winning_region_.
Referenced by run().
bool LearnSynthSAT::computeWinningRegionPlain () [protected]
Uses the standard method to compute a winning region.
The standard method works as described in the class description.
Returns
True if the specification was realizable, false otherwise.
Definition at line 178 of file LearnSynthSAT.cpp.
References CNF::addClauseAndSimplify(), CNF::addCNF(), CNF::clear(), Utils::compressStateCNF(), Utils::containsInit(), VarInfo::CTRL, SatSolver::doMinCores(), SatSolver::doRandModels(), Utils::extract(), AIG2CNF::getNextSafeStates(), AIG2CNF::getNextUnsafeStates(), AIG2CNF::getSafeStates(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incAddClause(), SatSolver::incAddCNF(), SatSolver::incIsSatModelOrCore(), VarInfo::INPUT, VarManager::instance(), AIG2CNF::instance(), L_DBG, MASSERT, CNF::negate(), LearnStatisticsSAT::notifyAfterCheckCandidateFailed(), LearnStatisticsSAT::notifyAfterCheckCandidateFound(), LearnStatisticsSAT::notifyAfterComputeCandidate(), LearnStatisticsSAT::notifyAfterRefine(), LearnStatisticsSAT::notifyBeforeCheckCandidate(), LearnStatisticsSAT::notifyBeforeComputeCandidate(), LearnStatisticsSAT::notifyBeforeRefine(), LearnStatisticsSAT::notifyRestart(), VarInfo::PRES_STATE, VarManager::resetToLastPush(), solver_ctrl_, solver_i_, SatSolver::startIncrementalSession(), statistics_, Utils::swapPresentToNext(), CNF::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
bool LearnSynthSAT::computeWinningRegionRG () [protected]
Compute a winning region with optimization RG when generalizing counterexamples.
Optimization RG is described in LearnSynthQBFInd already. In a nutshell, the generalization query is modified so a state that prevents generalization must be either initial or have a predecessor in F. Otherwise it is unreachable and we do not care. This means that we can remove states that are winning for the protagonist from the winning region of they are unreachalbe in the final implementation.
Returns
True if the specification was realizable, false otherwise.
Definition at line 326 of file LearnSynthSAT.cpp.
References CNF::addClauseAndSimplify(), CNF::addCNF(), CNF::clear(), Utils::compressStateCNF(), Utils::containsInit(), VarInfo::CTRL, current_state_is_initial_, current_to_previous_map_, SatSolver::doMinCores(), SatSolver::doRandModels(), Utils::extract(), VarManager::getAllNonTempVars(), AIG2CNF::getNextSafeStates(), AIG2CNF::getNextUnsafeStates(), VarManager::getPresErrorStateVar(), AIG2CNF::getSafeStates(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incAddClause(), SatSolver::incAddCNF(), SatSolver::incAddCube(), SatSolver::incAddNegCubeAsClause(), SatSolver::incAddUnitClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), SatSolver::incPop(), SatSolver::incPush(), VarInfo::INPUT, VarManager::instance(), AIG2CNF::instance(), L_DBG, MASSERT, CNF::negate(), LearnStatisticsSAT::notifyAfterCheckCandidateFailed(), LearnStatisticsSAT::notifyAfterCheckCandidateFound(), LearnStatisticsSAT::notifyAfterComputeCandidate(), LearnStatisticsSAT::notifyAfterRefine(), LearnStatisticsSAT::notifyBeforeCheckCandidate(), LearnStatisticsSAT::notifyBeforeComputeCandidate(), LearnStatisticsSAT::notifyBeforeRefine(), LearnStatisticsSAT::notifyRestart(), VarInfo::PRES_STATE, presentToPrevious(), prev_trans_or_initial_, Utils::remove(), VarManager::resetToLastPush(), solver_ctrl_, solver_ctrl_ind_, solver_i_, SatSolver::startIncrementalSession(), statistics_, Utils::swapPresentToNext(), CNF::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
bool LearnSynthSAT::computeWinningRegionRGRC () [protected]
Compute a winning region with optimization RG and RC enabled.
In addition to optimization RG (see computeWinningRegionRG()), this method also applies optimization RC as described in LearnSynthQBFInd. In a nutshell, the queries to compute counterexamples are modified in such a way that the counterexample-state is either initial or has a predecessor in the current over-approximation of the winning region. Otherwise, the state is unreachable and can be ignored.
Returns
True if the specification was realizable, false otherwise.
Definition at line 510 of file LearnSynthSAT.cpp.
References CNF::addClauseAndSimplify(), CNF::addCNF(), CNF::clear(), Utils::compressStateCNF(), Utils::containsInit(), VarInfo::CTRL, current_state_is_initial_, current_to_previous_map_, different_from_prev_or_initial_, SatSolver::doMinCores(), SatSolver::doRandModels(), Utils::extract(), VarManager::getAllNonTempVars(), AIG2CNF::getNextSafeStates(), AIG2CNF::getNextUnsafeStates(), VarManager::getPresErrorStateVar(), AIG2CNF::getSafeStates(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incAddClause(), SatSolver::incAddCNF(), SatSolver::incAddCube(), SatSolver::incAddNegCubeAsClause(), SatSolver::incAddUnitClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), SatSolver::incPop(), SatSolver::incPush(), VarInfo::INPUT, VarManager::instance(), AIG2CNF::instance(), L_DBG, MASSERT, CNF::negate(), LearnStatisticsSAT::notifyAfterCheckCandidateFailed(), LearnStatisticsSAT::notifyAfterCheckCandidateFound(), LearnStatisticsSAT::notifyAfterComputeCandidate(), LearnStatisticsSAT::notifyAfterRefine(), LearnStatisticsSAT::notifyBeforeCheckCandidate(), LearnStatisticsSAT::notifyBeforeComputeCandidate(), LearnStatisticsSAT::notifyBeforeRefine(), LearnStatisticsSAT::notifyRestart(), VarInfo::PRES_STATE, presentToPrevious(), prev_trans_or_initial_, Utils::remove(), VarManager::resetToLastPush(), solver_ctrl_, solver_ctrl_ind_, solver_i_, solver_i_ind_, SatSolver::startIncrementalSession(), statistics_, Utils::swapPresentToNext(), CNF::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
void LearnSynthSAT::debugCheckWinReg () [protected]
Checks a winning region computed with optimization RC for correctness.
We usually check the correctness of the winning region in debug-mode by calling Utils::debugCheckWinReg(). However, this method of Utils does not work for winning regions that have been computed with optimization RC enabled. In such cases we this method.
Definition at line 753 of file LearnSynthSAT.cpp.
References QBFSolver::A, CNF::addCNF(), CNF::clear(), VarInfo::CTRL, different_from_prev_or_initial_, QBFSolver::E, VarInfo::INPUT, AIG2CNF::instance(), DepQBFApi::isSat(), LingelingApi::isSat(), L_DBG, MASSERT, CNF::negate(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, presentToPrevious(), VarInfo::PREV, prev_trans_or_initial_, CNF::swapPresentToNext(), VarInfo::TMP, and winning_region_.
Referenced by computeWinningRegion().
LearnSynthSAT& LearnSynthSAT::operator= (const LearnSynthSAT & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
int LearnSynthSAT::presentToPrevious (int literal) const [protected]
Returns the previous-state copy of a literal.
Parameters
literal The literal to transform.
Returns
The previous-state copy of a literal.
Definition at line 723 of file LearnSynthSAT.cpp.
References current_to_previous_map_.
Referenced by computeWinningRegionRG(), computeWinningRegionRGRC(), debugCheckWinReg(), LearnSynthSAT(), and presentToPrevious().
void LearnSynthSAT::presentToPrevious (vector< int > & cube_or_clause) const [protected]
Computes the previous-state copy of a cube or clause.
Parameters
cube_or_clause A cube or clause (in form of a vector of literals) over the present state variables. This vector is overwritten by the corresponding cube of clause over the previous-state literals (i.e., all literals are replaced by their previous-state copy).
Definition at line 733 of file LearnSynthSAT.cpp.
References presentToPrevious().
void LearnSynthSAT::presentToPrevious (CNF & cnf) const [protected]
Computes the previous-state copy of a CNF.
Parameters
cnf A CNF formula over the present state variables. This CNF is overwritten by the corresponding CNF over the previous-state literals (i.e., all literals are replaced by their previous-state copy).
Definition at line 740 of file LearnSynthSAT.cpp.
References CNF::addClause(), CNF::clear(), CNF::getClauses(), and presentToPrevious().
bool LearnSynthSAT::run () [virtual]
Executes this back-end.
The working principle of this method is very similar to LearnSynthQBF::run(): We start by setting the winning region F to the set of all safe states P. In a loop, we first compute a counterexample to the correctness of this guess in form of a state from which the antagonist (controlling the uncontrollable inputs i) can enforce to leave F. The state is represented as a cube over all state-variables. Next, this state-cube is generalized into a larger region of states by dropping literals as long as the cube contains only states that are winning for the antagonist (and hence must be removed or have already been removed from F). Finally, the generalized cube is removed from F. The next iteration checks for counterexample-state on the refined F. This is repeated until no more counterexample-states exist (then the specification is realizable and F is a winning region) or the initial state has been removed from F (in which case the specification is unrealizable). The difference to LearnSynthQBF is that this method uses two competing SAT-solvers to compute a counterexample. First, solver solver_i_ finds some input values i that could be chosen by the antagonist in order to leave the winning_region_. Next, solver_ctrl_ checks if there exists a response of the protagonist to chose control values c such that the winning region is not left. If no such response exists, then we have found a counterexample. Otherwise, we exclude the state-input combination found by solver_i_ (after generalizing it into a larger set of state-input pairs) and try again. There is also an optimization which allows to use solver_i_ incrementally: The next state-copy of the winning region is updated only lazily. Also the generalization of counterexamples is implemented with a QBF-solver instead of a SAT solver. Details and background can be found in the VMCAI'14 paper `SAT-Based
Synthesis Methods for Safety Specs`.
Command-line parameters (--mode) are used to select different variants of this method. There is
the standard method as described above,
a variant which uses inductive reachability reasoning in the generalization of counterexamples, just like LearnSynthQBFInd (optimization 'RG')
a variant which uses inductive reachability reasoning also in the computation of counterexamples, just like LearnSynthQBFInd (optimization 'RG' and 'RC')
Returns
True if the specification was realizable, false otherwise.
Implements BackEnd.
Definition at line 117 of file LearnSynthSAT.cpp.
References computeWinningRegion(), QBFCertImplExtractor::extractCircuit(), VarManager::instance(), Options::instance(), L_INF, L_RES, LearnStatisticsSAT::logStatistics(), MASSERT, LearnStatisticsSAT::notifyRelDetEnd(), LearnStatisticsSAT::notifyRelDetStart(), LearnStatisticsSAT::notifyWinRegEnd(), LearnStatisticsSAT::notifyWinRegStart(), VarManager::push(), statistics_, and winning_region_.
Member Data Documentation
int LearnSynthSAT::current_state_is_initial_ [protected]
A literal that is true if the current state is initial and false otherwise.
The clauses assigning the literal are part of prev_trans_or_initial_.
Definition at line 271 of file LearnSynthSAT.h.
Referenced by computeWinningRegionRG(), computeWinningRegionRGRC(), and LearnSynthSAT().
vector<int> LearnSynthSAT::current_to_previous_map_ [protected]
A map from present-state variables to their previous-state copy.
Definition at line 264 of file LearnSynthSAT.h.
Referenced by computeWinningRegionRG(), computeWinningRegionRGRC(), LearnSynthSAT(), and presentToPrevious().
CNF LearnSynthSAT::different_from_prev_or_initial_ [protected]
Says: the current state is different from the previous one.
This CNF expresses that the current state is different from the previous state. This is an important building block for the CNF to compute counterexamples if optimization RC is enabled.
Definition at line 280 of file LearnSynthSAT.h.
Referenced by computeWinningRegionRGRC(), debugCheckWinReg(), and LearnSynthSAT().
CNF LearnSynthSAT::prev_trans_or_initial_ [protected]
Says: the current state is initial or the previous transition relation holds.
This CNF expresses that the current state is initial or the previous-state copy of the transition relation holds. This is an important building block for the CNF to compute or generalize counterexamples if optimization RG or RC is enabled.
Definition at line 259 of file LearnSynthSAT.h.
Referenced by computeWinningRegionRG(), computeWinningRegionRGRC(), debugCheckWinReg(), and LearnSynthSAT().
SatSolver* LearnSynthSAT::solver_ctrl_ [protected]
The solver for checking counterexample-candidates.
It is also used to generalize counterexamples if optimization RG is disabled.
Definition at line 292 of file LearnSynthSAT.h.
Referenced by computeWinningRegionPlain(), computeWinningRegionRG(), computeWinningRegionRGRC(), and ~LearnSynthSAT().
SatSolver* LearnSynthSAT::solver_ctrl_ind_ [protected]
The solver for generalizing counterexamples if optimization RG is endabled.
Definition at line 302 of file LearnSynthSAT.h.
Referenced by computeWinningRegionRG(), computeWinningRegionRGRC(), and ~LearnSynthSAT().
SatSolver* LearnSynthSAT::solver_i_ [protected]
The solver for computing counterexample-candidates if optimization RC is disabled.
Definition at line 285 of file LearnSynthSAT.h.
Referenced by computeWinningRegionPlain(), computeWinningRegionRG(), computeWinningRegionRGRC(), and ~LearnSynthSAT().
SatSolver* LearnSynthSAT::solver_i_ind_ [protected]
The solver for computing counterexample-candidates if optimization RC is enabled.
Definition at line 297 of file LearnSynthSAT.h.
Referenced by computeWinningRegionRGRC(), and ~LearnSynthSAT().
LearnStatisticsSAT LearnSynthSAT::statistics_ [protected]
Stores and maintains statistics and performance measures.
Definition at line 230 of file LearnSynthSAT.h.
Referenced by computeWinningRegionPlain(), computeWinningRegionRG(), computeWinningRegionRGRC(), and run().
CNF LearnSynthSAT::winning_region_ [protected]
The current over-approximation of the winning region.
Only when computeWinningRegion() is done, this field will store the correct winning region.
Definition at line 238 of file LearnSynthSAT.h.
Referenced by computeWinningRegion(), computeWinningRegionPlain(), computeWinningRegionRG(), computeWinningRegionRGRC(), debugCheckWinReg(), and run().
CNF LearnSynthSAT::winning_region_large_ [protected]
The current over-approximation of the winning region in an uncompressed form.
This CNF is logically equivalent to winning_region_. However, winning_region_ is 'compressed' from time to time by removing redundant clauses (clauses that are implied by other clauses in the winning region). This field stores the uncompressed version of the winning region. Having the uncompressed winning region can be good because throwing away redundant clauses is not always beneficial. The CNF get smaller, but the solver may have to re-discover the removed clauses.
Definition at line 250 of file LearnSynthSAT.h.
Referenced by computeWinningRegionPlain(), computeWinningRegionRG(), and computeWinningRegionRGRC().
The documentation for this class was generated from the following files:
src/LearnSynthSAT.h
src/LearnSynthSAT.cpp