Utils Class Reference
Contains utility functions that can be usful in various back-ends.
#include <Utils.h>
Static Public Member Functions
static bool containsInit (const vector< int > &cube)
Checks if a cube (in form of a vector of literals) contains the initial state.
static bool containsInit (const set< int > &cube)
Checks if a cube (in form of a set of literals) contains the initial state.
static vector< int > extract (const vector< int > &cube_or_clause, VarInfo::VarKind kind)
Extracts literals that are of a given type from a cube or clause.
static vector< int > extractPresIn (const vector< int > &cube_or_clause)
Extracts present-state literals and input literals from a cube or clause.
static vector< int > extractNextAsPresent (const vector< int > &cube_or_clause)
Extracts next-state literals and returns the present-state copy.
static vector< int > extract (const vector< int > &cube_or_clause, const vector< int > &vars)
Extracts certain literals from a cube or clause.
static void randomize (vector< int > &vec)
Randomizes the order (not the value) of a given vector of integers.
static void sort (vector< int > &vec)
Sorts a vector of integers in ascending order.
static bool remove (vector< int > &vec, int elem)
Removes a certain element from a vector.
static bool contains (const vector< int > &vec, int elem)
Checks if a vector contains a certain element.
static bool eq (const vector< int > &v1, const vector< int > &v2, int start_idx=0)
Checks if two vectors contain the same set of elements.
static void negateLiterals (vector< int > &cube_or_clause)
Negates all literals in a cube or clause.
static void swapPresentToNext (vector< int > &vec)
Replaces all current-state literals by their next-state copy.
static bool intersectionEmpty (const vector< int > &x, const set< int > &y)
Checks if a vector and a set have an empty intersection.
static bool intersectionEmpty (const set< int > &x, const set< int > &y)
Checks if the intersection of two sets is empty.
static bool isSubset (const vector< int > &subset, const vector< int > &superset)
Checks if one vector forms a subset of another one.
static bool compressStateCNF (CNF &cnf, bool hardcore=false)
Compresses a state-CNF by removing clauses that are implied by others.
static void negateStateCNF (CNF &cnf)
Negates a CNF over the state-variables without introducing temporary variables.
static void negateViaAig (CNF &cnf)
Negates a CNF by transforming into AIGER and back.
static void compressNextStateCNF (CNF &ps_cnf, CNF &ns_cnf, bool hardcore=false)
Compresses a state-CNF by removing implied clauses and computes the next-state CNF.
static size_t getCurrentMemUsage ()
Returns the current memory usage as debug message in kB.
static void debugPrint (const vector< int > &vec, string prefix=``)
Prints a vector of literals (mainly for debugging purposes).
static void debugCheckWinReg (const CNF &winning_region)
Checks a winning region for correctness.
static void debugCheckWinReg (const CNF &winning_region, const CNF &neg_winning_region)
Checks a winning region and its negation for correctness.
static void debugPrintCurrentMemUsage ()
Prints the current memory usage as debug message.
Private Member Functions
Utils ()
Constructor.
virtual ~Utils ()
Constructor.
Utils (const Utils &other)
Copy constructor.
Utils & operator= (const Utils &other)
Assignment operator.
Detailed Description
Contains utility functions that can be usful in various back-ends.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 45 of file Utils.h.
Constructor & Destructor Documentation
Utils::Utils () [private]
Constructor.
The constructor is private and not implemented. Use the static methods.
virtual Utils::~Utils () [private], [virtual]
Constructor.
The constructor is private and not implemented. Use the static methods.
Utils::Utils (const Utils & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void Utils::compressNextStateCNF (CNF & ps_cnf, CNF & ns_cnf, bool hardcore = false) [static]
Compresses a state-CNF by removing implied clauses and computes the next-state CNF.
This method is similar to compressStateCNF(). The difference is that this method also computes a compact representation of the next-state copy of passed state-CNF. When compressing the next-state copy, clauses are removed if they are already implied by existing clauses or the present-state copy of the CNF. That is, the compression of the next-state copy is only valid if the current-state copy is going to be asserted in the solver.
Parameters
ps_cnf The CNF formula to compress. We assume that this CNF only talks about the present-state variables. This CNF is compressed, similar as done by compressStateCNF().
ns_cnf An empty CNF. This CNF is filled with the compression of the next-state copy of ps_cnf. The resulting ns_cnf is only valid under the assumption that ps_cnf is asserted.
hardcore Set this parameter to true if you do not only want to remove clauses but also literals from clauses. This is more expensive, but can produce smaller CNF representations.
Definition at line 502 of file Utils.cpp.
References CNF::addClause(), CNF::addNegCubeAsClause(), CNF::clear(), VarManager::getAllNonTempVars(), CNF::getNrOfClauses(), Options::getSATSolver(), SatSolver::incAddClause(), SatSolver::incAddCNF(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), MASSERT, negateLiterals(), CNF::removeSmallest(), SatSolver::startIncrementalSession(), CNF::swapPresentToNext(), and CNF::swapWith().
Referenced by UnivExpander::resetSolverIExp(), and LearningImplExtractor::runLearningExp().
bool Utils::compressStateCNF (CNF & cnf, bool hardcore = false) [static]
Compresses a state-CNF by removing clauses that are implied by others.
This is done by incremental SAT-solving and is usually quite fast (at least compared to QBF solving).
Parameters
cnf The CNF formula to compress.
hardcore Set this parameter to true if you do not only want to remove clauses but also literals from clauses. This is more expensive, but can produce smaller CNF representations.
Returns
True if the CNF was modified, false otherwise.
Definition at line 305 of file Utils.cpp.
References CNF::addClause(), CNF::addNegCubeAsClause(), CNF::clear(), CNF::getClauses(), CNF::getNrOfClauses(), Options::getSATSolver(), SatSolver::incAddClause(), SatSolver::incAddCNF(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), VarManager::instance(), Options::instance(), MASSERT, negateLiterals(), VarInfo::PRES_STATE, CNF::removeSmallest(), and SatSolver::startIncrementalSession().
Referenced by LearnSynthQBF::computeCounterexampleSAT(), LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::considerNewInfoFromOthers(), CNFImplExtractor::extractCircuit(), TemplExplorer::findWinRegCNFTempl(), and ParallelLearner::triggerExplorerRestart().
bool Utils::contains (const vector< int > & vec, int elem) [static]
Checks if a vector contains a certain element.
Parameters
vec The vector in which the element should be searched.
elem The element to search.
Returns
True if the vector contains the element, false otherwise.
Definition at line 195 of file Utils.cpp.
Referenced by IFM13Explorer::addBlockedState(), LearnSynthSAT::computeWinningRegionRGExp(), TemplExplorer::exclude(), ClauseExplorerSAT::exploreClauses(), extract(), CounterGenSAT::generalizeCeFuther(), DepQBFExt::parseModel(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), and ParExtractorWorker::runSATDep().
bool Utils::containsInit (const vector< int > & cube) [static]
Checks if a cube (in form of a vector of literals) contains the initial state.
In our synthesis problems, there is exactly one initial state of the system (this is a restriction imposed by the AIGER format which serves as input for our tool). Furthermore, the initial state is always characterized by having all state bits set to FALSE. However, this may change with future AIGER versions.
Parameters
cube The cube (a conjuction of literals) in form of a vector of literals over the current-state variables.
Returns
True if the cube contains the initial state (i.e., the initial state satisfies the cube, i.e., the cube contains only negated literals). False otherwise.
Definition at line 45 of file Utils.cpp.
Referenced by LearnSynthQBFInc::computeAllBlockingClauses(), LearnSynthQBF::computeAllBlockingClauses(), LearnSynthQBFInd::computeAllBlockingClauses(), LearnSynthQBFInc::computeBlockingClause(), LearnSynthQBF::computeBlockingClause(), LearnSynthQBFInd::computeBlockingClause(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::exploreClauses(), CounterGenSAT::generalizeCounterexamples(), ClauseMinimizerQBF::minimizeClausesInc(), ClauseMinimizerQBF::minimizeClausesNoInc(), IFM13Synth::recBlockCube(), and IFM13Explorer::recBlockCube().
bool Utils::containsInit (const set< int > & cube) [static]
Checks if a cube (in form of a set of literals) contains the initial state.
In our synthesis problems, there is exactly one initial state of the system (this is a restriction imposed by the AIGER format which serves as input for our tool). Furthermore, the initial state is always characterized by having all state bits set to FALSE. However, this may change with future AIGER versions.
Parameters
cube The cube (a conjuction of literals) in form of a set of literals over the current-state variables.
Returns
True if the cube contains the initial state (i.e., the initial state satisfies the cube, i.e., the cube contains only negated literals). False otherwise.
Definition at line 56 of file Utils.cpp.
void Utils::debugCheckWinReg (const CNF & winning_region) [static]
Checks a winning region for correctness.
The check is only done in debug-mode. In release-mode this method does nothing. In debug-mode this method checks three properties of a winning region W.
I(x) => W(x): every initial state must be contained in the winning region
W(x) => P(x): every state of the winning region must be safe
forall x,i: exists c,x': W(x) => (T(x,i,c,x') & W(x')): from every state in the winning region it must be possible to stay in the winning region by setting the c-signals appropriately.
These three properties are sufficient for turning the winning region into a circuit. However, thise conditions are not necessary. E.g., if optimization RC is used by LearnSynthQBFInd or LearnSynthSAT, the third property does not hold. Hence, these classes have special methods to check such winning regions.
Parameters
winning_region The winning region to check.
Definition at line 645 of file Utils.cpp.
References CNF::negate().
Referenced by LearnSynthSAT::computeWinningRegion(), LearnSynthQBFInd::computeWinningRegion(), LearnSynthQBFInc::run(), TemplateSynth::run(), IFM13Synth::run(), LearnSynthQBF::run(), and ParallelLearner::run().
void Utils::debugCheckWinReg (const CNF & winning_region, const CNF & neg_winning_region) [static]
Checks a winning region and its negation for correctness.
Use this method if you have the negation of the winning region available. Otherwise, we would end up with a double-negation, which is inefficient.
The check is only done in debug-mode. In release-mode this method does nothing. In debug-mode this method checks three properties of a winning region W.
I(x) => W(x): every initial state must be contained in the winning region
W(x) => P(x): every state of the winning region must be safe
forall x,i: exists c,x': W(x) => (T(x,i,c,x') & W(x')): from every state in the winning region it must be possible to stay in the winning region by setting the c-signals appropriately.
These three properties are sufficient for turning the winning region into a circuit. However, thise conditions are not necessary. E.g., if optimization RC is used by LearnSynthQBFInd or LearnSynthSAT, the third property does not hold. Hence, these classes have special methods to check such winning regions.
Parameters
winning_region The winning region to check.
neg_winning_region The negation of the winning region to check.
Definition at line 655 of file Utils.cpp.
References QBFSolver::A, CNF::addCNF(), CNF::clear(), VarInfo::CTRL, QBFSolver::E, extract(), Options::getQBFSolver(), Options::getSATSolver(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incIsSatModelOrCore(), VarInfo::INPUT, VarManager::instance(), Options::instance(), AIG2CNF::instance(), QBFSolver::isSat(), SatSolver::isSat(), L_DBG, MASSERT, VarInfo::NEXT_STATE, VarInfo::PRES_STATE, CNF::renameTmps(), SatSolver::startIncrementalSession(), CNF::swapPresentToNext(), and VarInfo::TMP.
void Utils::debugPrint (const vector< int > & vec, string prefix = ``) [static]
Prints a vector of literals (mainly for debugging purposes).
Parameters
vec The vector of literals to print.
prefix An optional prefix for the debug message.
Definition at line 630 of file Utils.cpp.
References L_DBG.
Referenced by LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), LearnSynthQBF::computeWinningRegionOneSAT(), and DepQBFApi::debugCheckBloqqerModel().
void Utils::debugPrintCurrentMemUsage () [static]
Prints the current memory usage as debug message.
Definition at line 756 of file Utils.cpp.
References L_DBG.
Referenced by main().
bool Utils::eq (const vector< int > & v1, const vector< int > & v2, int start_idx = 0) [static]
Checks if two vectors contain the same set of elements.
Parameters
v1 The first vector for the comparison.
v2 The first vector for the comparison.
start_idx The start index for the comparison.
Returns
True if the two vectors contain the same set of elements.
Definition at line 206 of file Utils.cpp.
vector< int > Utils::extract (const vector< int > & cube_or_clause, VarInfo::VarKind kind) [static]
Extracts literals that are of a given type from a cube or clause.
This method takes as argument a cube or a clause (a set of literals), and a kind of variables. It returns the same set of literals with all variables of other kind removed.
Parameters
cube_or_clause The cube or clause from which only the desired literals should be extracted.
kind The kind of literals that should be extracted. Literals of other kinds will be discarded.
Returns
The literals of cube_or_clause that are of a given type. That is, the returned vector is a subset of cube_or_clause, where all elements are of the desired kind.
Definition at line 67 of file Utils.cpp.
References VarManager::getVarsOfType(), and VarManager::instance().
Referenced by LearnSynthQBF::computeCounterexampleSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), debugCheckWinReg(), ClauseExplorerSAT::exploreClauses(), CounterGenSAT::generalizeCounterexamples(), IFM13Synth::recBlockCube(), and IFM13Explorer::recBlockCube().
vector< int > Utils::extract (const vector< int > & cube_or_clause, const vector< int > & vars) [static]
Extracts certain literals from a cube or clause.
Parameters
cube_or_clause The cube or clause to analyze.
vars The variables to extract from cube_or_clause.
Returns
All literals of cube_or_clause where the corresponding variable occurs in vars.
Definition at line 153 of file Utils.cpp.
References contains().
vector< int > Utils::extractNextAsPresent (const vector< int > & cube_or_clause) [static]
Extracts next-state literals and returns the present-state copy.
This method takes as argument a cube or a clause (a set of literals). It returns the present-state copy of all the next-state literals in the cube or clause.
Parameters
cube_or_clause The cube or clause from which the current-state copy of the next-state literals should be extracted.
Returns
current-state copy of the next-state literals in cube_or_clause.
Definition at line 128 of file Utils.cpp.
References VarManager::getVarsOfType(), VarManager::instance(), VarInfo::NEXT_STATE, and VarInfo::PRES_STATE.
Referenced by IFM13Synth::recBlockCube(), and IFM13Explorer::recBlockCube().
vector< int > Utils::extractPresIn (const vector< int > & cube_or_clause) [static]
Extracts present-state literals and input literals from a cube or clause.
This method takes as argument a cube or a clause (a set of literals). It returns the all literals from this set which are either present-state literals or (uncontrollable) input literals.
Parameters
cube_or_clause The cube or clause from which only current-state and input literals should be extracted.
Returns
The literals of cube_or_clause that are either current-state literals or inputs.
Definition at line 90 of file Utils.cpp.
References VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), and VarInfo::PRES_STATE.
Referenced by IFM13Synth::recBlockCube(), and IFM13Explorer::recBlockCube().
size_t Utils::getCurrentMemUsage () [static]
Returns the current memory usage as debug message in kB.
Returns
The current memory usage as debug message in kB.
Definition at line 597 of file Utils.cpp.
Referenced by UnivExpander::initSolverIData(), and UnivExpander::resetSolverIExp().
bool Utils::intersectionEmpty (const vector< int > & x, const set< int > & y) [static]
Checks if a vector and a set have an empty intersection.
Parameters
x The vector to check.
y The set to check.
Returns
True if the intersection of the vector and the set is empty, false otherwise.
Definition at line 248 of file Utils.cpp.
Referenced by LearnSynthQBFInc::computeAllBlockingClauses(), LearnSynthQBF::computeAllBlockingClauses(), LearnSynthQBFInd::computeAllBlockingClauses(), and CounterGenSAT::generalizeCounterexamples().
bool Utils::intersectionEmpty (const set< int > & x, const set< int > & y) [static]
Checks if the intersection of two sets is empty.
Parameters
x The first set for the check.
y The second set for the check.
Returns
True if the intersection is empty, false otherwise.
Definition at line 265 of file Utils.cpp.
bool Utils::isSubset (const vector< int > & subset, const vector< int > & superset) [static]
Checks if one vector forms a subset of another one.
Parameters
subset The potential subset in the check.
superset The potential superset in the check.
Returns
True if 'subset' is really a subset of 'superset', false otherwise.
Definition at line 282 of file Utils.cpp.
Referenced by CNF::addClauseAndSimplify(), and CNF::simplify().
void Utils::negateLiterals (vector< int > & cube_or_clause) [static]
Negates all literals in a cube or clause.
Parameters
cube_or_clause The cube or clause in which all literals should be negated.
Definition at line 220 of file Utils.cpp.
Referenced by CounterGenSAT::bored(), compressNextStateCNF(), compressStateCNF(), LearnSynthQBFInc::computeAllBlockingClauses(), LearnSynthQBF::computeAllBlockingClauses(), LearnSynthQBFInd::computeAllBlockingClauses(), LearnSynthQBFInc::computeBlockingClause(), LearnSynthQBF::computeBlockingClause(), LearnSynthQBFInd::computeBlockingClause(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRCExp(), ClauseExplorerSAT::exploreClauses(), TemplateSynth::findWinRegANDNetwork(), CounterGenSAT::generalizeCeFuther(), CounterGenSAT::generalizeCounterexamples(), ClauseMinimizerQBF::minimizeClausesInc(), ClauseMinimizerQBF::minimizeClausesNoInc(), LearnSynthQBFInc::reduceExistingClauses(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), TemplateSynth::syntSAT(), and TemplExplorer::syntSAT().
void Utils::negateStateCNF (CNF & cnf) [static]
Negates a CNF over the state-variables without introducing temporary variables.
The negation of the passed CNF is computed via computational learning. It uses a SAT solver in an incremental fashion. This is more expensive than simply calling cnf.negate(), but it does not introduce temporary variables, and hence may lead to a smaller CNF.
Parameters
cnf The CNF formula to negate.
Definition at line 371 of file Utils.cpp.
References CNF::addNegCubeAsClause(), CNF::clear(), Options::getSATSolver(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incIsSatModelOrCore(), VarManager::instance(), Options::instance(), MASSERT, CNF::negate(), VarManager::pop(), VarInfo::PRES_STATE, VarManager::push(), and SatSolver::startIncrementalSession().
Referenced by IFM13Explorer::exploreClauses().
void Utils::negateViaAig (CNF & cnf) [static]
Negates a CNF by transforming into AIGER and back.
This method performs the following 3 steps to negate a CNF: (1) the CNF is transformed into AIGER format, (2) optimized with ABC, and (3) transformed back into CNF. The new CNF has one (fresh) temporary variable per AIGER gate.
Parameters
cnf The CNF formula to negate.
Definition at line 410 of file Utils.cpp.
References CNF::add1LitClause(), CNF::add2LitClause(), CNF::add3LitClause(), CNF::appendVarsTo(), CNF::clear(), VarManager::createFreshTmpVar(), CNF::getClauses(), Options::getTPDirName(), Options::getUniqueTmpFileName(), VarManager::instance(), Options::instance(), and MASSERT.
Utils& Utils::operator= (const Utils & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
void Utils::randomize (vector< int > & vec) [static]
Randomizes the order (not the value) of a given vector of integers.
Parameters
vec The vector to randomize. This vector is modified in-place, i.e., after calling this method, the order of the elements in the passed vector will be randomized.
Definition at line 168 of file Utils.cpp.
Referenced by LearnSynthQBFInc::computeBlockingClause(), LearnSynthQBF::computeBlockingClause(), LearnSynthQBFInd::computeBlockingClause(), ClauseExplorerSAT::exploreClauses(), DepQBFApi::extractCore(), ClauseMinimizerQBF::minimizeClausesInc(), ClauseMinimizerQBF::minimizeClausesNoInc(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), and ParExtractorWorker::runSATDep().
bool Utils::remove (vector< int > & vec, int elem) [static]
Removes a certain element from a vector.
This method may change the order of the elements arbitrarily.
Parameters
vec The vector from which the element should be removed.
elem The element to remove.
Returns
True if the element was removed, false otherwise.
Definition at line 180 of file Utils.cpp.
Referenced by LearnSynthQBFInc::computeAllBlockingClauses(), LearnSynthQBF::computeAllBlockingClauses(), LearnSynthQBFInd::computeAllBlockingClauses(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::exploreClauses(), DepQBFApi::extractCore(), CounterGenSAT::generalizeCeFuther(), LearnSynthQBF::generalizeCounterexample(), LearnSynthQBFInd::generalizeCounterexample(), LearnSynthQBFInc::generalizeCounterexampleFurther(), CounterGenSAT::generalizeCounterexamples(), LingelingApi::incIsSatModelOrCore(), PicoSatApi::incIsSatModelOrCore(), MiniSatApi::incIsSatModelOrCore(), PicoSatApi::isSatModelOrCore(), LingelingApi::isSatModelOrCore(), MiniSatApi::isSatModelOrCore(), ClauseMinimizerQBF::minimizeClausesInc(), ClauseMinimizerQBF::minimizeClausesNoInc(), LearnSynthQBF::reduceExistingClauses(), LearnSynthQBFInd::reduceExistingClauses(), LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), LearningImplExtractor::runLearningQBF(), LearningImplExtractor::runLearningQBFInc(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void Utils::sort (vector< int > & vec) [static]
Sorts a vector of integers in ascending order.
Parameters
vec The vector to sort. This vector is modified in-place, i.e., after calling this method, this vector will be sorted.
Definition at line 174 of file Utils.cpp.
Referenced by LearnSynthQBFInc::generalizeCounterexample(), LearnSynthQBF::generalizeCounterexample(), LearnSynthQBFInd::generalizeCounterexample(), and LearnSynthQBFInc::generalizeCounterexampleFurther().
void Utils::swapPresentToNext (vector< int > & vec) [static]
Replaces all current-state literals by their next-state copy.
Note
The passed vector of literals must only contain current-state literals.
Parameters
vec The vector of literals in which all current-state literals (it must only talk about current-state literals) should be replaced by their next-state copy.
Definition at line 227 of file Utils.cpp.
References VarManager::getMaxCNFVar(), VarManager::getVarsOfType(), VarManager::instance(), MASSERT, VarInfo::NEXT_STATE, and VarInfo::PRES_STATE.
Referenced by IFM13Synth::addBlockedState(), IFM13Explorer::addBlockedState(), IFM13Synth::addLose(), IFM13Explorer::addLose(), LearnSynthQBFInc::computeAllBlockingClauses(), LearnSynthQBF::computeAllBlockingClauses(), LearnSynthQBFInd::computeAllBlockingClauses(), LearnSynthQBFInc::computeBlockingClause(), LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), LearnSynthQBF::computeWinningRegionOneSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::exploreClauses(), CounterGenSAT::generalizeCeFuther(), LearnSynthQBF::generalizeCounterexample(), LearnSynthQBFInd::generalizeCounterexample(), ClauseMinimizerQBF::minimizeClausesNoInc(), IFM13Synth::propagateBlockedStates(), IFM13Explorer::propagateBlockedStates(), and LearnSynthQBFInc::reduceExistingClauses().
The documentation for this class was generated from the following files:
src/Utils.h
src/Utils.cpp