PrevStateInfo Class Reference
Just a container for previous-state information.
#include <ParallelLearner.h>
Public Member Functions
PrevStateInfo (bool use_ind)
Standard constructor.
PrevStateInfo (const PrevStateInfo &other)
Copy constructor.
PrevStateInfo & operator= (const PrevStateInfo &other)
Assignment operator.
int presentToPrevious (int literal) const
Returns the previous-state copy of a literal.
void presentToPrevious (vector< int > &cube_or_clause) const
Computes the previous-state copy of a cube or clause.
void presentToPrevious (CNF &cnf) const
Computes the previous-state copy of a CNF.
Public Attributes
bool use_ind_
A flag indicating if optimization RG should be used.
CNF prev_trans_or_initial_
Says: the current state is initial or the previous transition relation holds.
vector< int > current_to_previous_map_
A map from present-state variables to their previous-state copy.
int current_state_is_initial_
A literal that is true if the current state is initial and false otherwise.
int prev_safe_
The previous-state copy of the literal that characterizes all safe states.
vector< int > px_unused_
Activation variables for a previous state clause.
vector< int > px_neg_
Activation variables for a previous state clause.
vector< int > px_act_
Activation literals for a previous state clause.
vector< int > prev_vars_
The vector of all variables of type VarInfo::PREV.
Detailed Description
Just a container for previous-state information.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 61 of file ParallelLearner.h.
Constructor & Destructor Documentation
PrevStateInfo::PrevStateInfo (bool use_ind)
Standard constructor.
Parameters
use_ind True if previous state info (optimization RG) should be used during the generalization of clauses, and False otherwise.
Definition at line 119 of file ParallelLearner.cpp.
References CNF::add2LitClause(), CNF::add4LitClause(), CNF::addClause(), VarManager::createFreshPrevVar(), VarManager::createFreshTmpVar(), VarInfo::CTRL, current_state_is_initial_, current_to_previous_map_, CNF::getClauses(), VarManager::getMaxCNFVar(), VarManager::getPresErrorStateVar(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), AIG2CNF::instance(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, presentToPrevious(), VarInfo::PREV, prev_safe_, prev_trans_or_initial_, prev_vars_, px_act_, px_neg_, px_unused_, CNF::swapWith(), VarInfo::TMP, and use_ind_.
PrevStateInfo::PrevStateInfo (const PrevStateInfo & other)
Copy constructor.
Parameters
other The source for creating the copy.
Definition at line 187 of file ParallelLearner.cpp.
Member Function Documentation
PrevStateInfo & PrevStateInfo::operator= (const PrevStateInfo & other)
Assignment operator.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
Definition at line 202 of file ParallelLearner.cpp.
References current_state_is_initial_, current_to_previous_map_, prev_safe_, prev_trans_or_initial_, prev_vars_, px_act_, px_neg_, px_unused_, and use_ind_.
int PrevStateInfo::presentToPrevious (int literal) const
Returns the previous-state copy of a literal.
Parameters
literal The literal to transform.
Returns
The previous-state copy of a literal.
Definition at line 217 of file ParallelLearner.cpp.
References current_to_previous_map_.
Referenced by ClauseExplorerSAT::considerNewInfoFromOthers(), CounterGenSAT::considerNewInfoFromOthers(), ClauseMinimizerQBF::minimizeClausesInc(), ClauseMinimizerQBF::minimizeClausesNoInc(), presentToPrevious(), and PrevStateInfo().
void PrevStateInfo::presentToPrevious (vector< int > & cube_or_clause) const
Computes the previous-state copy of a cube or clause.
Parameters
cube_or_clause A cube or clause (in form of a vector of literals) over the present state variables. This vector is overwritten by the corresponding cube of clause over the previous-state literals (i.e., all literals are replaced by their previous-state copy).
Definition at line 227 of file ParallelLearner.cpp.
References presentToPrevious().
void PrevStateInfo::presentToPrevious (CNF & cnf) const
Computes the previous-state copy of a CNF.
Parameters
cnf A CNF formula over the present state variables. This CNF is overwritten by the corresponding CNF over the previous-state literals (i.e., all literals are replaced by their previous-state copy).
Definition at line 234 of file ParallelLearner.cpp.
References CNF::addClause(), CNF::clear(), CNF::getClauses(), and presentToPrevious().
Member Data Documentation
int PrevStateInfo::current_state_is_initial_
A literal that is true if the current state is initial and false otherwise.
The clauses assigning the literal are part of prev_trans_or_initial_.
Definition at line 141 of file ParallelLearner.h.
Referenced by ClauseMinimizerQBF::minimizeClausesNoInc(), operator=(), and PrevStateInfo().
vector<int> PrevStateInfo::current_to_previous_map_
A map from present-state variables to their previous-state copy.
Definition at line 134 of file ParallelLearner.h.
Referenced by operator=(), presentToPrevious(), and PrevStateInfo().
int PrevStateInfo::prev_safe_
The previous-state copy of the literal that characterizes all safe states.
Definition at line 146 of file ParallelLearner.h.
Referenced by ClauseExplorerSAT::exploreClauses(), CounterGenSAT::generalizeCounterexamples(), ClauseMinimizerQBF::minimizeClausesInc(), operator=(), and PrevStateInfo().
CNF PrevStateInfo::prev_trans_or_initial_
Says: the current state is initial or the previous transition relation holds.
This CNF expresses that the current state is initial or the previous-state copy of the transition relation holds. This is an important building block for the CNF to generalize counterexamples if optimization RG is enabled.
Definition at line 129 of file ParallelLearner.h.
Referenced by ClauseExplorerSAT::considerNewInfoFromOthers(), ClauseExplorerSAT::exploreClauses(), CounterGenSAT::generalizeCounterexamples(), ClauseMinimizerQBF::minimizeClausesInc(), ClauseMinimizerQBF::minimizeClausesNoInc(), operator=(), and PrevStateInfo().
vector<int> PrevStateInfo::prev_vars_
The vector of all variables of type VarInfo::PREV.
Definition at line 176 of file ParallelLearner.h.
Referenced by ClauseExplorerSAT::exploreClauses(), operator=(), and PrevStateInfo().
vector<int> PrevStateInfo::px_act_
Activation literals for a previous state clause.
Their value is defined by px_unused_ and px_neg_.
Definition at line 171 of file ParallelLearner.h.
Referenced by operator=(), and PrevStateInfo().
vector<int> PrevStateInfo::px_neg_
Activation variables for a previous state clause.
If px_neg_[i] is true, then this means that the previous state variable nr i occurs negated in the previous-state clause controlled by these variables. If set to false, then it occurs unnegated.
Definition at line 164 of file ParallelLearner.h.
Referenced by ClauseExplorerSAT::exploreClauses(), CounterGenSAT::generalizeCeFuther(), operator=(), and PrevStateInfo().
vector<int> PrevStateInfo::px_unused_
Activation variables for a previous state clause.
If px_unused_[i] is true, then this means that the previous state variable nr i does not occur in the previous-state clause controlled by these variables. If set to false then it occurs.
Definition at line 155 of file ParallelLearner.h.
Referenced by ClauseExplorerSAT::exploreClauses(), CounterGenSAT::generalizeCeFuther(), operator=(), and PrevStateInfo().
bool PrevStateInfo::use_ind_
A flag indicating if optimization RG should be used.
See LearnSynthQBFInd for an explanation.
Definition at line 120 of file ParallelLearner.h.
Referenced by ClauseMinimizerQBF::ClauseMinimizerQBF(), ClauseExplorerSAT::considerNewInfoFromOthers(), CounterGenSAT::considerNewInfoFromOthers(), ClauseExplorerSAT::exploreClauses(), CounterGenSAT::generalizeCeFuther(), CounterGenSAT::generalizeCounterexample(), CounterGenSAT::generalizeCounterexamples(), ClauseMinimizerQBF::minimizeClausesInc(), ClauseMinimizerQBF::minimizeClausesNoInc(), operator=(), and PrevStateInfo().
The documentation for this class was generated from the following files:
src/ParallelLearner.h
src/ParallelLearner.cpp