RareqsExt Class Reference
Calls the RAReQS QBF-solver in a separate process, communicating with files.
#include <RareqsExt.h>
Public Types
enum Quant { E,
A
 }
A type for the different kinds of quantifiers.
Public Member Functions
RareqsExt ()
Constructor.
virtual ~RareqsExt ()
Destructor.
virtual bool isSat (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
Checks if a given QBF is satisfiable (with quantification over variable kinds).
virtual bool isSat (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
Checks if a given QBF is satisfiable (with quantification over variable sets).
virtual bool isSatModel (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf, vector< int > &model)
Checks satisfiability and extracts a model (quantifying over variable kinds).
virtual bool isSatModel (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf, vector< int > &model)
Checks satisfiability and extracts a model (quantifying over variable sets).
Static Public Member Functions
static void dumpQBF (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf, const string &filename)
Dumps a QBF (quantification over variable kinds) into a file in QDIMACS format.
static void dumpQBF (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf, const string &filename)
Dumps a QBF (quantification over variable kinds) into a file in QDIMACS format.
Protected Member Functions
virtual string getSolverCommand () const
Returns the command to execute DepQBF.
virtual string getSolverCommandModel () const
Returns the command to execute DepQBF such that it produces models.
virtual bool parseModel (int ret, vector< int > &model) const
Parses the answer of the QBF solver to get the satisfiability verdict and a model.
virtual bool parseAnswer (int ret) const
Parses the answer of the QBF solver to get the satisfiability verdict.
virtual bool parseModel (int ret, const vector< int > &get, vector< int > &model) const
Parses the answer of the QBF solver to get the satisfiability verdict and a model.
virtual void cleanup ()
Deletes the temporary files that have been used for communication.
Protected Attributes
string path_to_rareqs_
The path to the RAReQS executable.
string in_file_name_
The name of the QDIMACS file containing the QBF to be solved.
string out_file_name_
The name of the file that is produced by the QBF-solver (containing the model).
Private Member Functions
RareqsExt (const RareqsExt &other)
Copy constructor.
RareqsExt & operator= (const RareqsExt &other)
Assignment operator.
Detailed Description
Calls the RAReQS QBF-solver in a separate process, communicating with files.
This class represents an interface to the QBF-solver RAReQS (see http://sat.inesc-id.pt/~mikolas/sw/areqs/). For a given Quantified Boolean formula (a CNF with a quantifier prefix), this class is able to determine satisfiability. Furthermore, in case of satisfiability, it can extract satisfying assignments for variables quantified existentially on the outermost level. The RAReQS solver is executed in a separate process. Communication with this process works via files.
Most of work is actually implemented in the base class ExtQBFSolver. This class mainly overrides some methods which are specific for RAReQS.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 53 of file RareqsExt.h.
Member Enumeration Documentation
enum QBFSolver::Quant [inherited]
A type for the different kinds of quantifiers.
Enumerator
E
 The value for existential quantification.
A
 The value for universal quantification.
Definition at line 56 of file QBFSolver.h.
Constructor & Destructor Documentation
RareqsExt::RareqsExt ()
Constructor.
Definition at line 37 of file RareqsExt.cpp.
References Options::getTPDirName(), Options::instance(), MASSERT, and path_to_rareqs_.
RareqsExt::~RareqsExt () [virtual]
Destructor.
Definition at line 45 of file RareqsExt.cpp.
RareqsExt::RareqsExt (const RareqsExt & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void ExtQBFSolver::cleanup () [protected], [virtual], [inherited]
Deletes the temporary files that have been used for communication.
Definition at line 217 of file ExtQBFSolver.cpp.
References ExtQBFSolver::in_file_name_, and ExtQBFSolver::out_file_name_.
Referenced by ExtQBFSolver::isSat(), ExtQBFSolver::isSatModel(), and DepQBFExt::qbfCert().
void ExtQBFSolver::dumpQBF (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf, const string & filename) [static], [inherited]
Dumps a QBF (quantification over variable kinds) into a file in QDIMACS format.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
filename The name of the file (including path) to write to.
Definition at line 105 of file ExtQBFSolver.cpp.
References QBFSolver::E, VarManager::getMaxCNFVar(), CNF::getNrOfClauses(), VarManager::getVarsOfType(), VarManager::instance(), and CNF::toString().
Referenced by DepQBFApi::debugCheckBloqqerModel(), DepQBFApi::debugCheckBloqqerVerdict(), ExtQBFSolver::isSat(), ExtQBFSolver::isSatModel(), and DepQBFExt::qbfCert().
void ExtQBFSolver::dumpQBF (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf, const string & filename) [static], [inherited]
Dumps a QBF (quantification over variable kinds) into a file in QDIMACS format.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
filename The name of the file (including path) to write to.
Definition at line 138 of file ExtQBFSolver.cpp.
References QBFSolver::E, CNF::getNrOfClauses(), and CNF::toString().
string RareqsExt::getSolverCommand () const [protected], [virtual]
Returns the command to execute DepQBF.
Returns
The command to execute DepQBF.
Implements ExtQBFSolver.
Definition at line 51 of file RareqsExt.cpp.
References ExtQBFSolver::in_file_name_, ExtQBFSolver::out_file_name_, and path_to_rareqs_.
string RareqsExt::getSolverCommandModel () const [protected], [virtual]
Returns the command to execute DepQBF such that it produces models.
Returns
The command to execute DepQBF such that it produces models.
Implements ExtQBFSolver.
Definition at line 57 of file RareqsExt.cpp.
References ExtQBFSolver::in_file_name_, ExtQBFSolver::out_file_name_, and path_to_rareqs_.
bool ExtQBFSolver::isSat (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [virtual], [inherited]
Checks if a given QBF is satisfiable (with quantification over variable kinds).
The QBF consists of a quantifier prefix and a Boolean formula in CNF. The quantifier prefix assigns an existential or universal quantifier to every kind of variable. The QBF is dumped into a file, a QBF-solver is called, and the exit code is used to infer the satisfiability result.
Exceptions
DemiurgeException if the solver crashed or a timeout occurred.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 54 of file ExtQBFSolver.cpp.
References ExtQBFSolver::cleanup(), ExtQBFSolver::dumpQBF(), ExtQBFSolver::getSolverCommand(), ExtQBFSolver::in_file_name_, and ExtQBFSolver::parseAnswer().
Referenced by QBFCertImplExtractor::run().
bool ExtQBFSolver::isSat (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [virtual], [inherited]
Checks if a given QBF is satisfiable (with quantification over variable sets).
The QBF consists of a quantifier prefix and a Boolean formula in CNF. The quantifier prefix assigns an existential or universal quantifier to different sets variable. The QBF is dumped into a file, a QBF-solver is called, and the exit code is used to infer the satisfiability result.
Exceptions
DemiurgeException if the solver crashed or a timeout occurred.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 66 of file ExtQBFSolver.cpp.
References ExtQBFSolver::cleanup(), ExtQBFSolver::dumpQBF(), ExtQBFSolver::getSolverCommand(), ExtQBFSolver::in_file_name_, and ExtQBFSolver::parseAnswer().
bool ExtQBFSolver::isSatModel (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf, vector< int > & model) [virtual], [inherited]
Checks satisfiability and extracts a model (quantifying over variable kinds).
Just like isSat() , this method checks a quantified Boolean formula for satisfiability. If the QBF is satisfiable, this method also extracts a model (a satisfying assignment) for all variables which are quantified existentially on the outermost level. The model is provided as cube: negated variables in the cube are FALSE, unnegated ones are TRUE.
Exceptions
DemiurgeException if the solver crashed or a timeout occurred.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
model The resulting model in form of a cube in case of satisfiability. Negated variables in the cube are FALSE, unnegated ones are TRUE. If the formula is unsatisfiable (this method returns false) then this parameter is not modified.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 78 of file ExtQBFSolver.cpp.
References ExtQBFSolver::cleanup(), ExtQBFSolver::dumpQBF(), ExtQBFSolver::getSolverCommandModel(), VarManager::getVarsOfType(), ExtQBFSolver::in_file_name_, VarManager::instance(), and ExtQBFSolver::parseModel().
Referenced by TemplExplorer::syntQBF().
bool ExtQBFSolver::isSatModel (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf, vector< int > & model) [virtual], [inherited]
Checks satisfiability and extracts a model (quantifying over variable sets).
Just like isSat() , this method checks a quantified Boolean formula for satisfiability. If the QBF is satisfiable, this method also extracts a model (a satisfying assignment) for all variables which are quantified existentially on the outermost level. The model is provided as cube: negated variables in the cube are FALSE, unnegated ones are TRUE.
Exceptions
DemiurgeException if the solver crashed or a timeout occurred.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
model The resulting model in form of a cube in case of satisfiability. Negated variables in the cube are FALSE, unnegated ones are TRUE. If the formula is unsatisfiable (this method returns false) then this parameter is not modified.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 92 of file ExtQBFSolver.cpp.
References ExtQBFSolver::cleanup(), ExtQBFSolver::dumpQBF(), ExtQBFSolver::getSolverCommandModel(), ExtQBFSolver::in_file_name_, and ExtQBFSolver::parseModel().
RareqsExt& RareqsExt::operator= (const RareqsExt & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
bool ExtQBFSolver::parseAnswer (int ret) const [protected], [virtual], [inherited]
Parses the answer of the QBF solver to get the satisfiability verdict.
Exceptions
DemiurgeException if the solver crashed or a timeout occurred.
Parameters
ret The exit code of the process running the QBF solver.
Returns
True in case of satisfiability, false for unsatisfiability.
Definition at line 180 of file ExtQBFSolver.cpp.
Referenced by ExtQBFSolver::isSat().
bool RareqsExt::parseModel (int ret, vector< int > & model) const [protected], [virtual]
Parses the answer of the QBF solver to get the satisfiability verdict and a model.
Parameters
ret The exit code of the process running the QBF solver.
model An empty vector. In case of satisfiability, this method will write a satisfying assignment in form of a cube into this vector.
Returns
True in case of satisfiability, false for unsatisfiability.
Definition at line 63 of file RareqsExt.cpp.
References MASSERT, ExtQBFSolver::out_file_name_, and FileUtils::readFile().
bool ExtQBFSolver::parseModel (int ret, const vector< int > & get, vector< int > & model) const [protected], [virtual], [inherited]
Parses the answer of the QBF solver to get the satisfiability verdict and a model.
Exceptions
DemiurgeException if the solver crashed or a timeout occurred.
Parameters
ret The exit code of the process running the QBF solver.
get The variables of interest for which we want to have a satisfying assignment.
model An empty vector. In case of satisfiability, this method will write a satisfying assignment in form of a cube into this vector.
Returns
True in case of satisfiability, false for unsatisfiability.
Reimplemented in DepQBFExt.
Definition at line 190 of file ExtQBFSolver.cpp.
References MASSERT, ExtQBFSolver::out_file_name_, and FileUtils::readFile().
Referenced by ExtQBFSolver::isSatModel().
Member Data Documentation
string ExtQBFSolver::in_file_name_ [protected], [inherited]
The name of the QDIMACS file containing the QBF to be solved.
Definition at line 232 of file ExtQBFSolver.h.
Referenced by ExtQBFSolver::cleanup(), ExtQBFSolver::ExtQBFSolver(), getSolverCommand(), QuBEExt::getSolverCommand(), DepQBFExt::getSolverCommand(), getSolverCommandModel(), QuBEExt::getSolverCommandModel(), DepQBFExt::getSolverCommandModel(), ExtQBFSolver::isSat(), ExtQBFSolver::isSatModel(), and DepQBFExt::qbfCert().
string ExtQBFSolver::out_file_name_ [protected], [inherited]
The name of the file that is produced by the QBF-solver (containing the model).
Definition at line 237 of file ExtQBFSolver.h.
Referenced by ExtQBFSolver::cleanup(), ExtQBFSolver::ExtQBFSolver(), getSolverCommand(), QuBEExt::getSolverCommand(), DepQBFExt::getSolverCommand(), getSolverCommandModel(), QuBEExt::getSolverCommandModel(), DepQBFExt::getSolverCommandModel(), parseModel(), DepQBFExt::parseModel(), and ExtQBFSolver::parseModel().
string RareqsExt::path_to_rareqs_ [protected]
The path to the RAReQS executable.
Definition at line 96 of file RareqsExt.h.
Referenced by getSolverCommand(), getSolverCommandModel(), and RareqsExt().
The documentation for this class was generated from the following files:
src/RareqsExt.h
src/RareqsExt.cpp