ParExtractorWorker Class Reference
A worker thread for the ParExtractor.
#include <ParExtractor.h>
Public Member Functions
ParExtractorWorker (ParExtractor &coordinator, const CNF &win_region, const CNF &neg_win_region)
Constructor.
virtual ~ParExtractorWorker ()
Destructor.
void runSAT ()
Runs SAT-based learning without dependency optimization.
void runSATDep ()
Runs SAT-based learning with dependency optimization.
void logStats ()
Logs the detailed statistics collected by the fastest worker.
Public Attributes
bool done_
Indicates if standalone_circuit_ is ready.
bool waiting_
Indicates if this thread is waiting for others to finish.
bool did_second_run_
True if this thread did a second minimization run (just for printing statistics).
aiger * standalone_circuit_
The synthesis result as stand-alone circuit.
LearningExtractorStatistics statistics
A helper for collecting performance data and statistics.
Protected Member Functions
void waitForOthersToFinish (size_t elapsed_until_done)
Waits for other worker threads to finish.
CNF makeEq (int var, CNF impl, vector< int > *new_temps=NULL)
Creates a CNF that assigns a variable to the result of some other CNF.
void addToStandAloneAiger (int ctrl_var, const CNF &solution)
Adds the solution for one output function to the AIGER circuit we have so far.
void addToStandAloneAiger2 (int ctrl_var, const CNF &solution)
Same as addToStandAloneAiger but operating on the copy standalone_circuit2_.
int cnfToAig (int cnf_lit)
Transforms a CNF literal into an AIGER literal as used in standalone_circuit_.
int makeAnd (int in1, int in2)
Creates the AND between two AIGER literals and returns the resulting literal.
int makeAnd2 (int in1, int in2)
Same as makeAnd but operating on the copy standalone_circuit2_.
int makeOr (int in1, int in2)
Creates the OR between two AIGER literals and returns the resulting literal.
int makeOr2 (int in1, int in2)
Same as makeAnd but operating on the copy standalone_circuit2_.
void insertMissingAndFromTrans (aiger *standalone_circuit)
Copies missing AND gates from the spec.
Protected Attributes
ParExtractor & coordinator_
A reference to the coordinator.
SatSolver * check_
A SAT solver to check for counterexamples.
SatSolver * gen_
A SAT solver to generalize counterexamples.
const CNF & win_region_
The winning region from which the circuit should be extracted.
const CNF & neg_win_region_
The negation of the winning region.
int next_free_aig_lit_
The next unused AIGER literal in standalone_circuit_.
int next_free_cnf_lit_
We need to create fresh variables locally.
vector< int > cnf_var_to_standalone_aig_var_
A map from variables as they occur in CNFs to the corresponding AIGER literals.
vector< int > ip_
The list of uncontrollable input variables followed by the present state variables.
vector< int > ipc_
The list of uncontrollable inputs, state variables, and control signals.
aiger * standalone_circuit2_
A second (optimized) version of the standalone_circuit.
int next_free_aig_lit2_
The next unused AIGER literal in standalone_circuit2_.
Private Member Functions
ParExtractorWorker (const ParExtractorWorker &other)
Copy constructor.
ParExtractorWorker & operator= (const ParExtractorWorker &other)
Assignment operator.
Detailed Description
A worker thread for the ParExtractor.
This class implements selected circuit extraction methods from the LearningImplExtractor in a parallelized way.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 171 of file ParExtractor.h.
Constructor & Destructor Documentation
ParExtractorWorker::ParExtractorWorker (ParExtractor & coordinator, const CNF & win_region, const CNF & neg_win_region)
Constructor.
Parameters
coordinator A reference to the coordinator. All communication to other worker-threads is done via the coordinator.
win_region The winning region from which the circuit should be extracted.
neg_win_region The negation of the winning region.
Definition at line 193 of file ParExtractor.cpp.
References cnf_var_to_standalone_aig_var_, VarInfo::CTRL, VarManager::getInfo(), VarInfo::getLitInAIG(), VarInfo::getName(), VarManager::getPresErrorStateVar(), AIG2CNF::getTmpDepsTrans(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), AIG2CNF::instance(), ip_, ipc_, AIG2CNF::isTrueInTrans(), next_free_aig_lit2_, next_free_aig_lit_, VarInfo::PRES_STATE, standalone_circuit2_, and standalone_circuit_.
ParExtractorWorker::~ParExtractorWorker () [virtual]
Destructor.
Definition at line 281 of file ParExtractor.cpp.
References check_, gen_, standalone_circuit2_, and standalone_circuit_.
ParExtractorWorker::ParExtractorWorker (const ParExtractorWorker & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void ParExtractorWorker::addToStandAloneAiger (int ctrl_var, const CNF & solution) [protected]
Adds the solution for one output function to the AIGER circuit we have so far.
The AIGER circuit we have so far is built up in standalone_circuit_. This method adds an output function (in CNF) for one control signal.
Parameters
ctrl_var The control signal for which we would like to add an output function.
solution The output function (in CNF) defining the control signal.
Definition at line 921 of file ParExtractor.cpp.
References cnfToAig(), CNF::getClauses(), makeAnd(), makeOr(), and standalone_circuit_.
Referenced by ParExtractorQBFWorker::runQBF(), runSAT(), and runSATDep().
void ParExtractorWorker::addToStandAloneAiger2 (int ctrl_var, const CNF & solution) [protected]
Same as addToStandAloneAiger but operating on the copy standalone_circuit2_.
Parameters
ctrl_var The control signal for which we would like to add an output function.
solution The output function (in CNF) defining the control signal.
Definition at line 957 of file ParExtractor.cpp.
References cnfToAig(), CNF::getClauses(), makeAnd2(), makeOr2(), and standalone_circuit2_.
Referenced by runSAT(), and runSATDep().
int ParExtractorWorker::cnfToAig (int cnf_lit) [protected]
Transforms a CNF literal into an AIGER literal as used in standalone_circuit_.
Parameters
cnf_lit The literal as it occurs in CNF formulas.
Returns
The corresponding AIGER index of the literal as it is used in the standalone_circuit_.
Definition at line 993 of file ParExtractor.cpp.
References cnf_var_to_standalone_aig_var_.
Referenced by addToStandAloneAiger(), addToStandAloneAiger2(), and insertMissingAndFromTrans().
void ParExtractorWorker::insertMissingAndFromTrans (aiger * standalone_circuit) [protected]
Copies missing AND gates from the spec.
This method is only used for an optimization in the method runSATDep. This method allows solutions to depend on temporary variables that appear in the original specification. The rules for SYNTComp do not allow to refer to such temporary variables from the specification in the final solution. Hence, this method simply copies the AND gates from the specification into the standalone_circuit passed as argument.
Parameters
standalone_circuit The circuit to complete with missing AND gates.
Definition at line 1039 of file ParExtractor.cpp.
References VarManager::aigLitToCnfLit(), cnf_var_to_standalone_aig_var_, cnfToAig(), Options::getAigInFileName(), AIG2CNF::getTmpDeps(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), MASSERT, and VarInfo::TMP.
Referenced by runSATDep().
void ParExtractorWorker::logStats ()
Logs the detailed statistics collected by the fastest worker.
int ParExtractorWorker::makeAnd (int in1, int in2) [protected]
Creates the AND between two AIGER literals and returns the resulting literal.
This method extends the standalone_circuit_ with logic to compute the AND between two AIGER literals. The literal that represents the result of the AND is returned.
Parameters
in1 The first operand of the AND: an AIGER literal from standalone_circuit_.
in2 The second operand of the AND: an AIGER literal from standalone_circuit_.
Returns
The literal that represents the result of the AND.
Definition at line 1003 of file ParExtractor.cpp.
References next_free_aig_lit_, and standalone_circuit_.
Referenced by addToStandAloneAiger().
int ParExtractorWorker::makeAnd2 (int in1, int in2) [protected]
Same as makeAnd but operating on the copy standalone_circuit2_.
Parameters
in1 The first operand of the AND: an AIGER literal from standalone_circuit2_.
in2 The second operand of the AND: an AIGER literal from standalone_circuit2_.
Returns
The literal that represents the result of the AND.
Definition at line 1012 of file ParExtractor.cpp.
References next_free_aig_lit2_, and standalone_circuit2_.
Referenced by addToStandAloneAiger2().
CNF ParExtractorWorker::makeEq (int var, CNF impl, vector< int > * new_temps = NULL) [protected]
Creates a CNF that assigns a variable to the result of some other CNF.
This method creates a CNF that for (var <-> impl), where var is a variable and impl is a CNF. It is used to say that a certain control signal is now defined by a function that has been computed in CNF form.
Parameters
var The variable to set equal to the result of the CNF impl.
impl The CNF that should define the value of var.
new_temps A vector of variables. New auxiliary variables introduced by this method will be appended to this vector. The vector can also be omitted if not needed.
Returns
A CNF representation of (var <-> impl).
Definition at line 871 of file ParExtractor.cpp.
References CNF::addClause(), CNF::addCNF(), CNF::getClauses(), next_free_cnf_lit_, and CNF::swapWith().
Referenced by ParExtractorQBFWorker::runQBF(), runSAT(), and runSATDep().
int ParExtractorWorker::makeOr (int in1, int in2) [protected]
Creates the OR between two AIGER literals and returns the resulting literal.
This method extends the standalone_circuit_ with logic to compute the OR between two AIGER literals. The literal that represents the result of the OR is returned.
Parameters
in1 The first operand of the OR: an AIGER literal from standalone_circuit_.
in2 The second operand of the OR: an AIGER literal from standalone_circuit_.
Returns
The literal that represents the result of the OR.
Definition at line 1021 of file ParExtractor.cpp.
References next_free_aig_lit_, and standalone_circuit_.
Referenced by addToStandAloneAiger().
int ParExtractorWorker::makeOr2 (int in1, int in2) [protected]
Same as makeAnd but operating on the copy standalone_circuit2_.
Parameters
in1 The first operand of the OR: an AIGER literal from standalone_circuit2_.
in2 The second operand of the OR: an AIGER literal from standalone_circuit2_.
Returns
The literal that represents the result of the OR.
Definition at line 1030 of file ParExtractor.cpp.
References next_free_aig_lit2_, and standalone_circuit2_.
Referenced by addToStandAloneAiger2().
ParExtractorWorker& ParExtractorWorker::operator= (const ParExtractorWorker & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
void ParExtractorWorker::runSAT ()
Runs SAT-based learning without dependency optimization.
Roughly implements LearningImplExtractor::runLearningJiangSATInc1().
Definition at line 294 of file ParExtractor.cpp.
References CNF::add2LitClause(), CNF::add3LitClause(), CNF::addClause(), CNF::addCNF(), CNF::addNegCubeAsClause(), addToStandAloneAiger(), addToStandAloneAiger2(), check_, coordinator_, VarInfo::CTRL, did_second_run_, SatSolver::doMinCores(), done_, ParExtractor::extr_command_, EXTR_STOP, gen_, Options::getEstimatedTimeRemaining(), Stopwatch::getRealTimeSec(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), ip_, ipc_, makeEq(), MASSERT, neg_win_region_, Utils::negateLiterals(), next_free_cnf_lit_, LearningExtractorStatistics::notifyAfterABC(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeABC(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), CNFImplExtractor::optimizeWithABC(), Utils::remove(), CNF::renameVars(), CNF::setVarValue(), standalone_circuit2_, standalone_circuit_, Stopwatch::start(), SatSolver::startIncrementalSession(), statistics, CNF::swapPresentToNext(), waitForOthersToFinish(), and win_region_.
Referenced by ParExtractor::run().
void ParExtractorWorker::runSATDep ()
Runs SAT-based learning with dependency optimization.
Roughly implements LearningImplExtractor::runLearningJiangSATTmpCtrl().
Definition at line 553 of file ParExtractor.cpp.
References CNF::addCNF(), CNF::addNegCubeAsClause(), addToStandAloneAiger(), addToStandAloneAiger2(), check_, Utils::contains(), CNF::contains(), coordinator_, VarInfo::CTRL, DASSERT, did_second_run_, SatSolver::doMinCores(), done_, ParExtractor::extr_command_, EXTR_STOP, gen_, Options::getEstimatedTimeRemaining(), Stopwatch::getRealTimeSec(), AIG2CNF::getTmpDepsTrans(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incAddUnitClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), insertMissingAndFromTrans(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), ipc_, makeEq(), MASSERT, neg_win_region_, Utils::negateLiterals(), next_free_cnf_lit_, LearningExtractorStatistics::notifyAfterABC(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeABC(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), CNFImplExtractor::optimizeWithABC(), Utils::randomize(), Utils::remove(), CNF::renameVars(), CNF::setVarValue(), standalone_circuit2_, standalone_circuit_, Stopwatch::start(), SatSolver::startIncrementalSession(), statistics, CNF::swapPresentToNext(), waitForOthersToFinish(), and win_region_.
void ParExtractorWorker::waitForOthersToFinish (size_t elapsed_until_done) [protected]
Waits for other worker threads to finish.
If a worker thread is finished it does not terminate and kill other worker threads immediately. Instead, it waits for some time hoping that other worker threads will finish as well. This way, we can choose among the different circuits created by the different threads. However, if some thread loses her patience while waiting, it can kill other worker threads.
Parameters
elapsed_until_done The time in seconds this worker thread needed until it found a solution. This number is used for heuristics that decide when to kill the other workers.
Definition at line 834 of file ParExtractor.cpp.
References ParExtractor::allWaiting(), coordinator_, ParExtractor::extr_command_, EXTR_STOP, Options::getEstimatedTimeRemaining(), Stopwatch::getRealTimeSec(), Options::instance(), ParExtractor::killThemAll(), standalone_circuit_, Stopwatch::start(), and waiting_.
Referenced by ParExtractorQBFWorker::runQBF(), runSAT(), and runSATDep().
Member Data Documentation
SatSolver* ParExtractorWorker::check_ [protected]
A SAT solver to check for counterexamples.
Definition at line 374 of file ParExtractor.h.
Referenced by runSAT(), runSATDep(), and ~ParExtractorWorker().
vector<int> ParExtractorWorker::cnf_var_to_standalone_aig_var_ [protected]
A map from variables as they occur in CNFs to the corresponding AIGER literals.
This vector maps variables as they occur in CNFs to the corresponding AIGER literals as they occur in the standalone_circuit_. Use cnfToAig to transform literals.
Note
The AIGER literal numbering scheme in the standalone_circuit_ is different from the numbering scheme in the original specification. The reason is that we want to avoid big 'holes' of unused AIGER literals right from the beginning.
Definition at line 411 of file ParExtractor.h.
Referenced by cnfToAig(), insertMissingAndFromTrans(), and ParExtractorWorker().
ParExtractor& ParExtractorWorker::coordinator_ [protected]
A reference to the coordinator.
All communication to other worker-threads is done via the coordinator.
Definition at line 369 of file ParExtractor.h.
Referenced by ParExtractorQBFWorker::runQBF(), runSAT(), runSATDep(), and waitForOthersToFinish().
bool ParExtractorWorker::did_second_run_
True if this thread did a second minimization run (just for printing statistics).
Definition at line 224 of file ParExtractor.h.
Referenced by runSAT(), and runSATDep().
bool ParExtractorWorker::done_
Indicates if standalone_circuit_ is ready.
Definition at line 214 of file ParExtractor.h.
Referenced by ParExtractorQBFWorker::runQBF(), runSAT(), and runSATDep().
SatSolver* ParExtractorWorker::gen_ [protected]
A SAT solver to generalize counterexamples.
Definition at line 379 of file ParExtractor.h.
Referenced by runSAT(), runSATDep(), and ~ParExtractorWorker().
vector<int> ParExtractorWorker::ip_ [protected]
The list of uncontrollable input variables followed by the present state variables.
This vector contains the CNF version of the uncontrollable input variables followed by the present state variables. This vector of variables is used often, and thus stored here as a field.
Definition at line 420 of file ParExtractor.h.
Referenced by ParExtractorWorker(), ParExtractorQBFWorker::runQBF(), and runSAT().
vector<int> ParExtractorWorker::ipc_ [protected]
The list of uncontrollable inputs, state variables, and control signals.
This vector contains the CNF version of the uncontrollable input variables followed by the present state variables, followed by the control signals. This vector of variables is used often, and thus stored here as a field.
Definition at line 429 of file ParExtractor.h.
Referenced by ParExtractorWorker(), runSAT(), and runSATDep().
const CNF& ParExtractorWorker::neg_win_region_ [protected]
The negation of the winning region.
Definition at line 389 of file ParExtractor.h.
Referenced by ParExtractorQBFWorker::runQBF(), runSAT(), and runSATDep().
int ParExtractorWorker::next_free_aig_lit2_ [protected]
The next unused AIGER literal in standalone_circuit2_.
Definition at line 442 of file ParExtractor.h.
Referenced by makeAnd2(), makeOr2(), and ParExtractorWorker().
int ParExtractorWorker::next_free_aig_lit_ [protected]
The next unused AIGER literal in standalone_circuit_.
Definition at line 394 of file ParExtractor.h.
Referenced by makeAnd(), makeOr(), and ParExtractorWorker().
int ParExtractorWorker::next_free_cnf_lit_ [protected]
We need to create fresh variables locally.
Definition at line 399 of file ParExtractor.h.
Referenced by makeEq(), runSAT(), and runSATDep().
aiger* ParExtractorWorker::standalone_circuit2_ [protected]
A second (optimized) version of the standalone_circuit.
We will always finish standalone_circuit_, and then work on standalone_circuit2_ if there is still time.
Definition at line 437 of file ParExtractor.h.
Referenced by addToStandAloneAiger2(), makeAnd2(), makeOr2(), ParExtractorWorker(), runSAT(), runSATDep(), and ~ParExtractorWorker().
aiger* ParExtractorWorker::standalone_circuit_
The synthesis result as stand-alone circuit.
This AIGER circuit is combinatorial, i.e., has no latches. The inputs of the circuit are: the uncontrollable inputs from the spec (in the order in which they appear in the spec) followed by the state-signals (the output of the latches in the spec, in the order in which they appear in the spec). The outputs of the circuit are the controllable inputs in the order in which they are defined in the spec.
This circuit will be built up by one of the methods runLearningX. Then, it will be optimized using ABC. Finally, it will be inserted into the original specification, as required by the rules for SYNTComp.
Definition at line 240 of file ParExtractor.h.
Referenced by addToStandAloneAiger(), makeAnd(), makeOr(), ParExtractorWorker(), ParExtractorQBFWorker::runQBF(), runSAT(), runSATDep(), waitForOthersToFinish(), and ~ParExtractorWorker().
LearningExtractorStatistics ParExtractorWorker::statistics
A helper for collecting performance data and statistics.
Definition at line 245 of file ParExtractor.h.
Referenced by ParExtractorQBFWorker::runQBF(), runSAT(), and runSATDep().
bool ParExtractorWorker::waiting_
Indicates if this thread is waiting for others to finish.
Definition at line 219 of file ParExtractor.h.
Referenced by ParExtractorQBFWorker::runQBF(), and waitForOthersToFinish().
const CNF& ParExtractorWorker::win_region_ [protected]
The winning region from which the circuit should be extracted.
Definition at line 384 of file ParExtractor.h.
Referenced by ParExtractorQBFWorker::runQBF(), runSAT(), and runSATDep().
The documentation for this class was generated from the following files:
src/ParExtractor.h
src/ParExtractor.cpp