LearningImplExtractor Class Reference
Implements different learning-based methods for circuit extraction.
#include <LearningImplExtractor.h>
Public Member Functions
LearningImplExtractor ()
Constructor.
virtual ~LearningImplExtractor ()
Destructor.
virtual void run (const CNF &winning_region, const CNF &neg_winning_region)
Runs this circuit extractor.
virtual void extractCircuit (const CNF &winning_region)
Extracts a circuit from the winning region.
virtual void extractCircuit (const CNF &winning_region, const CNF &neg_winning_region)
Extracts a circuit from the winning region and its negation.
virtual void logStatistics ()
Logs statistical information about circuit extraction.
Static Public Member Functions
static aiger * optimizeWithABC (aiger *circuit)
Optimizes a combinatorial AIGER circuit with ABC.
Protected Member Functions
void runLearningQBF (const CNF &win_region, const CNF &neg_win_region)
Implements circuit extraction with non-incremental QBF-based CNF learning.
void runLearningQBFInc (const CNF &win_region, const CNF &neg_win_region)
Implements circuit extraction with incremental QBF-based CNF learning.
void runLearningExp (const CNF &win_region, const CNF &neg_win_region)
Same as runLearningQBFInc, but using universal expansion and a SAT solver.
void runLearningJiangSAT (const CNF &win_region, const CNF &neg_win_region, bool second_run=false, bool min_cores=true)
Uses SAT-based CNF learning with Jiang-resubstitution.
void runLearningJiangSATInc1 (const CNF &win_region, const CNF &neg_win_region, bool second_run=false, bool min_cores=true)
Like runLearningJiangSAT but with more aggressive incremental solving.
void runLearningJiangSATInc2 (const CNF &win_region, const CNF &neg_win_region, bool second_run=false, bool min_cores=true)
Like runLearningJiangSATInc1 but with even more aggressive incremental solving.
void runLearningJiangSATTmp (const CNF &win_region, const CNF &neg_win_region, bool second_run=false, bool min_cores=true)
Uses SAT-based CNF learning with Jiang-resubstitution and temporary variables.
void runLearningJiangSATTmpCtrl (const CNF &win_region, const CNF &neg_win_region, bool second_run=false, bool min_cores=true)
Like runLearningJiangSATTmp, but also allows dependencies on control signals.
void runLearningJiangSATTmpCtrlInc2 (const CNF &win_region, const CNF &neg_win_region, bool second_run=false, bool min_cores=true)
Combines runLearningJiangSATTmpCtrl and runLearningJiangSATInc2.
CNF makeEq (int var, CNF impl)
Creates a CNF that assigns a variable to the result of some other CNF.
CNF makeEq2 (int var, CNF impl)
An alternative implementation of makeEq, which seems to be slower.
void addToStandAloneAiger (int ctrl_var, const CNF &solution)
Adds the solution for one output function to the AIGER circuit we have so far.
int cnfToAig (int cnf_lit)
Transforms a CNF literal into an AIGER literal as used in standalone_circuit_.
int makeAnd (int in1, int in2)
Creates the AND between two AIGER literals and returns the resulting literal.
int makeOr (int in1, int in2)
Creates the OR between two AIGER literals and returns the resulting literal.
void insertMissingAndFromTrans ()
Copies missing AND gates from the spec.
void logDetailedStatistics ()
Logs the detailed statistics collected in the LearningExtractorStatistics.
size_t insertIntoSpec (aiger *standalone_circuit) const
Takes a circuit defining the control signals and inserts it into the spec.
Protected Attributes
QBFSolver * qbf_solver_
The QBF solver to use (as selected by the user with command-line arguments).
int next_free_aig_lit_
The next unused AIGER literal in standalone_circuit_.
aiger * standalone_circuit_
The synthesis result as stand-alone circuit.
vector< int > cnf_var_to_standalone_aig_var_
A map from variables as they occur in CNFs to the corresponding AIGER literals.
vector< int > ip_
The list of uncontrollable input variables followed by the present state variables.
vector< int > ipc_
The list of uncontrollable inputs, state variables, and control signals.
LearningExtractorStatistics statistics
A helper for collecting performance data and statistics.
double extraction_cpu_time_
The circuit extraction time in CPU-seconds.
size_t extraction_real_time_
Like extraction_cpu_time_ but real-time.
Private Member Functions
LearningImplExtractor (const LearningImplExtractor &other)
Copy constructor.
LearningImplExtractor & operator= (const LearningImplExtractor &other)
Assignment operator.
Detailed Description
Implements different learning-based methods for circuit extraction.
This class implements different learning-based methods for circuit extraction. All methods are based on the CNF learning algorithm from the paper Ruediger Ehlers, Robert Koenighofer, Georg Hofferek: Symbolically synthesizing small circuits. FMCAD 2012: 91.2.0 Some methods use QBF-solving, some incremental QBF solving, and some incremental SAT solving with various optimizations. The method that should be used is defined by the command-line option --circuit-mode or -n.
The general flow is as follows.
We compute a combinational (no latches) stand-alone circuit that computes the control signals based on the uncontrollable inputs and state variables in AIGER format.
We optimize this stand-alone circuit using ABC.
The optimized circuit is inserted into the original specification as requited by the rules of the SYNTComp competition.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 64 of file LearningImplExtractor.h.
Constructor & Destructor Documentation
LearningImplExtractor::LearningImplExtractor ()
Constructor.
Definition at line 48 of file LearningImplExtractor.cpp.
References cnf_var_to_standalone_aig_var_, VarInfo::CTRL, VarManager::getInfo(), VarInfo::getLitInAIG(), VarInfo::getName(), VarManager::getPresErrorStateVar(), AIG2CNF::getTmpDepsTrans(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), AIG2CNF::instance(), ip_, ipc_, AIG2CNF::isTrueInTrans(), next_free_aig_lit_, VarInfo::PRES_STATE, and standalone_circuit_.
LearningImplExtractor::~LearningImplExtractor () [virtual]
Destructor.
Definition at line 121 of file LearningImplExtractor.cpp.
References qbf_solver_, and standalone_circuit_.
LearningImplExtractor::LearningImplExtractor (const LearningImplExtractor & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void LearningImplExtractor::addToStandAloneAiger (int ctrl_var, const CNF & solution) [protected]
Adds the solution for one output function to the AIGER circuit we have so far.
The AIGER circuit we have so far is built up in standalone_circuit_. This method adds an output function (in CNF) for one control signal.
Parameters
ctrl_var The control signal for which we would like to add an output function.
solution The output function (in CNF) defining the control signal.
Definition at line 1742 of file LearningImplExtractor.cpp.
References cnfToAig(), CNF::getClauses(), makeAnd(), makeOr(), and standalone_circuit_.
Referenced by runLearningExp(), runLearningJiangSAT(), runLearningJiangSATInc1(), runLearningJiangSATInc2(), runLearningJiangSATTmp(), runLearningJiangSATTmpCtrl(), runLearningJiangSATTmpCtrlInc2(), runLearningQBF(), and runLearningQBFInc().
int LearningImplExtractor::cnfToAig (int cnf_lit) [protected]
Transforms a CNF literal into an AIGER literal as used in standalone_circuit_.
Parameters
cnf_lit The literal as it occurs in CNF formulas.
Returns
The corresponding AIGER index of the literal as it is used in the standalone_circuit_.
Definition at line 1778 of file LearningImplExtractor.cpp.
References cnf_var_to_standalone_aig_var_.
Referenced by addToStandAloneAiger(), and insertMissingAndFromTrans().
void CNFImplExtractor::extractCircuit (const CNF & winning_region) [virtual], [inherited]
Extracts a circuit from the winning region.
How this is done (interpolation, learning, etc.) depends on the concrete implementation of this abstract class. The result is written into the output file specified by the user.
Parameters
winning_region The winning region from which the circuit should be extracted. For circuit extraction we need both the winning region and its negation. The negation is computed inside this function. If you already have a negation, use the other circuit extraction method of this class.
Reimplemented in StoreImplExtractor.
Definition at line 85 of file CNFImplExtractor.cpp.
References Utils::compressStateCNF(), CNFImplExtractor::extraction_cpu_time_, CNFImplExtractor::extraction_real_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), CNF::negate(), CNFImplExtractor::run(), and Stopwatch::start().
Referenced by LoadSynth::run(), LearnSynthQBFInc::run(), TemplateSynth::run(), IFM13Synth::run(), LearnSynthQBF::run(), LearnSynthSAT::run(), LearnSynthQBFInd::run(), and ParallelLearner::run().
void CNFImplExtractor::extractCircuit (const CNF & winning_region, const CNF & neg_winning_region) [virtual], [inherited]
Extracts a circuit from the winning region and its negation.
How this is done (interpolation, learning, etc.) depends on the concrete implementation of this abstract class. The result is written into the output file specified by the user.
Parameters
winning_region The winning region from which the circuit should be extracted.
neg_winning_region The negation of the winning region.
Definition at line 102 of file CNFImplExtractor.cpp.
References CNFImplExtractor::extraction_cpu_time_, CNFImplExtractor::extraction_real_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), CNFImplExtractor::run(), and Stopwatch::start().
size_t CNFImplExtractor::insertIntoSpec (aiger * standalone_circuit) const [protected], [inherited]
Takes a circuit defining the control signals and inserts it into the spec.
This method takes as argument an aiger circuit of the following form:
The circuit is combinational, i.e., has no latches.
The inputs of the circuit are: the uncontrollable inputs from the spec (in the order in which they appear in the spec) followed by the state-signals (the output of the latches in the spec, in the order in which they appear in the spec).
The outputs of the circuit are the controllable inputs in the order in which they are defined in the spec.
Parameters
standalone_circuit A circuit defining the control signals.
Returns
The number of additional AND gates introduced into the spec.
Definition at line 149 of file CNFImplExtractor.cpp.
References VarInfo::CTRL, Options::getAigInFileName(), Options::getAigOutFileName(), VarManager::getInfo(), VarInfo::getLitInAIG(), VarManager::getMaxAIGVar(), VarManager::getPresErrorStateVar(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), Options::instance(), MASSERT, VarInfo::PRES_STATE, and StringUtils::toLowerCaseIn().
Referenced by ParExtractor::run(), run(), and QBFCertImplExtractor::run().
void LearningImplExtractor::insertMissingAndFromTrans () [protected]
Copies missing AND gates from the spec.
This method is only used for an optimization in the methods runLearningJiangSATTmp, runLearningJiangSATTmpCtrl, and runLearningJiangSATTmpCtrlInc2. These methods allow solutions to depend on temporary variables that appear in the original specification. The rules for SYNTComp do not allow to refer to such temporary variables from the specification in the final solution. Hence, this method simply copies the AND gates from the specification into the standalone_circuit_.
Definition at line 1806 of file LearningImplExtractor.cpp.
References VarManager::aigLitToCnfLit(), cnf_var_to_standalone_aig_var_, cnfToAig(), Options::getAigInFileName(), AIG2CNF::getTmpDeps(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), MASSERT, standalone_circuit_, and VarInfo::TMP.
Referenced by runLearningJiangSATTmp(), runLearningJiangSATTmpCtrl(), and runLearningJiangSATTmpCtrlInc2().
void LearningImplExtractor::logDetailedStatistics () [protected], [virtual]
Logs the detailed statistics collected in the LearningExtractorStatistics.
Reimplemented from CNFImplExtractor.
Definition at line 1865 of file LearningImplExtractor.cpp.
References LearningExtractorStatistics::logStatistics(), and statistics.
void CNFImplExtractor::logStatistics () [virtual], [inherited]
Logs statistical information about circuit extraction.
This method logs the overall execution time plus whatever detailed information is collected by the concrete implementation of this class.
Definition at line 290 of file CNFImplExtractor.cpp.
References CNFImplExtractor::extraction_cpu_time_, CNFImplExtractor::extraction_real_time_, L_LOG, and CNFImplExtractor::logDetailedStatistics().
Referenced by LoadSynth::run(), LearnSynthQBFInc::run(), TemplateSynth::run(), IFM13Synth::run(), LearnSynthQBF::run(), LearnSynthSAT::run(), LearnSynthQBFInd::run(), and ParallelLearner::run().
int LearningImplExtractor::makeAnd (int in1, int in2) [protected]
Creates the AND between two AIGER literals and returns the resulting literal.
This method extends the standalone_circuit_ with logic to compute the AND between two AIGER literals. The literal that represents the result of the AND is returned.
Parameters
in1 The first operand of the AND: an AIGER literal from standalone_circuit_.
in2 The second operand of the AND: an AIGER literal from standalone_circuit_.
Returns
The literal that represents the result of the AND.
Definition at line 1788 of file LearningImplExtractor.cpp.
References next_free_aig_lit_, and standalone_circuit_.
Referenced by addToStandAloneAiger().
CNF LearningImplExtractor::makeEq (int var, CNF impl) [protected]
Creates a CNF that assigns a variable to the result of some other CNF.
This method creates a CNF that for (var <-> impl), where var is a variable and impl is a CNF. It is used to say that a certain control signal is now defined by a function that has been computed in CNF form.
Parameters
var The variable to set equal to the result of the CNF impl.
impl The CNF that should define the value of var.
Returns
A CNF representation of (var <-> impl).
Definition at line 1654 of file LearningImplExtractor.cpp.
References CNF::addClause(), CNF::addCNF(), CNF::getClauses(), CNF::negate(), and CNF::swapWith().
Referenced by runLearningExp(), runLearningJiangSAT(), runLearningJiangSATInc1(), runLearningJiangSATInc2(), runLearningJiangSATTmp(), runLearningJiangSATTmpCtrl(), runLearningJiangSATTmpCtrlInc2(), runLearningQBF(), and runLearningQBFInc().
CNF LearningImplExtractor::makeEq2 (int var, CNF impl) [protected]
An alternative implementation of makeEq, which seems to be slower.
Parameters
var The variable to set equal to the result of the CNF impl.
impl The CNF that should define the value of var.
Returns
A CNF representation of (var <-> impl).
Definition at line 1691 of file LearningImplExtractor.cpp.
References CNF::add2LitClause(), CNF::add3LitClause(), CNF::addClause(), VarManager::createFreshTmpVar(), CNF::getClauses(), and VarManager::instance().
int LearningImplExtractor::makeOr (int in1, int in2) [protected]
Creates the OR between two AIGER literals and returns the resulting literal.
This method extends the standalone_circuit_ with logic to compute the OR between two AIGER literals. The literal that represents the result of the OR is returned.
Parameters
in1 The first operand of the OR: an AIGER literal from standalone_circuit_.
in2 The second operand of the OR: an AIGER literal from standalone_circuit_.
Returns
The literal that represents the result of the OR.
Definition at line 1797 of file LearningImplExtractor.cpp.
References next_free_aig_lit_, and standalone_circuit_.
Referenced by addToStandAloneAiger().
LearningImplExtractor& LearningImplExtractor::operator= (const LearningImplExtractor & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
aiger * CNFImplExtractor::optimizeWithABC (aiger * circuit) [static], [inherited]
Optimizes a combinatorial AIGER circuit with ABC.
Note
The returned structure must be deleted by the caller.
Parameters
circuit The circuit to optimize.
Returns
The optimized version of the circuit. The returned aiger structure must be deleted by the caller.
Definition at line 112 of file CNFImplExtractor.cpp.
References Options::getTPDirName(), Options::getUniqueTmpFileName(), Options::instance(), and MASSERT.
Referenced by run(), QBFCertImplExtractor::run(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void LearningImplExtractor::run (const CNF & winning_region, const CNF & neg_winning_region) [virtual]
Runs this circuit extractor.
Depending on the selected method (using the command --circuit-mode or -n), one of the methods runLearningX is called with appropriate parameters. Finally, ABC is used to optimize the resulting circuit, and the implementation is inserted into the specification (as required by the SYNTComp rules).
Parameters
winning_region The winning region from which the circuit should be extracted.
neg_winning_region The negation of the winning region.
Implements CNFImplExtractor.
Definition at line 130 of file LearningImplExtractor.cpp.
References CNFImplExtractor::insertIntoSpec(), Options::instance(), MASSERT, LearningExtractorStatistics::notifyAfterABC(), LearningExtractorStatistics::notifyBeforeABC(), LearningExtractorStatistics::notifyFinalSize(), CNFImplExtractor::optimizeWithABC(), runLearningExp(), runLearningJiangSAT(), runLearningJiangSATInc1(), runLearningJiangSATInc2(), runLearningJiangSATTmp(), runLearningJiangSATTmpCtrl(), runLearningJiangSATTmpCtrlInc2(), runLearningQBF(), runLearningQBFInc(), standalone_circuit_, and statistics.
void LearningImplExtractor::runLearningExp (const CNF & win_region, const CNF & neg_win_region) [protected]
Same as runLearningQBFInc, but using universal expansion and a SAT solver.
Although using SAT solvers instead of QBF appears to pay off when computing the winning region, this does not seem to hold true here: this method is relatively slow.
Parameters
win_region The winning region from which the circuit should be extracted.
neg_win_region The negation of the winning region.
Definition at line 367 of file LearningImplExtractor.cpp.
References CNF::addCNF(), CNF::addNegCubeAsClause(), addToStandAloneAiger(), Utils::compressNextStateCNF(), VarInfo::CTRL, UnivExpander::extrExp(), Options::getSATSolverExtr(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incIsSatModelOrCore(), VarManager::instance(), Options::instance(), ip_, makeEq(), MASSERT, LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), Utils::remove(), CNF::setVarValue(), and statistics.
Referenced by run().
void LearningImplExtractor::runLearningJiangSAT (const CNF & win_region, const CNF & neg_win_region, bool second_run = false, bool min_cores = true) [protected]
Uses SAT-based CNF learning with Jiang-resubstitution.
This method also implements the same CNF learning algorithm as runLearningQBF. The difference is that this method uses a SAT solver instead of a QBF solver. In order to avoid solving a quantifier alternation, the method handles output signals just like inputs (temporarily) as explained in the paper: Jie-Hong Roland Jiang, Hsuan-Po Lin, Wei-Lun Hung: Interpolating functions from large Boolean relations. ICCAD 2009: 779-784. Once a working solution has been computed, this method can also run a second minimization round, where it tries to simplify the solution further. This second optimization round can be enabled or disabled.
Parameters
win_region The winning region from which the circuit should be extracted.
neg_win_region The negation of the winning region.
second_run A flag to control whether a second optimization round should be performed after a working solution is already available. This costs time, but can lead to smaller circuits. If the parameter is omitted, then this step will NOT be performed. Personal feeling: it usually does not pay off.
min_cores A flag that controls whether the SAT solver should compute minimal unsatisfiable cores, or just regular ones. Especially if the second_run flag is true, it may make sense to set this flag to false to be faster in the first round. However, often having min_cores=false makes things slower (and leads to larger circuits). That's why true is the default value.
Definition at line 436 of file LearningImplExtractor.cpp.
References CNF::addCNF(), CNF::addNegCubeAsClause(), addToStandAloneAiger(), VarInfo::CTRL, SatSolver::doMinCores(), VarManager::getMaxCNFVar(), Options::getSATSolverExtr(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incAddUnitClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), ipc_, makeEq(), MASSERT, Utils::negateLiterals(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), Utils::remove(), CNF::renameVars(), CNF::setVarValue(), SatSolver::startIncrementalSession(), statistics, and CNF::swapPresentToNext().
Referenced by run().
void LearningImplExtractor::runLearningJiangSATInc1 (const CNF & win_region, const CNF & neg_win_region, bool second_run = false, bool min_cores = true) [protected]
Like runLearningJiangSAT but with more aggressive incremental solving.
The method runLearningJiangSAT uses incremental solving, but only it has two different solver instances per control signal: one for computing problematic situations, and one for generalizing them using an unsatisfiable core computation. This method uses incremental soling in a more aggressive way. It uses only two solver instances, one for computing problematic situations across all control signals, and one for generalizing them across all iterations. This is achieved by introducing activation variables that activate or deactivate different parts of the formula, depending on the control signal we are currently synthesizing.
Parameters
win_region The winning region from which the circuit should be extracted.
neg_win_region The negation of the winning region.
second_run A flag to control whether a second optimization round should be performed after a working solution is already available. This costs time, but can lead to smaller circuits. If the parameter is omitted, then this step will NOT be performed. Personal feeling: it usually does not pay off.
min_cores A flag that controls whether the SAT solver should compute minimal unsatisfiable cores, or just regular ones. Especially if the second_run flag is true, it may make sense to set this flag to false to be faster in the first round. However, often having min_cores=false makes things slower (and leads to larger circuits). That's why true is the default value.
Definition at line 1249 of file LearningImplExtractor.cpp.
References CNF::add2LitClause(), CNF::add3LitClause(), CNF::addClause(), CNF::addCNF(), CNF::addNegCubeAsClause(), addToStandAloneAiger(), VarManager::createFreshTmpVar(), VarInfo::CTRL, SatSolver::doMinCores(), VarManager::getMaxCNFVar(), Options::getSATSolverExtr(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), ip_, ipc_, makeEq(), MASSERT, Utils::negateLiterals(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), Utils::remove(), CNF::renameVars(), CNF::setVarValue(), SatSolver::startIncrementalSession(), statistics, and CNF::swapPresentToNext().
Referenced by run().
void LearningImplExtractor::runLearningJiangSATInc2 (const CNF & win_region, const CNF & neg_win_region, bool second_run = false, bool min_cores = true) [protected]
Like runLearningJiangSATInc1 but with even more aggressive incremental solving.
While the method runLearningJiangSATInc1 uses two solver instances to compute all control signals, this method uses only one instance. This is achieved by introducing even more activation variables.
Parameters
win_region The winning region from which the circuit should be extracted.
neg_win_region The negation of the winning region.
second_run A flag to control whether a second optimization round should be performed after a working solution is already available. This costs time, but can lead to smaller circuits. If the parameter is omitted, then this step will NOT be performed. Personal feeling: it usually does not pay off.
min_cores A flag that controls whether the SAT solver should compute minimal unsatisfiable cores, or just regular ones. Especially if the second_run flag is true, it may make sense to set this flag to false to be faster in the first round. However, often having min_cores=false makes things slower (and leads to larger circuits). That's why true is the default value.
Definition at line 1456 of file LearningImplExtractor.cpp.
References CNF::add2LitClause(), CNF::add3LitClause(), CNF::addClause(), CNF::addCNF(), CNF::addNegCubeAsClause(), addToStandAloneAiger(), VarManager::createFreshTmpVar(), VarInfo::CTRL, SatSolver::doMinCores(), VarManager::getMaxCNFVar(), Options::getSATSolverExtr(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), ip_, ipc_, makeEq(), MASSERT, Utils::negateLiterals(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), Utils::remove(), CNF::renameVars(), CNF::setVarValue(), SatSolver::startIncrementalSession(), statistics, and CNF::swapPresentToNext().
Referenced by run().
void LearningImplExtractor::runLearningJiangSATTmp (const CNF & win_region, const CNF & neg_win_region, bool second_run = false, bool min_cores = true) [protected]
Uses SAT-based CNF learning with Jiang-resubstitution and temporary variables.
This method is very similar to runLearningJiangSAT. The only difference is that this method also allows control signals to depend on temporary variables from the original input file (the specification), as long as these temporary variables do not depend on the respective control signal. Since the rules for SYNTComp do not allow such dependencies in the final output, they are removed again simply by copying the respective parts of the original input file before producing the output file.
Parameters
win_region The winning region from which the circuit should be extracted.
neg_win_region The negation of the winning region.
second_run A flag to control whether a second optimization round should be performed after a working solution is already available. This costs time, but can lead to smaller circuits. If the parameter is omitted, then this step will NOT be performed. Personal feeling: it usually does not pay off.
min_cores A flag that controls whether the SAT solver should compute minimal unsatisfiable cores, or just regular ones. Especially if the second_run flag is true, it may make sense to set this flag to false to be faster in the first round. However, often having min_cores=false makes things slower (and leads to larger circuits). That's why true is the default value.
Definition at line 604 of file LearningImplExtractor.cpp.
References CNF::addCNF(), CNF::addNegCubeAsClause(), addToStandAloneAiger(), Utils::contains(), VarInfo::CTRL, SatSolver::doMinCores(), VarManager::getMaxCNFVar(), Options::getSATSolverExtr(), AIG2CNF::getTmpDepsTrans(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incAddUnitClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), insertMissingAndFromTrans(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), ipc_, makeEq(), MASSERT, Utils::negateLiterals(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), Utils::randomize(), Utils::remove(), CNF::renameVars(), CNF::setVarValue(), SatSolver::startIncrementalSession(), statistics, and CNF::swapPresentToNext().
Referenced by run().
void LearningImplExtractor::runLearningJiangSATTmpCtrl (const CNF & win_region, const CNF & neg_win_region, bool second_run = false, bool min_cores = true) [protected]
Like runLearningJiangSATTmp, but also allows dependencies on control signals.
This method is very similar to runLearningJiangSATTmp. The only difference is that this method also even more dependencies between control signals. If a certain already computed control signal A does not depend on a yet to compute control signal B, then B is allowed to depend on A.
Parameters
win_region The winning region from which the circuit should be extracted.
neg_win_region The negation of the winning region.
second_run A flag to control whether a second optimization round should be performed after a working solution is already available. This costs time, but can lead to smaller circuits. If the parameter is omitted, then this step will NOT be performed. Personal feeling: it usually does not pay off.
min_cores A flag that controls whether the SAT solver should compute minimal unsatisfiable cores, or just regular ones. Especially if the second_run flag is true, it may make sense to set this flag to false to be faster in the first round. However, often having min_cores=false makes things slower (and leads to larger circuits). That's why true is the default value.
Definition at line 792 of file LearningImplExtractor.cpp.
References CNF::addCNF(), CNF::addNegCubeAsClause(), addToStandAloneAiger(), Utils::contains(), CNF::contains(), VarInfo::CTRL, DASSERT, SatSolver::doMinCores(), VarManager::getMaxCNFVar(), Options::getSATSolverExtr(), AIG2CNF::getTmpDepsTrans(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incAddUnitClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), insertMissingAndFromTrans(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), ipc_, makeEq(), MASSERT, Utils::negateLiterals(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), Utils::randomize(), Utils::remove(), CNF::renameVars(), CNF::setVarValue(), SatSolver::startIncrementalSession(), statistics, and CNF::swapPresentToNext().
Referenced by run().
void LearningImplExtractor::runLearningJiangSATTmpCtrlInc2 (const CNF & win_region, const CNF & neg_win_region, bool second_run = false, bool min_cores = true) [protected]
Combines runLearningJiangSATTmpCtrl and runLearningJiangSATInc2.
This method is like runLearningJiangSATTmpCtrl, but uses incremental solving more aggressively, just like runLearningJiangSATInc2. This is achieved by introducing acitvation variables that enable or disable different parts of the formula.
Parameters
win_region The winning region from which the circuit should be extracted.
neg_win_region The negation of the winning region.
second_run A flag to control whether a second optimization round should be performed after a working solution is already available. This costs time, but can lead to smaller circuits. If the parameter is omitted, then this step will NOT be performed. Personal feeling: it usually does not pay off.
min_cores A flag that controls whether the SAT solver should compute minimal unsatisfiable cores, or just regular ones. Especially if the second_run flag is true, it may make sense to set this flag to false to be faster in the first round. However, often having min_cores=false makes things slower (and leads to larger circuits). That's why true is the default value.
Definition at line 1024 of file LearningImplExtractor.cpp.
References CNF::add2LitClause(), CNF::addCNF(), CNF::addNegCubeAsClause(), addToStandAloneAiger(), Utils::contains(), CNF::contains(), VarInfo::CTRL, DASSERT, SatSolver::doMinCores(), VarManager::getMaxCNFVar(), Options::getSATSolverExtr(), AIG2CNF::getTmpDepsTrans(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), insertMissingAndFromTrans(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), ipc_, makeEq(), MASSERT, Utils::negateLiterals(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), Utils::randomize(), Utils::remove(), CNF::renameVars(), CNF::setVarValue(), SatSolver::startIncrementalSession(), statistics, and CNF::swapPresentToNext().
Referenced by run().
void LearningImplExtractor::runLearningQBF (const CNF & win_region, const CNF & neg_win_region) [protected]
Implements circuit extraction with non-incremental QBF-based CNF learning.
This is a more or less straightforward implementation of the CNF learning method from the paper Ruediger Ehlers, Robert Koenighofer, Georg Hofferek: Symbolically synthesizing small circuits. FMCAD 2012: 91.2.0 using a QBF solver.
Parameters
win_region The winning region from which the circuit should be extracted.
neg_win_region The negation of the winning region.
Definition at line 202 of file LearningImplExtractor.cpp.
References QBFSolver::A, CNF::addCNF(), CNF::addCube(), CNF::addNegCubeAsClause(), addToStandAloneAiger(), VarInfo::CTRL, QBFSolver::E, VarManager::getVarsOfType(), VarManager::instance(), AIG2CNF::instance(), ip_, QBFSolver::isSat(), QBFSolver::isSatModel(), makeEq(), VarInfo::NEXT_STATE, LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), qbf_solver_, Utils::remove(), CNF::setVarValue(), statistics, CNF::swapPresentToNext(), and VarInfo::TMP.
Referenced by run().
void LearningImplExtractor::runLearningQBFInc (const CNF & win_region, const CNF & neg_win_region) [protected]
Implements circuit extraction with incremental QBF-based CNF learning.
This method is very similar to runLearningQBF. The difference is that this one uses incremental QBF solving using DepQBF via its API. This method will always use DepQBF, no matter which solver the user selects via command-line arguments.
Parameters
win_region The winning region from which the circuit should be extracted.
neg_win_region The negation of the winning region.
Definition at line 284 of file LearningImplExtractor.cpp.
References QBFSolver::A, CNF::addCNF(), CNF::addNegCubeAsClause(), addToStandAloneAiger(), VarInfo::CTRL, QBFSolver::E, VarManager::getVarsOfType(), DepQBFApi::incAddCNF(), DepQBFApi::incAddNegCubeAsClause(), DepQBFApi::incIsSatCore(), DepQBFApi::incIsSatModel(), VarManager::instance(), AIG2CNF::instance(), ip_, makeEq(), MASSERT, VarInfo::NEXT_STATE, LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), Utils::remove(), CNF::setVarValue(), DepQBFApi::startIncrementalSession(), statistics, CNF::swapPresentToNext(), and VarInfo::TMP.
Referenced by run().
Member Data Documentation
vector<int> LearningImplExtractor::cnf_var_to_standalone_aig_var_ [protected]
A map from variables as they occur in CNFs to the corresponding AIGER literals.
This vector maps variables as they occur in CNFs to the corresponding AIGER literals as they occur in the standalone_circuit_. Use cnfToAig to transform literals.
Note
The AIGER literal numbering scheme in the standalone_circuit_ is different from the numbering scheme in the original specification. The reason is that we want to avoid big 'holes' of unused AIGER literals right from the beginning.
Definition at line 408 of file LearningImplExtractor.h.
Referenced by cnfToAig(), insertMissingAndFromTrans(), and LearningImplExtractor().
double CNFImplExtractor::extraction_cpu_time_ [protected], [inherited]
The circuit extraction time in CPU-seconds.
Definition at line 145 of file CNFImplExtractor.h.
Referenced by CNFImplExtractor::extractCircuit(), and CNFImplExtractor::logStatistics().
size_t CNFImplExtractor::extraction_real_time_ [protected], [inherited]
Like extraction_cpu_time_ but real-time.
Definition at line 150 of file CNFImplExtractor.h.
Referenced by CNFImplExtractor::extractCircuit(), and CNFImplExtractor::logStatistics().
vector<int> LearningImplExtractor::ip_ [protected]
The list of uncontrollable input variables followed by the present state variables.
This vector contains the CNF version of the uncontrollable input variables followed by the present state variables. This vector of variables is used often, and thus stored here as a field.
Definition at line 417 of file LearningImplExtractor.h.
Referenced by LearningImplExtractor(), runLearningExp(), runLearningJiangSATInc1(), runLearningJiangSATInc2(), runLearningQBF(), and runLearningQBFInc().
vector<int> LearningImplExtractor::ipc_ [protected]
The list of uncontrollable inputs, state variables, and control signals.
This vector contains the CNF version of the uncontrollable input variables followed by the present state variables, followed by the control signals. This vector of variables is used often, and thus stored here as a field.
Definition at line 426 of file LearningImplExtractor.h.
Referenced by LearningImplExtractor(), runLearningJiangSAT(), runLearningJiangSATInc1(), runLearningJiangSATInc2(), runLearningJiangSATTmp(), runLearningJiangSATTmpCtrl(), and runLearningJiangSATTmpCtrlInc2().
int LearningImplExtractor::next_free_aig_lit_ [protected]
The next unused AIGER literal in standalone_circuit_.
Definition at line 381 of file LearningImplExtractor.h.
Referenced by LearningImplExtractor(), makeAnd(), and makeOr().
QBFSolver* LearningImplExtractor::qbf_solver_ [protected]
The QBF solver to use (as selected by the user with command-line arguments).
Definition at line 376 of file LearningImplExtractor.h.
Referenced by runLearningQBF(), and ~LearningImplExtractor().
aiger* LearningImplExtractor::standalone_circuit_ [protected]
The synthesis result as stand-alone circuit.
This AIGER circuit is combinatorial, i.e., has no latches. The inputs of the circuit are: the uncontrollable inputs from the spec (in the order in which they appear in the spec) followed by the state-signals (the output of the latches in the spec, in the order in which they appear in the spec). The outputs of the circuit are the controllable inputs in the order in which they are defined in the spec.
This circuit will be built up by one of the methods runLearningX. Then, it will be optimized using ABC. Finally, it will be inserted into the original specification, as required by the rules for SYNTComp.
Definition at line 396 of file LearningImplExtractor.h.
Referenced by addToStandAloneAiger(), insertMissingAndFromTrans(), LearningImplExtractor(), makeAnd(), makeOr(), run(), and ~LearningImplExtractor().
LearningExtractorStatistics LearningImplExtractor::statistics [protected]
A helper for collecting performance data and statistics.
Definition at line 431 of file LearningImplExtractor.h.
Referenced by logDetailedStatistics(), run(), runLearningExp(), runLearningJiangSAT(), runLearningJiangSATInc1(), runLearningJiangSATInc2(), runLearningJiangSATTmp(), runLearningJiangSATTmpCtrl(), runLearningJiangSATTmpCtrlInc2(), runLearningQBF(), and runLearningQBFInc().
The documentation for this class was generated from the following files:
src/LearningImplExtractor.h
src/LearningImplExtractor.cpp