LearnStatisticsQBF Class Reference
Collects statistics and performance data for LearnSynthQBF (and all its variants).
#include <LearnStatisticsQBF.h>
Public Member Functions
LearnStatisticsQBF ()
Constructor.
virtual ~LearnStatisticsQBF ()
Destructor.
void notifyWinRegStart ()
Called before the computation of the winning region starts.
void notifyWinRegEnd ()
Called after the computation of the winning region is done.
void notifyRelDetStart ()
Called before the relation determinization (the computation of circuits) starts.
void notifyRelDetEnd ()
Called after the relation determinization (the computation of circuits) starts.
void notifyBeforeComputeCube ()
Called before the QBF solver is called to compute a counterexample-state.
void notifyAfterComputeCube ()
Called after the QBF solver is done computing a counterexample-state.
void notifyBeforeCubeMin ()
Called before the generalization of the counterexample-state starts.
void notifyAfterCubeMin (size_t from_size, size_t to_size)
Called after the generalization of the counterexample-state is done.
void notifyAfterCubeMin ()
Called after the generalization of the counterexample-state is done.
void notifyCubeMin (size_t from_size, size_t to_size)
Stores the result of a counterexample-cube generalization.
void logStatistics () const
Writes the statistics to stdout as messages of type Logger::LOG.
Protected Attributes
PointInTime win_reg_start_time_
The time when the computation of the winning region was started.
double win_reg_cpu_time_
The winning region computation time in CPU-seconds.
size_t win_reg_real_time_
Like win_reg_cpu_time_ but real-time.
PointInTime rel_det_start_time_
The time when the computation of the circuits was started.
double rel_det_cpu_time_
circuit computation time in CPU-seconds.
size_t rel_det_real_time_
Like rel_det_cpu_time_ but real-time.
size_t nr_of_cube_computations_
The total number of counterexample-cube computations.
PointInTime compute_start_time_
The time when the last computation of a counterexample-cube was started.
double sum_compute_cpu_time_
The total counterexample computation time in CPU-seconds.
size_t sum_compute_real_time_
Like sum_compute_cpu_time_ but real-time.
size_t nr_of_cube_min_
The total number of counterexample-cube generalizations.
PointInTime min_start_time_
The time when the last generalization of a counterexample-cube was started.
double sum_min_cpu_time_
The total counterexample generalization time in CPU-seconds.
size_t sum_min_real_time_
Like sum_min_cpu_time_ but real-time.
size_t sum_cube_size_from_
The sum of the counterexample cube sizes (nr of literals) before generalization.
size_t sum_cube_size_to_
The sum of the counterexample cube sizes (nr of literals) after generalization.
Private Member Functions
LearnStatisticsQBF (const LearnStatisticsQBF &other)
Copy constructor.
LearnStatisticsQBF & operator= (const LearnStatisticsQBF &other)
Assignment operator.
Detailed Description
Collects statistics and performance data for LearnSynthQBF (and all its variants).
This class collects statistics and performance data for the learning-based synthesis method implemented with a QBF-solver (implemented in the class LearnSynthQBF).
Definition at line 43 of file LearnStatisticsQBF.h.
Constructor & Destructor Documentation
LearnStatisticsQBF::LearnStatisticsQBF ()
Constructor.
Definition at line 34 of file LearnStatisticsQBF.cpp.
LearnStatisticsQBF::~LearnStatisticsQBF () [virtual]
Destructor.
Definition at line 52 of file LearnStatisticsQBF.cpp.
LearnStatisticsQBF::LearnStatisticsQBF (const LearnStatisticsQBF & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void LearnStatisticsQBF::logStatistics () const
Writes the statistics to stdout as messages of type Logger::LOG.
If messages of type Logger::LOG are disabled (see Logger), then nothing happens.
Definition at line 129 of file LearnStatisticsQBF.cpp.
References L_LOG, nr_of_cube_computations_, nr_of_cube_min_, rel_det_cpu_time_, rel_det_real_time_, sum_compute_cpu_time_, sum_compute_real_time_, sum_cube_size_from_, sum_cube_size_to_, sum_min_cpu_time_, sum_min_real_time_, win_reg_cpu_time_, and win_reg_real_time_.
Referenced by LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOneSAT(), LearnSynthQBFInc::run(), LearnSynthQBF::run(), and LearnSynthQBFInd::run().
void LearnStatisticsQBF::notifyAfterComputeCube ()
Called after the QBF solver is done computing a counterexample-state.
This method just reads out the Stopwatch and stores the execution time.
Definition at line 90 of file LearnStatisticsQBF.cpp.
References compute_start_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), nr_of_cube_computations_, sum_compute_cpu_time_, and sum_compute_real_time_.
Referenced by LearnSynthQBFInc::computeCounterexampleQBF(), LearnSynthQBF::computeCounterexampleQBF(), LearnSynthQBFInd::computeCounterexampleQBF(), and LearnSynthQBF::computeCounterexampleSAT().
void LearnStatisticsQBF::notifyAfterCubeMin (size_t from_size, size_t to_size)
Called after the generalization of the counterexample-state is done.
This method just reads out the Stopwatch and stores the execution time. Furthermore, it stores the results of generalizing the counterexample.
Parameters
from_size The size of the counterexample (number of literals in the cube) before generalization (by dropping literals from the cube).
to_size The size of the counterexample (number of literals in the cube) after generalization (by dropping literals from the cube).
Definition at line 104 of file LearnStatisticsQBF.cpp.
References Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), min_start_time_, nr_of_cube_min_, sum_cube_size_from_, sum_cube_size_to_, sum_min_cpu_time_, and sum_min_real_time_.
Referenced by LearnSynthQBFInc::computeAllBlockingClauses(), LearnSynthQBF::computeAllBlockingClauses(), LearnSynthQBFInd::computeAllBlockingClauses(), LearnSynthQBFInc::computeBlockingClause(), LearnSynthQBF::computeBlockingClause(), LearnSynthQBFInd::computeBlockingClause(), LearnSynthQBFInc::reduceExistingClauses(), LearnSynthQBF::reduceExistingClauses(), and LearnSynthQBFInd::reduceExistingClauses().
void LearnStatisticsQBF::notifyAfterCubeMin ()
Called after the generalization of the counterexample-state is done.
This method just reads out the Stopwatch and stores the execution time. It does not store the results of generalizing the counterexample. This can be done with a call to notifyCubeMin() .
Definition at line 114 of file LearnStatisticsQBF.cpp.
References Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), min_start_time_, sum_min_cpu_time_, and sum_min_real_time_.
void LearnStatisticsQBF::notifyBeforeComputeCube ()
Called before the QBF solver is called to compute a counterexample-state.
This method just starts a Stopwatch.
Definition at line 84 of file LearnStatisticsQBF.cpp.
References compute_start_time_, and Stopwatch::start().
Referenced by LearnSynthQBFInc::computeCounterexampleQBF(), LearnSynthQBF::computeCounterexampleQBF(), LearnSynthQBFInd::computeCounterexampleQBF(), and LearnSynthQBF::computeCounterexampleSAT().
void LearnStatisticsQBF::notifyBeforeCubeMin ()
Called before the generalization of the counterexample-state starts.
This method just starts a Stopwatch.
Definition at line 98 of file LearnStatisticsQBF.cpp.
References min_start_time_, and Stopwatch::start().
Referenced by LearnSynthQBFInc::computeAllBlockingClauses(), LearnSynthQBF::computeAllBlockingClauses(), LearnSynthQBFInd::computeAllBlockingClauses(), LearnSynthQBFInc::computeBlockingClause(), LearnSynthQBF::computeBlockingClause(), LearnSynthQBFInd::computeBlockingClause(), LearnSynthQBFInc::reduceExistingClauses(), LearnSynthQBF::reduceExistingClauses(), and LearnSynthQBFInd::reduceExistingClauses().
void LearnStatisticsQBF::notifyCubeMin (size_t from_size, size_t to_size)
Stores the result of a counterexample-cube generalization.
This method is useful if notifyAfterCubeMin() is called without parameters.
Parameters
from_size The size of the counterexample (number of literals in the cube) before generalization (by dropping literals from the cube).
to_size The size of the counterexample (number of literals in the cube) after generalization (by dropping literals from the cube).
Definition at line 121 of file LearnStatisticsQBF.cpp.
References nr_of_cube_min_, sum_cube_size_from_, and sum_cube_size_to_.
Referenced by LearnSynthQBFInc::computeAllBlockingClauses(), LearnSynthQBF::computeAllBlockingClauses(), and LearnSynthQBFInd::computeAllBlockingClauses().
void LearnStatisticsQBF::notifyRelDetEnd ()
Called after the relation determinization (the computation of circuits) starts.
This method just reads out the Stopwatch and stores the execution time.
Definition at line 77 of file LearnStatisticsQBF.cpp.
References Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), rel_det_cpu_time_, rel_det_real_time_, and rel_det_start_time_.
Referenced by LearnSynthQBFInc::run(), LearnSynthQBF::run(), and LearnSynthQBFInd::run().
void LearnStatisticsQBF::notifyRelDetStart ()
Called before the relation determinization (the computation of circuits) starts.
This method just starts a Stopwatch.
Definition at line 71 of file LearnStatisticsQBF.cpp.
References rel_det_start_time_, and Stopwatch::start().
Referenced by LearnSynthQBFInc::run(), LearnSynthQBF::run(), and LearnSynthQBFInd::run().
void LearnStatisticsQBF::notifyWinRegEnd ()
Called after the computation of the winning region is done.
This method just reads out the Stopwatch and stores the execution time.
Definition at line 64 of file LearnStatisticsQBF.cpp.
References Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), win_reg_cpu_time_, win_reg_real_time_, and win_reg_start_time_.
Referenced by LearnSynthQBFInc::run(), LearnSynthQBF::run(), and LearnSynthQBFInd::run().
void LearnStatisticsQBF::notifyWinRegStart ()
Called before the computation of the winning region starts.
This method just starts a Stopwatch.
Definition at line 58 of file LearnStatisticsQBF.cpp.
References Stopwatch::start(), and win_reg_start_time_.
Referenced by LearnSynthQBFInc::run(), LearnSynthQBF::run(), and LearnSynthQBFInd::run().
LearnStatisticsQBF& LearnStatisticsQBF::operator= (const LearnStatisticsQBF & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
Member Data Documentation
PointInTime LearnStatisticsQBF::compute_start_time_ [protected]
The time when the last computation of a counterexample-cube was started.
Definition at line 187 of file LearnStatisticsQBF.h.
Referenced by notifyAfterComputeCube(), and notifyBeforeComputeCube().
PointInTime LearnStatisticsQBF::min_start_time_ [protected]
The time when the last generalization of a counterexample-cube was started.
Definition at line 207 of file LearnStatisticsQBF.h.
Referenced by notifyAfterCubeMin(), and notifyBeforeCubeMin().
size_t LearnStatisticsQBF::nr_of_cube_computations_ [protected]
The total number of counterexample-cube computations.
Definition at line 182 of file LearnStatisticsQBF.h.
Referenced by logStatistics(), and notifyAfterComputeCube().
size_t LearnStatisticsQBF::nr_of_cube_min_ [protected]
The total number of counterexample-cube generalizations.
Definition at line 202 of file LearnStatisticsQBF.h.
Referenced by logStatistics(), notifyAfterCubeMin(), and notifyCubeMin().
double LearnStatisticsQBF::rel_det_cpu_time_ [protected]
circuit computation time in CPU-seconds.
Definition at line 172 of file LearnStatisticsQBF.h.
Referenced by logStatistics(), and notifyRelDetEnd().
size_t LearnStatisticsQBF::rel_det_real_time_ [protected]
Like rel_det_cpu_time_ but real-time.
Definition at line 177 of file LearnStatisticsQBF.h.
Referenced by logStatistics(), and notifyRelDetEnd().
PointInTime LearnStatisticsQBF::rel_det_start_time_ [protected]
The time when the computation of the circuits was started.
Definition at line 167 of file LearnStatisticsQBF.h.
Referenced by notifyRelDetEnd(), and notifyRelDetStart().
double LearnStatisticsQBF::sum_compute_cpu_time_ [protected]
The total counterexample computation time in CPU-seconds.
Definition at line 192 of file LearnStatisticsQBF.h.
Referenced by logStatistics(), and notifyAfterComputeCube().
size_t LearnStatisticsQBF::sum_compute_real_time_ [protected]
Like sum_compute_cpu_time_ but real-time.
Definition at line 197 of file LearnStatisticsQBF.h.
Referenced by logStatistics(), and notifyAfterComputeCube().
size_t LearnStatisticsQBF::sum_cube_size_from_ [protected]
The sum of the counterexample cube sizes (nr of literals) before generalization.
This is tracked to assess the effectiveness of the generalization.
Definition at line 224 of file LearnStatisticsQBF.h.
Referenced by logStatistics(), notifyAfterCubeMin(), and notifyCubeMin().
size_t LearnStatisticsQBF::sum_cube_size_to_ [protected]
The sum of the counterexample cube sizes (nr of literals) after generalization.
This is tracked to assess the effectiveness of the generalization.
Definition at line 231 of file LearnStatisticsQBF.h.
Referenced by logStatistics(), notifyAfterCubeMin(), and notifyCubeMin().
double LearnStatisticsQBF::sum_min_cpu_time_ [protected]
The total counterexample generalization time in CPU-seconds.
Definition at line 212 of file LearnStatisticsQBF.h.
Referenced by logStatistics(), and notifyAfterCubeMin().
size_t LearnStatisticsQBF::sum_min_real_time_ [protected]
Like sum_min_cpu_time_ but real-time.
Definition at line 217 of file LearnStatisticsQBF.h.
Referenced by logStatistics(), and notifyAfterCubeMin().
double LearnStatisticsQBF::win_reg_cpu_time_ [protected]
The winning region computation time in CPU-seconds.
Definition at line 157 of file LearnStatisticsQBF.h.
Referenced by logStatistics(), and notifyWinRegEnd().
size_t LearnStatisticsQBF::win_reg_real_time_ [protected]
Like win_reg_cpu_time_ but real-time.
Definition at line 162 of file LearnStatisticsQBF.h.
Referenced by logStatistics(), and notifyWinRegEnd().
PointInTime LearnStatisticsQBF::win_reg_start_time_ [protected]
The time when the computation of the winning region was started.
Definition at line 152 of file LearnStatisticsQBF.h.
Referenced by notifyWinRegEnd(), and notifyWinRegStart().
The documentation for this class was generated from the following files:
src/LearnStatisticsQBF.h
src/LearnStatisticsQBF.cpp