LearnSynthQBFInc Class Reference
Implements a learning-based synthesis with incremental QBF solving.
#include <LearnSynthQBFInc.h>
Public Member Functions
LearnSynthQBFInc (CNFImplExtractor *impl_extractor)
Constructor.
virtual ~LearnSynthQBFInc ()
Destructor.
virtual bool run ()
Executes this back-end.
Protected Member Functions
bool computeWinningRegion ()
Computes the winning region and stores the result in winning_region_.
bool computeWinningRegionOne ()
Uses the standard method to compute the winning region, with incremental solving.
bool computeWinningRegionOnePush ()
Uses incremental solving and push/pop to handle negation incrementally.
bool computeWinningRegionOnePool ()
Uses incremental solving and a pool of variables to handle negation incrementally.
bool computeWinningRegionAll ()
Computes the winning region, always computing all counterexample generalizations.
bool computeWinningRegionAllPush ()
Uses push/pop and always computes all counterexample generalizations.
bool computeWinningRegionAllPool ()
Uses a pool of variables and always computes all counterexample generalizations .
bool computeCounterexampleQBF (vector< int > &ce)
Computes a counterexample-state using a QBF-solver with incremental solving.
bool computeCounterexampleQBFPool (vector< int > &ce)
Computes a counterexample-state using a QBF-solver with incremental solving.
bool computeBlockingClause (vector< int > &ce, vector< int > &blocking_clause)
Computes a blocking clause for a counterexample.
bool computeAllBlockingClauses (vector< int > &ce, vector< vector< int > > &blocking_clauses)
Computes all minimal blocking clauses for a counterexample.
void reduceExistingClauses ()
Tries to drop literals from clauses in the winning region.
void recomputeCheckCNF (bool take_small_win=true)
Recomputes the CNF (of the QBF) that is used for computing counterexamples.
void recomputeGenCNF (bool take_small_win=true)
Recomputes the CNF (of the QBF) that is used for generalizing counterexamples.
void restrictToStates (vector< int > &vec) const
Restricts a vector of literals (a cube or clause) to state-variables only.
bool generalizeCounterexample (vector< int > &ce)
Generalizes a counterexample-state by dropping literals.
void generalizeCounterexampleFurther (vector< int > &ce)
Generalizes a counterexample-state further by dropping literals.
Protected Attributes
CNF winning_region_
The current over-approximation of the winning region.
CNF winning_region_large_
The current over-approximation of the winning region in an uncompressed form.
LearnStatisticsQBF statistics_
Stores and maintains statistics and performance measures.
vector< pair< VarInfo::VarKind,
*
QBFSolver::Quant > > check_quant_
The quantifier prefix of the QBF for computing counterexamples.
CNF check_cnf_
The CNF matrix of the QBF for computing counterexamples.
DepQBFApi solver_check_
The QBF-solver used for computing counterexamples.
vector< int > negcl_var_pool_
A pool of variables, which are used to express that a certain clause in negated.
vector< int > negcl_var_pool_act_
The activation variables to express that a var in negcl_var_pool_ is not yet used.
vector< pair< VarInfo::VarKind,
*
QBFSolver::Quant > > gen_quant_
The quantifier prefix of the QBF for generalizing counterexamples.
CNF generalize_clause_cnf_
The CNF matrix of the QBF for generalizing counterexamples.
DepQBFApi solver_gen_
The QBF-solver used for generalizing counterexamples.
CNFImplExtractor * impl_extractor_
The engine to use for circuit extraction.
Private Member Functions
LearnSynthQBFInc (const LearnSynthQBFInc &other)
Copy constructor.
LearnSynthQBFInc & operator= (const LearnSynthQBFInc &other)
Assignment operator.
Detailed Description
Implements a learning-based synthesis with incremental QBF solving.
This class is almost an exact copy of LearnSynthQBF. Hence, we refer to the documentation of LearnSynthQBF for an explanation of the basic working principle. The main difference is that this class utilizes incremental QBF solving features of DepQBF. We also use the ability of DepQBF to compute unsatisfiable cores.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 55 of file LearnSynthQBFInc.h.
Constructor & Destructor Documentation
LearnSynthQBFInc::LearnSynthQBFInc (CNFImplExtractor * impl_extractor)
Constructor.
Parameters
impl_extractor The engine to use for circuit extraction. It will be deleted by this class.
Definition at line 40 of file LearnSynthQBFInc.cpp.
References QBFSolver::A, check_quant_, VarInfo::CTRL, QBFSolver::E, gen_quant_, VarInfo::INPUT, VarInfo::NEXT_STATE, VarInfo::PRES_STATE, VarInfo::TEMPL_PARAMS, and VarInfo::TMP.
LearnSynthQBFInc::~LearnSynthQBFInc () [virtual]
Destructor.
Definition at line 66 of file LearnSynthQBFInc.cpp.
References impl_extractor_.
LearnSynthQBFInc::LearnSynthQBFInc (const LearnSynthQBFInc & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
bool LearnSynthQBFInc::computeAllBlockingClauses (vector< int > & ce, vector< vector< int > > & blocking_clauses) [protected]
Computes all minimal blocking clauses for a counterexample.
This method works like LearnSynthQBF::computeAllBlockingClauses() but using unsatisfiable cores to generalize the counterexample instead of just iterating over the literals.
Parameters
ce The counterexample to block. It is a full or partial cube over the state variables.
blocking_clauses An empty vector. It is used to store the computed blocking clauses. The counterexample falsifies all blocking clauses in this vector.
Returns
False if one of the blocking clauses blocks the initial state. This means that the initial state is removed from the winning region, i.e., the specification is unrealizable. True is returned otherwise.
Definition at line 765 of file LearnSynthQBFInc.cpp.
References Utils::containsInit(), generalizeCounterexample(), generalizeCounterexampleFurther(), DepQBFApi::incAddClause(), Utils::intersectionEmpty(), MASSERT, Utils::negateLiterals(), LearnStatisticsQBF::notifyAfterCubeMin(), LearnStatisticsQBF::notifyBeforeCubeMin(), LearnStatisticsQBF::notifyCubeMin(), Utils::remove(), solver_gen_, statistics_, and Utils::swapPresentToNext().
Referenced by computeWinningRegionAll(), computeWinningRegionAllPool(), and computeWinningRegionAllPush().
bool LearnSynthQBFInc::computeBlockingClause (vector< int > & ce, vector< int > & blocking_clause) [protected]
Computes a blocking clause for a counterexample.
This method works like LearnSynthQBF::computeBlockingClause() but using unsatisfiable cores to generalize the counterexample instead of just iterating over the literals.
Parameters
ce The counterexample to block. It is a full or partial cube over the state variables.
blocking_clause An empty vector. It is used to store the computed blocking clause. The counterexample falsifies the blocking clause.
Returns
False if the blocking clause blocks the initial state. This means that the initial state is removed from the winning region, i.e., the specification is unrealizable. True is returned otherwise.
Definition at line 733 of file LearnSynthQBFInc.cpp.
References Utils::containsInit(), generalizeCounterexample(), generalizeCounterexampleFurther(), DepQBFApi::incAddClause(), L_DBG, MASSERT, Utils::negateLiterals(), LearnStatisticsQBF::notifyAfterCubeMin(), LearnStatisticsQBF::notifyBeforeCubeMin(), Utils::randomize(), solver_gen_, statistics_, and Utils::swapPresentToNext().
Referenced by computeWinningRegionOne(), computeWinningRegionOnePool(), and computeWinningRegionOnePush().
bool LearnSynthQBFInc::computeCounterexampleQBF (vector< int > & ce) [protected]
Computes a counterexample-state using a QBF-solver with incremental solving.
This method works like LearnSynthQBF::computeCounterexampleQBF() but using incremental solving and unsatisfiable cores. 'Using incremental solving' means, instead of solving exists x,i: forall c: exists x',tmp: F & T & !F' where F is the winning_region_ we solve exists x,i: forall c: exists x',tmp: F & T & !G' where G is a copy of F that is updated only lazily. That is, whenever new clauses are discovered, they are added only to F but not to G. Only if this method returns false, we update G := F and try again. The synthesis algorithm only aborts if false is returned while G = F.
Parameters
ce An empty vector. The computed counterexample is stored in this vector in form of a cube over the state variables. The cube does not necessarily contain all state variables. If some state variables are irrelevant, then they may be omitted.
Returns
True if a counterexample was found, false if no counterexample exists.
Definition at line 710 of file LearnSynthQBFInc.cpp.
References DepQBFApi::incIsSatModel(), LearnStatisticsQBF::notifyAfterComputeCube(), LearnStatisticsQBF::notifyBeforeComputeCube(), restrictToStates(), solver_check_, and statistics_.
Referenced by computeWinningRegionAll(), computeWinningRegionAllPush(), computeWinningRegionOne(), and computeWinningRegionOnePush().
bool LearnSynthQBFInc::computeCounterexampleQBFPool (vector< int > & ce) [protected]
Computes a counterexample-state using a QBF-solver with incremental solving.
This method works like computeCounterexampleQBF() but without the lazy update of the next-state copy of the winning region. Instead, we use a pool of variables to express the negated next-state copy of the winning region. Variables of this pool which are not yet used are set to false until they are used.
Parameters
ce An empty vector. The computed counterexample is stored in this vector in form of a cube over the state variables. The cube does not necessarily contain all state variables. If some state variables are irrelevant, then they may be omitted.
Returns
True if a counterexample was found, false if no counterexample exists.
Definition at line 722 of file LearnSynthQBFInc.cpp.
References DepQBFApi::incIsSatModel(), negcl_var_pool_act_, LearnStatisticsQBF::notifyAfterComputeCube(), LearnStatisticsQBF::notifyBeforeComputeCube(), restrictToStates(), solver_check_, and statistics_.
Referenced by computeWinningRegionAllPool(), and computeWinningRegionOnePool().
bool LearnSynthQBFInc::computeWinningRegion () [protected]
Computes the winning region and stores the result in winning_region_.
Depending on the command-line parameters (--mode) this method calls one of
computeWinningRegionOne()
computeWinningRegionAll()
Returns
True if the specification was realizable, false otherwise.
Definition at line 106 of file LearnSynthQBFInc.cpp.
References computeWinningRegionAll(), computeWinningRegionAllPool(), computeWinningRegionAllPush(), computeWinningRegionOne(), computeWinningRegionOnePool(), computeWinningRegionOnePush(), and Options::instance().
Referenced by run().
bool LearnSynthQBFInc::computeWinningRegionAll () [protected]
Computes the winning region, always computing all counterexample generalizations.
This method works like LearnSynthQBF::computeWinningRegionAll() but using incremental solving and unsatisfiable cores.
Returns
True if the specification was realizable, false otherwise.
Definition at line 408 of file LearnSynthQBFInc.cpp.
References CNF::addClauseAndSimplify(), check_cnf_, check_quant_, CNF::clear(), Utils::compressStateCNF(), computeAllBlockingClauses(), computeCounterexampleQBF(), VarInfo::CTRL, Logger::DBG, Utils::debugPrint(), DepQBFApi::doMinCores(), gen_quant_, generalize_clause_cnf_, CNF::getNrOfClauses(), CNF::getNrOfLits(), AIG2CNF::getSafeStates(), VarManager::getVarsOfType(), DepQBFApi::incAddClause(), DepQBFApi::incAddCNF(), VarInfo::INPUT, VarManager::instance(), Logger::instance(), AIG2CNF::instance(), Logger::isEnabled(), L_DBG, LearnStatisticsQBF::logStatistics(), VarInfo::PRES_STATE, recomputeCheckCNF(), recomputeGenCNF(), reduceExistingClauses(), solver_check_, solver_gen_, DepQBFApi::startIncrementalSession(), statistics_, Utils::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
bool LearnSynthQBFInc::computeWinningRegionAllPool () [protected]
Uses a pool of variables and always computes all counterexample generalizations .
This method works like computeWinningRegionAll() but uses a pool of variables to handle the computation of counterexamples incrementally, instead of updating the next-state copy of the winning region only lazily.
Returns
True if the specification was realizable, false otherwise.
Definition at line 565 of file LearnSynthQBFInc.cpp.
References CNF::add2LitClause(), CNF::addClause(), CNF::addClauseAndSimplify(), CNF::addCNF(), check_quant_, CNF::clear(), Utils::compressStateCNF(), computeAllBlockingClauses(), computeCounterexampleQBFPool(), VarManager::createFreshTemplParam(), VarManager::createFreshTmpVar(), VarInfo::CTRL, Logger::DBG, Utils::debugPrint(), DepQBFApi::doMinCores(), gen_quant_, CNF::getClauses(), VarManager::getNextErrorStateVar(), CNF::getNrOfClauses(), CNF::getNrOfLits(), VarManager::getPresErrorStateVar(), AIG2CNF::getSafeStates(), VarManager::getVarsOfType(), DepQBFApi::incAdd2LitClause(), DepQBFApi::incAddClause(), DepQBFApi::incAddCNF(), DepQBFApi::incAddUnitClause(), VarInfo::INPUT, VarManager::instance(), Logger::instance(), AIG2CNF::instance(), Logger::isEnabled(), L_DBG, LearnStatisticsQBF::logStatistics(), negcl_var_pool_, negcl_var_pool_act_, VarInfo::PRES_STATE, reduceExistingClauses(), VarManager::resetToLastPush(), solver_check_, solver_gen_, DepQBFApi::startIncrementalSession(), statistics_, Utils::swapPresentToNext(), CNF::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
bool LearnSynthQBFInc::computeWinningRegionAllPush () [protected]
Uses push/pop and always computes all counterexample generalizations.
This method works like computeWinningRegionAll() but uses a push/pop to handle the computation of counterexamples incrementally, instead of updating the next-state copy of the winning region only lazily.
Returns
True if the specification was realizable, false otherwise.
Definition at line 488 of file LearnSynthQBFInc.cpp.
References CNF::addClause(), check_quant_, CNF::clear(), computeAllBlockingClauses(), computeCounterexampleQBF(), VarManager::createFreshTmpVar(), VarInfo::CTRL, Logger::DBG, Utils::debugPrint(), DepQBFApi::doMinCores(), gen_quant_, VarManager::getNextErrorStateVar(), CNF::getNrOfClauses(), CNF::getNrOfLits(), VarManager::getPresErrorStateVar(), AIG2CNF::getSafeStates(), VarManager::getVarsOfType(), DepQBFApi::incAdd2LitClause(), DepQBFApi::incAddClause(), DepQBFApi::incAddCNF(), DepQBFApi::incAddUnitClause(), DepQBFApi::incAddVarAtInnermostQuant(), DepQBFApi::incPop(), DepQBFApi::incPush(), VarInfo::INPUT, VarManager::instance(), Logger::instance(), AIG2CNF::instance(), Logger::isEnabled(), L_DBG, LearnStatisticsQBF::logStatistics(), VarInfo::PRES_STATE, solver_check_, solver_gen_, DepQBFApi::startIncrementalSession(), statistics_, Utils::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
bool LearnSynthQBFInc::computeWinningRegionOne () [protected]
Uses the standard method to compute the winning region, with incremental solving.
This method works like LearnSynthQBF::computeWinningRegionOne() but using incremental solving and unsatisfiable cores.
Returns
True if the specification was realizable, false otherwise.
Definition at line 122 of file LearnSynthQBFInc.cpp.
References CNF::addClauseAndSimplify(), check_cnf_, check_quant_, CNF::clear(), Utils::compressStateCNF(), computeBlockingClause(), computeCounterexampleQBF(), VarInfo::CTRL, Logger::DBG, Utils::debugPrint(), DepQBFApi::doMinCores(), gen_quant_, generalize_clause_cnf_, CNF::getNrOfClauses(), CNF::getNrOfLits(), AIG2CNF::getSafeStates(), VarManager::getVarsOfType(), DepQBFApi::incAddClause(), DepQBFApi::incAddCNF(), VarInfo::INPUT, VarManager::instance(), Logger::instance(), AIG2CNF::instance(), Logger::isEnabled(), L_DBG, LearnStatisticsQBF::logStatistics(), VarInfo::PRES_STATE, recomputeCheckCNF(), recomputeGenCNF(), solver_check_, solver_gen_, DepQBFApi::startIncrementalSession(), statistics_, Utils::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
bool LearnSynthQBFInc::computeWinningRegionOnePool () [protected]
Uses incremental solving and a pool of variables to handle negation incrementally.
This method works like computeWinningRegionOne() but uses a pool of variables to handle the computation of counterexamples incrementally, instead of updating the next-state copy of the winning region only lazily.
Returns
True if the specification was realizable, false otherwise.
Definition at line 273 of file LearnSynthQBFInc.cpp.
References CNF::add2LitClause(), CNF::addClause(), CNF::addClauseAndSimplify(), CNF::addCNF(), check_quant_, CNF::clear(), Utils::compressStateCNF(), computeBlockingClause(), computeCounterexampleQBFPool(), VarManager::createFreshTemplParam(), VarManager::createFreshTmpVar(), VarInfo::CTRL, Logger::DBG, Utils::debugPrint(), DepQBFApi::doMinCores(), gen_quant_, CNF::getClauses(), VarManager::getNextErrorStateVar(), CNF::getNrOfClauses(), CNF::getNrOfLits(), VarManager::getPresErrorStateVar(), AIG2CNF::getSafeStates(), VarManager::getVarsOfType(), DepQBFApi::incAdd2LitClause(), DepQBFApi::incAddClause(), DepQBFApi::incAddCNF(), DepQBFApi::incAddUnitClause(), VarInfo::INPUT, VarManager::instance(), Logger::instance(), AIG2CNF::instance(), Logger::isEnabled(), L_DBG, LearnStatisticsQBF::logStatistics(), negcl_var_pool_, negcl_var_pool_act_, VarInfo::PRES_STATE, VarManager::resetToLastPush(), solver_check_, solver_gen_, DepQBFApi::startIncrementalSession(), statistics_, Utils::swapPresentToNext(), CNF::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
bool LearnSynthQBFInc::computeWinningRegionOnePush () [protected]
Uses incremental solving and push/pop to handle negation incrementally.
This method works like computeWinningRegionOne() but uses push/pop, instead of updating the next-state copy of the winning region only lazily.
Returns
True if the specification was realizable, false otherwise.
Definition at line 199 of file LearnSynthQBFInc.cpp.
References CNF::addClause(), check_quant_, CNF::clear(), computeBlockingClause(), computeCounterexampleQBF(), VarManager::createFreshTmpVar(), VarInfo::CTRL, Logger::DBG, Utils::debugPrint(), DepQBFApi::doMinCores(), gen_quant_, VarManager::getNextErrorStateVar(), CNF::getNrOfClauses(), CNF::getNrOfLits(), VarManager::getPresErrorStateVar(), AIG2CNF::getSafeStates(), VarManager::getVarsOfType(), DepQBFApi::incAdd2LitClause(), DepQBFApi::incAddClause(), DepQBFApi::incAddCNF(), DepQBFApi::incAddUnitClause(), DepQBFApi::incAddVarAtInnermostQuant(), DepQBFApi::incPop(), DepQBFApi::incPush(), VarInfo::INPUT, VarManager::instance(), Logger::instance(), AIG2CNF::instance(), Logger::isEnabled(), L_DBG, LearnStatisticsQBF::logStatistics(), VarInfo::PRES_STATE, solver_check_, solver_gen_, DepQBFApi::startIncrementalSession(), statistics_, Utils::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
bool LearnSynthQBFInc::generalizeCounterexample (vector< int > & ce) [protected]
Generalizes a counterexample-state by dropping literals.
This method works like LearnSynthQBF::generalizeCounterexample() but using unsatisfiable cores to generalize the counterexample instead of just iterating over the literals.
Parameters
ce The counterexample to generalize (it will be overwritten by its own generalization). This is a complete or partial cube over the present state variables.
Returns
True if the passed vector is a valid (generalization of a) counterexample, false otherwise.
Definition at line 960 of file LearnSynthQBFInc.cpp.
References DepQBFApi::incIsSatCore(), solver_gen_, and Utils::sort().
Referenced by computeAllBlockingClauses(), and computeBlockingClause().
void LearnSynthQBFInc::generalizeCounterexampleFurther (vector< int > & ce) [protected]
Generalizes a counterexample-state further by dropping literals.
This method works like generalizeCounterexample() but does not use the unsatisfiable core feature of the QBF solver, but iterates over all the literals instead.
Parameters
ce The counterexample to generalize further (it will be overwritten by its own generalization). This is a complete or partial cube over the present state variables.
Definition at line 972 of file LearnSynthQBFInc.cpp.
References DepQBFApi::incIsSat(), Utils::remove(), solver_gen_, and Utils::sort().
Referenced by computeAllBlockingClauses(), computeBlockingClause(), and reduceExistingClauses().
LearnSynthQBFInc& LearnSynthQBFInc::operator= (const LearnSynthQBFInc & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
void LearnSynthQBFInc::recomputeCheckCNF (bool take_small_win = true) [protected]
Recomputes the CNF (of the QBF) that is used for computing counterexamples.
The CNF used for computing counterexamples is F & T & !F', where F is the winning_region_. The result is stored in check_cnf_. In contrast to LearnSynthQBF, this class calls this method not so often (only when computeCounterexampleQBF() returns unsatisfiable.
Parameters
take_small_win If this parameter is true (or omitted) the winning_region_ is used to compute the check_cnf_. Otherwise, the winning_region_large_ is used. The difference between these two winning region versions is as follows. From time to we remove redundant clauses (clauses implied by other clauses) from winning_region_ but not from winning_region_large_. Hence, winning_region_ is often smaller, but winning_region_large_ may contain clauses the solver may have to learn when using winning_region_.
Definition at line 897 of file LearnSynthQBFInc.cpp.
References CNF::addCNF(), check_cnf_, CNF::clear(), AIG2CNF::instance(), CNF::negate(), VarManager::resetToLastPush(), CNF::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegionAll(), and computeWinningRegionOne().
void LearnSynthQBFInc::recomputeGenCNF (bool take_small_win = true) [protected]
Recomputes the CNF (of the QBF) that is used for generalizing counterexamples.
The CNF used for generalizing counterexamples is F & T & F', where F is the winning_region_. The result is stored in generalize_clause_cnf_. Since F is constantly updated with new clauses, generalize_clause_cnf_ needs to be updated as well. In an old version, we updated the generalize_clause_cnf_ in place. This results in ugly code at some places (especially when the winning_region_ is compressed or simplified). Since this operation is not performance critical (compared to QBF-solving), we now recompute generalize_clause_cnf_ completely in each iteration.
Parameters
take_small_win If this parameter is true (or omitted) the winning_region_ is used to compute the generalize_clause_cnf_. Otherwise, the winning_region_large_ is used. The difference between these two winning region versions is as follows. From time to we remove redundant clauses (clauses implied by other clauses) from winning_region_ but not from winning_region_large_. Hence, winning_region_ is often smaller, but winning_region_large_ may contain clauses the solver may have to learn when using winning_region_.
Definition at line 920 of file LearnSynthQBFInc.cpp.
References CNF::addCNF(), CNF::clear(), generalize_clause_cnf_, AIG2CNF::instance(), CNF::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegionAll(), and computeWinningRegionOne().
void LearnSynthQBFInc::reduceExistingClauses () [protected]
Tries to drop literals from clauses in the winning region.
This method examines all clauses (in winning_region_) that have already been computed and checks if more literals can be dropped. This is done in the same way as for dropping literals when generalizing a counterexample.
The intuition behind this method is that, even if a literal could not be dropped before, it could be dropped at a later point in time because the winning region has been refined in the meantime. However, in practice, typically only very few additional literals can be dropped, so this method often does not pay off.
Definition at line 865 of file LearnSynthQBFInc.cpp.
References CNF::addClauseAndSimplify(), generalizeCounterexampleFurther(), CNF::getClauses(), CNF::getNrOfClauses(), CNF::getNrOfLits(), DepQBFApi::incAddClause(), L_DBG, Utils::negateLiterals(), LearnStatisticsQBF::notifyAfterCubeMin(), LearnStatisticsQBF::notifyBeforeCubeMin(), solver_gen_, statistics_, Utils::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegionAll(), and computeWinningRegionAllPool().
void LearnSynthQBFInc::restrictToStates (vector< int > & vec) const [protected]
Restricts a vector of literals (a cube or clause) to state-variables only.
That is, all literals that do not talk about present state variables are removed.
Parameters
vec The vector of literals (the cube or clause) to restricts to state-variables only.
Definition at line 941 of file LearnSynthQBFInc.cpp.
References VarManager::getInfo(), VarInfo::getKind(), VarManager::getPresErrorStateVar(), VarManager::instance(), and VarInfo::PRES_STATE.
Referenced by computeCounterexampleQBF(), and computeCounterexampleQBFPool().
bool LearnSynthQBFInc::run () [virtual]
Executes this back-end.
This class is almost an exact copy of LearnSynthQBF. Hence, we refer to the documentation of LearnSynthQBF for an explanation of the basic working principle. The main difference is that this class utilizes incremental QBF solving features of DepQBF. We also use the ability of DepQBF to compute unsatisfiable cores.
Returns
True if the specification was realizable, false otherwise.
Implements BackEnd.
Definition at line 73 of file LearnSynthQBFInc.cpp.
References computeWinningRegion(), Utils::debugCheckWinReg(), CNFImplExtractor::extractCircuit(), impl_extractor_, VarManager::instance(), Options::instance(), L_INF, L_RES, CNFImplExtractor::logStatistics(), LearnStatisticsQBF::logStatistics(), LearnStatisticsQBF::notifyWinRegEnd(), LearnStatisticsQBF::notifyWinRegStart(), VarManager::push(), statistics_, and winning_region_.
Member Data Documentation
CNF LearnSynthQBFInc::check_cnf_ [protected]
The CNF matrix of the QBF for computing counterexamples.
This CNF is always F & T & !F', where F is the winning_region_.
Definition at line 356 of file LearnSynthQBFInc.h.
Referenced by computeWinningRegionAll(), computeWinningRegionOne(), and recomputeCheckCNF().
vector<pair<VarInfo::VarKind, QBFSolver::Quant> > LearnSynthQBFInc::check_quant_ [protected]
The quantifier prefix of the QBF for computing counterexamples.
This quantifier prefix is always exists x,i: forall c: exists x',tmp:
Definition at line 349 of file LearnSynthQBFInc.h.
Referenced by computeWinningRegionAll(), computeWinningRegionAllPool(), computeWinningRegionAllPush(), computeWinningRegionOne(), computeWinningRegionOnePool(), computeWinningRegionOnePush(), and LearnSynthQBFInc().
vector<pair<VarInfo::VarKind, QBFSolver::Quant> > LearnSynthQBFInc::gen_quant_ [protected]
The quantifier prefix of the QBF for generalizing counterexamples.
This quantifier prefix is always exists x: forall i: exists c,x',tmp:
Definition at line 398 of file LearnSynthQBFInc.h.
Referenced by computeWinningRegionAll(), computeWinningRegionAllPool(), computeWinningRegionAllPush(), computeWinningRegionOne(), computeWinningRegionOnePool(), computeWinningRegionOnePush(), and LearnSynthQBFInc().
CNF LearnSynthQBFInc::generalize_clause_cnf_ [protected]
The CNF matrix of the QBF for generalizing counterexamples.
This CNF is always F & T & F', where F is the winning_region_.
Definition at line 405 of file LearnSynthQBFInc.h.
Referenced by computeWinningRegionAll(), computeWinningRegionOne(), and recomputeGenCNF().
CNFImplExtractor* LearnSynthQBFInc::impl_extractor_ [protected]
The engine to use for circuit extraction.
It will be deleted by this class (in the destructor).
Definition at line 423 of file LearnSynthQBFInc.h.
Referenced by run(), and ~LearnSynthQBFInc().
vector<int> LearnSynthQBFInc::negcl_var_pool_ [protected]
A pool of variables, which are used to express that a certain clause in negated.
This set of variables is supposed to support incremental solving within solver_check_. The solver_check_ needs to solve exists x,i: forall c: exists x',tmp: F & T & !F' In each iteration, we add a clause (or several clauses) to F. In order to handle the update to !F' incrementally, we add one big clause consisting of all the literals of the vector neg_clause_var_pool_. Initially, none of the literals is 'used', so we add assumptions that they are all false. Whenever we add a new clause to F, we simply pick a new variable v from the pool, and say that v implies the negated new clause. Then this variable v is no longer set to zero, but used to encode the negated clause. When we run out of variables, we start a new incremental session, with a new pool of variables.
Definition at line 385 of file LearnSynthQBFInc.h.
Referenced by computeWinningRegionAllPool(), and computeWinningRegionOnePool().
vector<int> LearnSynthQBFInc::negcl_var_pool_act_ [protected]
The activation variables to express that a var in negcl_var_pool_ is not yet used.
Definition at line 390 of file LearnSynthQBFInc.h.
Referenced by computeCounterexampleQBFPool(), computeWinningRegionAllPool(), and computeWinningRegionOnePool().
DepQBFApi LearnSynthQBFInc::solver_check_ [protected]
The QBF-solver used for computing counterexamples.
It is used in an incremental way. It is initialized to check_quant_: check_cnf_, i.e., exists x,i: forall c: exists x',tmp: F & T & !F' where F is the winning_region_. However, when new clauses are discovered, they are only added to the current-state copy of F but not to the next-state copy. This allows to to use the solver incrementally until it returns UNSAT. If it returns UNSAT, we recompute the check_cnf_ (with correct next-state copy of the winning region) and restart the solver with this CNF.
Definition at line 369 of file LearnSynthQBFInc.h.
Referenced by computeCounterexampleQBF(), computeCounterexampleQBFPool(), computeWinningRegionAll(), computeWinningRegionAllPool(), computeWinningRegionAllPush(), computeWinningRegionOne(), computeWinningRegionOnePool(), and computeWinningRegionOnePush().
DepQBFApi LearnSynthQBFInc::solver_gen_ [protected]
The QBF-solver used for generalizing counterexamples.
At the moment we do not really use this solver incrementally (we do not update the next- state copy of the winning region lazily to do so because this sacrifices generalization power in favor of incrementality and appears to be a bad deal). We only use its capabilities of computing unsatisfiable cores (during one core computation, we use it incrementally).
Definition at line 416 of file LearnSynthQBFInc.h.
Referenced by computeAllBlockingClauses(), computeBlockingClause(), computeWinningRegionAll(), computeWinningRegionAllPool(), computeWinningRegionAllPush(), computeWinningRegionOne(), computeWinningRegionOnePool(), computeWinningRegionOnePush(), generalizeCounterexample(), generalizeCounterexampleFurther(), and reduceExistingClauses().
LearnStatisticsQBF LearnSynthQBFInc::statistics_ [protected]
Stores and maintains statistics and performance measures.
Definition at line 341 of file LearnSynthQBFInc.h.
Referenced by computeAllBlockingClauses(), computeBlockingClause(), computeCounterexampleQBF(), computeCounterexampleQBFPool(), computeWinningRegionAll(), computeWinningRegionAllPool(), computeWinningRegionAllPush(), computeWinningRegionOne(), computeWinningRegionOnePool(), computeWinningRegionOnePush(), reduceExistingClauses(), and run().
CNF LearnSynthQBFInc::winning_region_ [protected]
The current over-approximation of the winning region.
Only when computeWinningRegion() is done, this field will store the correct winning region.
Definition at line 324 of file LearnSynthQBFInc.h.
Referenced by computeWinningRegionAll(), computeWinningRegionAllPool(), computeWinningRegionAllPush(), computeWinningRegionOne(), computeWinningRegionOnePool(), computeWinningRegionOnePush(), recomputeCheckCNF(), recomputeGenCNF(), reduceExistingClauses(), and run().
CNF LearnSynthQBFInc::winning_region_large_ [protected]
The current over-approximation of the winning region in an uncompressed form.
This CNF is logically equivalent to winning_region_. However, winning_region_ is 'compressed' from time to time by removing redundant clauses (clauses that are implied by other clauses in the winning region). This field stores the uncompressed version of the winning region. Having the uncompressed winning region can be good because throwing away redundant clauses is not always beneficial. The CNF get smaller, but the solver may have to re-discover the removed clauses.
Definition at line 336 of file LearnSynthQBFInc.h.
Referenced by computeWinningRegionAll(), computeWinningRegionAllPool(), computeWinningRegionAllPush(), computeWinningRegionOne(), computeWinningRegionOnePool(), computeWinningRegionOnePush(), recomputeCheckCNF(), recomputeGenCNF(), and reduceExistingClauses().
The documentation for this class was generated from the following files:
src/LearnSynthQBFInc.h
src/LearnSynthQBFInc.cpp