ParExtractorQBFWorker Class Reference
A worker thread for the ParExtractor.
#include <ParExtractor.h>
Public Member Functions
ParExtractorQBFWorker (ParExtractor &coordinator, const CNF &win_region, const CNF &neg_win_region)
Constructor.
virtual ~ParExtractorQBFWorker ()
Destructor.
void runQBF ()
Runs QBF-based learning.
void runSAT ()
Runs SAT-based learning without dependency optimization.
void runSATDep ()
Runs SAT-based learning with dependency optimization.
void logStats ()
Logs the detailed statistics collected by the fastest worker.
Static Public Member Functions
static void * startQBF (void *object)
A C-style wrapper around runQBF() so that we can run it from a phread.
Public Attributes
bool done_
Indicates if standalone_circuit_ is ready.
bool waiting_
Indicates if this thread is waiting for others to finish.
bool did_second_run_
True if this thread did a second minimization run (just for printing statistics).
aiger * standalone_circuit_
The synthesis result as stand-alone circuit.
LearningExtractorStatistics statistics
A helper for collecting performance data and statistics.
Protected Member Functions
void waitForOthersToFinish (size_t elapsed_until_done)
Waits for other worker threads to finish.
CNF makeEq (int var, CNF impl, vector< int > *new_temps=NULL)
Creates a CNF that assigns a variable to the result of some other CNF.
void addToStandAloneAiger (int ctrl_var, const CNF &solution)
Adds the solution for one output function to the AIGER circuit we have so far.
void addToStandAloneAiger2 (int ctrl_var, const CNF &solution)
Same as addToStandAloneAiger but operating on the copy standalone_circuit2_.
int cnfToAig (int cnf_lit)
Transforms a CNF literal into an AIGER literal as used in standalone_circuit_.
int makeAnd (int in1, int in2)
Creates the AND between two AIGER literals and returns the resulting literal.
int makeAnd2 (int in1, int in2)
Same as makeAnd but operating on the copy standalone_circuit2_.
int makeOr (int in1, int in2)
Creates the OR between two AIGER literals and returns the resulting literal.
int makeOr2 (int in1, int in2)
Same as makeAnd but operating on the copy standalone_circuit2_.
void insertMissingAndFromTrans (aiger *standalone_circuit)
Copies missing AND gates from the spec.
Protected Attributes
DepQBFApi * check_solver_
A local variable of runQBF made a field variable to avoid calls to its destructor.
DepQBFApi * gen_solver_
A local variable of runQBF made a field variable to avoid calls to its destructor.
CNF neg_rel_
A local variable of runQBF made a field variable to avoid calls to its destructor.
CNF check_
A local variable of runQBF made a field variable to avoid calls to its destructor.
CNF gen_
A local variable of runQBF made a field variable to avoid calls to its destructor.
CNF solution_
A local variable of runQBF made a field variable to avoid calls to its destructor.
vector< int > tmp_
A local variable of runQBF made a field variable to avoid calls to its destructor.
vector< int > none_
A local variable of runQBF made a field variable to avoid calls to its destructor.
vector< int > ctrl_univ_
A local variable of runQBF made a field variable to avoid calls to its destructor.
vector< int > ctrl_exist_
A local variable of runQBF made a field variable to avoid calls to its destructor.
vector< int > false_pos_
A local variable of runQBF made a field variable to avoid calls to its destructor.
vector< int > gen_false_pos_
A local variable of runQBF made a field variable to avoid calls to its destructor.
vector< pair< vector< int >
*
, QBFSolver::Quant > > quant_
A local variable of runQBF made a field variable to avoid calls to its destructor.
ParExtractor & coordinator_
A reference to the coordinator.
const CNF & win_region_
The winning region from which the circuit should be extracted.
const CNF & neg_win_region_
The negation of the winning region.
int next_free_aig_lit_
The next unused AIGER literal in standalone_circuit_.
int next_free_cnf_lit_
We need to create fresh variables locally.
vector< int > cnf_var_to_standalone_aig_var_
A map from variables as they occur in CNFs to the corresponding AIGER literals.
vector< int > ip_
The list of uncontrollable input variables followed by the present state variables.
vector< int > ipc_
The list of uncontrollable inputs, state variables, and control signals.
aiger * standalone_circuit2_
A second (optimized) version of the standalone_circuit.
int next_free_aig_lit2_
The next unused AIGER literal in standalone_circuit2_.
Private Member Functions
ParExtractorQBFWorker (const ParExtractorWorker &other)
Copy constructor.
ParExtractorQBFWorker & operator= (const ParExtractorQBFWorker &other)
Assignment operator.
Detailed Description
A worker thread for the ParExtractor.
This class implements selected circuit extraction methods from the LearningImplExtractor in a parallelized way.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 478 of file ParExtractor.h.
Constructor & Destructor Documentation
ParExtractorQBFWorker::ParExtractorQBFWorker (ParExtractor & coordinator, const CNF & win_region, const CNF & neg_win_region)
Constructor.
The ParExtractorQBFWorker is implemented in a separate class. The reason is as follows. Instances of this worker can get killed by other threads. That is, the thread is not nicely asked to terminate. It is really killed whereever it is in the code. The reason is that QBF solver calls may take so long that we do not want to wait for them to finish. Killing a thread is essentially done by throwing an exception. The stack is cleaned up, and while doing this, the destructors of all objects on the stack are called. Some objects may be in an inconsistent state, however. Calling their destructor may cause the program to crash. We therefore store also the local variables as fields in this class. This way, we can postpone the call of their destructor.
Parameters
coordinator A reference to the coordinator. All communication to other worker-threads is done via the coordinator.
win_region The winning region from which the circuit should be extracted.
neg_win_region The negation of the winning region.
Definition at line 1098 of file ParExtractor.cpp.
ParExtractorQBFWorker::~ParExtractorQBFWorker () [virtual]
Destructor.
Definition at line 1109 of file ParExtractor.cpp.
References check_solver_, and gen_solver_.
ParExtractorQBFWorker::ParExtractorQBFWorker (const ParExtractorWorker & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void ParExtractorWorker::addToStandAloneAiger (int ctrl_var, const CNF & solution) [protected], [inherited]
Adds the solution for one output function to the AIGER circuit we have so far.
The AIGER circuit we have so far is built up in standalone_circuit_. This method adds an output function (in CNF) for one control signal.
Parameters
ctrl_var The control signal for which we would like to add an output function.
solution The output function (in CNF) defining the control signal.
Definition at line 921 of file ParExtractor.cpp.
References ParExtractorWorker::cnfToAig(), CNF::getClauses(), ParExtractorWorker::makeAnd(), ParExtractorWorker::makeOr(), and ParExtractorWorker::standalone_circuit_.
Referenced by runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void ParExtractorWorker::addToStandAloneAiger2 (int ctrl_var, const CNF & solution) [protected], [inherited]
Same as addToStandAloneAiger but operating on the copy standalone_circuit2_.
Parameters
ctrl_var The control signal for which we would like to add an output function.
solution The output function (in CNF) defining the control signal.
Definition at line 957 of file ParExtractor.cpp.
References ParExtractorWorker::cnfToAig(), CNF::getClauses(), ParExtractorWorker::makeAnd2(), ParExtractorWorker::makeOr2(), and ParExtractorWorker::standalone_circuit2_.
Referenced by ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
int ParExtractorWorker::cnfToAig (int cnf_lit) [protected], [inherited]
Transforms a CNF literal into an AIGER literal as used in standalone_circuit_.
Parameters
cnf_lit The literal as it occurs in CNF formulas.
Returns
The corresponding AIGER index of the literal as it is used in the standalone_circuit_.
Definition at line 993 of file ParExtractor.cpp.
References ParExtractorWorker::cnf_var_to_standalone_aig_var_.
Referenced by ParExtractorWorker::addToStandAloneAiger(), ParExtractorWorker::addToStandAloneAiger2(), and ParExtractorWorker::insertMissingAndFromTrans().
void ParExtractorWorker::insertMissingAndFromTrans (aiger * standalone_circuit) [protected], [inherited]
Copies missing AND gates from the spec.
This method is only used for an optimization in the method runSATDep. This method allows solutions to depend on temporary variables that appear in the original specification. The rules for SYNTComp do not allow to refer to such temporary variables from the specification in the final solution. Hence, this method simply copies the AND gates from the specification into the standalone_circuit passed as argument.
Parameters
standalone_circuit The circuit to complete with missing AND gates.
Definition at line 1039 of file ParExtractor.cpp.
References VarManager::aigLitToCnfLit(), ParExtractorWorker::cnf_var_to_standalone_aig_var_, ParExtractorWorker::cnfToAig(), Options::getAigInFileName(), AIG2CNF::getTmpDeps(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), MASSERT, and VarInfo::TMP.
Referenced by ParExtractorWorker::runSATDep().
void ParExtractorWorker::logStats () [inherited]
Logs the detailed statistics collected by the fastest worker.
int ParExtractorWorker::makeAnd (int in1, int in2) [protected], [inherited]
Creates the AND between two AIGER literals and returns the resulting literal.
This method extends the standalone_circuit_ with logic to compute the AND between two AIGER literals. The literal that represents the result of the AND is returned.
Parameters
in1 The first operand of the AND: an AIGER literal from standalone_circuit_.
in2 The second operand of the AND: an AIGER literal from standalone_circuit_.
Returns
The literal that represents the result of the AND.
Definition at line 1003 of file ParExtractor.cpp.
References ParExtractorWorker::next_free_aig_lit_, and ParExtractorWorker::standalone_circuit_.
Referenced by ParExtractorWorker::addToStandAloneAiger().
int ParExtractorWorker::makeAnd2 (int in1, int in2) [protected], [inherited]
Same as makeAnd but operating on the copy standalone_circuit2_.
Parameters
in1 The first operand of the AND: an AIGER literal from standalone_circuit2_.
in2 The second operand of the AND: an AIGER literal from standalone_circuit2_.
Returns
The literal that represents the result of the AND.
Definition at line 1012 of file ParExtractor.cpp.
References ParExtractorWorker::next_free_aig_lit2_, and ParExtractorWorker::standalone_circuit2_.
Referenced by ParExtractorWorker::addToStandAloneAiger2().
CNF ParExtractorWorker::makeEq (int var, CNF impl, vector< int > * new_temps = NULL) [protected], [inherited]
Creates a CNF that assigns a variable to the result of some other CNF.
This method creates a CNF that for (var <-> impl), where var is a variable and impl is a CNF. It is used to say that a certain control signal is now defined by a function that has been computed in CNF form.
Parameters
var The variable to set equal to the result of the CNF impl.
impl The CNF that should define the value of var.
new_temps A vector of variables. New auxiliary variables introduced by this method will be appended to this vector. The vector can also be omitted if not needed.
Returns
A CNF representation of (var <-> impl).
Definition at line 871 of file ParExtractor.cpp.
References CNF::addClause(), CNF::addCNF(), CNF::getClauses(), ParExtractorWorker::next_free_cnf_lit_, and CNF::swapWith().
Referenced by runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
int ParExtractorWorker::makeOr (int in1, int in2) [protected], [inherited]
Creates the OR between two AIGER literals and returns the resulting literal.
This method extends the standalone_circuit_ with logic to compute the OR between two AIGER literals. The literal that represents the result of the OR is returned.
Parameters
in1 The first operand of the OR: an AIGER literal from standalone_circuit_.
in2 The second operand of the OR: an AIGER literal from standalone_circuit_.
Returns
The literal that represents the result of the OR.
Definition at line 1021 of file ParExtractor.cpp.
References ParExtractorWorker::next_free_aig_lit_, and ParExtractorWorker::standalone_circuit_.
Referenced by ParExtractorWorker::addToStandAloneAiger().
int ParExtractorWorker::makeOr2 (int in1, int in2) [protected], [inherited]
Same as makeAnd but operating on the copy standalone_circuit2_.
Parameters
in1 The first operand of the OR: an AIGER literal from standalone_circuit2_.
in2 The second operand of the OR: an AIGER literal from standalone_circuit2_.
Returns
The literal that represents the result of the OR.
Definition at line 1030 of file ParExtractor.cpp.
References ParExtractorWorker::next_free_aig_lit2_, and ParExtractorWorker::standalone_circuit2_.
Referenced by ParExtractorWorker::addToStandAloneAiger2().
ParExtractorQBFWorker& ParExtractorQBFWorker::operator= (const ParExtractorQBFWorker & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
void ParExtractorQBFWorker::runQBF ()
Runs QBF-based learning.
Roughly implements LearningImplExtractor::runLearningQBFInc().
Definition at line 1128 of file ParExtractor.cpp.
References QBFSolver::A, CNF::addCNF(), CNF::addNegCubeAsClause(), ParExtractorWorker::addToStandAloneAiger(), check_, check_solver_, CNF::clear(), ParExtractorWorker::coordinator_, VarInfo::CTRL, ctrl_exist_, ctrl_univ_, ParExtractorWorker::done_, QBFSolver::E, ParExtractor::extr_command_, EXTR_STOP, false_pos_, gen_, gen_false_pos_, gen_solver_, CNF::getNrOfLits(), Stopwatch::getRealTimeSec(), VarManager::getVarsOfType(), DepQBFApi::incAddCNF(), DepQBFApi::incAddNegCubeAsClause(), DepQBFApi::incIsSatCore(), DepQBFApi::incIsSatModel(), VarManager::instance(), AIG2CNF::instance(), ParExtractorWorker::ip_, ParExtractorWorker::makeEq(), MASSERT, neg_rel_, ParExtractorWorker::neg_win_region_, VarInfo::NEXT_STATE, none_, LearningExtractorStatistics::notifyAfterABC(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeABC(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), CNFImplExtractor::optimizeWithABC(), quant_, Utils::remove(), CNF::setVarValue(), solution_, ParExtractorWorker::standalone_circuit_, Stopwatch::start(), DepQBFApi::startIncrementalSession(), ParExtractorWorker::statistics, CNF::swapPresentToNext(), VarInfo::TMP, tmp_, ParExtractorWorker::waitForOthersToFinish(), ParExtractorWorker::waiting_, and ParExtractorWorker::win_region_.
Referenced by startQBF().
void ParExtractorWorker::runSAT () [inherited]
Runs SAT-based learning without dependency optimization.
Roughly implements LearningImplExtractor::runLearningJiangSATInc1().
Definition at line 294 of file ParExtractor.cpp.
References CNF::add2LitClause(), CNF::add3LitClause(), CNF::addClause(), CNF::addCNF(), CNF::addNegCubeAsClause(), ParExtractorWorker::addToStandAloneAiger(), ParExtractorWorker::addToStandAloneAiger2(), ParExtractorWorker::check_, ParExtractorWorker::coordinator_, VarInfo::CTRL, ParExtractorWorker::did_second_run_, SatSolver::doMinCores(), ParExtractorWorker::done_, ParExtractor::extr_command_, EXTR_STOP, ParExtractorWorker::gen_, Options::getEstimatedTimeRemaining(), Stopwatch::getRealTimeSec(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), ParExtractorWorker::ip_, ParExtractorWorker::ipc_, ParExtractorWorker::makeEq(), MASSERT, ParExtractorWorker::neg_win_region_, Utils::negateLiterals(), ParExtractorWorker::next_free_cnf_lit_, LearningExtractorStatistics::notifyAfterABC(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeABC(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), CNFImplExtractor::optimizeWithABC(), Utils::remove(), CNF::renameVars(), CNF::setVarValue(), ParExtractorWorker::standalone_circuit2_, ParExtractorWorker::standalone_circuit_, Stopwatch::start(), SatSolver::startIncrementalSession(), ParExtractorWorker::statistics, CNF::swapPresentToNext(), ParExtractorWorker::waitForOthersToFinish(), and ParExtractorWorker::win_region_.
Referenced by ParExtractor::run().
void ParExtractorWorker::runSATDep () [inherited]
Runs SAT-based learning with dependency optimization.
Roughly implements LearningImplExtractor::runLearningJiangSATTmpCtrl().
Definition at line 553 of file ParExtractor.cpp.
References CNF::addCNF(), CNF::addNegCubeAsClause(), ParExtractorWorker::addToStandAloneAiger(), ParExtractorWorker::addToStandAloneAiger2(), ParExtractorWorker::check_, Utils::contains(), CNF::contains(), ParExtractorWorker::coordinator_, VarInfo::CTRL, DASSERT, ParExtractorWorker::did_second_run_, SatSolver::doMinCores(), ParExtractorWorker::done_, ParExtractor::extr_command_, EXTR_STOP, ParExtractorWorker::gen_, Options::getEstimatedTimeRemaining(), Stopwatch::getRealTimeSec(), AIG2CNF::getTmpDepsTrans(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incAddUnitClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), ParExtractorWorker::insertMissingAndFromTrans(), VarManager::instance(), Options::instance(), AIG2CNF::instance(), ParExtractorWorker::ipc_, ParExtractorWorker::makeEq(), MASSERT, ParExtractorWorker::neg_win_region_, Utils::negateLiterals(), ParExtractorWorker::next_free_cnf_lit_, LearningExtractorStatistics::notifyAfterABC(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearningExtractorStatistics::notifyBeforeABC(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), CNFImplExtractor::optimizeWithABC(), Utils::randomize(), Utils::remove(), CNF::renameVars(), CNF::setVarValue(), ParExtractorWorker::standalone_circuit2_, ParExtractorWorker::standalone_circuit_, Stopwatch::start(), SatSolver::startIncrementalSession(), ParExtractorWorker::statistics, CNF::swapPresentToNext(), ParExtractorWorker::waitForOthersToFinish(), and ParExtractorWorker::win_region_.
void * ParExtractorQBFWorker::startQBF (void * object) [static]
A C-style wrapper around runQBF() so that we can run it from a phread.
Parameters
object A pointer to a ParExtractorQBFWorker object.
Returns
I have no idea. Don't use it.
Definition at line 1121 of file ParExtractor.cpp.
References runQBF().
Referenced by ParExtractor::run().
void ParExtractorWorker::waitForOthersToFinish (size_t elapsed_until_done) [protected], [inherited]
Waits for other worker threads to finish.
If a worker thread is finished it does not terminate and kill other worker threads immediately. Instead, it waits for some time hoping that other worker threads will finish as well. This way, we can choose among the different circuits created by the different threads. However, if some thread loses her patience while waiting, it can kill other worker threads.
Parameters
elapsed_until_done The time in seconds this worker thread needed until it found a solution. This number is used for heuristics that decide when to kill the other workers.
Definition at line 834 of file ParExtractor.cpp.
References ParExtractor::allWaiting(), ParExtractorWorker::coordinator_, ParExtractor::extr_command_, EXTR_STOP, Options::getEstimatedTimeRemaining(), Stopwatch::getRealTimeSec(), Options::instance(), ParExtractor::killThemAll(), ParExtractorWorker::standalone_circuit_, Stopwatch::start(), and ParExtractorWorker::waiting_.
Referenced by runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
Member Data Documentation
CNF ParExtractorQBFWorker::check_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 544 of file ParExtractor.h.
Referenced by runQBF().
DepQBFApi* ParExtractorQBFWorker::check_solver_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 529 of file ParExtractor.h.
Referenced by runQBF(), and ~ParExtractorQBFWorker().
vector<int> ParExtractorWorker::cnf_var_to_standalone_aig_var_ [protected], [inherited]
A map from variables as they occur in CNFs to the corresponding AIGER literals.
This vector maps variables as they occur in CNFs to the corresponding AIGER literals as they occur in the standalone_circuit_. Use cnfToAig to transform literals.
Note
The AIGER literal numbering scheme in the standalone_circuit_ is different from the numbering scheme in the original specification. The reason is that we want to avoid big 'holes' of unused AIGER literals right from the beginning.
Definition at line 411 of file ParExtractor.h.
Referenced by ParExtractorWorker::cnfToAig(), ParExtractorWorker::insertMissingAndFromTrans(), and ParExtractorWorker::ParExtractorWorker().
ParExtractor& ParExtractorWorker::coordinator_ [protected], [inherited]
A reference to the coordinator.
All communication to other worker-threads is done via the coordinator.
Definition at line 369 of file ParExtractor.h.
Referenced by runQBF(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), and ParExtractorWorker::waitForOthersToFinish().
vector<int> ParExtractorQBFWorker::ctrl_exist_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 574 of file ParExtractor.h.
Referenced by runQBF().
vector<int> ParExtractorQBFWorker::ctrl_univ_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 569 of file ParExtractor.h.
Referenced by runQBF().
bool ParExtractorWorker::did_second_run_ [inherited]
True if this thread did a second minimization run (just for printing statistics).
Definition at line 224 of file ParExtractor.h.
Referenced by ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
bool ParExtractorWorker::done_ [inherited]
Indicates if standalone_circuit_ is ready.
Definition at line 214 of file ParExtractor.h.
Referenced by runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
vector<int> ParExtractorQBFWorker::false_pos_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 579 of file ParExtractor.h.
Referenced by runQBF().
CNF ParExtractorQBFWorker::gen_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 549 of file ParExtractor.h.
Referenced by runQBF().
vector<int> ParExtractorQBFWorker::gen_false_pos_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 584 of file ParExtractor.h.
Referenced by runQBF().
DepQBFApi* ParExtractorQBFWorker::gen_solver_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 534 of file ParExtractor.h.
Referenced by runQBF(), and ~ParExtractorQBFWorker().
vector<int> ParExtractorWorker::ip_ [protected], [inherited]
The list of uncontrollable input variables followed by the present state variables.
This vector contains the CNF version of the uncontrollable input variables followed by the present state variables. This vector of variables is used often, and thus stored here as a field.
Definition at line 420 of file ParExtractor.h.
Referenced by ParExtractorWorker::ParExtractorWorker(), runQBF(), and ParExtractorWorker::runSAT().
vector<int> ParExtractorWorker::ipc_ [protected], [inherited]
The list of uncontrollable inputs, state variables, and control signals.
This vector contains the CNF version of the uncontrollable input variables followed by the present state variables, followed by the control signals. This vector of variables is used often, and thus stored here as a field.
Definition at line 429 of file ParExtractor.h.
Referenced by ParExtractorWorker::ParExtractorWorker(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
CNF ParExtractorQBFWorker::neg_rel_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 539 of file ParExtractor.h.
Referenced by runQBF().
const CNF& ParExtractorWorker::neg_win_region_ [protected], [inherited]
The negation of the winning region.
Definition at line 389 of file ParExtractor.h.
Referenced by runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
int ParExtractorWorker::next_free_aig_lit2_ [protected], [inherited]
The next unused AIGER literal in standalone_circuit2_.
Definition at line 442 of file ParExtractor.h.
Referenced by ParExtractorWorker::makeAnd2(), ParExtractorWorker::makeOr2(), and ParExtractorWorker::ParExtractorWorker().
int ParExtractorWorker::next_free_aig_lit_ [protected], [inherited]
The next unused AIGER literal in standalone_circuit_.
Definition at line 394 of file ParExtractor.h.
Referenced by ParExtractorWorker::makeAnd(), ParExtractorWorker::makeOr(), and ParExtractorWorker::ParExtractorWorker().
int ParExtractorWorker::next_free_cnf_lit_ [protected], [inherited]
We need to create fresh variables locally.
Definition at line 399 of file ParExtractor.h.
Referenced by ParExtractorWorker::makeEq(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
vector<int> ParExtractorQBFWorker::none_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 564 of file ParExtractor.h.
Referenced by runQBF().
vector<pair<vector<int>, QBFSolver::Quant> > ParExtractorQBFWorker::quant_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 589 of file ParExtractor.h.
Referenced by runQBF().
CNF ParExtractorQBFWorker::solution_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 554 of file ParExtractor.h.
Referenced by runQBF().
aiger* ParExtractorWorker::standalone_circuit2_ [protected], [inherited]
A second (optimized) version of the standalone_circuit.
We will always finish standalone_circuit_, and then work on standalone_circuit2_ if there is still time.
Definition at line 437 of file ParExtractor.h.
Referenced by ParExtractorWorker::addToStandAloneAiger2(), ParExtractorWorker::makeAnd2(), ParExtractorWorker::makeOr2(), ParExtractorWorker::ParExtractorWorker(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), and ParExtractorWorker::~ParExtractorWorker().
aiger* ParExtractorWorker::standalone_circuit_ [inherited]
The synthesis result as stand-alone circuit.
This AIGER circuit is combinatorial, i.e., has no latches. The inputs of the circuit are: the uncontrollable inputs from the spec (in the order in which they appear in the spec) followed by the state-signals (the output of the latches in the spec, in the order in which they appear in the spec). The outputs of the circuit are the controllable inputs in the order in which they are defined in the spec.
This circuit will be built up by one of the methods runLearningX. Then, it will be optimized using ABC. Finally, it will be inserted into the original specification, as required by the rules for SYNTComp.
Definition at line 240 of file ParExtractor.h.
Referenced by ParExtractorWorker::addToStandAloneAiger(), ParExtractorWorker::makeAnd(), ParExtractorWorker::makeOr(), ParExtractorWorker::ParExtractorWorker(), runQBF(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), ParExtractorWorker::waitForOthersToFinish(), and ParExtractorWorker::~ParExtractorWorker().
LearningExtractorStatistics ParExtractorWorker::statistics [inherited]
A helper for collecting performance data and statistics.
Definition at line 245 of file ParExtractor.h.
Referenced by runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
vector<int> ParExtractorQBFWorker::tmp_ [protected]
A local variable of runQBF made a field variable to avoid calls to its destructor.
Definition at line 559 of file ParExtractor.h.
Referenced by runQBF().
bool ParExtractorWorker::waiting_ [inherited]
Indicates if this thread is waiting for others to finish.
Definition at line 219 of file ParExtractor.h.
Referenced by runQBF(), and ParExtractorWorker::waitForOthersToFinish().
const CNF& ParExtractorWorker::win_region_ [protected], [inherited]
The winning region from which the circuit should be extracted.
Definition at line 384 of file ParExtractor.h.
Referenced by runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
The documentation for this class was generated from the following files:
src/ParExtractor.h
src/ParExtractor.cpp