Stopwatch Class Reference
Implements a stopwatch that can be used to measure execution time.
#include <Stopwatch.h>
Public Member Functions
virtual ~Stopwatch ()
Destructor.
Static Public Member Functions
static PointInTime start ()
Starts the stopwatch.
static double getCPUTimeSec (const PointInTime &start_time)
Returns the elapsed CPU time in seconds.
static double getCPUTimeMilliSec (const PointInTime &start_time)
Returns the elapsed CPU time in milliseconds.
static size_t getRealTimeSec (const PointInTime &start_time)
Returns the elapsed real-time in seconds.
static string getTimeAsString (const PointInTime &start_time)
Returns both the CPU time and the elapsed time as string.
Private Member Functions
Stopwatch ()
Constructor.
Stopwatch (const Stopwatch &other)
Copy constructor.
Stopwatch & operator= (const Stopwatch &other)
Assignment operator.
Detailed Description
Implements a stopwatch that can be used to measure execution time.
The stopwatch is able to find out both elapsed CPU time and elapsed realtime. CPU time is meant to be used for precise measurements of short time periods. For longer periods, it may overflow (typically after 36 minutes in a 32 bit machine; on a 64-bit machine this usually does not happen). Use getRealTimeSec() to crosscheck.
Usage example:
PointInTime start_time = Stopwatch::start();
doFirstPart();
double first_part_cpu = Stopwatch::getCPUTimeSec(start_time);
L_LOG("doFirstPart() took " << first_part_cpu << " seconds of CPU time.");
doSecondPart();
double all_real_time = Stopwatch::getRealTimeSec(start_time);
L_LOG("The whole computation took " << all_real_time << " seconds (real-time).");
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 66 of file Stopwatch.h.
Constructor & Destructor Documentation
Stopwatch::~Stopwatch () [virtual]
Destructor.
Definition at line 70 of file Stopwatch.cpp.
Stopwatch::Stopwatch () [private]
Constructor.
Constructor is private. Use the static methods instead.
Stopwatch::Stopwatch (const Stopwatch & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
double Stopwatch::getCPUTimeMilliSec (const PointInTime & start_time) [static]
Returns the elapsed CPU time in milliseconds.
CPU time is meant to be used for precise measurements of short time periods. For longer periods, it may overflow (typically after 36 minutes in a 32 bit machine; on a 64-bit machine this usually does not happen). Use getRealTimeSec() to crosscheck.
Parameters
start_time The start time as produced by the start() method.
Returns
The CPU time elapsed since the corresponding call to start(), in milliseconds.
Definition at line 48 of file Stopwatch.cpp.
double Stopwatch::getCPUTimeSec (const PointInTime & start_time) [static]
Returns the elapsed CPU time in seconds.
CPU time is meant to be used for precise measurements of short time periods. For longer periods, it may overflow (typically after 36 minutes in a 32 bit machine; on a 64-bit machine this usually does not happen). Use getRealTimeSec() to crosscheck.
Parameters
start_time The start time as produced by the start() method.
Returns
The CPU time elapsed since the corresponding call to start(), in seconds.
Definition at line 41 of file Stopwatch.cpp.
Referenced by CNFImplExtractor::extractCircuit(), getTimeAsString(), main(), LearningExtractorStatistics::notifyAfterABC(), LearnStatisticsSAT::notifyAfterCheckCandidateFailed(), LearnStatisticsSAT::notifyAfterCheckCandidateFound(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearnStatisticsSAT::notifyAfterComputeCandidate(), LearnStatisticsQBF::notifyAfterComputeCube(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearnStatisticsQBF::notifyAfterCubeMin(), LearnStatisticsSAT::notifyAfterRefine(), LearnStatisticsSAT::notifyWinRegEnd(), and LearnStatisticsQBF::notifyWinRegEnd().
size_t Stopwatch::getRealTimeSec (const PointInTime & start_time) [static]
Returns the elapsed real-time in seconds.
This method returns the elapsed real-time in a rather coarse way. You can use it to check whether the CPU-time counter had an overflow.
Parameters
start_time The start time as produced by the start() method.
Returns
The real-time elapsed since the corresponding call to start(), in seconds.
Definition at line 55 of file Stopwatch.cpp.
Referenced by TemplExplorer::check(), CNFImplExtractor::extractCircuit(), Options::getEstimatedTimeRemaining(), getTimeAsString(), main(), LearningExtractorStatistics::notifyAfterABC(), LearnStatisticsSAT::notifyAfterCheckCandidateFailed(), LearnStatisticsSAT::notifyAfterCheckCandidateFound(), LearningExtractorStatistics::notifyAfterClauseComp(), LearningExtractorStatistics::notifyAfterClauseMin(), LearnStatisticsSAT::notifyAfterComputeCandidate(), LearnStatisticsQBF::notifyAfterComputeCube(), LearningExtractorStatistics::notifyAfterCtrlSignal(), LearnStatisticsQBF::notifyAfterCubeMin(), LearnStatisticsSAT::notifyAfterRefine(), LearnStatisticsSAT::notifyWinRegEnd(), LearnStatisticsQBF::notifyWinRegEnd(), QBFCertImplExtractor::run(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), TemplExplorer::syntSAT(), and ParExtractorWorker::waitForOthersToFinish().
string Stopwatch::getTimeAsString (const PointInTime & start_time) [static]
Returns both the CPU time and the elapsed time as string.
This method returns the string 'XX s (YY s)', where XX is the elapsed CPU time and YY is the elapsed real-time.
Parameters
start_time The start time as produced by the start() method.
Returns
Both the CPU time and the elapsed time as string.
Definition at line 62 of file Stopwatch.cpp.
References getCPUTimeSec(), and getRealTimeSec().
Stopwatch& Stopwatch::operator= (const Stopwatch & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
PointInTime Stopwatch::start () [static]
Starts the stopwatch.
Returns
Information about the moment in time where the stopwatch was started.
Definition at line 33 of file Stopwatch.cpp.
Referenced by CNFImplExtractor::extractCircuit(), main(), LearningExtractorStatistics::notifyBeforeABC(), LearnStatisticsSAT::notifyBeforeCheckCandidate(), LearningExtractorStatistics::notifyBeforeClauseComp(), LearningExtractorStatistics::notifyBeforeClauseMin(), LearnStatisticsSAT::notifyBeforeComputeCandidate(), LearnStatisticsQBF::notifyBeforeComputeCube(), LearningExtractorStatistics::notifyBeforeCtrlSignal(), LearnStatisticsQBF::notifyBeforeCubeMin(), LearnStatisticsSAT::notifyBeforeRefine(), LearnStatisticsSAT::notifyWinRegStart(), LearnStatisticsQBF::notifyWinRegStart(), QBFCertImplExtractor::run(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), TemplExplorer::syntSAT(), and ParExtractorWorker::waitForOthersToFinish().
The documentation for this class was generated from the following files:
src/Stopwatch.h
src/Stopwatch.cpp