SatSolver Class Reference
An abstract interface for all SAT-solver implementations.
#include <SatSolver.h>
Public Member Functions
SatSolver (bool rand_models=false, bool min_cores=true)
Constructor.
virtual ~SatSolver ()
Destructor.
void doMinCores (bool min_cores=true)
Enables or disables the computation of MINIMAL unsatisfiable cores.
void doRandModels (bool rand_models=true)
Enables or disables the randomization of satisfying assignments.
virtual bool isSat (const CNF &cnf)=0
Checks if a CNF is satisfiable.
virtual bool isSatModelOrCore (const CNF &cnf, const vector< int > &assumptions, const vector< int > &vars_of_interest, vector< int > &model_or_core)=0
Checks if a CNF is satisfiable and extracts a model or an unsatisfiable core.
virtual void startIncrementalSession (const vector< int > &vars_to_keep, bool use_push=true)=0
Starts a new incremental session.
virtual void clearIncrementalSession ()=0
Deletes the solver instance that is used in the incremental session.
virtual void incAddCNF (const CNF &cnf)=0
Adds a new CNF to the current incremental session.
virtual void incAddClause (const vector< int > &clause)=0
Adds a new clause to the current incremental session.
virtual void incAddUnitClause (int lit)=0
Adds a new unit clause to the current incremental session.
virtual void incAdd2LitClause (int lit1, int lit2)=0
Adds a new clause consisting of 2 literals to the current incremental session.
virtual void incAdd3LitClause (int lit1, int lit2, int lit3)=0
Adds a new clause consisting of 3 literals to the current incremental session.
virtual void incAdd4LitClause (int lit1, int lit2, int lit3, int lit4)=0
Adds a new clause consisting of 4 literals to the current incremental session.
virtual void incAddCube (const vector< int > &cube)=0
Adds a new cube to the current incremental session.
virtual void incAddNegCubeAsClause (const vector< int > &cube)=0
Adds the negation of a given cube (which is a clause) to the incremental session.
virtual bool incIsSat ()=0
Checks if a the CNF in the incremental session is satisfiable.
virtual bool incIsSat (const vector< int > &assumptions)=0
Checks if a the CNF in the incremental session is satisfiable under assumptions.
virtual bool incIsSatModelOrCore (const vector< int > &assumptions, const vector< int > &vars_of_interest, vector< int > &model_or_core)=0
Checks the CNF in the incremental session and computes a model or unsat core.
virtual bool incIsSatModelOrCore (const vector< int > &core_assumptions, const vector< int > &more_assumptions, const vector< int > &vars_of_interest, vector< int > &model_or_core)=0
Computes a satisfying assignment or core using additional assumptions.
virtual void incPush ()=0
Stores the current state of the incremental session on a stack.
virtual void incPop ()=0
Restores the incremental session back to the point where incPush() was called.
Protected Attributes
bool min_cores_
Indicates if the unsat cores returned by the solver should be minimized further.
bool rand_models_
Indicates if satisfying assignments should be randomized.
Private Member Functions
SatSolver (const SatSolver &other)
Copy constructor.
SatSolver & operator= (const SatSolver &other)
Assignment operator.
Detailed Description
An abstract interface for all SAT-solver implementations.
This class represents an abstract interface all SAT-solver instances. You cannot instantiate objects of this class. You need to instantiate objects of one of the derived classes (e.g., LingelingApi, MiniSatApi, PicoSatApi) instead. Typically, you will call Options::getSATSolver() to get a concrete instance of a SatSolver (namely the one the user selected with command-line parameters).
For a given CNF, a SatSolver is able to determine satisfiability. Furthermore, in case of satisfiability, it can extract satisfying assignments. In case of unsatisfiability, it can compute an unsatisfiable core. It can be used in two different ways. In the incremental usage scenario, all information the solver has learned so far is retained. Methods for incremental solving start with 'inc'. Other methods (like isSat() or isSatModelOrCore()) instantiate a fresh solver instance for every call.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 58 of file SatSolver.h.
Constructor & Destructor Documentation
SatSolver::SatSolver (bool rand_models = false, bool min_cores = true)
Constructor.
Parameters
rand_models A flag indicating if satisfying assignments should be randomized. This is done in a post-processing step (values are flipped randomly and then we check if this still constitutes a satisfying assignment). This is expensive. If this parameter is skipped, then satisfying assignments are not randomized.
min_cores A flag indicating if unsatisfiable cores returned by the solver should be minimized further by trying to drop one literal after the other. This makes the calls slower but produces potentially smaller cubes.
Definition at line 33 of file SatSolver.cpp.
SatSolver::~SatSolver () [virtual]
Destructor.
Definition at line 41 of file SatSolver.cpp.
SatSolver::SatSolver (const SatSolver & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
virtual void SatSolver::clearIncrementalSession () [pure virtual]
Deletes the solver instance that is used in the incremental session.
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
void SatSolver::doMinCores (bool min_cores = true)
Enables or disables the computation of MINIMAL unsatisfiable cores.
Parameters
min_cores A flag indicating if unsatisfiable cores returned by the solver should be minimized further by trying to drop one literal after the other. This makes the calls slower but produces potentially smaller cubes. If the parameter is skipped the computation of minimal cores is enabled.
Definition at line 47 of file SatSolver.cpp.
References min_cores_.
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void SatSolver::doRandModels (bool rand_models = true)
Enables or disables the randomization of satisfying assignments.
Parameters
rand_models A flag indicating if satisfying assignments should be randomized. This is done in a post-processing step (values are flipped randomly and then we check if this still constitutes a satisfying assignment). This is expensive. If this parameter is skipped, then randomization is enabled.
Definition at line 53 of file SatSolver.cpp.
References rand_models_.
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), and LearnSynthSAT::computeWinningRegionRGRecy().
virtual void SatSolver::incAdd2LitClause (int lit1, int lit2) [pure virtual]
Adds a new clause consisting of 2 literals to the current incremental session.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Precondition
startIncrementalSession() must have been called before.
Parameters
lit1 The first literal of the clause to add to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed literal talks about a variables that have been mentioned in vars_to_keep when calling startIncrementalSession().
lit2 The second literal of the clause to add to the currently open incremental session (must be contained in vars_to_keep as well).
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by LearnSynthSAT::computeWinningRegionRGExp(), UnivExpander::extrExp(), UnivExpander::initSolverCExp(), OrigUnivExpander::resetSolverCExp(), and OrigUnivExpander::resetSolverIExp().
virtual void SatSolver::incAdd3LitClause (int lit1, int lit2, int lit3) [pure virtual]
Adds a new clause consisting of 3 literals to the current incremental session.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Precondition
startIncrementalSession() must have been called before.
Parameters
lit1 The first literal of the clause to add to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed literal talks about a variables that have been mentioned in vars_to_keep when calling startIncrementalSession().
lit2 The second literal of the clause to add to the currently open incremental session (must be contained in vars_to_keep as well).
lit3 The third literal of the clause to add to the currently open incremental session (must be contained in vars_to_keep as well).
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by UnivExpander::extrExp(), UnivExpander::initSolverCExp(), and OrigUnivExpander::resetSolverCExp().
virtual void SatSolver::incAdd4LitClause (int lit1, int lit2, int lit3, int lit4) [pure virtual]
Adds a new clause consisting of 4 literals to the current incremental session.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Precondition
startIncrementalSession() must have been called before.
Parameters
lit1 The first literal of the clause to add to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed literal talks about a variables that have been mentioned in vars_to_keep when calling startIncrementalSession().
lit2 The second literal of the clause to add to the currently open incremental session (must be contained in vars_to_keep as well).
lit3 The third literal of the clause to add to the currently open incremental session (must be contained in vars_to_keep as well).
lit4 The third literal of the clause to add to the currently open incremental session (must be contained in vars_to_keep as well).
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by LearnSynthSAT::computeWinningRegionRGExp().
virtual void SatSolver::incAddClause (const vector< int > & clause) [pure virtual]
Adds a new clause to the current incremental session.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Precondition
startIncrementalSession() must have been called before.
Parameters
clause The clause (a disjunction of literals) to add (conjunct) to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed clause talks only about variables that have been mentioned in vars_to_keep when calling startIncrementalSession().
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by IFM13Synth::addBlockedState(), IFM13Explorer::addBlockedState(), IFM13Synth::addBlockedTransition(), IFM13Explorer::addBlockedTransition(), OrigUnivExpander::addExpNxtClauseToC(), UnivExpander::addExpNxtClauseToC(), IFM13Synth::addLose(), IFM13Explorer::addLose(), Utils::compressNextStateCNF(), Utils::compressStateCNF(), LearnSynthQBF::computeCounterexampleSAT(), LearnSynthQBF::computeWinningRegionOneSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::exploreClauses(), UnivExpander::extrExp(), CounterGenSAT::generalizeCeFuther(), IFM13Synth::propagateBlockedStates(), IFM13Explorer::propagateBlockedStates(), and OrigUnivExpander::resetSolverIExp().
virtual void SatSolver::incAddCNF (const CNF & cnf) [pure virtual]
Adds a new CNF to the current incremental session.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Precondition
startIncrementalSession() must have been called before.
Parameters
cnf The CNF to add to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed CNF talks only about variables that have been mentioned in vars_to_keep when calling startIncrementalSession().
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by TemplateSynth::check(), TemplExplorer::check(), CounterGenSAT::compressBored(), Utils::compressNextStateCNF(), Utils::compressStateCNF(), LearnSynthQBF::computeCounterexampleSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::considerNewInfoFromOthers(), CounterGenSAT::considerNewInfoFromOthers(), IFM13Explorer::considerNewInfoFromOthers(), Utils::debugCheckWinReg(), TemplateSynth::exclude(), TemplExplorer::exclude(), ClauseExplorerSAT::exploreClauses(), CounterGenSAT::generalizeCounterexamples(), IFM13Explorer::IFM13Explorer(), IFM13Synth::IFM13Synth(), LearnSynthQBF::LearnSynthQBF(), ClauseMinimizerQBF::minimizeClausesInc(), Utils::negateStateCNF(), UnivExpander::resetSolverCExp(), OrigUnivExpander::resetSolverIExp(), LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), and ParallelLearner::triggerExplorerRestart().
virtual void SatSolver::incAddCube (const vector< int > & cube) [pure virtual]
Adds a new cube to the current incremental session.
That is, all literals of the cube are added as unit clauses to the current incremental session. For instance, if the cube [2, -4, 8] is passed as argument, then this method adds the three unit clauses [2], [-4], [8].
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Precondition
startIncrementalSession() must have been called before.
Parameters
cube The cube (a conjunction of literals) to add (conjunct) to the currently open incremental session. All literals of this cube will be added as unit clauses. If this method is called after solving for the first time, be sure that the passed clause talks only about variables that have been mentioned in vars_to_keep when calling startIncrementalSession().
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), and LearnSynthSAT::computeWinningRegionRGRecy().
virtual void SatSolver::incAddNegCubeAsClause (const vector< int > & cube) [pure virtual]
Adds the negation of a given cube (which is a clause) to the incremental session.
For instance, if the cube [2, -4, 8] is passed as argument, then this method adds the clauses [-2, 4, -8] to the current incremental session.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Precondition
startIncrementalSession() must have been called before.
Parameters
cube The cube (a conjunction of literals) to negate and add (conjunct) to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed cube talks only about variables that have been mentioned in vars_to_keep when calling startIncrementalSession().
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by TemplateSynth::check(), TemplExplorer::check(), CounterGenSAT::compressBored(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRecy(), Utils::debugCheckWinReg(), Utils::negateStateCNF(), LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
virtual void SatSolver::incAddUnitClause (int lit) [pure virtual]
Adds a new unit clause to the current incremental session.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Precondition
startIncrementalSession() must have been called before.
Parameters
lit The (one and only) literal of the unit clause to add to the currently open incremental session. If this method is called after solving for the first time, be sure that the passed literal talks about a variables that have been mentioned in vars_to_keep when calling startIncrementalSession().
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::exploreClauses(), UnivExpander::extrExp(), CounterGenSAT::generalizeCounterexamples(), UnivExpander::initSolverCExp(), OrigUnivExpander::resetSolverCExp(), OrigUnivExpander::resetSolverIExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), and ParExtractorWorker::runSATDep().
virtual bool SatSolver::incIsSat () [pure virtual]
Checks if a the CNF in the incremental session is satisfiable.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Precondition
startIncrementalSession() must have been called before.
Returns
True in case of satisfiability, false otherwise.
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by IFM13Synth::addBlockedState(), IFM13Explorer::addBlockedState(), CounterGenSAT::bored(), CounterGenSAT::compressBored(), Utils::compressNextStateCNF(), Utils::compressStateCNF(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::exploreClauses(), CounterGenSAT::generalizeCeFuther(), CounterGenSAT::generalizeCounterexamples(), ClauseMinimizerQBF::minimizeClausesInc(), IFM13Synth::propagateBlockedStates(), IFM13Explorer::propagateBlockedStates(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
virtual bool SatSolver::incIsSat (const vector< int > & assumptions) [pure virtual]
Checks if a the CNF in the incremental session is satisfiable under assumptions.
This method checks if the CNF in the incremental session is satisfiable given that all literals passed in the vector 'assumptions' are true. The assumptions are not persistently added to the CNF of the incremental session.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Precondition
startIncrementalSession() must have been called before.
Parameters
assumptions A vector of literals. This method then checks if the CNF of the incremental session is satisfiable given that all literals passed in this vector are true. The assumptions are not persistently added to the CNF. The assumptions must be a subset of the vars_to_keep passed to startIncrementalSession().
Returns
True in case of satisfiability, false otherwise.
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
virtual bool SatSolver::incIsSatModelOrCore (const vector< int > & assumptions, const vector< int > & vars_of_interest, vector< int > & model_or_core) [pure virtual]
Checks the CNF in the incremental session and computes a model or unsat core.
This method checks if the CNF of the incremental session is satisfiable given that all literals passed in the vector 'assumptions' is true. If this is the case, then a satisfying assignment will be written into model_or_core. You can specify which variables you want to have in the satisfying assignment using the vars_of_interest vector. The reason is that your CNF may contain thousands of temporary variables stemming from some Tseitin encoding, but usually one in only interested in the value of a few variables. In case of unsatisfiability, an unsatisfiable core is stored in model_or_core. The unsatisfiable core is a subset of the literals passed in 'assumptions' such that the CNF is still unsatisfiable when these literals hold.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Parameters
assumptions A vector of literals. This method then checks if the CNF of the incremental session is satisfiable given that all literals passed in this vector are true. The assumptions are not persistently added to the CNF. The assumptions must be a subset of the vars_to_keep passed to startIncrementalSession().
vars_of_interest The variables for which you want to have a value in case of satisfiability. vars_of_interest must be a subset of the vars_to_keep passed to startIncrementalSession().
model_or_core An empty vector. Depending on the outcome of the call, either a satisfying assignment (a cube over the variables passed in vars_of_interest) or an unsatisfiable core (a subset of the literals passed in 'assumptions') will be written into this vector.
Returns
True in case of satisfiability (of the CNF of the incremental session in conjunction conjuncted with all assumptions), false otherwise.
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by TemplateSynth::check(), TemplExplorer::check(), Utils::compressNextStateCNF(), Utils::compressStateCNF(), LearnSynthQBF::computeCounterexampleSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), Utils::debugCheckWinReg(), ClauseExplorerSAT::exploreClauses(), IFM13Synth::genAndBlockTrans(), IFM13Explorer::genAndBlockTrans(), CounterGenSAT::generalizeCeFuther(), CounterGenSAT::generalizeCounterexample(), Utils::negateStateCNF(), IFM13Synth::recBlockCube(), IFM13Explorer::recBlockCube(), LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), TemplateSynth::syntSAT(), and TemplExplorer::syntSAT().
virtual bool SatSolver::incIsSatModelOrCore (const vector< int > & core_assumptions, const vector< int > & more_assumptions, const vector< int > & vars_of_interest, vector< int > & model_or_core) [pure virtual]
Computes a satisfying assignment or core using additional assumptions.
In contrast to the previous method, this one allows to define two sets of assumptions. The core_assumptions are used as basis for extracting an unsatisfiable core in case of unsatisfiability. The more_assumptions are assumed but not considered for the computation of unsatisfiable cores. This is convenient to avoid calls to incPush() and incPop() when temporarily working under assumptions that should not be minimized for the unsatisfiable core.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Parameters
core_assumptions A vector of literals. This method then checks if the CNF of the incremental session is satisfiable given that all literals passed in this vector and all literals passed in more_assumptions are true. However, for computing the the unsatisfiable core, only the core_assumptions will be minimized and the more_assumptions stay as they are. That is, in case of unsatisfiability, model_or_core will contain a subset X of the core_assumptions such that X & more_assumptions & incremental_cnf is still unsatisfiable. core_assumptions must be a subset of the vars_to_keep passed to startIncrementalSession().
more_assumptions A vector of assumptions that are assumed, but not minimized when an unsatisfiable core is computed. That is, in case of unsatisfiability, model_or_core will contain a subset X of the core_assumptions such that X & more_assumptions & incremental_cnf is still unsatisfiable. more_assumptions must be a subset of the vars_to_keep passed to startIncrementalSession().
vars_of_interest The variables for which you want to have a value in case of satisfiability. vars_of_interest must be a subset of the vars_to_keep passed to startIncrementalSession().
model_or_core An empty vector. Depending on the outcome of the call, either a satisfying assignment (a cube over the variables passed in vars_of_interest) or an unsatisfiable core (a subset of the literals passed in 'core_assumptions') will be written into this vector.
Returns
True in case of satisfiability (of the CNF of the incremental session in conjunction conjuncted with all assumptions), false otherwise.
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
virtual void SatSolver::incPop () [pure virtual]
Restores the incremental session back to the point where incPush() was called.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), and LearnSynthSAT::computeWinningRegionRGRecy().
virtual void SatSolver::incPush () [pure virtual]
Stores the current state of the incremental session on a stack.
The state can be restored later by calling incPop().
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), and LearnSynthSAT::computeWinningRegionRGRecy().
virtual bool SatSolver::isSat (const CNF & cnf) [pure virtual]
Checks if a CNF is satisfiable.
This method is not incremental. At aver call to this method, a new solver instance is created and deleted afterwards. This method does not interfere with an incremental session that may be open in parallel.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Parameters
cnf The CNF formula for which we want to know if it is satisfiable.
Returns
True in case of satisfiability, false otherwise.
Implemented in MiniSatApi, LingelingApi, and PicoSatApi.
Referenced by IFM13Synth::debugCheckInvariants(), Utils::debugCheckWinReg(), and ClauseMinimizerQBF::minimizeClausesNoInc().
virtual bool SatSolver::isSatModelOrCore (const CNF & cnf, const vector< int > & assumptions, const vector< int > & vars_of_interest, vector< int > & model_or_core) [pure virtual]
Checks if a CNF is satisfiable and extracts a model or an unsatisfiable core.
This method is not incremental. At aver call to this method, a new solver instance is created and deleted afterwards. This method does not interfere with an incremental session that may be open in parallel. This method checks if the passed CNF is satisfiable given that all literals passed in the vector 'assumptions' is true. If this is the case, then a satisfying assignment will be written into model_or_core. You can specify which variables you want to have in the satisfying assignment using the vars_of_interest vector. The reason is that you CNF may contain thousands of temporary variables stemming from some Tseitin encoding, but usually one in only interested in the value of a few variables. In case of unsatisfiability, an unsatisfiable core is stored in model_or_core. The unsatisfiable core is a subset of the literals passed in 'assumptions' such that the CNF is still unsatisfiable when these literals hold.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Parameters
cnf The CNF formula for which we want to know if it is satisfiable (in conjunction with the assumptions).
assumptions A vector of literals. These literals are conjuncted to the CNF before solving. If you do not have any assumptions but want to decide the satisfiability of the cnf only, then simply leave this vector empty.
vars_of_interest The variables for which you want to have a value in case of satisfiability.
model_or_core An empty vector. Depending on the outcome of the call, either a satisfying assignment (a cube over the variables passed in vars_of_interest) or an unsatisfiable core (a subset of the literals passed in 'assumptions') will be written into this vector.
Returns
True in case of satisfiability (of the CNF conjuncted with all assumptions), false otherwise.
Implemented in MiniSatApi, LingelingApi, and PicoSatApi.
SatSolver& SatSolver::operator= (const SatSolver & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
virtual void SatSolver::startIncrementalSession (const vector< int > & vars_to_keep, bool use_push = true) [pure virtual]
Starts a new incremental session.
Every instance of this class can have at most one open incremental session. If there is an old open incremental session it will be closed before. An incremental session allows you to execute sequences of calls, where the information the solver learned in previous calls is retained and may speedup later calls. You can add new clauses between calls, but you cannot remove clauses.
This is an abstract method which must be implemented in all derived classes (all classes implementing this interface).
Parameters
vars_to_keep A set of variables the solver should not optimize away. Clauses added later in an incremental session can only talk about variables contained in this vector.
use_push A hint to the solver if you are ever going to use incPush() or incPop(). Some solver implementations (like MiniSatApi) do not support push and and pop natively, so we have to make a workaround. This workaround is expensive and we can safe some computation time if we skip it when we will not need it.
Implemented in MiniSatApi, PicoSatApi, and LingelingApi.
Referenced by TemplateSynth::check(), TemplExplorer::check(), ClauseMinimizerQBF::ClauseMinimizerQBF(), CounterGenSAT::compressBored(), Utils::compressNextStateCNF(), Utils::compressStateCNF(), LearnSynthQBF::computeCounterexampleSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::considerNewInfoFromOthers(), Utils::debugCheckWinReg(), ClauseExplorerSAT::exploreClauses(), UnivExpander::extrExp(), CounterGenSAT::generalizeCounterexamples(), IFM13Explorer::IFM13Explorer(), IFM13Synth::IFM13Synth(), UnivExpander::initSolverCExp(), LearnSynthQBF::LearnSynthQBF(), Utils::negateStateCNF(), OrigUnivExpander::resetSolverCExp(), UnivExpander::resetSolverCExp(), OrigUnivExpander::resetSolverIExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), TemplateSynth::syntSAT(), TemplExplorer::syntSAT(), and ParallelLearner::triggerExplorerRestart().
Member Data Documentation
bool SatSolver::min_cores_ [protected]
Indicates if the unsat cores returned by the solver should be minimized further.
Definition at line 448 of file SatSolver.h.
Referenced by doMinCores(), LingelingApi::incIsSatModelOrCore(), PicoSatApi::incIsSatModelOrCore(), MiniSatApi::incIsSatModelOrCore(), LingelingApi::isSatModelOrCore(), PicoSatApi::isSatModelOrCore(), and MiniSatApi::isSatModelOrCore().
bool SatSolver::rand_models_ [protected]
Indicates if satisfying assignments should be randomized.
Definition at line 453 of file SatSolver.h.
Referenced by doRandModels(), LingelingApi::incIsSatModelOrCore(), PicoSatApi::incIsSatModelOrCore(), MiniSatApi::incIsSatModelOrCore(), LingelingApi::isSatModelOrCore(), PicoSatApi::isSatModelOrCore(), and MiniSatApi::isSatModelOrCore().
The documentation for this class was generated from the following files:
src/SatSolver.h
src/SatSolver.cpp