TemplExplorer Class Reference
Implements the method of TemplateSynth in a parallelized way.
#include <ParallelLearner.h>
Public Member Functions
TemplExplorer (ParallelLearner &coordinator)
Constructor.
virtual ~TemplExplorer ()
Destructor.
void computeWinningRegion ()
Computes the winning region as instantiation of a generic template.
void notifyNewWinRegClause (const vector< int > &clause, int src)
Notifies this worker about a new winning region clause.
Protected Member Functions
int findWinRegCNFTempl (size_t nr_of_clauses, size_t timeout, bool use_sat)
Computes the winning region as instantiation of a generic CNF template.
int syntQBF (const CNF &win_constr, int w1, int w2, vector< int > &solution, size_t timeout)
Resolves the template by calling a QBF solver.
int syntSAT (const CNF &win_constr, int w1, int w2, vector< int > &solution, size_t timeout)
Resolves the template by calling a SAT solver in a CEGIS loop.
void exclude (const vector< int > &ce, const CNF &gen, SatSolver *solver)
A helper for the CEGIS loop of syntSAT(), eliminating a counterexample.
int check (const vector< int > &cand, const CNF &win_constr, int w1, int w2, size_t timeout, vector< int > &ce)
A helper for the CEGIS loop of syntSAT(), checking if a candidate solution works.
int newTmp ()
Returns a fresh temporary variable.
int newParam ()
Returns a fresh template parameter.
void swapPresentToNext (vector< int > &vec) const
A helper that transforms all current state variables into next state variables.
Protected Attributes
ParallelLearner & coordinator_
A reference to the coordinator.
CNF final_winning_region_
The resulting winning region.
mutex known_clauses_lock_
A lock that protects the known_clauses_ from race-conditions.
CNF known_clauses_
The resulting winning region.
vector< int > s_
The list of present-state variables.
vector< int > i_
The list of (uncontrollable) input variables.
vector< int > c_
The list of control signals (controllable input variables).
vector< int > n_
The list of next-state variables.
vector< int > templ_
The list of template parameters.
vector< int > orig_tmp_
The original list of temporary variables.
vector< int > current_tmp_
The current list of temporary variables.
int orig_next_free_var_
The initial next free CNF variable.
int next_free_var_
The current next free CNF variable.
int p_err_
The present-state error variable.
int n_err_
The next-state error variable.
PointInTime start_
The point in time where the SAT-based method has been started.
vector< int > pres_to_nxt_
A map from present-state variables to corresponding next state variables.
Detailed Description
Implements the method of TemplateSynth in a parallelized way.
This class basically implements the same method as TemplateSynth. It only has a few additional methods to communicate with other threads. It considers all clauses of the winning region found by other threads already. However, it does not produce any information for the other threads. It is an information sink.
See Also
TemplateSynth
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 1630 of file ParallelLearner.h.
Constructor & Destructor Documentation
TemplExplorer::TemplExplorer (ParallelLearner & coordinator)
Constructor.
Parameters
coordinator A reference to the coordinator. All communication to other worker-threads is done via the coordinator.
Definition at line 2226 of file ParallelLearner.cpp.
References n_, pres_to_nxt_, and s_.
TemplExplorer::~TemplExplorer () [virtual]
Destructor.
Definition at line 2250 of file ParallelLearner.cpp.
Member Function Documentation
int TemplExplorer::check (const vector< int > & cand, const CNF & win_constr, int w1, int w2, size_t timeout, vector< int > & ce) [protected]
A helper for the CEGIS loop of syntSAT(), checking if a candidate solution works.
Parameters
cand A canidate solution in the form of concrete values for the template parameters.
win_constr CNF constraints that constitute a correct solution for the winning region using the generic template. Essentially, three constraints are encoded in this CNF:
I(x) => W(x): every initial state is contained in the winning region
W(x) => P(x): every state of the winning region is safe
forall x,i: exists c,x': W(x) => (T(x,i,c,x') & W(x')): from every state in the winning region we can enforce to stay in the winning region by setting the c-signals appropriately.
w1 The literal that represents the present-state copy of the winning region in win_constr.
w2 The literal that represents the next-state copy of the winning region in win_constr.
timeout A time-out is seconds.
ce An empty vector. If the candidate solution is incorrect, a counterexample in the form of concrete values for state and input variables for which we fall out of the winning region is stored in this vector.
Returns
The value 1 the candidate solution is correct, the value 0 if the candicate solution is incorrect, 2 if a time-out was reached.
Definition at line 2611 of file ParallelLearner.cpp.
References CNF::add1LitClause(), CNF::addCNF(), c_, coordinator_, Stopwatch::getRealTimeSec(), Options::getSATSolver(), AIG2CNF::getTrans(), i_, SatSolver::incAddCNF(), SatSolver::incAddNegCubeAsClause(), SatSolver::incIsSatModelOrCore(), Options::instance(), AIG2CNF::instance(), MASSERT, ParallelLearner::result_, s_, CNF::setVarValue(), start_, SatSolver::startIncrementalSession(), and UNKNOWN.
Referenced by syntSAT().
void TemplExplorer::computeWinningRegion ()
Computes the winning region as instantiation of a generic template.
Definition at line 2256 of file ParallelLearner.cpp.
References coordinator_, final_winning_region_, findWinRegCNFTempl(), L_LOG, REALIZABLE, ParallelLearner::result_, UNKNOWN, ParallelLearner::winning_region_, and ParallelLearner::winning_region_lock_.
Referenced by ParallelLearner::run().
void TemplExplorer::exclude (const vector< int > & ce, const CNF & gen, SatSolver * solver) [protected]
A helper for the CEGIS loop of syntSAT(), eliminating a counterexample.
Parameters
ce A counterexample that has been computed previously by calling check(). A counterexample is simply a set of values for state variables and input variables for which we fall out of the winning region.
gen The CNF containing the constraints for a correct winning region. We simply add constraints here saying that the winning region must now also work for the counterexample.
solver The solver to which the constraints eliminating the counterexample shall be added.
Definition at line 2700 of file ParallelLearner.cpp.
References CNF::appendVarsTo(), Utils::contains(), SatSolver::incAddCNF(), newTmp(), CNF::renameVars(), CNF::setVarValue(), and templ_.
Referenced by syntSAT().
int TemplExplorer::findWinRegCNFTempl (size_t nr_of_clauses, size_t timeout, bool use_sat) [protected]
Computes the winning region as instantiation of a generic CNF template.
Parameters
nr_of_clauses The number N of clauses to use in the template.
timeout A time-out is seconds.
use_sat True if a SAT solver shall be used, false if a QBF solver shall be used.
Returns
The value 0 if no winning region exists, the value 1 if a winning region was successfully computed, the value 2 if we had a time-out.
Definition at line 2299 of file ParallelLearner.cpp.
References CNF::add1LitClause(), CNF::add2LitClause(), CNF::add4LitClause(), CNF::addClause(), CNF::addCNF(), Utils::compressStateCNF(), current_tmp_, final_winning_region_, CNF::getClauses(), CNF::getNrOfClauses(), known_clauses_, known_clauses_lock_, n_, n_err_, newParam(), newTmp(), next_free_var_, orig_next_free_var_, orig_tmp_, p_err_, s_, swapPresentToNext(), syntQBF(), syntSAT(), and templ_.
Referenced by computeWinningRegion().
int TemplExplorer::newParam () [protected]
Returns a fresh template parameter.
Returns
A fresh template parameter.
Definition at line 2735 of file ParallelLearner.cpp.
References next_free_var_, and templ_.
Referenced by findWinRegCNFTempl().
int TemplExplorer::newTmp () [protected]
Returns a fresh temporary variable.
Returns
A fresh temporary variable.
Definition at line 2726 of file ParallelLearner.cpp.
References current_tmp_, and next_free_var_.
Referenced by exclude(), and findWinRegCNFTempl().
void TemplExplorer::notifyNewWinRegClause (const vector< int > & clause, int src)
Notifies this worker about a new winning region clause.
Parameters
clause The new clause that has been discovered.
src An integer number defining which kind of worker-thread discovered the clause. At the moment, this information is ignored.
Definition at line 2291 of file ParallelLearner.cpp.
References CNF::addClause(), known_clauses_, and known_clauses_lock_.
void TemplExplorer::swapPresentToNext (vector< int > & vec) const [protected]
A helper that transforms all current state variables into next state variables.
Parameters
vec A vector of state variables or their negation.
Definition at line 2744 of file ParallelLearner.cpp.
References pres_to_nxt_.
Referenced by findWinRegCNFTempl().
int TemplExplorer::syntQBF (const CNF & win_constr, int w1, int w2, vector< int > & solution, size_t timeout) [protected]
Resolves the template by calling a QBF solver.
Parameters
win_constr CNF constraints that constitute a correct solution for the winning region using the generic template. Essentially, three constraints are encoded in this CNF:
I(x) => W(x): every initial state is contained in the winning region
W(x) => P(x): every state of the winning region is safe
forall x,i: exists c,x': W(x) => (T(x,i,c,x') & W(x')): from every state in the winning region we can enforce to stay in the winning region by setting the c-signals appropriately.
w1 The literal that represents the present-state copy of the winning region in win_constr.
w2 The literal that represents the next-state copy of the winning region in win_constr.
solution An empty vector. If a solution exists, then the corresponding template parameter values are written into this vector.
timeout A time-out is seconds.
Returns
The value 0 if no winning region exists, the value 1 if a winning region was successfully computed, the value 2 if we had a time-out.
Definition at line 2502 of file ParallelLearner.cpp.
References QBFSolver::A, CNF::addCNF(), c_, current_tmp_, QBFSolver::E, AIG2CNF::getT(), AIG2CNF::getTransEqT(), i_, AIG2CNF::instance(), ExtQBFSolver::isSatModel(), n_, s_, and templ_.
Referenced by findWinRegCNFTempl().
int TemplExplorer::syntSAT (const CNF & win_constr, int w1, int w2, vector< int > & solution, size_t timeout) [protected]
Resolves the template by calling a SAT solver in a CEGIS loop.
Parameters
win_constr CNF constraints that constitute a correct solution for the winning region using the generic template. Essentially, three constraints are encoded in this CNF:
I(x) => W(x): every initial state is contained in the winning region
W(x) => P(x): every state of the winning region is safe
forall x,i: exists c,x': W(x) => (T(x,i,c,x') & W(x')): from every state in the winning region we can enforce to stay in the winning region by setting the c-signals appropriately.
w1 The literal that represents the present-state copy of the winning region in win_constr.
w2 The literal that represents the next-state copy of the winning region in win_constr.
solution An empty vector. If a solution exists, then the corresponding template parameter values are written into this vector.
timeout A time-out is seconds.
Returns
The value 0 if no winning region exists, the value 1 if a winning region was successfully computed, the value 2 if we had a time-out.
Definition at line 2544 of file ParallelLearner.cpp.
References CNF::addCNF(), check(), coordinator_, exclude(), Stopwatch::getRealTimeSec(), Options::getSATSolver(), AIG2CNF::getTrans(), i_, SatSolver::incIsSatModelOrCore(), Options::instance(), AIG2CNF::instance(), Utils::negateLiterals(), ParallelLearner::result_, s_, Stopwatch::start(), start_, SatSolver::startIncrementalSession(), templ_, and UNKNOWN.
Referenced by findWinRegCNFTempl().
Member Data Documentation
vector<int> TemplExplorer::c_ [protected]
The list of control signals (controllable input variables).
This list is often used, so we keep it as a field to increase readability of the code.
Definition at line 1832 of file ParallelLearner.h.
Referenced by check(), and syntQBF().
ParallelLearner& TemplExplorer::coordinator_ [protected]
A reference to the coordinator.
All communication to other worker-threads is done via the coordinator.
Definition at line 1793 of file ParallelLearner.h.
Referenced by check(), computeWinningRegion(), and syntSAT().
vector<int> TemplExplorer::current_tmp_ [protected]
The current list of temporary variables.
We do not want to access the global VarManager (to avoid too much locking), so we keep everything local.
Definition at line 1863 of file ParallelLearner.h.
Referenced by findWinRegCNFTempl(), newTmp(), and syntQBF().
CNF TemplExplorer::final_winning_region_ [protected]
The resulting winning region.
Definition at line 1798 of file ParallelLearner.h.
Referenced by computeWinningRegion(), and findWinRegCNFTempl().
vector<int> TemplExplorer::i_ [protected]
The list of (uncontrollable) input variables.
This list is often used, so we keep it as a field to increase readability of the code.
Definition at line 1825 of file ParallelLearner.h.
Referenced by check(), syntQBF(), and syntSAT().
CNF TemplExplorer::known_clauses_ [protected]
The resulting winning region.
Definition at line 1811 of file ParallelLearner.h.
Referenced by findWinRegCNFTempl(), and notifyNewWinRegClause().
mutex TemplExplorer::known_clauses_lock_ [protected]
A lock that protects the known_clauses_ from race-conditions.
Many worker-threads modify the known_clauses_ (add new ones). This lock ensures that only one thread is modifying or reading the known_clauses_ at one time.
Definition at line 1806 of file ParallelLearner.h.
Referenced by findWinRegCNFTempl(), and notifyNewWinRegClause().
vector<int> TemplExplorer::n_ [protected]
The list of next-state variables.
This list is often used, so we keep it as a field to increase readability of the code.
Definition at line 1839 of file ParallelLearner.h.
Referenced by findWinRegCNFTempl(), syntQBF(), and TemplExplorer().
int TemplExplorer::n_err_ [protected]
The next-state error variable.
It is stored here locally so that we do not always have to access the global variable manager (which may cause a concurrency issue).
Definition at line 1895 of file ParallelLearner.h.
Referenced by findWinRegCNFTempl().
int TemplExplorer::next_free_var_ [protected]
The current next free CNF variable.
We do not want to access the global VarManager (to avoid too much locking), so we keep everything local.
Definition at line 1879 of file ParallelLearner.h.
Referenced by findWinRegCNFTempl(), newParam(), and newTmp().
int TemplExplorer::orig_next_free_var_ [protected]
The initial next free CNF variable.
We do not want to access the global VarManager (to avoid too much locking), so we keep everything local.
Definition at line 1871 of file ParallelLearner.h.
Referenced by findWinRegCNFTempl().
vector<int> TemplExplorer::orig_tmp_ [protected]
The original list of temporary variables.
We do not want to access the global VarManager (to avoid too much locking), so we keep everything local.
Definition at line 1855 of file ParallelLearner.h.
Referenced by findWinRegCNFTempl().
int TemplExplorer::p_err_ [protected]
The present-state error variable.
It is stored here locally so that we do not always have to access the global variable manager (which may cause a concurrency issue).
Definition at line 1887 of file ParallelLearner.h.
Referenced by findWinRegCNFTempl().
vector<int> TemplExplorer::pres_to_nxt_ [protected]
A map from present-state variables to corresponding next state variables.
Definition at line 1908 of file ParallelLearner.h.
Referenced by swapPresentToNext(), and TemplExplorer().
vector<int> TemplExplorer::s_ [protected]
The list of present-state variables.
This list is often used, so we keep it as a field to increase readability of the code.
Definition at line 1818 of file ParallelLearner.h.
Referenced by check(), findWinRegCNFTempl(), syntQBF(), syntSAT(), and TemplExplorer().
PointInTime TemplExplorer::start_ [protected]
The point in time where the SAT-based method has been started.
This is used for a heuristic that defines when to abort the SAT-based exploration.
Definition at line 1902 of file ParallelLearner.h.
Referenced by check(), and syntSAT().
vector<int> TemplExplorer::templ_ [protected]
The list of template parameters.
We do not want to access the global VarManager (to avoid too much locking), so we keep everything local.
Definition at line 1847 of file ParallelLearner.h.
Referenced by exclude(), findWinRegCNFTempl(), newParam(), syntQBF(), and syntSAT().
The documentation for this class was generated from the following files:
src/ParallelLearner.h
src/ParallelLearner.cpp