ClauseExplorerSAT Class Reference
Implements the method of LearnSynthSAT in a parallelized way.
#include <ParallelLearner.h>
Public Member Functions
ClauseExplorerSAT (size_t instance_nr, ParallelLearner &coordinator)
Constructor if optimization RG is disabled.
ClauseExplorerSAT (size_t instance_nr, ParallelLearner &coordinator, const CNF &prev_trans_or_initial, const vector< int > &current_to_previous_map, int current_state_is_initial)
Constructor if optimization RG is enabled.
virtual ~ClauseExplorerSAT ()
Destructor.
void exploreClauses ()
The work-horse of this class.
void notifyBeforeNewInfo ()
The method must be called before new information is passed to this object.
void notifyAfterNewInfo ()
The method must be called after new information is passed to this object.
void notifyNewWinRegClause (const vector< int > &clause, int src)
Notifies this worker about a new winning region clause.
void notifyNewUselessInputClause (const vector< int > &clause, int level)
Notifies this ClauseExplorerSAT-instance that a new U-clause is available.
void notifyRestart (const CNF &restart_with_cnf)
Notifies this ClauseExplorerSAT-instance that it should restart its solver.
const LearnStatisticsSAT & getStatistics () const
Returns the statistics and performance measures computed by this object.
Protected Member Functions
void considerNewInfoFromOthers ()
Considers new information discovered by other threads in the solvers.
bool waitUntilOngoingRestartDone ()
Checks if some other thread is computing a restart. If yes: waits until it is done.
int presentToPrevious (int literal) const
Returns the previous-state copy of a literal.
void presentToPrevious (vector< int > &cube_or_clause) const
Computes the previous-state copy of a cube or clause.
void presentToPrevious (CNF &cnf) const
Computes the previous-state copy of a CNF.
Protected Attributes
size_t instance_nr_
A unique instance number.
bool use_ind_
A flag indicating if optimization RG should be used.
LearnStatisticsSAT statistics_
Stores and maintains statistics and performance measures.
ParallelLearner & coordinator_
A reference to the coordinator.
bool precise_
A flag indicating if the next-state copy of the winning region is accurate.
SatSolver * solver_i_
The solver for computing counterexample-candidates.
SatSolver * solver_ctrl_
The solver for checking counterexample-candidates.
vector< int > vars_to_keep_
A set of variables the solver should not optimize by the SAT-solver.
mutex new_info_lock_
A lock to protect many fields from race conditions.
CNF restart_with_cnf_
A CNF to restart solver_i_ with.
CNF new_win_reg_clauses_for_solver_i_
All new winning region clauses that have not yet been fed into solver_i_.
CNF new_win_reg_clauses_for_solver_ctrl_
All new winning region clauses that have not yet been fed into solver_ctrl_.
CNF new_foreign_win_reg_clauses_for_solver_i_
All foreign winning region clauses that have not yet been fed into solver_i_.
CNF new_useless_input_clauses_
All U-clauses that have not yet been added to solver_i_.
int new_useless_input_clauses_level_
The level on which the clauses in new_useless_input_clauses_ have been found.
int restart_level_
The number of solver restarts that have already been performed.
int new_restart_level_
The restart level we have after we consider restart_with_cnf_.
SatSolver * solver_ctrl_ind_
The solver for generalizing counterexamples if optimization RG is endabled.
CNF prev_trans_or_initial_
Says: the current state is initial or the previous transition relation holds.
vector< int > current_to_previous_map_
A map from present-state variables to their previous-state copy.
int current_state_is_initial_
Says: the current state is initial or the previous transition relation holds.
int prev_safe_
A literal saying that the previous-state is safe.
Private Member Functions
ClauseExplorerSAT (const ClauseExplorerSAT &other)
Copy constructor.
ClauseExplorerSAT & operator= (const ClauseExplorerSAT &other)
Assignment operator.
Detailed Description
Implements the method of LearnSynthSAT in a parallelized way.
This class basically implements the same method as LearnSynthSAT. It only has a few additional methods to communicate with other threads. Whenever it finds a new clause of the winning region, it communicates this clause to all other worker-threads (via the ParallelLearner, which acts as a coordinator). Also, if it finds out that some state-input combination is not useful for the antagonist in trying to leave the winning region, it communicates a clause to all other instances of the same class. For that to work, all ClauseExplorerSAT-instances must be synchronized to a certain extend: All ClauseExplorerSAT-instances must do solver restarts simultaneously, i.e., they must all work with the same next-state copy of the winning region. This is done by coordinating and communicating solver restarts via the ParallelLearner.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.1.0
Definition at line 411 of file ParallelLearner.h.
Constructor & Destructor Documentation
ClauseExplorerSAT::ClauseExplorerSAT (size_t instance_nr, ParallelLearner & coordinator)
Constructor if optimization RG is disabled.
Parameters
instance_nr A unique instance number. It is used to bring in some asymmetry between the different ClauseExplorerSAT-instances: depending on the instance number, the instance selects a different SatSolver to use.
coordinator A reference to the coordinator. All communication to other worker-threads is done via the coordinator.
Definition at line 474 of file ParallelLearner.cpp.
References solver_ctrl_, and solver_i_.
ClauseExplorerSAT::ClauseExplorerSAT (size_t instance_nr, ParallelLearner & coordinator, const CNF & prev_trans_or_initial, const vector< int > & current_to_previous_map, int current_state_is_initial)
Constructor if optimization RG is enabled.
Parameters
instance_nr A unique instance number. It is used to bring in some asymmetry between the different ClauseExplorerSAT-instances: depending on the instance number, the instance selects a different SatSolver to use.
coordinator A reference to the coordinator. All communication to other worker-threads is done via the coordinator.
prev_trans_or_initial A CNF that says: the current state is initial or the previous transition relation holds. This is an important building block for the CNF to generalize counterexamples if optimization RG is enabled. This CNF is computed only once by the ParallelLearner and passed to all ClauseExplorerSAT instances.
current_to_previous_map A map from present-state variables to their previous-state copy. This map is computed only once by the ParallelLearner and passed to all ClauseExplorerSAT instances.
current_state_is_initial A literal that is true if the current state is initial and false otherwise. The clauses assigning the literal are part of prev_trans_or_initial.
Definition at line 513 of file ParallelLearner.cpp.
References solver_ctrl_, solver_ctrl_ind_, and solver_i_.
ClauseExplorerSAT::~ClauseExplorerSAT () [virtual]
Destructor.
Definition at line 569 of file ParallelLearner.cpp.
References solver_ctrl_, solver_ctrl_ind_, and solver_i_.
ClauseExplorerSAT::ClauseExplorerSAT (const ClauseExplorerSAT & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void ClauseExplorerSAT::considerNewInfoFromOthers () [protected]
Considers new information discovered by other threads in the solvers.
New information includes:
A new CNF for the solver to compute counterexamples (we need to do a restart). This info came from notifyRestart().
New clauses refining the winning region (coming from notifyNewWinRegClause()).
New clauses defining useless state-input combinations (coming from notifyNewUselessInputClause()).
Definition at line 775 of file ParallelLearner.cpp.
References CNF::clear(), CNF::getNrOfClauses(), SatSolver::incAddCNF(), new_foreign_win_reg_clauses_for_solver_i_, new_info_lock_, new_restart_level_, new_useless_input_clauses_, new_useless_input_clauses_level_, new_win_reg_clauses_for_solver_ctrl_, new_win_reg_clauses_for_solver_i_, LearnStatisticsSAT::notifyRestart(), precise_, presentToPrevious(), restart_level_, restart_with_cnf_, solver_ctrl_, solver_ctrl_ind_, solver_i_, SatSolver::startIncrementalSession(), statistics_, CNF::swapPresentToNext(), use_ind_, and vars_to_keep_.
Referenced by exploreClauses().
void ClauseExplorerSAT::exploreClauses ()
The work-horse of this class.
This method computes clauses refining the winning region, just like LearnSynthSAT. It only has a few additional methods to communicate with other threads. Whenever it finds a new clause of the winning region, it communicates it to all other worker-threads (via the ParallelLearner, which acts as a coordinator). Also, if it finds out that some state-input combination is not useful for the antagonist in trying to leave the winning region, it communicates a clause to all other instances of the same class. In every iteration, it also considers all new incoming clauses found by others. All ClauseExplorerSAT-instances must be synchronized to a certain extend: All ClauseExplorerSAT-instances must do solver restarts simultaneously, i.e., they must all work with the same next-state copy of the winning region. This is done by coordinating and communicating solver restarts via the ParallelLearner.
Definition at line 580 of file ParallelLearner.cpp.
References considerNewInfoFromOthers(), Utils::containsInit(), coordinator_, VarInfo::CTRL, current_state_is_initial_, EXPL, Utils::extract(), AIG2CNF::getNextSafeStates(), AIG2CNF::getNextUnsafeStates(), AIG2CNF::getSafeStates(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), SatSolver::incAddCNF(), SatSolver::incAddCube(), SatSolver::incAddNegCubeAsClause(), SatSolver::incAddUnitClause(), SatSolver::incIsSat(), SatSolver::incIsSatModelOrCore(), SatSolver::incPop(), SatSolver::incPush(), VarInfo::INPUT, VarManager::instance(), AIG2CNF::instance(), instance_nr_, L_DBG, MASSERT, LearnStatisticsSAT::notifyAfterCheckCandidateFailed(), LearnStatisticsSAT::notifyAfterCheckCandidateFound(), LearnStatisticsSAT::notifyAfterComputeCandidate(), LearnStatisticsSAT::notifyAfterRefine(), LearnStatisticsSAT::notifyBeforeCheckCandidate(), LearnStatisticsSAT::notifyBeforeComputeCandidate(), LearnStatisticsSAT::notifyBeforeRefine(), ParallelLearner::notifyNewCounterexample(), ParallelLearner::notifyNewUselessInputClause(), ParallelLearner::notifyNewWinRegClause(), precise_, VarInfo::PRES_STATE, presentToPrevious(), prev_safe_, prev_trans_or_initial_, Utils::randomize(), REALIZABLE, Utils::remove(), restart_level_, ParallelLearner::result_, solver_ctrl_, solver_ctrl_ind_, solver_i_, SatSolver::startIncrementalSession(), statistics_, Utils::swapPresentToNext(), ParallelLearner::triggerExplorerRestart(), UNKNOWN, UNREALIZABLE, use_ind_, vars_to_keep_, and waitUntilOngoingRestartDone().
Referenced by ParallelLearner::run().
const LearnStatisticsSAT & ClauseExplorerSAT::getStatistics () const
Returns the statistics and performance measures computed by this object.
It is used by the ParallelLearner to merge the statistics of the different workers.
Returns
The statistics and performance measures computed by this object.
Definition at line 769 of file ParallelLearner.cpp.
References statistics_.
void ClauseExplorerSAT::notifyAfterNewInfo ()
The method must be called after new information is passed to this object.
See notifyBeforeNewInfo() for an explanation.
Definition at line 726 of file ParallelLearner.cpp.
References new_info_lock_.
void ClauseExplorerSAT::notifyBeforeNewInfo ()
The method must be called before new information is passed to this object.
After the new information has been set, notifyAfterNewInfo() must be called. This way the coordinator (the ParallelLearner) can inform all ClauseExplorerSAT-instances simultaneously: It calls notifyBeforeNewInfo() on all instances, then communicates the new information to all instances, then calls notifyAfterNewInfo() on all instances. This way, no thread can work with the new information before the others got it. This method must be used for notifyNewWinRegClause(), notifyNewUselessInputClause(), and notifyNewUselessInputClause(). If this method finds out that the specification is realizable or unrealizable, it sets the flag ParallelLearner::result_ accordingly. It also polls this flag regularly. If it has been set by some other thread, it quits.
Definition at line 720 of file ParallelLearner.cpp.
References new_info_lock_.
void ClauseExplorerSAT::notifyNewUselessInputClause (const vector< int > & clause, int level)
Notifies this ClauseExplorerSAT-instance that a new U-clause is available.
A U-clause states that a certain state-input is useless for the antagonist in trying to leave the winning region (see LearnSynthSAT for details). If one ClauseExplorerSAT discovers such a clause, it communicates it to all other ClauseExplorerSAT-instances such that they can also benefit from it and do not need to re-discover the same fact again.
Note
Be sure to call notifyBeforeNewInfo() before this method and notifyAfterNewInfo() after calling this method.
Parameters
clause A new U-clause stating that a certain state-input is useless for the antagonist in trying to leave the winning region (see LearnSynthSAT for details).
level The restart level (the number of solver restarts that have already been performed. This information allows this instance to decide whether or not this clause is useful for her (or if it is already out-dated).
Definition at line 747 of file ParallelLearner.cpp.
References CNF::addClause(), CNF::clear(), new_useless_input_clauses_, and new_useless_input_clauses_level_.
void ClauseExplorerSAT::notifyNewWinRegClause (const vector< int > & clause, int src)
Notifies this worker about a new winning region clause.
Note
Be sure to call notifyBeforeNewInfo() before this method and notifyAfterNewInfo() after calling this method.
Parameters
clause The new clause that has been discovered.
src An integer number defining which kind of worker-thread discovered the clause. For performance reasons, this method distinguishes between clauses discovered by ClauseExplorerSAT-instances, and clauses discovered by other kinds of workers.
Definition at line 732 of file ParallelLearner.cpp.
References CNF::addClause(), EXPL, new_foreign_win_reg_clauses_for_solver_i_, new_win_reg_clauses_for_solver_ctrl_, and new_win_reg_clauses_for_solver_i_.
void ClauseExplorerSAT::notifyRestart (const CNF & restart_with_cnf)
Notifies this ClauseExplorerSAT-instance that it should restart its solver.
The ClauseExplorerSAT update their next-state copy of the winning region only in a lazy manner. This allows them to use incremental SAT-solving more effectively. See LearnSynthSAT for a description. If no more solutions exists with one next-state copy of the winning region, it must be updated to the newest version. This method tells this instance that such a newer version should be used.
It is absolutely important that all ClauseExplorerSAT instances work with the same next-state copy of the winning region. Otherwise, they could not exchange U-clauses (or rather, the U-clause discovered by one thread would not make sense for the other).
See Also
notifyNewUselessInputClause()
ParallelLearner::triggerExplorerRestart()
Parameters
restart_with_cnf The CNF for W & T & !W', where W is the current over-approximation of the winning region.
Definition at line 759 of file ParallelLearner.cpp.
References CNF::clear(), new_foreign_win_reg_clauses_for_solver_i_, new_restart_level_, new_win_reg_clauses_for_solver_i_, and restart_with_cnf_.
ClauseExplorerSAT& ClauseExplorerSAT::operator= (const ClauseExplorerSAT & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
int ClauseExplorerSAT::presentToPrevious (int literal) const [protected]
Returns the previous-state copy of a literal.
Parameters
literal The literal to transform.
Returns
The previous-state copy of a literal.
Definition at line 843 of file ParallelLearner.cpp.
References current_to_previous_map_.
Referenced by considerNewInfoFromOthers(), exploreClauses(), and presentToPrevious().
void ClauseExplorerSAT::presentToPrevious (vector< int > & cube_or_clause) const [protected]
Computes the previous-state copy of a cube or clause.
Parameters
cube_or_clause A cube or clause (in form of a vector of literals) over the present state variables. This vector is overwritten by the corresponding cube of clause over the previous-state literals (i.e., all literals are replaced by their previous-state copy).
Definition at line 853 of file ParallelLearner.cpp.
References presentToPrevious().
void ClauseExplorerSAT::presentToPrevious (CNF & cnf) const [protected]
Computes the previous-state copy of a CNF.
Parameters
cnf A CNF formula over the present state variables. This CNF is overwritten by the corresponding CNF over the previous-state literals (i.e., all literals are replaced by their previous-state copy).
Definition at line 860 of file ParallelLearner.cpp.
References CNF::addClause(), CNF::clear(), CNF::getClauses(), and presentToPrevious().
bool ClauseExplorerSAT::waitUntilOngoingRestartDone () [protected]
Checks if some other thread is computing a restart. If yes: waits until it is done.
This is just a performance optimization. Before we trigger a restart, we check if someone else is already working on a restart (computing a restart point takes some time because we also compress the CNF of the winning region for performance reasons). If so, we wait until it is done. Otherwise, we would do two very similar restarts one after the other. This would be correct, but more inefficient.
Returns
True if a restart is available. False otherwise.
Definition at line 829 of file ParallelLearner.cpp.
References coordinator_, CNF::getNrOfClauses(), new_info_lock_, restart_with_cnf_, and ParallelLearner::var_man_lock_.
Referenced by exploreClauses().
Member Data Documentation
ParallelLearner& ClauseExplorerSAT::coordinator_ [protected]
A reference to the coordinator.
All communication to other worker-threads is done via the coordinator.
Definition at line 644 of file ParallelLearner.h.
Referenced by exploreClauses(), and waitUntilOngoingRestartDone().
int ClauseExplorerSAT::current_state_is_initial_ [protected]
Says: the current state is initial or the previous transition relation holds.
This CNF expresses that the current state is initial or the previous-state copy of the transition relation holds. This is an important building block for the CNF to generalize counterexamples if optimization RG is enabled. If optimization RG is disabled, then this field is meaningless.
Definition at line 797 of file ParallelLearner.h.
Referenced by exploreClauses().
vector<int> ClauseExplorerSAT::current_to_previous_map_ [protected]
A map from present-state variables to their previous-state copy.
If optimization RG is disabled, then this CNF is empty.
Definition at line 786 of file ParallelLearner.h.
Referenced by presentToPrevious().
size_t ClauseExplorerSAT::instance_nr_ [protected]
A unique instance number.
It is used to bring in some asymmetry between the different ClauseExplorerSAT-instances: depending on the instance number, the instance selects a different SatSolver to use. Furthermore, it is used for debugging to print more meaningful messages (WHO is printing a message).
Definition at line 623 of file ParallelLearner.h.
Referenced by exploreClauses().
CNF ClauseExplorerSAT::new_foreign_win_reg_clauses_for_solver_i_ [protected]
All foreign winning region clauses that have not yet been fed into solver_i_.
This CNF contains only clauses that have not been discovered by ClauseExplorerSAT-threads. Clauses discovered by ClauseExplorerSAT-threads are stored in new_win_reg_clauses_for_solver_i_. Clauses discovered by other threads are handled in a special way for performance reasons. They are not added immediately because this could make the solver imprecise, which prevents it from terminating. Foreign clauses are only added if the solver_i_ is already imprecise (precise_ is false). Otherwise, other threads could spam ClauseExplorerSAT-threads with clauses that prevent the ClauseExplorerSAT-threads from being precise long enough to conclude realizability. (Acutally I don't know if this is really an issue, but the optimization is implemented just in case).
Definition at line 732 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), notifyNewWinRegClause(), and notifyRestart().
mutex ClauseExplorerSAT::new_info_lock_ [protected]
A lock to protect many fields from race conditions.
This lock protects the fields
restart_with_cnf_
new_win_reg_clauses_for_solver_i_
new_win_reg_clauses_for_solver_ctrl_
new_foreign_win_reg_clauses_for_solver_i_
new_useless_input_clauses_
new_useless_input_clauses_level_
From race conditions. These fields are modified by other threads when new information comes in. They are read by this thread when this new information is taken into account.
Todo
Todo A more fine-grained locking could improve the performance.
Definition at line 689 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), notifyAfterNewInfo(), notifyBeforeNewInfo(), and waitUntilOngoingRestartDone().
int ClauseExplorerSAT::new_restart_level_ [protected]
The restart level we have after we consider restart_with_cnf_.
The thing is: this thread can skip a restart level completely if it does not get scheduled often. In this case, we have to increase our restart level by more than one when we actually do the restart (consider restart_with_cnf_). The new restart level is tracked by this field.
Definition at line 764 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), and notifyRestart().
CNF ClauseExplorerSAT::new_useless_input_clauses_ [protected]
All U-clauses that have not yet been added to solver_i_.
A U-clause states that a certain state-input is useless for the antagonist in trying to leave the winning region (see LearnSynthSAT for details).
Definition at line 740 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), and notifyNewUselessInputClause().
int ClauseExplorerSAT::new_useless_input_clauses_level_ [protected]
The level on which the clauses in new_useless_input_clauses_ have been found.
'Level' means the number of solver restarts that have already been performed. new_useless_input_clauses_ are only considered if their level matches the restart_level_ of this object.
Definition at line 749 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), and notifyNewUselessInputClause().
CNF ClauseExplorerSAT::new_win_reg_clauses_for_solver_ctrl_ [protected]
All new winning region clauses that have not yet been fed into solver_ctrl_.
We do not distinguish clauses discovered by ClauseExplorerSAT-threads and clauses discovered by other threads. We also add all clauses to solver_ctrl_ immediately.
Definition at line 716 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), and notifyNewWinRegClause().
CNF ClauseExplorerSAT::new_win_reg_clauses_for_solver_i_ [protected]
All new winning region clauses that have not yet been fed into solver_i_.
This CNF contains only clauses that have been discovered by ClauseExplorerSAT-threads. Clauses discovered by other threads are stored in new_foreign_win_reg_clauses_for_solver_i_ because they are treaded specially (for performance reasons).
Definition at line 708 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), notifyNewWinRegClause(), and notifyRestart().
bool ClauseExplorerSAT::precise_ [protected]
A flag indicating if the next-state copy of the winning region is accurate.
See Also
LearnSynthSAT
Definition at line 651 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), and exploreClauses().
int ClauseExplorerSAT::prev_safe_ [protected]
A literal saying that the previous-state is safe.
We store this literal here and do not read it out of the VarManager again and again to avoid a concurrency issue. The VarManager is sometimes modified (new temporary variables are created). This does not affect the literal defining safe states. However, we do not want to lock reading-accesses to the variable manager and we do not want to read out the variable manager in an inconsistent state. Hence, we read it out once and store it. If optimization RG is disabled, then this field is meaningless.
Definition at line 809 of file ParallelLearner.h.
Referenced by exploreClauses().
CNF ClauseExplorerSAT::prev_trans_or_initial_ [protected]
Says: the current state is initial or the previous transition relation holds.
This CNF expresses that the current state is initial or the previous-state copy of the transition relation holds. This is an important building block for the CNF to generalize counterexamples if optimization RG is enabled. If optimization RG is disabled, then this CNF is empty.
Definition at line 779 of file ParallelLearner.h.
Referenced by exploreClauses().
int ClauseExplorerSAT::restart_level_ [protected]
The number of solver restarts that have already been performed.
Definition at line 754 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), and exploreClauses().
CNF ClauseExplorerSAT::restart_with_cnf_ [protected]
A CNF to restart solver_i_ with.
This CNF contains F & T & !F', where F is the current over-approximation of the winning region if a restart of solver_i_ needs to be done. If no restart needs to be done, then this CNF is empty (i.e., true).
Definition at line 698 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), notifyRestart(), and waitUntilOngoingRestartDone().
SatSolver* ClauseExplorerSAT::solver_ctrl_ [protected]
The solver for checking counterexample-candidates.
It is also used to generalize counterexamples if optimization RG is disabled.
Definition at line 663 of file ParallelLearner.h.
Referenced by ClauseExplorerSAT(), considerNewInfoFromOthers(), exploreClauses(), and ~ClauseExplorerSAT().
SatSolver* ClauseExplorerSAT::solver_ctrl_ind_ [protected]
The solver for generalizing counterexamples if optimization RG is endabled.
Definition at line 769 of file ParallelLearner.h.
Referenced by ClauseExplorerSAT(), considerNewInfoFromOthers(), exploreClauses(), and ~ClauseExplorerSAT().
SatSolver* ClauseExplorerSAT::solver_i_ [protected]
The solver for computing counterexample-candidates.
Definition at line 656 of file ParallelLearner.h.
Referenced by ClauseExplorerSAT(), considerNewInfoFromOthers(), exploreClauses(), and ~ClauseExplorerSAT().
LearnStatisticsSAT ClauseExplorerSAT::statistics_ [protected]
Stores and maintains statistics and performance measures.
Basically, this is a merge of the statistics from all worker-threads.
Definition at line 637 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), exploreClauses(), and getStatistics().
bool ClauseExplorerSAT::use_ind_ [protected]
A flag indicating if optimization RG should be used.
See LearnSynthQBFInd for an explanation.
Definition at line 630 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), and exploreClauses().
vector<int> ClauseExplorerSAT::vars_to_keep_ [protected]
A set of variables the solver should not optimize by the SAT-solver.
These are all variables except for temporary ones (type VarInfo::TMP).
Definition at line 670 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), and exploreClauses().
The documentation for this class was generated from the following files:
src/ParallelLearner.h
src/ParallelLearner.cpp