CNF Class Reference
Represents a propositional formula in Conjunctive Normal Form.
#include <CNF.h>
Public Types
typedef list< vector< int >
*
 >::const_iterator ClauseConstIter
A type for a const-iterator over the clauses.
typedef list< vector< int >
*
 >::iterator ClauseIter
A type for an iterator over the clauses.
Public Member Functions
CNF ()
Constructor.
CNF (const string &filename)
Constructor from DIMACS file.
CNF (const CNF &other)
Copy constructor.
virtual CNF & operator= (const CNF &other)
Assignment operator.
virtual ~CNF ()
Destructor.
void clear ()
Clears the CNF, i.e., sets the CNF back to TRUE (the empty set of clauses).
void addClause (const vector< int > &clause)
Adds a new clause to the CNF.
void addNegClauseAsCube (const vector< int > &clause)
Conjuncts the CNF with the negation of a given clause (which is a cube then).
void addCube (const vector< int > &cube)
Conjuncts the CNF with a given cube.
void addNegCubeAsClause (const vector< int > &cube)
Conjuncts the CNF with the negation of a given cube (which is a clause then).
bool addClauseAndSimplify (const vector< int > &clause)
Adds a new clause to the CNF, and then simplifies the CNF.
void add1LitClause (int lit1)
Adds a unit clause to the CNF.
void add2LitClause (int lit1, int lit2)
Adds a clause consisting of two literal to the CNF.
void add3LitClause (int lit1, int lit2, int lit3)
Adds a clause consisting of three literal to the CNF.
void add4LitClause (int lit1, int lit2, int lit3, int lit4)
Adds a clause consisting of four literal to the CNF.
vector< int > removeSmallest ()
Removes and returns the smallest clause (least number of literals).
vector< int > removeSomeClause ()
Removes and returns some clause.
void addCNF (const CNF &cnf)
Conjuncts the CNF with another CNF.
void swapPresentToNext ()
Replaces all current-state variables in the CNF with their next-state copy.
void renameTmps ()
Renames all temporary variables that occur in this CNF with fresh ones.
void negate ()
Negates this CNF.
void swapWith (list< vector< int > > &clauses)
Swaps the content of this CNF with the passed set of clauses.
void swapWith (CNF &other)
Swaps the content of this CNF with the passed CNF.
size_t getNrOfClauses () const
Returns the number of clauses in this CNF.
size_t getNrOfLits () const
Returns the sum of the sizes of all clauses in the CNF.
string toString () const
Returns a string representation of the CNF in DIMACS format.
void saveToFile (const string &filename) const
Stores the CNF into a file in DIMACS format.
const list< vector< int > > & getClauses () const
Returns the clauses of the CNF as list of vectors.
void simplify ()
Simplifies the CNF syntactically.
void removeDuplicates ()
Removes all duplicates from the CNF.
bool isSatBy (const vector< int > &cube) const
Checks if the CNF is satisfied by a certain variable assignment.
void setVarValue (int var, bool value)
Replaces a variable in the CNF by true or false.
void doPureAndUnit (const vector< int > &keep)
Simplifies the CNF by propagating unit clauses and pure literals until fixpoint.
void renameVars (const vector< int > &rename_map)
Renames all variables in a CNF.
bool contains (int var) const
Returns true if this CNF contains a certain variable, and false otherwise.
vector< int > getVars () const
Returns the set of all variables that occur in the CNF.
void appendVarsTo (set< int > &var_set) const
Adds all variables that occur in the CNF to the given set.
bool operator== (const CNF &other) const
Compares two CNFs syntactically.
Protected Attributes
list< vector< int > > clauses_
The CNF represented as list of clauses (in turn being vectors of literals).
Detailed Description
Represents a propositional formula in Conjunctive Normal Form.
This class also provides many methods for manipulating CNFs conveniently.
A Conjunctive Normal Form formula is a conjunction of clauses. Each clause is a disjunction of literals. A literal is a Boolean variable or its negation. Internally, every literal is represented as integer number (0 is not used). Every clause is a vector of literals. A CNF is a list of clauses. This representation was chosen for pragmatic reasons: we often manipulate clauses, so we chose a simple representation which can be manipulated efficiently. The CNF is a list (and no vector) of clauses because we often append clauses, which can be inefficient with vectors. Furthermore, we usually do not need random access to individual clauses.
Other options would be (a) to sort the literals in the clauses, (b) represent clauses as sets, (c) represent a CNF as set of sets of integers, etc. So far, we considered these options an over-kill because the time for manipulating CNFs is negligable compared to SAT- or QBF-solving time.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 59 of file CNF.h.
Member Typedef Documentation
list< vector< int > >::const_iterator CNF::ClauseConstIter
A type for a const-iterator over the clauses.
Definition at line 410 of file CNF.h.
list< vector< int > >::iterator CNF::ClauseIter
A type for an iterator over the clauses.
Definition at line 416 of file CNF.h.
Constructor & Destructor Documentation
CNF::CNF ()
Constructor.
After construction, the CNF represents the empty set of clauses, i.e., the formula TRUE.
Definition at line 39 of file CNF.cpp.
CNF::CNF (const string & filename)
Constructor from DIMACS file.
Parameters
filename The name (including path and extension) of the DIMACS file containing the definition of the CNF.
Definition at line 45 of file CNF.cpp.
References clauses_, VarManager::instance(), and MASSERT.
CNF::CNF (const CNF & other)
Copy constructor.
Makes a (deep) copy of the CNF.
Parameters
other The source for creating the (deep) copy.
Definition at line 92 of file CNF.cpp.
CNF::~CNF () [virtual]
Destructor.
Definition at line 105 of file CNF.cpp.
Member Function Documentation
void CNF::add1LitClause (int lit1)
Adds a unit clause to the CNF.
Parameters
lit1 The (one and only) literal of the unit clause to add.
Definition at line 169 of file CNF.cpp.
References clauses_.
Referenced by addCube(), addNegClauseAsCube(), TemplateSynth::check(), TemplExplorer::check(), doPureAndUnit(), TemplateSynth::findWinRegANDNetwork(), TemplateSynth::findWinRegCNFTempl(), TemplExplorer::findWinRegCNFTempl(), AIG2CNF::initFromAig(), UnivExpander::initSolverCExp(), LingelingApi::isSatModelOrCore(), PicoSatApi::isSatModelOrCore(), MiniSatApi::isSatModelOrCore(), and Utils::negateViaAig().
void CNF::add2LitClause (int lit1, int lit2)
Adds a clause consisting of two literal to the CNF.
Parameters
lit1 The first literal of the clause to add.
lit2 The second literal of the clause to add.
Definition at line 177 of file CNF.cpp.
References clauses_.
Referenced by LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionOnePool(), TemplateSynth::findWinRegANDNetwork(), TemplateSynth::findWinRegCNFTempl(), TemplExplorer::findWinRegCNFTempl(), AIG2CNF::initFromAig(), UnivExpander::initSolverCExp(), OrigUnivExpander::initSolverIData(), LearnSynthQBFInd::LearnSynthQBFInd(), LearnSynthSAT::LearnSynthSAT(), LearningImplExtractor::makeEq2(), negate(), Utils::negateViaAig(), PrevStateInfo::PrevStateInfo(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), and ParExtractorWorker::runSAT().
void CNF::add3LitClause (int lit1, int lit2, int lit3)
Adds a clause consisting of three literal to the CNF.
Parameters
lit1 The first literal of the clause to add.
lit2 The second literal of the clause to add.
lit3 The third literal of the clause to add.
Definition at line 186 of file CNF.cpp.
References clauses_.
Referenced by AIG2CNF::initFromAig(), UnivExpander::initSolverCExp(), OrigUnivExpander::initSolverIData(), LearnSynthQBFInd::LearnSynthQBFInd(), LearnSynthSAT::LearnSynthSAT(), LearningImplExtractor::makeEq2(), Utils::negateViaAig(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), and ParExtractorWorker::runSAT().
void CNF::add4LitClause (int lit1, int lit2, int lit3, int lit4)
Adds a clause consisting of four literal to the CNF.
Parameters
lit1 The first literal of the clause to add.
lit2 The second literal of the clause to add.
lit3 The third literal of the clause to add.
lit4 The fourth literal of the clause to add.
Definition at line 196 of file CNF.cpp.
References clauses_.
Referenced by TemplateSynth::findWinRegANDNetwork(), TemplateSynth::findWinRegCNFTempl(), TemplExplorer::findWinRegCNFTempl(), and PrevStateInfo::PrevStateInfo().
void CNF::addClause (const vector< int > & clause)
Adds a new clause to the CNF.
Parameters
clause The new clause to add.
Definition at line 117 of file CNF.cpp.
References clauses_.
Referenced by IFM13Synth::addBlockedState(), IFM13Explorer::addBlockedState(), Utils::compressNextStateCNF(), Utils::compressStateCNF(), LearnSynthQBF::computeAllBlockingClauses(), LearnSynthQBFInd::computeAllBlockingClauses(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), LearnSynthSAT::computeWinningRegionPlainDep2(), TemplateSynth::findWinRegANDNetwork(), TemplateSynth::findWinRegCNFTempl(), TemplExplorer::findWinRegCNFTempl(), AIG2CNF::initFromAig(), LearnSynthQBFInd::LearnSynthQBFInd(), LearnSynthSAT::LearnSynthSAT(), ParExtractorWorker::makeEq(), LearningImplExtractor::makeEq(), LearningImplExtractor::makeEq2(), ClauseMinimizerQBF::minimizeClausesNoInc(), ClauseExplorerSAT::notifyNewUselessInputClause(), ParallelLearner::notifyNewWinRegClause(), ClauseExplorerSAT::notifyNewWinRegClause(), CounterGenSAT::notifyNewWinRegClause(), ClauseMinimizerQBF::notifyNewWinRegClause(), IFM13Explorer::notifyNewWinRegClause(), TemplExplorer::notifyNewWinRegClause(), PrevStateInfo::presentToPrevious(), LearnSynthSAT::presentToPrevious(), LearnSynthQBFInd::presentToPrevious(), PrevStateInfo::PrevStateInfo(), LearnSynthQBFInd::reduceExistingClauses(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), and ParExtractorWorker::runSAT().
bool CNF::addClauseAndSimplify (const vector< int > & clause)
Adds a new clause to the CNF, and then simplifies the CNF.
The only simplification we do is to remove all clauses which form a superset of the newly added clause.
Parameters
clause The new clause to add.
Returns
True if some clauses were removed due to simplification, false otherwise.
Definition at line 146 of file CNF.cpp.
References clauses_, and Utils::isSubset().
Referenced by IFM13Synth::addBlockedTransition(), IFM13Explorer::addBlockedTransition(), IFM13Synth::addLose(), IFM13Explorer::addLose(), LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBF::computeWinningRegionOneSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), ParallelLearner::notifyNewWinRegClause(), ClauseExplorerSAT::notifyNewWinRegClause(), LearnSynthQBFInc::reduceExistingClauses(), LearnSynthQBF::reduceExistingClauses(), and LearnSynthQBFInd::reduceExistingClauses().
void CNF::addCNF (const CNF & cnf)
Conjuncts the CNF with another CNF.
That is, this method appends all clauses of the other CNF to this one.
Parameters
cnf The CNF that shall be conjuncted to this CNF.
Definition at line 230 of file CNF.cpp.
References clauses_.
Referenced by TemplateSynth::check(), TemplExplorer::check(), LearnSynthQBF::computeCounterexampleSAT(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRecy(), IFM13Explorer::considerNewInfoFromOthers(), IFM13Synth::debugCheckInvariants(), LearnSynthSAT::debugCheckWinReg(), Utils::debugCheckWinReg(), LearnSynthQBFInd::debugCheckWinRegReach(), TemplExplorer::findWinRegCNFTempl(), IFM13Explorer::IFM13Explorer(), IFM13Synth::IFM13Synth(), LearnSynthQBFInd::LearnSynthQBFInd(), ParExtractorWorker::makeEq(), LearningImplExtractor::makeEq(), ClauseMinimizerQBF::minimizeClausesNoInc(), LearnSynthQBFInc::recomputeCheckCNF(), LearnSynthQBF::recomputeCheckCNF(), LearnSynthQBFInd::recomputeCheckCNF(), LearnSynthQBFInc::recomputeGenCNF(), LearnSynthQBF::recomputeGenCNF(), LearnSynthQBFInd::recomputeGenCNF(), QBFCertImplExtractor::run(), ParallelLearner::run(), LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), LearningImplExtractor::runLearningQBF(), LearningImplExtractor::runLearningQBFInc(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), TemplateSynth::syntQBF(), TemplExplorer::syntQBF(), TemplateSynth::syntSAT(), and TemplExplorer::syntSAT().
void CNF::addCube (const vector< int > & cube)
Conjuncts the CNF with a given cube.
This means: every literal of the cube is added as a unit clause to the CNF. For instance, if the cube [2, -4, 8] is passed as argument, then this method adds the three unit clauses [2], [-4], [8] to the CNF.
Parameters
cube The new cube to add.
Definition at line 130 of file CNF.cpp.
References add1LitClause().
Referenced by DepQBFApi::debugCheckBloqqerModel(), LearnSynthQBF::generalizeCounterexample(), LearnSynthQBFInd::generalizeCounterexample(), and LearningImplExtractor::runLearningQBF().
void CNF::addNegClauseAsCube (const vector< int > & clause)
Conjuncts the CNF with the negation of a given clause (which is a cube then).
For instance, if the clause [2, -4, 8] is passed as argument, then this method adds the the three unit clauses [-2], [4], [-8] to the CNF.
Parameters
clause The clause which's negation should be conjuncted to the CNF.
Definition at line 123 of file CNF.cpp.
References add1LitClause().
Referenced by ClauseMinimizerQBF::minimizeClausesNoInc(), LearnSynthQBF::reduceExistingClauses(), and LearnSynthQBFInd::reduceExistingClauses().
void CNF::addNegCubeAsClause (const vector< int > & cube)
Conjuncts the CNF with the negation of a given cube (which is a clause then).
For instance, if the cube [2, -4, 8] is passed as argument, then this method adds the clauses [-2, 4, -8] to the CNF.
Parameters
cube The cube which's negation should be conjuncted to the CNF.
Definition at line 137 of file CNF.cpp.
References clauses_.
Referenced by Utils::compressNextStateCNF(), Utils::compressStateCNF(), LearnSynthQBF::generalizeCounterexample(), LearnSynthQBFInd::generalizeCounterexample(), Utils::negateStateCNF(), LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), LearningImplExtractor::runLearningQBF(), LearningImplExtractor::runLearningQBFInc(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void CNF::appendVarsTo (set< int > & var_set) const
Adds all variables that occur in the CNF to the given set.
Parameters
var_set The set to which all variables in the CNF should be appended to.
Definition at line 571 of file CNF.cpp.
References clauses_.
Referenced by TemplateSynth::exclude(), TemplExplorer::exclude(), getVars(), Utils::negateViaAig(), renameTmps(), OrigUnivExpander::univExpand(), and UnivExpander::univExpand().
void CNF::clear ()
Clears the CNF, i.e., sets the CNF back to TRUE (the empty set of clauses).
Definition at line 111 of file CNF.cpp.
References clauses_.
Referenced by UnivExpander::cleanup(), AIG2CNF::clear(), Utils::compressNextStateCNF(), Utils::compressStateCNF(), LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), LearnSynthQBF::computeWinningRegionOneSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::considerNewInfoFromOthers(), CounterGenSAT::considerNewInfoFromOthers(), IFM13Explorer::considerNewInfoFromOthers(), IFM13Synth::debugCheckInvariants(), LearnSynthSAT::debugCheckWinReg(), Utils::debugCheckWinReg(), LearnSynthQBFInd::debugCheckWinRegReach(), UnivExpander::initSolverCExp(), ClauseMinimizerQBF::minimizeClausesInc(), Utils::negateStateCNF(), Utils::negateViaAig(), ClauseExplorerSAT::notifyNewUselessInputClause(), ClauseExplorerSAT::notifyRestart(), PrevStateInfo::presentToPrevious(), LearnSynthSAT::presentToPrevious(), LearnSynthQBFInd::presentToPrevious(), LearnSynthQBFInc::recomputeCheckCNF(), LearnSynthQBF::recomputeCheckCNF(), LearnSynthQBFInd::recomputeCheckCNF(), LearnSynthQBFInc::recomputeGenCNF(), LearnSynthQBF::recomputeGenCNF(), LearnSynthQBFInd::recomputeGenCNF(), ParallelLearner::run(), and ParExtractorQBFWorker::runQBF().
bool CNF::contains (int var) const
Returns true if this CNF contains a certain variable, and false otherwise.
Parameters
var The variable to check for.
Returns
True if this CNF contains var, and false otherwise.
Definition at line 544 of file CNF.cpp.
References clauses_.
Referenced by LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), and ParExtractorWorker::runSATDep().
void CNF::doPureAndUnit (const vector< int > & keep)
Simplifies the CNF by propagating unit clauses and pure literals until fixpoint.
Todo
Todo So far, only unit clause propagation has been implemented. Pure literals still need to be done.
Parameters
keep A list of CNF variables. All CNF variables contained in the list will be kept assigned by the CNF (in a unit clause).
Definition at line 469 of file CNF.cpp.
References add1LitClause(), and clauses_.
const list< vector< int > > & CNF::getClauses () const
Returns the clauses of the CNF as list of vectors.
Returns
The clauses of the CNF as list of vectors.
Definition at line 360 of file CNF.cpp.
References clauses_.
Referenced by ParExtractorWorker::addToStandAloneAiger(), LearningImplExtractor::addToStandAloneAiger(), ParExtractorWorker::addToStandAloneAiger2(), Utils::compressStateCNF(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRCExp(), ClauseExplorerSAT::considerNewInfoFromOthers(), UnivExpander::extrExp(), TemplExplorer::findWinRegCNFTempl(), LingelingApi::incAddCNF(), PicoSatApi::incAddCNF(), MiniSatApi::incAddCNF(), DepQBFApi::incAddCNF(), DepQBFApi::initBloqqer(), DepQBFApi::initDepQBF(), UnivExpander::initSolverCExp(), OrigUnivExpander::initSolverIData(), UnivExpander::initSolverIData(), RareqsApi::isSat(), PicoSatApi::isSat(), LingelingApi::isSat(), MiniSatApi::isSat(), RareqsApi::isSatModel(), LingelingApi::isSatModelOrCore(), PicoSatApi::isSatModelOrCore(), MiniSatApi::isSatModelOrCore(), LearnSynthQBFInd::LearnSynthQBFInd(), LearnSynthSAT::LearnSynthSAT(), ParExtractorWorker::makeEq(), LearningImplExtractor::makeEq(), LearningImplExtractor::makeEq2(), Utils::negateViaAig(), PrevStateInfo::presentToPrevious(), LearnSynthSAT::presentToPrevious(), LearnSynthQBFInd::presentToPrevious(), PrevStateInfo::PrevStateInfo(), IFM13Synth::propagateBlockedStates(), IFM13Explorer::propagateBlockedStates(), LearnSynthQBFInc::reduceExistingClauses(), LearnSynthQBF::reduceExistingClauses(), LearnSynthQBFInd::reduceExistingClauses(), OrigUnivExpander::resetSolverCExp(), OrigUnivExpander::resetSolverIExp(), UnivExpander::resetSolverIExp(), OrigUnivExpander::univExpand(), and UnivExpander::univExpand().
size_t CNF::getNrOfClauses () const
Returns the number of clauses in this CNF.
Returns
The number of clauses in this CNF.
Definition at line 306 of file CNF.cpp.
References clauses_.
Referenced by Utils::compressNextStateCNF(), Utils::compressStateCNF(), LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), LearnSynthQBF::computeWinningRegionOneSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRCExp(), ClauseExplorerSAT::considerNewInfoFromOthers(), CounterGenSAT::considerNewInfoFromOthers(), ExtQBFSolver::dumpQBF(), TemplExplorer::findWinRegCNFTempl(), DepQBFApi::initBloqqer(), ClauseMinimizerQBF::minimizeClausesInc(), ClauseMinimizerQBF::minimizeClausesNoInc(), LearnSynthQBFInc::reduceExistingClauses(), LearnSynthQBF::reduceExistingClauses(), LearnSynthQBFInd::reduceExistingClauses(), and OrigUnivExpander::resetSolverIExp().
size_t CNF::getNrOfLits () const
Returns the sum of the sizes of all clauses in the CNF.
That is, if a literal is contained in several clauses then it is counted several times. This is a measure of the size of the CNF.
Returns
The sum of the sizes of all clauses in the CNF.
Definition at line 312 of file CNF.cpp.
References clauses_.
Referenced by LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), LearnSynthQBF::computeWinningRegionOneSAT(), LearnSynthQBFInc::reduceExistingClauses(), LearnSynthQBF::reduceExistingClauses(), LearnSynthQBFInd::reduceExistingClauses(), and ParExtractorQBFWorker::runQBF().
vector< int > CNF::getVars () const
Returns the set of all variables that occur in the CNF.
Returns
The set of all variables that occur in the CNF.
Definition at line 560 of file CNF.cpp.
References appendVarsTo().
bool CNF::isSatBy (const vector< int > & cube) const
Checks if the CNF is satisfied by a certain variable assignment.
This is a purely syntactic check, i.e., no SAT-solver is involved. The variable assignment is passed as a cube with the following meaning: variables occurring positively in the cube are set to TRUE, variables occurring in negative polarity are set to FALSE.
Parameters
cube The variable assignment in form of a cube: variables occurring positively in the cube are interpreted as TRUE, variables occurring in negative polarity are considered to be FALSE.
Returns
True if the CNF is satisfied by the passed variable assignment, false otherwise.
Definition at line 409 of file CNF.cpp.
References clauses_.
Referenced by LearnSynthSAT::computeWinningRegionRGRecy(), IFM13Synth::isBlocked(), IFM13Explorer::isBlocked(), IFM13Synth::isLose(), and IFM13Explorer::isLose().
void CNF::negate ()
Negates this CNF.
Be careful: this is an 'expensive' operation in the sense that the resulting CNF can be significantly larger. This method introduces fresh temporary variables (Tseitin variables) The freshly introduced variables are of type VarKind::TMP. Hence, this method also modifies the state of the VarManager. If you call negate() twice you will end up with a formula that is equisatisfiable to the original formula, but potentially much much larger.
Definition at line 272 of file CNF.cpp.
References add2LitClause(), clauses_, VarManager::createFreshTmpVar(), and VarManager::instance().
Referenced by LearnSynthQBF::computeCounterexampleSAT(), IFM13Synth::computeWinningRegion(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRecy(), IFM13Synth::debugCheckInvariants(), LearnSynthSAT::debugCheckWinReg(), Utils::debugCheckWinReg(), LearnSynthQBFInd::debugCheckWinRegReach(), CNFImplExtractor::extractCircuit(), TemplateSynth::findWinRegCNFTempl(), LearningImplExtractor::makeEq(), Utils::negateStateCNF(), LearnSynthQBFInc::recomputeCheckCNF(), LearnSynthQBF::recomputeCheckCNF(), LearnSynthQBFInd::recomputeCheckCNF(), and ParallelLearner::triggerExplorerRestart().
CNF & CNF::operator= (const CNF & other) [virtual]
Assignment operator.
Makes this object a deep copy of another object.
Parameters
other The source for creating the (deep) copy.
Returns
The result of the assignment, i.e, *this.
Definition at line 98 of file CNF.cpp.
References clauses_.
bool CNF::operator== (const CNF & other) const
Compares two CNFs syntactically.
This is a purely syntactical check, i.e., no SAT-solving is involved. If this method returns true, then the two CNFs are definitely equivalent. If it returns False, it could still be that they are equivalent.
Parameters
other The other CNF to compare with.
Returns
True if the two CNFs are syntactically equivalent, False otherwise. If false is returned, then the two CNFs can still be equivalent.
Definition at line 585 of file CNF.cpp.
References clauses_.
void CNF::removeDuplicates ()
Removes all duplicates from the CNF.
This method does even more: it transforms the CNF into a set of sets, and back. This means that all clauses and literals in clauses will be sorted according to a certain criterion after executing this method. The reason for this method is: sometimes we would actually prefer a representation of clauses as sets of sets.
Definition at line 398 of file CNF.cpp.
References clauses_.
Referenced by IFM13Synth::propagateBlockedStates(), and IFM13Explorer::propagateBlockedStates().
vector< int > CNF::removeSmallest ()
Removes and returns the smallest clause (least number of literals).
It is guaranteed that the removed clause is among the clauses with the lowest cardinality. If there are more such clauses, an arbitrary one is chosen.
Returns
The clause that has been removed from the CNF.
Definition at line 207 of file CNF.cpp.
References clauses_, and MASSERT.
Referenced by Utils::compressNextStateCNF(), Utils::compressStateCNF(), and ClauseMinimizerQBF::minimizeClausesNoInc().
vector< int > CNF::removeSomeClause ()
Removes and returns some clause.
Returns
The clause that has been removed from the CNF.
Definition at line 222 of file CNF.cpp.
References clauses_.
Referenced by ClauseMinimizerQBF::minimizeClausesInc().
void CNF::renameTmps ()
Renames all temporary variables that occur in this CNF with fresh ones.
Definition at line 252 of file CNF.cpp.
References appendVarsTo(), VarManager::createFreshTmpVar(), VarManager::getInfo(), VarInfo::getKind(), VarManager::instance(), renameVars(), and VarInfo::TMP.
Referenced by Utils::debugCheckWinReg().
void CNF::renameVars (const vector< int > & rename_map)
Renames all variables in a CNF.
Parameters
rename_map A map containing the new names of the variables. Every occurrence of variable i is replaced by rename_map[i]. If a certain variable i should not be renamed, then set rename_map[i]=i. This rename_map must contain a new name for EVERY variable that may appear in the CNF.
Definition at line 528 of file CNF.cpp.
References clauses_.
Referenced by LearnSynthSAT::computeWinningRegionPlainDep2(), TemplateSynth::exclude(), TemplExplorer::exclude(), renameTmps(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), and swapPresentToNext().
void CNF::saveToFile (const string & filename) const
Stores the CNF into a file in DIMACS format.
The CNF is stored in DIMACS format, i.e., you can pass this file directly on to SAT-solvers. DIMACS format means: every clause is printed as the list of its literals. Clauses are terminated by the special number '0' (which cannot be a literal).
Parameters
filename The name of the file to write to.
Definition at line 334 of file CNF.cpp.
References clauses_, MASSERT, and toString().
Referenced by StoreImplExtractor::extractCircuit().
void CNF::setVarValue (int var, bool value)
Replaces a variable in the CNF by true or false.
Parameters
var The variable to replace.
value The truth value of this variable.
Definition at line 433 of file CNF.cpp.
References clauses_.
Referenced by TemplateSynth::check(), TemplExplorer::check(), TemplateSynth::exclude(), TemplExplorer::exclude(), LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), LearningImplExtractor::runLearningQBF(), LearningImplExtractor::runLearningQBFInc(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void CNF::simplify ()
Simplifies the CNF syntactically.
The only simplification we do is to remove all clauses which form a superset of other clauses.
Definition at line 366 of file CNF.cpp.
References clauses_, Utils::isSubset(), and L_DBG.
void CNF::swapPresentToNext ()
Replaces all current-state variables in the CNF with their next-state copy.
All other variables are kept as they are. In particular, auxiliary variables (e.g., introduced in Tseitin transformations) will NOT be renamed.
Definition at line 236 of file CNF.cpp.
References VarManager::getMaxCNFVar(), VarManager::getVarsOfType(), VarManager::instance(), MASSERT, VarInfo::NEXT_STATE, VarInfo::PRES_STATE, and renameVars().
Referenced by Utils::compressNextStateCNF(), LearnSynthQBF::computeCounterexampleSAT(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::considerNewInfoFromOthers(), CounterGenSAT::considerNewInfoFromOthers(), IFM13Explorer::considerNewInfoFromOthers(), IFM13Synth::debugCheckInvariants(), LearnSynthSAT::debugCheckWinReg(), Utils::debugCheckWinReg(), LearnSynthQBFInd::debugCheckWinRegReach(), ClauseMinimizerQBF::minimizeClausesInc(), ClauseMinimizerQBF::minimizeClausesNoInc(), LearnSynthQBFInc::recomputeCheckCNF(), LearnSynthQBF::recomputeCheckCNF(), LearnSynthQBFInd::recomputeCheckCNF(), LearnSynthQBFInc::recomputeGenCNF(), LearnSynthQBF::recomputeGenCNF(), LearnSynthQBFInd::recomputeGenCNF(), QBFCertImplExtractor::run(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), LearningImplExtractor::runLearningQBF(), LearningImplExtractor::runLearningQBFInc(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), and ParallelLearner::triggerExplorerRestart().
void CNF::swapWith (list< vector< int > > & clauses)
Swaps the content of this CNF with the passed set of clauses.
This is cheaper than copying or assigning.
Parameters
clauses The clause set to swap content with.
Definition at line 294 of file CNF.cpp.
References clauses_.
Referenced by Utils::compressNextStateCNF(), LearnSynthQBFInd::LearnSynthQBFInd(), LearnSynthSAT::LearnSynthSAT(), ParExtractorWorker::makeEq(), LearningImplExtractor::makeEq(), PrevStateInfo::PrevStateInfo(), IFM13Synth::propagateBlockedStates(), IFM13Explorer::propagateBlockedStates(), OrigUnivExpander::univExpand(), and UnivExpander::univExpand().
void CNF::swapWith (CNF & other)
Swaps the content of this CNF with the passed CNF.
This is cheaper than copying or assigning.
Parameters
other The cnf to swap content with.
Definition at line 300 of file CNF.cpp.
References clauses_.
string CNF::toString () const
Returns a string representation of the CNF in DIMACS format.
The string is returned in DIMACS format, i.e., you can pass this string directly on to SAT- and QBF-solvers. DIMACS format means: every clause is printed as the list of its literals. Clauses are terminated by the special number '0' (which cannot be a literal).
Returns
A string representation of the CNF in DIMACS format.
Definition at line 321 of file CNF.cpp.
References clauses_.
Referenced by ExtQBFSolver::dumpQBF(), and saveToFile().
Member Data Documentation
list<vector<int> > CNF::clauses_ [protected]
The CNF represented as list of clauses (in turn being vectors of literals).
Definition at line 423 of file CNF.h.
Referenced by add1LitClause(), add2LitClause(), add3LitClause(), add4LitClause(), addClause(), addClauseAndSimplify(), addCNF(), addNegCubeAsClause(), appendVarsTo(), clear(), CNF(), contains(), doPureAndUnit(), getClauses(), getNrOfClauses(), getNrOfLits(), isSatBy(), negate(), operator=(), operator==(), removeDuplicates(), removeSmallest(), removeSomeClause(), renameVars(), saveToFile(), setVarValue(), simplify(), swapWith(), and toString().
The documentation for this class was generated from the following files:
src/CNF.h
src/CNF.cpp