StringUtils Class Reference
Contains utility functions on strings.
#include <StringUtils.h>
Public Member Functions
virtual ~StringUtils ()
Destructor.
Static Public Member Functions
static string toUpperCase (const string &in)
Returns a copy of a string where all lower-case letters are turned into upper-case.
static void toUpperCaseIn (string &in)
Turns all lower-case letters into upper-case letters.
static string toLowerCase (const string &in)
Returns a copy of a string where all upper-case letters are turned into lower-case.
static void toLowerCaseIn (string &in)
Turns all upper-case letters into lower-case letters.
static string trim (const string &in, const string &chars=WS)
Returns a copy of a string where all leading and trailing whitespaces are removed.
static string lTrim (const string &in, const string &chars=WS)
Returns a copy of the passed string where all leading whitespaces are removed.
static string rTrim (const string &in, const string &chars=WS)
Returns a copy of the passed string where all trailing whitespaces are removed.
static void trimIn (string &in, const string &chars=WS)
Removes all leading and trailing whitespaces.
static void lTrimIn (string &in, const string &chars=WS)
Removes all leading whitespaces.
static void rTrimIn (string &in, const string &chars=WS)
Removes all trailing whitespaces.
static size_t count (const string &in, const string &what)
Counts the occurrences of a certain pattern in a string.
static string replaceAll (const string &in, const string &from, const string &to)
Returns a copy of a string where all occurrences of a certain pattern are replaced.
static void replaceAllIn (string &in, const string &from, const string &to)
Replaces all occurrences of a substring in a string with another substring.
static void tokenize (const string &in, vector< string > &tok, const string &delim=WS)
Tokenizes a string with a given list of delimiters.
static void splitLines (const string &in, vector< string > &lines, bool keep_newlines)
Splits a string into its lines (separated by \n or \r).
Static Public Attributes
static const string WS = ` \t\r\n`
A string containing all whitespaces.
Private Member Functions
StringUtils ()
Constructor.
StringUtils (const StringUtils &other)
Copy constructor.
StringUtils & operator= (const StringUtils &other)
Assignment operator.
Detailed Description
Contains utility functions on strings.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.1.0
Definition at line 42 of file StringUtils.h.
Constructor & Destructor Documentation
StringUtils::~StringUtils () [virtual]
Destructor.
Definition at line 36 of file StringUtils.cpp.
StringUtils::StringUtils () [private]
Constructor.
The constructor is private and not implemented. Use the static methods.
StringUtils::StringUtils (const StringUtils & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
size_t StringUtils::count (const string & in, const string & what) [static]
Counts the occurrences of a certain pattern in a string.
Parameters
in The string in which the occurrences of 'what' should be counted.
what The string to count.
Returns
The number of times 'what' occurs in 'in'. If what is the empty string, 0 is returned.
Definition at line 121 of file StringUtils.cpp.
Referenced by splitLines().
string StringUtils::lTrim (const string & in, const string & chars = WS) [static]
Returns a copy of the passed string where all leading whitespaces are removed.
The only difference to lTrimIn is that this method does not modify the passed string.
Parameters
in The string in which all leading whitespaces should be removed.
chars A string containing all characters to trim. The default is a string containing all whitespace characters.
Returns
The passed string where all leading whitespaces have been removed.
Definition at line 78 of file StringUtils.cpp.
References lTrimIn().
void StringUtils::lTrimIn (string & in, const string & chars = WS) [static]
Removes all leading whitespaces.
The only difference to lTrim is that this method modifies the passed string.
Parameters
in The string in which all leading whitespaces should be removed.
chars A string containing all characters to trim. The default is a string containing all whitespace characters.
Definition at line 101 of file StringUtils.cpp.
Referenced by lTrim(), and trimIn().
StringUtils& StringUtils::operator= (const StringUtils & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
string StringUtils::replaceAll (const string & in, const string & from, const string & to) [static]
Returns a copy of a string where all occurrences of a certain pattern are replaced.
This method copies the passed string, replaces all occurrences of the string 'from' with the string 'to', and returns the resulting string. That is, StringUtils.replaceAll(`Evil devil`, `vi`, `mai`) returns `Email demail`. If 'from' is the empty string, nothing is replaced.
The only difference to replaceAllIn is that this method does not modify the passed string.
Parameters
in The string in which the replacement should be made.
from The string from which all occurrences should be replaced in 'in'.
to The string with which all occurrences of 'from' should be replaced.
Returns
The resulting string where the replacement has been performed.
Definition at line 137 of file StringUtils.cpp.
References replaceAllIn().
void StringUtils::replaceAllIn (string & in, const string & from, const string & to) [static]
Replaces all occurrences of a substring in a string with another substring.
This method replaces all occurrences of the string 'from' with the string 'to' in the string 'in'. If 'from' is the empty string, nothing is replaced.
The only difference to replaceAll is that this method modifies the passed string.
Parameters
in The string in which the replacement should be made.
from The string from which all occurrences should be replaced in 'in'.
to The string with which all occurrences of 'from' should be replaced.
Definition at line 145 of file StringUtils.cpp.
Referenced by replaceAll().
string StringUtils::rTrim (const string & in, const string & chars = WS) [static]
Returns a copy of the passed string where all trailing whitespaces are removed.
The only difference to rTrimIn is that this method does not modify the passed string.
Parameters
in The string in which all trailing whitespaces should be removed.
chars A string containing all characters to trim. The default is a string containing all whitespace characters.
Returns
The passed string where all trailing whitespaces have been removed.
Definition at line 86 of file StringUtils.cpp.
References rTrimIn().
void StringUtils::rTrimIn (string & in, const string & chars = WS) [static]
Removes all trailing whitespaces.
The only difference to rTrim is that this method modifies the passed string.
Parameters
in The string in which all trailing whitespaces should be removed.
chars A string containing all characters to trim. The default is a string containing all whitespace characters.
Definition at line 111 of file StringUtils.cpp.
Referenced by rTrim(), and trimIn().
void StringUtils::splitLines (const string & in, vector< string > & lines, bool keep_newlines) [static]
Splits a string into its lines (separated by \n or \r).
Emtpy lines are ignored.
Parameters
in The string to split.
lines The container to add the found lines to. Empty lines are not added.
keep_newlines True if the newline characters should be kept, false otherwise.
Definition at line 173 of file StringUtils.cpp.
References count(), and tokenize().
void StringUtils::tokenize (const string & in, vector< string > & tok, const string & delim = WS) [static]
Tokenizes a string with a given list of delimiters.
Parameters
in The string to tokenize.
tok The container to add the found tokens to.
delim A string where every character is seen as a delimiter. The default is to treat all whitespaces as delimiters.
Definition at line 160 of file StringUtils.cpp.
Referenced by splitLines().
string StringUtils::toLowerCase (const string & in) [static]
Returns a copy of a string where all upper-case letters are turned into lower-case.
The only difference to toLowerCaseIn is that this method does not modify the passed string.
Parameters
in The string in which all upper-case letters should be turned into lower-case letters. This string is NOT modified.
Returns
A copy of the passed string, where all upper-case letters are turned into lower case letters.
Definition at line 56 of file StringUtils.cpp.
References toLowerCaseIn().
Referenced by VarManager::initFromAig(), and EPRSynthesizer::run().
void StringUtils::toLowerCaseIn (string & in) [static]
Turns all upper-case letters into lower-case letters.
The only difference to toLowerCase is that this method modifies the passed string.
Parameters
in The string to process.
Definition at line 64 of file StringUtils.cpp.
Referenced by CNFImplExtractor::insertIntoSpec(), Options::parse(), and toLowerCase().
string StringUtils::toUpperCase (const string & in) [static]
Returns a copy of a string where all lower-case letters are turned into upper-case.
The only difference to toUppperCaseIn is that this method does not modify the passed string.
Parameters
in The string in which all lower-case letters should be turned into upper-case letters. This string is NOT modified.
Returns
A copy of the passed string, where all lower-case letters are turned into upper case letters.
Definition at line 42 of file StringUtils.cpp.
References toUpperCaseIn().
void StringUtils::toUpperCaseIn (string & in) [static]
Turns all lower-case letters into upper-case letters.
The only difference to toUppperCase is that this method modifies the passed string.
Parameters
in The string to process.
Definition at line 50 of file StringUtils.cpp.
Referenced by toUpperCase().
string StringUtils::trim (const string & in, const string & chars = WS) [static]
Returns a copy of a string where all leading and trailing whitespaces are removed.
The only difference to trimIn is that this method does not modify the passed string.
Parameters
in The string in which all leading and trailing whitespaces should be removed.
chars A string containing all characters to trim. The default is a string containing all whitespace characters.
Returns
The passed string where all leading and trailing whitespaces have been removed.
Definition at line 70 of file StringUtils.cpp.
References trimIn().
void StringUtils::trimIn (string & in, const string & chars = WS) [static]
Removes all leading and trailing whitespaces.
The only difference to trim is that this method modifies the passed string.
Parameters
in The string in which all leading and trailing whitespaces should be removed.
chars A string containing all characters to trim. The default is a string containing all whitespace characters.
Definition at line 94 of file StringUtils.cpp.
References lTrimIn(), and rTrimIn().
Referenced by trim().
Member Data Documentation
const string StringUtils::WS = ` \t\r\n` [static]
A string containing all whitespaces.
Definition at line 49 of file StringUtils.h.
The documentation for this class was generated from the following files:
src/StringUtils.h
src/StringUtils.cpp