QBFCertImplExtractor Class Reference
Given a winning region in CNF, this method extracts a circuit using QBFCert.
#include <QBFCertImplExtractor.h>
Public Member Functions
QBFCertImplExtractor ()
Constructor.
virtual ~QBFCertImplExtractor ()
Destructor.
virtual void run (const CNF &winning_region, const CNF &neg_winning_region)
Extracts a circuit from the winning region and its negation.
virtual void extractCircuit (const CNF &winning_region)
Extracts a circuit from the winning region.
virtual void extractCircuit (const CNF &winning_region, const CNF &neg_winning_region)
Extracts a circuit from the winning region and its negation.
virtual void logStatistics ()
Logs statistical information about circuit extraction.
Static Public Member Functions
static aiger * optimizeWithABC (aiger *circuit)
Optimizes a combinatorial AIGER circuit with ABC.
Protected Member Functions
void logDetailedStatistics ()
Logs some detailed statistics (time for QBFCert, ABC, circuit sizes, etc.).
size_t insertIntoSpec (aiger *standalone_circuit) const
Takes a circuit defining the control signals and inserts it into the spec.
Protected Attributes
size_t size_before_abc_
Statistics: the number of AND gates before optimization with ABC.
size_t size_after_abc_
Statistics: the number of AND gates after optimization with ABC.
size_t size_final_
Statistics: the final number of additional AND gates.
size_t qbfcert_real_time_
Statistics: the real time (in seconds) needed by QBFCert.
size_t abc_real_time_
Statistics: the real time (in seconds) needed for the optimization with ABC.
double extraction_cpu_time_
The circuit extraction time in CPU-seconds.
size_t extraction_real_time_
Like extraction_cpu_time_ but real-time.
Detailed Description
Given a winning region in CNF, this method extracts a circuit using QBFCert.
QBFCert (see http://fmv.jku.at/qbfcert/) is a framework for computing Skolem or Herbrand functions as witnesses for quantified Boolean formulas. We use it to compute circuits from a winning region. Let W be the winning region. Then we can compute a circuit as a skolem function for the c-signals in:
   forall x,i: exists c,x': (!W) | (T & W')
 However, for performance reasons, we actually compute Herbrand functions for the c-signals in the formula:
   exists x,i: forall c: exists x': W & T & !W'
 QBFCert outputs the result in AIGER format. Hence, all we have to do in order to obtain the final output of our tool is to embed this AIGER-circuits for the c-signals in the input AIGER file.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 57 of file QBFCertImplExtractor.h.
Constructor & Destructor Documentation
QBFCertImplExtractor::QBFCertImplExtractor ()
Constructor.
Definition at line 46 of file QBFCertImplExtractor.cpp.
QBFCertImplExtractor::~QBFCertImplExtractor () [virtual]
Destructor.
Definition at line 57 of file QBFCertImplExtractor.cpp.
Member Function Documentation
void CNFImplExtractor::extractCircuit (const CNF & winning_region) [virtual], [inherited]
Extracts a circuit from the winning region.
How this is done (interpolation, learning, etc.) depends on the concrete implementation of this abstract class. The result is written into the output file specified by the user.
Parameters
winning_region The winning region from which the circuit should be extracted. For circuit extraction we need both the winning region and its negation. The negation is computed inside this function. If you already have a negation, use the other circuit extraction method of this class.
Reimplemented in StoreImplExtractor.
Definition at line 85 of file CNFImplExtractor.cpp.
References Utils::compressStateCNF(), CNFImplExtractor::extraction_cpu_time_, CNFImplExtractor::extraction_real_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), CNF::negate(), CNFImplExtractor::run(), and Stopwatch::start().
Referenced by LoadSynth::run(), LearnSynthQBFInc::run(), TemplateSynth::run(), IFM13Synth::run(), LearnSynthQBF::run(), LearnSynthSAT::run(), LearnSynthQBFInd::run(), and ParallelLearner::run().
void CNFImplExtractor::extractCircuit (const CNF & winning_region, const CNF & neg_winning_region) [virtual], [inherited]
Extracts a circuit from the winning region and its negation.
How this is done (interpolation, learning, etc.) depends on the concrete implementation of this abstract class. The result is written into the output file specified by the user.
Parameters
winning_region The winning region from which the circuit should be extracted.
neg_winning_region The negation of the winning region.
Definition at line 102 of file CNFImplExtractor.cpp.
References CNFImplExtractor::extraction_cpu_time_, CNFImplExtractor::extraction_real_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), CNFImplExtractor::run(), and Stopwatch::start().
size_t CNFImplExtractor::insertIntoSpec (aiger * standalone_circuit) const [protected], [inherited]
Takes a circuit defining the control signals and inserts it into the spec.
This method takes as argument an aiger circuit of the following form:
The circuit is combinational, i.e., has no latches.
The inputs of the circuit are: the uncontrollable inputs from the spec (in the order in which they appear in the spec) followed by the state-signals (the output of the latches in the spec, in the order in which they appear in the spec).
The outputs of the circuit are the controllable inputs in the order in which they are defined in the spec.
Parameters
standalone_circuit A circuit defining the control signals.
Returns
The number of additional AND gates introduced into the spec.
Definition at line 149 of file CNFImplExtractor.cpp.
References VarInfo::CTRL, Options::getAigInFileName(), Options::getAigOutFileName(), VarManager::getInfo(), VarInfo::getLitInAIG(), VarManager::getMaxAIGVar(), VarManager::getPresErrorStateVar(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), Options::instance(), MASSERT, VarInfo::PRES_STATE, and StringUtils::toLowerCaseIn().
Referenced by ParExtractor::run(), LearningImplExtractor::run(), and run().
void QBFCertImplExtractor::logDetailedStatistics () [protected], [virtual]
Logs some detailed statistics (time for QBFCert, ABC, circuit sizes, etc.).
Reimplemented from CNFImplExtractor.
Definition at line 147 of file QBFCertImplExtractor.cpp.
References abc_real_time_, L_LOG, qbfcert_real_time_, size_after_abc_, size_before_abc_, and size_final_.
void CNFImplExtractor::logStatistics () [virtual], [inherited]
Logs statistical information about circuit extraction.
This method logs the overall execution time plus whatever detailed information is collected by the concrete implementation of this class.
Definition at line 290 of file CNFImplExtractor.cpp.
References CNFImplExtractor::extraction_cpu_time_, CNFImplExtractor::extraction_real_time_, L_LOG, and CNFImplExtractor::logDetailedStatistics().
Referenced by LoadSynth::run(), LearnSynthQBFInc::run(), TemplateSynth::run(), IFM13Synth::run(), LearnSynthQBF::run(), LearnSynthSAT::run(), LearnSynthQBFInd::run(), and ParallelLearner::run().
aiger * CNFImplExtractor::optimizeWithABC (aiger * circuit) [static], [inherited]
Optimizes a combinatorial AIGER circuit with ABC.
Note
The returned structure must be deleted by the caller.
Parameters
circuit The circuit to optimize.
Returns
The optimized version of the circuit. The returned aiger structure must be deleted by the caller.
Definition at line 112 of file CNFImplExtractor.cpp.
References Options::getTPDirName(), Options::getUniqueTmpFileName(), Options::instance(), and MASSERT.
Referenced by LearningImplExtractor::run(), run(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void QBFCertImplExtractor::run (const CNF & winning_region, const CNF & neg_winning_region) [virtual]
Extracts a circuit from the winning region and its negation.
The result is written into the output file specified by the user. This method should be preferred if you have the winning region and its negation available. The other method computes the negation by itself and may introduce quite a lot of temporary variables.
This method uses QBFCert to compute a solution. QBFCert (see http://fmv.jku.at/qbfcert/) is a framework for computing Skolem or Herbrand functions as witnesses for quantified Boolean formulas. We use it to compute circuits from a winning region. Let W be the winning region. Then we can compute a circuit as a skolem function for the c-signals in:
   forall x,i: exists c,x': (!W) | (T & W')
 However, for performance reasons, we actually compute Herbrand functions for the c-signals in the formula:
   exists x,i: forall c: exists x': W & T & !W'
 QBFCert outputs the result in AIGER format. Hence, all we have to do in order to obtain the final output of our tool is to embed this AIGER-circuits for the c-signals in the input AIGER file.
Parameters
winning_region The winning region from which the circuit should be extracted.
neg_winning_region The negation of the winning region.
Implements CNFImplExtractor.
Definition at line 63 of file QBFCertImplExtractor.cpp.
References QBFSolver::A, abc_real_time_, CNF::addCNF(), VarInfo::CTRL, QBFSolver::E, Stopwatch::getRealTimeSec(), VarManager::getVarsOfType(), VarInfo::INPUT, CNFImplExtractor::insertIntoSpec(), VarManager::instance(), AIG2CNF::instance(), ExtQBFSolver::isSat(), L_DBG, MASSERT, VarInfo::NEXT_STATE, CNFImplExtractor::optimizeWithABC(), VarInfo::PRES_STATE, DepQBFExt::qbfCert(), qbfcert_real_time_, size_after_abc_, size_before_abc_, size_final_, Stopwatch::start(), CNF::swapPresentToNext(), and VarInfo::TMP.
Member Data Documentation
size_t QBFCertImplExtractor::abc_real_time_ [protected]
Statistics: the real time (in seconds) needed for the optimization with ABC.
Definition at line 127 of file QBFCertImplExtractor.h.
Referenced by logDetailedStatistics(), and run().
double CNFImplExtractor::extraction_cpu_time_ [protected], [inherited]
The circuit extraction time in CPU-seconds.
Definition at line 145 of file CNFImplExtractor.h.
Referenced by CNFImplExtractor::extractCircuit(), and CNFImplExtractor::logStatistics().
size_t CNFImplExtractor::extraction_real_time_ [protected], [inherited]
Like extraction_cpu_time_ but real-time.
Definition at line 150 of file CNFImplExtractor.h.
Referenced by CNFImplExtractor::extractCircuit(), and CNFImplExtractor::logStatistics().
size_t QBFCertImplExtractor::qbfcert_real_time_ [protected]
Statistics: the real time (in seconds) needed by QBFCert.
Definition at line 122 of file QBFCertImplExtractor.h.
Referenced by logDetailedStatistics(), and run().
size_t QBFCertImplExtractor::size_after_abc_ [protected]
Statistics: the number of AND gates after optimization with ABC.
Definition at line 112 of file QBFCertImplExtractor.h.
Referenced by logDetailedStatistics(), and run().
size_t QBFCertImplExtractor::size_before_abc_ [protected]
Statistics: the number of AND gates before optimization with ABC.
Definition at line 107 of file QBFCertImplExtractor.h.
Referenced by logDetailedStatistics(), and run().
size_t QBFCertImplExtractor::size_final_ [protected]
Statistics: the final number of additional AND gates.
Definition at line 117 of file QBFCertImplExtractor.h.
Referenced by logDetailedStatistics(), and run().
The documentation for this class was generated from the following files:
src/QBFCertImplExtractor.h
src/QBFCertImplExtractor.cpp