ExtQBFSolver Class Reference
A generic interface to QBF-solvers started as external processes.
#include <ExtQBFSolver.h>
Public Types
enum Quant { E,
A
 }
A type for the different kinds of quantifiers.
Public Member Functions
ExtQBFSolver ()
Constructor.
virtual ~ExtQBFSolver ()
Destructor.
virtual bool isSat (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
Checks if a given QBF is satisfiable (with quantification over variable kinds).
virtual bool isSat (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
Checks if a given QBF is satisfiable (with quantification over variable sets).
virtual bool isSatModel (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf, vector< int > &model)
Checks satisfiability and extracts a model (quantifying over variable kinds).
virtual bool isSatModel (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf, vector< int > &model)
Checks satisfiability and extracts a model (quantifying over variable sets).
Static Public Member Functions
static void dumpQBF (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf, const string &filename)
Dumps a QBF (quantification over variable kinds) into a file in QDIMACS format.
static void dumpQBF (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf, const string &filename)
Dumps a QBF (quantification over variable kinds) into a file in QDIMACS format.
Protected Member Functions
virtual bool parseAnswer (int ret) const
Parses the answer of the QBF solver to get the satisfiability verdict.
virtual bool parseModel (int ret, const vector< int > &get, vector< int > &model) const
Parses the answer of the QBF solver to get the satisfiability verdict and a model.
virtual void cleanup ()
Deletes the temporary files that have been used for communication.
virtual string getSolverCommand () const =0
Returns the command to start the solver if no model is needed.
virtual string getSolverCommandModel () const =0
Returns the command to start the solver if a model is needed.
Protected Attributes
string in_file_name_
The name of the QDIMACS file containing the QBF to be solved.
string out_file_name_
The name of the file that is produced by the QBF-solver (containing the model).
Private Member Functions
ExtQBFSolver (const ExtQBFSolver &other)
Copy constructor.
ExtQBFSolver & operator= (const ExtQBFSolver &other)
Assignment operator.
Detailed Description
A generic interface to QBF-solvers started as external processes.
This is an abstract base class for all interfaces to QBF-solvers which start the QBF-solver in a separate process. Practically all QBF-solvers understand the QDIMACS format as input. Hence, different QBF-solvers can be interfaced in the same way. The only things that differ from solver to solver are the location of the executable and the command-line options that must be set. These solver-specific aspects are handled in the derived classes (by overriding certain methods). Everything else is handled in this abstract base class. At he moment there are two implementations of this abstract class: DepQBFExt and QuBEExt.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 53 of file ExtQBFSolver.h.
Member Enumeration Documentation
enum QBFSolver::Quant [inherited]
A type for the different kinds of quantifiers.
Enumerator
E
 The value for existential quantification.
A
 The value for universal quantification.
Definition at line 56 of file QBFSolver.h.
Constructor & Destructor Documentation
ExtQBFSolver::ExtQBFSolver ()
Constructor.
Definition at line 38 of file ExtQBFSolver.cpp.
References Options::getTmpDirName(), Options::getUniqueTmpFileName(), in_file_name_, Options::instance(), and out_file_name_.
ExtQBFSolver::~ExtQBFSolver () [virtual]
Destructor.
Definition at line 48 of file ExtQBFSolver.cpp.
ExtQBFSolver::ExtQBFSolver (const ExtQBFSolver & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void ExtQBFSolver::cleanup () [protected], [virtual]
Deletes the temporary files that have been used for communication.
Definition at line 217 of file ExtQBFSolver.cpp.
References in_file_name_, and out_file_name_.
Referenced by isSat(), isSatModel(), and DepQBFExt::qbfCert().
void ExtQBFSolver::dumpQBF (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf, const string & filename) [static]
Dumps a QBF (quantification over variable kinds) into a file in QDIMACS format.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
filename The name of the file (including path) to write to.
Definition at line 105 of file ExtQBFSolver.cpp.
References QBFSolver::E, VarManager::getMaxCNFVar(), CNF::getNrOfClauses(), VarManager::getVarsOfType(), VarManager::instance(), and CNF::toString().
Referenced by DepQBFApi::debugCheckBloqqerModel(), DepQBFApi::debugCheckBloqqerVerdict(), isSat(), isSatModel(), and DepQBFExt::qbfCert().
void ExtQBFSolver::dumpQBF (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf, const string & filename) [static]
Dumps a QBF (quantification over variable kinds) into a file in QDIMACS format.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
filename The name of the file (including path) to write to.
Definition at line 138 of file ExtQBFSolver.cpp.
References QBFSolver::E, CNF::getNrOfClauses(), and CNF::toString().
virtual string ExtQBFSolver::getSolverCommand () const [protected], [pure virtual]
Returns the command to start the solver if no model is needed.
This command should contain the path to the executable as well as all necessary command line parameters. This method is supposed to be implemented by derived classes.
Returns
The command to start the solver if no model is needed.
Implemented in DepQBFExt, QuBEExt, and RareqsExt.
Referenced by isSat().
virtual string ExtQBFSolver::getSolverCommandModel () const [protected], [pure virtual]
Returns the command to start the solver if a model is needed.
This command should contain the path to the executable as well as all necessary command line parameters. This method is supposed to be implemented by derived classes.
Returns
The command to start the solver if a model is needed.
Implemented in DepQBFExt, QuBEExt, and RareqsExt.
Referenced by isSatModel().
bool ExtQBFSolver::isSat (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [virtual]
Checks if a given QBF is satisfiable (with quantification over variable kinds).
The QBF consists of a quantifier prefix and a Boolean formula in CNF. The quantifier prefix assigns an existential or universal quantifier to every kind of variable. The QBF is dumped into a file, a QBF-solver is called, and the exit code is used to infer the satisfiability result.
Exceptions
DemiurgeException if the solver crashed or a timeout occurred.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 54 of file ExtQBFSolver.cpp.
References cleanup(), dumpQBF(), getSolverCommand(), in_file_name_, and parseAnswer().
Referenced by QBFCertImplExtractor::run().
bool ExtQBFSolver::isSat (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [virtual]
Checks if a given QBF is satisfiable (with quantification over variable sets).
The QBF consists of a quantifier prefix and a Boolean formula in CNF. The quantifier prefix assigns an existential or universal quantifier to different sets variable. The QBF is dumped into a file, a QBF-solver is called, and the exit code is used to infer the satisfiability result.
Exceptions
DemiurgeException if the solver crashed or a timeout occurred.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 66 of file ExtQBFSolver.cpp.
References cleanup(), dumpQBF(), getSolverCommand(), in_file_name_, and parseAnswer().
bool ExtQBFSolver::isSatModel (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf, vector< int > & model) [virtual]
Checks satisfiability and extracts a model (quantifying over variable kinds).
Just like isSat() , this method checks a quantified Boolean formula for satisfiability. If the QBF is satisfiable, this method also extracts a model (a satisfying assignment) for all variables which are quantified existentially on the outermost level. The model is provided as cube: negated variables in the cube are FALSE, unnegated ones are TRUE.
Exceptions
DemiurgeException if the solver crashed or a timeout occurred.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
model The resulting model in form of a cube in case of satisfiability. Negated variables in the cube are FALSE, unnegated ones are TRUE. If the formula is unsatisfiable (this method returns false) then this parameter is not modified.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 78 of file ExtQBFSolver.cpp.
References cleanup(), dumpQBF(), getSolverCommandModel(), VarManager::getVarsOfType(), in_file_name_, VarManager::instance(), and parseModel().
Referenced by TemplExplorer::syntQBF().
bool ExtQBFSolver::isSatModel (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf, vector< int > & model) [virtual]
Checks satisfiability and extracts a model (quantifying over variable sets).
Just like isSat() , this method checks a quantified Boolean formula for satisfiability. If the QBF is satisfiable, this method also extracts a model (a satisfying assignment) for all variables which are quantified existentially on the outermost level. The model is provided as cube: negated variables in the cube are FALSE, unnegated ones are TRUE.
Exceptions
DemiurgeException if the solver crashed or a timeout occurred.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
model The resulting model in form of a cube in case of satisfiability. Negated variables in the cube are FALSE, unnegated ones are TRUE. If the formula is unsatisfiable (this method returns false) then this parameter is not modified.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 92 of file ExtQBFSolver.cpp.
References cleanup(), dumpQBF(), getSolverCommandModel(), in_file_name_, and parseModel().
ExtQBFSolver& ExtQBFSolver::operator= (const ExtQBFSolver & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
bool ExtQBFSolver::parseAnswer (int ret) const [protected], [virtual]
Parses the answer of the QBF solver to get the satisfiability verdict.
Exceptions
DemiurgeException if the solver crashed or a timeout occurred.
Parameters
ret The exit code of the process running the QBF solver.
Returns
True in case of satisfiability, false for unsatisfiability.
Definition at line 180 of file ExtQBFSolver.cpp.
Referenced by isSat().
bool ExtQBFSolver::parseModel (int ret, const vector< int > & get, vector< int > & model) const [protected], [virtual]
Parses the answer of the QBF solver to get the satisfiability verdict and a model.
Exceptions
DemiurgeException if the solver crashed or a timeout occurred.
Parameters
ret The exit code of the process running the QBF solver.
get The variables of interest for which we want to have a satisfying assignment.
model An empty vector. In case of satisfiability, this method will write a satisfying assignment in form of a cube into this vector.
Returns
True in case of satisfiability, false for unsatisfiability.
Reimplemented in DepQBFExt.
Definition at line 190 of file ExtQBFSolver.cpp.
References MASSERT, out_file_name_, and FileUtils::readFile().
Referenced by isSatModel().
Member Data Documentation
string ExtQBFSolver::in_file_name_ [protected]
The name of the QDIMACS file containing the QBF to be solved.
Definition at line 232 of file ExtQBFSolver.h.
Referenced by cleanup(), ExtQBFSolver(), RareqsExt::getSolverCommand(), QuBEExt::getSolverCommand(), DepQBFExt::getSolverCommand(), RareqsExt::getSolverCommandModel(), QuBEExt::getSolverCommandModel(), DepQBFExt::getSolverCommandModel(), isSat(), isSatModel(), and DepQBFExt::qbfCert().
string ExtQBFSolver::out_file_name_ [protected]
The name of the file that is produced by the QBF-solver (containing the model).
Definition at line 237 of file ExtQBFSolver.h.
Referenced by cleanup(), ExtQBFSolver(), RareqsExt::getSolverCommand(), QuBEExt::getSolverCommand(), DepQBFExt::getSolverCommand(), RareqsExt::getSolverCommandModel(), QuBEExt::getSolverCommandModel(), DepQBFExt::getSolverCommandModel(), RareqsExt::parseModel(), DepQBFExt::parseModel(), and parseModel().
The documentation for this class was generated from the following files:
src/ExtQBFSolver.h
src/ExtQBFSolver.cpp