OrigUnivExpander Class Reference
A utility class that can do universal expansion of given CNFs.
#include <OrigUnivExpander.h>
Public Member Functions
OrigUnivExpander ()
Constructor.
virtual ~OrigUnivExpander ()
Destructor.
bool resetSolverIExp (const CNF &win_reg, SatSolver *solver_i, bool limit_size=false)
Performs the reset of solver_i in LearnSynthSAT::computeWinningRegionPlainExp().
void resetSolverCExp (SatSolver *solver_c, const vector< int > &keep, size_t max_nr_of_signals_to_expand=1)
Performs the reset of solver_c in LearnSynthSAT::computeWinningRegionPlainExp().
void addExpNxtClauseToC (const vector< int > &clause, SatSolver *solver_c)
Adds next-state clauses to solver_c after initialization with resetSolverCExp().
Static Public Member Functions
static void univExpand (const CNF &orig, CNF &res, const vector< int > &vars_to_exp, const vector< int > &keep, float rate=1.1, const map< int, set< int > > *more_deps=NULL)
The standard method for universal expansion of certain variables.
Protected Member Functions
bool initSolverIData (bool limit_size=false)
A helper function for resetSolverIExp().
Protected Attributes
const vector< int > & s_
The list of present-state variables.
const vector< int > & i_
The list of (uncontrollable) input variables.
const vector< int > & c_
The list of control signals (controllable input variables).
const vector< int > & n_
The list of next-state variables.
CNF i_exp_trans_
The expansion of the transition relation for resetSolverIExp().
int i_max_trans_var_
The maximum variable index occurring in i_exp_trans_.
vector< int > i_s_to_ren_n_
A map, renaming present-state vars to a renamed version of the next-state copy.
vector< vector< int > > i_rename_maps_
The rename maps resulting from the expansion of the transition relation.
vector< vector< int > > i_orig_prop_maps_
The rename maps for constant propagation in the original during expansion.
vector< vector< int > > c_rename_maps_
The rename maps for the next-state variables for adding clauses to solver_c.
Private Member Functions
OrigUnivExpander (const OrigUnivExpander &other)
Copy constructor.
OrigUnivExpander & operator= (const OrigUnivExpander &other)
Assignment operator.
Detailed Description
A utility class that can do universal expansion of given CNFs.
Universal expansion of a CNF with respect to certain variables is an expensive operation, especially if there are a lot of variables to expand. Hence, this operation must be implemented cleverly. For this reason, this class provides several implementations, each one tailored towards a specific application (expanding CTRL-signals in a conjuction of the transition relation with some CNF over the next-state variables, etc.)
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 51 of file OrigUnivExpander.h.
Constructor & Destructor Documentation
OrigUnivExpander::OrigUnivExpander ()
Constructor.
Definition at line 38 of file OrigUnivExpander.cpp.
OrigUnivExpander::~OrigUnivExpander () [virtual]
Destructor.
Definition at line 49 of file OrigUnivExpander.cpp.
OrigUnivExpander::OrigUnivExpander (const OrigUnivExpander & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void OrigUnivExpander::addExpNxtClauseToC (const vector< int > & clause, SatSolver * solver_c)
Adds next-state clauses to solver_c after initialization with resetSolverCExp().
After resetSolverCExp() has been called to initialize solver_c, this method can be used to add next-state clauses to all expansions of the next-state variables.
Parameters
clause A clause over the current-state variables. It is added as clause over (all expansions of) the next state variables in solver_c.
solver_c The solver to which the next-state copies of this clause should be added.
Definition at line 830 of file OrigUnivExpander.cpp.
References c_rename_maps_, and SatSolver::incAddClause().
bool OrigUnivExpander::initSolverIData (bool limit_size = false) [protected]
A helper function for resetSolverIExp().
Some work in resetSolverIExp() needs to be done again and again when this method is called repeatedly. For instance, the expansion of the transition relation is always the same. This method performs these repeated tasks only once, and stores the resulting information in fields of this class. This way, they can then be reused by resetSolverIExp() whenever needed. All fields defined by this method start with 'i_'.
Parameters
limit_size If set to true, then this method aborts if the CNF size limit defined by Options::getSizeLimitForExpansion() is exceeded. This is supposed to prevent running out of memory during the expansion. If this flag is set to false, or omitted, then the size limit does not apply.
Returns
True if the size limit for the expansion has been exceeded during the initialization already. False if everything went OK.
Definition at line 846 of file OrigUnivExpander.cpp.
References CNF::add2LitClause(), CNF::add3LitClause(), c_, CNF::getClauses(), Options::getSizeLimitForExpansion(), AIG2CNF::getTmpDepsTrans(), AIG2CNF::getTrans(), i_exp_trans_, i_max_trans_var_, i_orig_prop_maps_, i_rename_maps_, i_s_to_ren_n_, Options::instance(), AIG2CNF::instance(), MASSERT, n_, and s_.
Referenced by resetSolverIExp().
OrigUnivExpander& OrigUnivExpander::operator= (const OrigUnivExpander & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
void OrigUnivExpander::resetSolverCExp (SatSolver * solver_c, const vector< int > & keep, size_t max_nr_of_signals_to_expand = 1)
Performs the reset of solver_c in LearnSynthSAT::computeWinningRegionPlainExp().
In LearnSynthSAT::computeWinningRegionPlainExp(), solver_c needs to check exists x: forall i: exists x',t: W(x) & T(x,i,c,x',t) & W(x') where W is the winning region (a CNF over the state variables x) and T is the transition relation with t being auxiliary variables. This method expands some of the input signals i in the transition relation T, and puts the resulting formula into solver_c. At the same time, this method also constructs a renaming map so clauses of W(x') can be added later on (using the method addExpNxtClauseToC()). This method is highly optimized for exactly this purpose. univExpand() could also be used in principle, but this method has more optimizations exploiting the structure of the transition relation.
Note
The newly created auxiliary variables are not registered in the VarManager for performance reasons (there may be zillions of new variables introduced during the expansion).
Parameters
solver_c The solver into which the expanded transition relation should be stored.
keep This method declares the current-state variables, the uncontrollable inputs, and the next-state variables (in their various copys) as reusable. If you also want other variables to be reusable (e.g. previous-state variables), then they can be enumerated in this vector.
max_nr_of_signals_to_expand For solver_c, expansion is very costly (more than for solver_i). Hence, we usually only expand a few input variables. This parameter defines the maximum number of input signals to expand. Low values are recommended.
Definition at line 576 of file OrigUnivExpander.cpp.
References c_, c_rename_maps_, VarInfo::CTRL, CNF::getClauses(), VarManager::getMaxCNFVar(), AIG2CNF::getTmpDepsTrans(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), i_, i_s_to_ren_n_, SatSolver::incAdd2LitClause(), SatSolver::incAdd3LitClause(), SatSolver::incAddUnitClause(), VarManager::instance(), AIG2CNF::instance(), MASSERT, n_, VarInfo::PREV, s_, and SatSolver::startIncrementalSession().
bool OrigUnivExpander::resetSolverIExp (const CNF & win_reg, SatSolver * solver_i, bool limit_size = false)
Performs the reset of solver_i in LearnSynthSAT::computeWinningRegionPlainExp().
In LearnSynthSAT::computeWinningRegionPlainExp(), solver_i needs to check exists x,i: forall c: exists x',t: W(x) & T(x,i,c,x',t) & !W(x') where W is the winning region (a CNF over the state variables x) and T is the transition relation with t being auxiliary variables. This method expands the control signals c of the above formula and puts the resulting formula into the SAT solver solver_i. This method is highly optimized for this purpose. For instance, the expansion of the transition relation is done only once and reused for different winning regions. univExpand() could also be used in principle, but this method has more optimizations exploiting the structure of the formula that needs to be expanded.
Note
The newly created auxiliary variables are not registered in the VarManager for performance reasons (there may be zillions of new variables introduced during the expansion).
Parameters
win_reg The winning region with which the solver should be initialized.
solver_i The solver into which the expanded CNF should be store.
limit_size If set to true, then this method aborts if the CNF size limit defined by Options::getSizeLimitForExpansion() is exceeded. This is supposed to prevent running out of memory during the expansion. If this flag is set to false, or omitted, then the size limit does not apply.
Returns
True if the size limit for the expansion has been exceeded. False if everything went OK (or nothing was checked because limit_size was set to false).
Definition at line 245 of file OrigUnivExpander.cpp.
References c_, CNF::getClauses(), CNF::getNrOfClauses(), i_, i_exp_trans_, i_max_trans_var_, i_orig_prop_maps_, i_rename_maps_, i_s_to_ren_n_, SatSolver::incAdd2LitClause(), SatSolver::incAddClause(), SatSolver::incAddCNF(), SatSolver::incAddUnitClause(), initSolverIData(), Options::instance(), s_, and SatSolver::startIncrementalSession().
void OrigUnivExpander::univExpand (const CNF & orig, CNF & res, const vector< int > & vars_to_exp, const vector< int > & keep, float rate = 1.1, const map< int, set< int > > * more_deps = NULL) [static]
The standard method for universal expansion of certain variables.
Note
The newly created auxiliary variables are not registered in the VarManager for performance reasons (there may be zillions of new variables introduced during the expansion).
Parameters
orig The original CNF in which we perform universal expansion.
res An empty CNF. This is where the result will be stored.
vars_to_exp The list of variables to expand.
keep The list of variables that are quantified outside of the vars_to_exp and should hence not be renamed during the expansion.
rate A number between 0 and 1. It defines which fraction of the vars_to_exp should be expanded. Value 0.4 means that 40% of the vars_to_exp should be expanded. Use a value larger than 1 (or omit this parameter) if you want to be sure that every signal is expanded.
more_deps Additional dependencies that can be exploited during expansion. This map must map user-defined (temporary) variables to a set of other variables that define these variables. Don't include the dependencies of the temporary variables used to encode the transition relation, and don't include the dependencies of the next-state variables because they are automatically read from AIG2CNF. But if you have additional temporary variables, e.g., from Tseitin encoding some formula part then the expansion can benefit from dependency information (it needs to copy less). In any case: more_deps[i] must only contain variables in keep or vars_to_exp.
Definition at line 55 of file OrigUnivExpander.cpp.
References CNF::appendVarsTo(), DASSERT, CNF::getClauses(), VarManager::getMaxCNFVar(), AIG2CNF::getTmpDepsTrans(), VarManager::instance(), AIG2CNF::instance(), and CNF::swapWith().
Member Data Documentation
const vector<int>& OrigUnivExpander::c_ [protected]
The list of control signals (controllable input variables).
This list is often used, so we keep it as a field to increase readability of the code.
Definition at line 206 of file OrigUnivExpander.h.
Referenced by initSolverIData(), resetSolverCExp(), and resetSolverIExp().
vector<vector<int> > OrigUnivExpander::c_rename_maps_ [protected]
The rename maps for the next-state variables for adding clauses to solver_c.
c_rename_maps_[i] is the rename map for present-state variables to the i-th copy of the next state variables.
Definition at line 277 of file OrigUnivExpander.h.
Referenced by addExpNxtClauseToC(), and resetSolverCExp().
const vector<int>& OrigUnivExpander::i_ [protected]
The list of (uncontrollable) input variables.
This list is often used, so we keep it as a field to increase readability of the code.
Definition at line 199 of file OrigUnivExpander.h.
Referenced by resetSolverCExp(), and resetSolverIExp().
CNF OrigUnivExpander::i_exp_trans_ [protected]
The expansion of the transition relation for resetSolverIExp().
We do not expand the transition relation again and again, but we do this only once and reuse it. The only thing we expand freshly each time is the next state copy of the (negation of the) winning region. All fields starting with 'i_' (like this one) are initialized by initSolverIData() and used by resetSolverIExp().
Definition at line 224 of file OrigUnivExpander.h.
Referenced by initSolverIData(), and resetSolverIExp().
int OrigUnivExpander::i_max_trans_var_ [protected]
The maximum variable index occurring in i_exp_trans_.
That is, for resetSolverIExp(), i_max_trans_var_ + 1 is the next fresh CNF variable. All fields starting with 'i_' (like this one) are initialized by initSolverIData() and used by resetSolverIExp().
Definition at line 233 of file OrigUnivExpander.h.
Referenced by initSolverIData(), and resetSolverIExp().
vector<vector<int> > OrigUnivExpander::i_orig_prop_maps_ [protected]
The rename maps for constant propagation in the original during expansion.
i_orig_prop_maps_[c_idx] defines how to rename variables in the original when creating the copy due to expansion of the control signal c_[c_idx]. A variable can only be renamed to itself, to 1 (TRUE) and to -1 (FALSE). That is, this is no real renaming but essentially only constant propagation.
Definition at line 269 of file OrigUnivExpander.h.
Referenced by initSolverIData(), and resetSolverIExp().
vector<vector<int> > OrigUnivExpander::i_rename_maps_ [protected]
The rename maps resulting from the expansion of the transition relation.
i_rename_maps_[c_idx] defines how to rename variables when expanding the control signal c_[c_idx]. This rename map does not only do renaming, but also constant propagation. If a certain variable is renamed to 1, then it is set to TRUE. If it is renamed to -1, then it is set to FALSE.
Definition at line 259 of file OrigUnivExpander.h.
Referenced by initSolverIData(), and resetSolverIExp().
vector<int> OrigUnivExpander::i_s_to_ren_n_ [protected]
A map, renaming present-state vars to a renamed version of the next-state copy.
resetSolverIExp() gets the winning region, and needs to expand and negate the next-state copy of the winning region. This map does two renamings in one go: (1) it renames present state variables to their corresponding next-state copy, and (2) it further renames the next-state copy of state variables to the auxiliary variables defining them in the transition relation. Originally, the transition relation CNF has special clauses that do this renaming. We remove these clauses and do the renaming with a map. This is more efficient. Otherwise, the renaming-clauses of the transition relation would get copied many many many times, which increases the size of the expanded CNFs unnecessarily. All fields starting with 'i_' (like this one) are initialized by initSolverIData() and used by resetSolverIExp().
Definition at line 249 of file OrigUnivExpander.h.
Referenced by initSolverIData(), resetSolverCExp(), and resetSolverIExp().
const vector<int>& OrigUnivExpander::n_ [protected]
The list of next-state variables.
This list is often used, so we keep it as a field to increase readability of the code.
Definition at line 213 of file OrigUnivExpander.h.
Referenced by initSolverIData(), and resetSolverCExp().
const vector<int>& OrigUnivExpander::s_ [protected]
The list of present-state variables.
This list is often used, so we keep it as a field to increase readability of the code.
Definition at line 192 of file OrigUnivExpander.h.
Referenced by initSolverIData(), resetSolverCExp(), and resetSolverIExp().
The documentation for this class was generated from the following files:
src/OrigUnivExpander.h
src/OrigUnivExpander.cpp