Options Class Reference
Parses the command-line options and makes them accessible to the back-ends.
#include <Options.h>
Public Member Functions
bool parse (int argc, char **argv)
Parses the command-line options and stores them in fields of this class.
const string & getAigInFileName () const
Returns the name (including the path) of the AIGER input file.
const string getAigInFileNameOnly () const
Returns the name of the input file without path and extension.
const string & getAigOutFileName () const
Returns the name (including the path) of the AIGER output file.
const string & getBackEndName () const
Returns the name of the back-end selected by the user.
BackEnd * getBackEnd () const
A factory method to construct a BackEnd, depending on the command-line parameters.
int getBackEndMode () const
Returns the mode of the back-end selected by the user.
const string & getCircuitExtractionName () const
Returns the name of the circuit extraction method that should be used.
int getCircuitExtractionMode () const
Returns the mode of the selected circuit extraction method.
CNFImplExtractor * getCircuitExtractor () const
A factory method to construct circuit extractors, depending on the parameters.
string getTmpDirName () const
Returns the name (including the path) of the directory for temporary files.
string getTPDirName () const
Returns the name (and path) of the directory containing the thirdparty tools.
string getUniqueTmpFileName (string start=``) const
Returns a unique name of a temporary file in the directory of temporary files.
QBFSolver * getQBFSolver () const
Returns a fresh instance of the QBF-solver selected by the user.
SatSolver * getSATSolver (bool rand_models=false, bool min_cores=true) const
Returns a fresh instance of the SAT-solver selected by the user.
SatSolver * getSATSolverExtr (bool rand_models=false, bool min_cores=true) const
Returns an instance of the SAT-solver selected by the user for circuit extraction.
bool doRealizabilityOnly () const
Returns true if the back-ends should only compute a winning region but no circuits.
Static Public Member Functions
static Options & instance ()
Returns the one and only instance of this class.
Static Public Attributes
static const string VERSION = string(`1.1.0`)
The version of the tool as string.
static const string TP_VAR = string(`DEMIURGETP`)
The environment variable with the directory containing all third-party software.
Protected Member Functions
void printHelp () const
Prints a help text to stdout.
void initLogger () const
Initializes the Logger by enabling the selected message kinds.
Protected Attributes
string aig_in_file_name_
The name (including the path) of the AIGER input file.
string aig_out_file_name_
The name (including the path) of the AIGER output file.
string print_string_
A string defining which messages to print.
string tmp_dir_
The name of a directory for temporary files.
string back_end_
The name of the selected back-end.
int mode_
The mode of the back-end selected by the user.
string circuit_extraction_name_
The name of the circuit extraction method that should be used.
int circuit_extraction_mode_
The mode of the selected circuit extraction method.
string qbf_solver_
The name of the selected QBF-solver.
string sat_solver_
The name of the selected SAT-solver.
string circuit_sat_solver_
The name of the SAT-solver to be used for circuit extraction.
bool real_only_
True if the back-ends should only compute a winning region but no circuits.
Private Member Functions
Options ()
Constructor.
virtual ~Options ()
Destructor.
Options (const Options &other)
Copy constructor.
Options & operator= (const Options &other)
Assignment operator.
Static Private Attributes
static Options * instance_ = NULL
The one and only instance of this class.
Detailed Description
Parses the command-line options and makes them accessible to the back-ends.
The main purpose of this class is to parse the command-line options. It provides methods not only for accessing the option values but also for instantiating concrete objects (SAT-solvers, QBF-solvers) as selected by the user.
This class is implemented as a Singleton. That is, you cannot instantiate objects of this class with the constructor. Use the method instance() to obtain the one and only instance of this class. This is done for convenience. Every back-end can easily access this object without passing it around.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.1.0
Definition at line 56 of file Options.h.
Constructor & Destructor Documentation
Options::Options () [private]
Constructor.
The constructor is disabled (set private) as this method is implemented as a Singleton. Use the method instance to obtain the one and only instance of this class.
Definition at line 786 of file Options.cpp.
Referenced by instance().
Options::~Options () [private], [virtual]
Destructor.
The destructor is disabled (set private) as this method is implemented as a Singleton. One cannot instantiate objects of this class, so there is no need to be able to delete them.
Definition at line 803 of file Options.cpp.
Options::Options (const Options & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
bool Options::doRealizabilityOnly () const
Returns true if the back-ends should only compute a winning region but no circuits.
Returns
true if the back-ends should only compute a winning region but no circuits.
Definition at line 498 of file Options.cpp.
References real_only_.
const string & Options::getAigInFileName () const
Returns the name (including the path) of the AIGER input file.
Returns
The name (including the path) of the AIGER input file.
Definition at line 321 of file Options.cpp.
References aig_in_file_name_.
Referenced by CNFImplExtractor::insertIntoSpec(), LearningImplExtractor::insertMissingAndFromTrans(), main(), and EPRSynthesizer::run().
const string Options::getAigInFileNameOnly () const
Returns the name of the input file without path and extension.
Returns
The name of the input file without path and extension.
Definition at line 327 of file Options.cpp.
References aig_in_file_name_.
Referenced by StoreImplExtractor::extractCircuit(), getUniqueTmpFileName(), and LoadSynth::run().
const string & Options::getAigOutFileName () const
Returns the name (including the path) of the AIGER output file.
Returns
The name (including the path) of the AIGER output file.
Definition at line 340 of file Options.cpp.
References aig_out_file_name_.
Referenced by CNFImplExtractor::insertIntoSpec().
BackEnd * Options::getBackEnd () const
A factory method to construct a BackEnd, depending on the command-line parameters.
This method returns the back-end that has been selected by the user with command-line parameters.
Note
The returned object has to be deleted by the caller.
Returns
The back-end selected by the user with commend-line options.
Definition at line 352 of file Options.cpp.
References back_end_, getCircuitExtractor(), L_ERR, and mode_.
Referenced by main().
int Options::getBackEndMode () const
Returns the mode of the back-end selected by the user.
Some back-ends can be used in several modes (certain optimizations or heuristics enabled or disabled, etc.). This integer number selects a mode.
Returns
The mode of the back-end selected by the user.
Definition at line 390 of file Options.cpp.
References mode_.
Referenced by LearnSynthSAT::computeWinningRegion(), LearnSynthQBFInd::computeWinningRegion(), and ParallelLearner::ParallelLearner().
const string & Options::getBackEndName () const
Returns the name of the back-end selected by the user.
Returns
The name of the back-end selected by the user.
Definition at line 346 of file Options.cpp.
References back_end_.
int Options::getCircuitExtractionMode () const
Returns the mode of the selected circuit extraction method.
Some circuit extraction methods can be used in several modes (certain optimizations or heuristics enabled or disabled, etc.). This integer number selects a mode.
Returns
The mode of the circuit extraction method selected by the user.
Definition at line 402 of file Options.cpp.
References circuit_extraction_mode_.
const string & Options::getCircuitExtractionName () const
Returns the name of the circuit extraction method that should be used.
Returns
The name of the circuit extraction method that should be used.
Definition at line 396 of file Options.cpp.
References circuit_extraction_name_.
CNFImplExtractor * Options::getCircuitExtractor () const
A factory method to construct circuit extractors, depending on the parameters.
This method returns the circuit extractor that has been selected by the user with command-line parameters.
Note
The returned object has to be deleted by the caller.
Returns
The circuit extractor selected by the user with commend-line options.
Definition at line 408 of file Options.cpp.
References circuit_extraction_name_, and L_ERR.
Referenced by getBackEnd().
QBFSolver * Options::getQBFSolver () const
Returns a fresh instance of the QBF-solver selected by the user.
Calling this method several times will give you different instances of the same solver.
Note
The returned object instance must be deleted by the caller.
Returns
A fresh instance of the QBF-solver selected by the user.
Definition at line 455 of file Options.cpp.
References MASSERT, and qbf_solver_.
Referenced by Utils::debugCheckWinReg().
SatSolver * Options::getSATSolver (bool rand_models = false, bool min_cores = true) const
Returns a fresh instance of the SAT-solver selected by the user.
Calling this method several times will give you different instances of the same solver.
Note
The returned object instance must be deleted by the caller.
Parameters
rand_models A flag indicating if satisfying assignments should be randomized. This is done in a post-processing step (values are flipped randomly and then we check if this still constitutes a satisfying assignment). This is expensive. If this parameter is skipped, then satisfying assignments are not randomized.
min_cores A flag indicating if unsatisfiable cores returned by the solver should be minimized further by trying to drop one literal after the other. This makes the calls slower but produces potentially smaller cubes. If this parameter is skipped, then cores will be further minimized.
Returns
A fresh instance of the SAT-solver selected by the user.
Definition at line 470 of file Options.cpp.
References MASSERT, and sat_solver_.
Referenced by CounterGenSAT::compressBored(), Utils::compressStateCNF(), IFM13Synth::debugCheckInvariants(), Utils::debugCheckWinReg(), getSATSolverExtr(), IFM13Explorer::IFM13Explorer(), IFM13Synth::IFM13Synth(), and Utils::negateStateCNF().
SatSolver * Options::getSATSolverExtr (bool rand_models = false, bool min_cores = true) const
Returns an instance of the SAT-solver selected by the user for circuit extraction.
This method is different from getSATSolver because the user can select a different SAT solver for circuit extraction than for computing the winning region.
Calling this method several times will give you different instances of the same solver.
Note
The returned object instance must be deleted by the caller.
Parameters
rand_models A flag indicating if satisfying assignments should be randomized. This is done in a post-processing step (values are flipped randomly and then we check if this still constitutes a satisfying assignment). This is expensive. If this parameter is skipped, then satisfying assignments are not randomized.
min_cores A flag indicating if unsatisfiable cores returned by the solver should be minimized further by trying to drop one literal after the other. This makes the calls slower but produces potentially smaller cubes. If this parameter is skipped, then cores will be further minimized.
Returns
A fresh instance of the SAT-solver selected by the user.
Definition at line 483 of file Options.cpp.
References circuit_sat_solver_, getSATSolver(), and MASSERT.
Referenced by LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), and LearningImplExtractor::runLearningJiangSATTmpCtrlInc2().
string Options::getTmpDirName () const
Returns the name (including the path) of the directory for temporary files.
Some back-ends or solvers produce temporary files. Store them in the directory returned by this method in order to avoid a mess: If all temporary files are stored in one signle directory, this directory can be deleted manually if something goes wrong.
The directory returned by this method is guaranteed to exist. If it does not, it will be created by this method.
Returns
The mode of the back-end selected by the user.
Definition at line 423 of file Options.cpp.
References MASSERT, and tmp_dir_.
Referenced by ExtQBFSolver::ExtQBFSolver(), and getUniqueTmpFileName().
string Options::getTPDirName () const
Returns the name (and path) of the directory containing the thirdparty tools.
The implementation of this method assumes that there is an environment variable named DEMIURGETP, which holds the name of the directory in which the third-party tools (SAT-solvers, QBF-solvers, logic optimizers, etc.) are installed. This method returns the name of this directory (where the environment variable is already resolved).
Returns
The name (and path) of the directory containing the thirdparty tools.
Definition at line 445 of file Options.cpp.
References MASSERT, and TP_VAR.
Referenced by DepQBFExt::DepQBFExt(), EPRSynthesizer::EPRSynthesizer(), CNFImplExtractor::optimizeWithABC(), and QuBEExt::QuBEExt().
string Options::getUniqueTmpFileName (string start = ``) const
Returns a unique name of a temporary file in the directory of temporary files.
Parameters
start An optional prefix for the file name.
Returns
A unique name of a temporary file in the directory of temporary files.
Definition at line 435 of file Options.cpp.
References getAigInFileNameOnly(), and getTmpDirName().
Referenced by EPRSynthesizer::EPRSynthesizer(), ExtQBFSolver::ExtQBFSolver(), and CNFImplExtractor::optimizeWithABC().
void Options::initLogger () const [protected]
Initializes the Logger by enabling the selected message kinds.
Definition at line 756 of file Options.cpp.
References Logger::DBG, Logger::disable(), Logger::enable(), Logger::ERR, Logger::INF, instance(), Logger::LOG, print_string_, Logger::RES, and Logger::WRN.
Referenced by parse().
Options & Options::instance () [static]
Returns the one and only instance of this class.
This class is implemented as a Singleton. That is, you cannot instantiate objects of this class with the constructor. Use this method to obtain the one and only instance of this class.
Returns
The one and only instance of this class.
Definition at line 65 of file Options.cpp.
References instance_, MASSERT, and Options().
Referenced by CounterGenSAT::compressBored(), Utils::compressStateCNF(), LearnSynthQBFInc::computeWinningRegion(), LearnSynthQBF::computeWinningRegion(), LearnSynthSAT::computeWinningRegion(), LearnSynthQBFInd::computeWinningRegion(), IFM13Synth::debugCheckInvariants(), Utils::debugCheckWinReg(), DepQBFExt::DepQBFExt(), EPRSynthesizer::EPRSynthesizer(), ExtQBFSolver::ExtQBFSolver(), StoreImplExtractor::extractCircuit(), IFM13Synth::getGenBlockTransSolver(), IFM13Explorer::getGenBlockTransSolver(), IFM13Synth::getGotoNextLowerSolver(), IFM13Explorer::getGotoNextLowerSolver(), IFM13Explorer::IFM13Explorer(), IFM13Synth::IFM13Synth(), initLogger(), CNFImplExtractor::insertIntoSpec(), LearningImplExtractor::insertMissingAndFromTrans(), LearnSynthQBFInd::LearnSynthQBFInd(), main(), Utils::negateStateCNF(), CNFImplExtractor::optimizeWithABC(), ParallelLearner::ParallelLearner(), QuBEExt::QuBEExt(), LoadSynth::run(), LearnSynthQBFInc::run(), LearningImplExtractor::run(), IFM13Synth::run(), ParallelLearner::run(), TemplateSynth::run(), LearnSynthQBF::run(), EPRSynthesizer::run(), LearnSynthSAT::run(), LearnSynthQBFInd::run(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), and LearningImplExtractor::runLearningJiangSATTmpCtrlInc2().
Options& Options::operator= (const Options & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
bool Options::parse (int argc, char ** argv)
Parses the command-line options and stores them in fields of this class.
Parameters
argc The number of arguments passed to main.
argv The arguments passed to main. argv_[0] is the name of the process, the real arguments start with argv_[1].
Returns
True if the tool should quit, false otherwise.
Definition at line 74 of file Options.cpp.
References aig_in_file_name_, aig_out_file_name_, back_end_, circuit_extraction_mode_, circuit_extraction_name_, circuit_sat_solver_, initLogger(), L_WRN, mode_, print_string_, printHelp(), qbf_solver_, real_only_, sat_solver_, tmp_dir_, StringUtils::toLowerCaseIn(), and VERSION.
Referenced by main().
void Options::printHelp () const [protected]
Prints a help text to stdout.
Definition at line 504 of file Options.cpp.
Referenced by parse().
Member Data Documentation
string Options::aig_in_file_name_ [protected]
The name (including the path) of the AIGER input file.
Definition at line 275 of file Options.h.
Referenced by getAigInFileName(), getAigInFileNameOnly(), and parse().
string Options::aig_out_file_name_ [protected]
The name (including the path) of the AIGER output file.
Definition at line 280 of file Options.h.
Referenced by getAigOutFileName(), and parse().
string Options::back_end_ [protected]
The name of the selected back-end.
Definition at line 307 of file Options.h.
Referenced by getBackEnd(), getBackEndName(), and parse().
int Options::circuit_extraction_mode_ [protected]
The mode of the selected circuit extraction method.
Some circuit extraction methods can be used in several modes (certain optimizations or heuristics enabled or disabled, etc.). This integer number selects a mode.
Definition at line 328 of file Options.h.
Referenced by getCircuitExtractionMode(), and parse().
string Options::circuit_extraction_name_ [protected]
The name of the circuit extraction method that should be used.
Definition at line 320 of file Options.h.
Referenced by getCircuitExtractionName(), getCircuitExtractor(), and parse().
string Options::circuit_sat_solver_ [protected]
The name of the SAT-solver to be used for circuit extraction.
This is different from sat_solver_ because the user may select a different solver for circuit extraction than for computing the winning region.
Definition at line 346 of file Options.h.
Referenced by getSATSolverExtr(), and parse().
Options * Options::instance_ = NULL [static], [private]
The one and only instance of this class.
Definition at line 395 of file Options.h.
Referenced by instance().
int Options::mode_ [protected]
The mode of the back-end selected by the user.
Some back-ends can be used in several modes (certain optimizations or heuristics enabled or disabled, etc.). This integer number selects a mode.
Definition at line 315 of file Options.h.
Referenced by getBackEnd(), getBackEndMode(), and parse().
string Options::print_string_ [protected]
A string defining which messages to print.
The string can be composed of the letters D,E,R,W,I,L in any order. If a letter occurs in the string, then this means that the respective message kind is enabled. If it does not occur in the string, then the message kind is disabled.
E enables error messages.
W enables warnings.
I enables info messages.
R enables result messages.
L enables log messages.
D enables debug messages.
Definition at line 297 of file Options.h.
Referenced by initLogger(), and parse().
string Options::qbf_solver_ [protected]
The name of the selected QBF-solver.
Definition at line 333 of file Options.h.
Referenced by getQBFSolver(), and parse().
bool Options::real_only_ [protected]
True if the back-ends should only compute a winning region but no circuits.
Definition at line 351 of file Options.h.
Referenced by doRealizabilityOnly(), and parse().
string Options::sat_solver_ [protected]
The name of the selected SAT-solver.
Definition at line 338 of file Options.h.
Referenced by getSATSolver(), and parse().
string Options::tmp_dir_ [protected]
The name of a directory for temporary files.
Definition at line 302 of file Options.h.
Referenced by getTmpDirName(), and parse().
const string Options::TP_VAR = string(`DEMIURGETP`) [static]
The environment variable with the directory containing all third-party software.
The third-party software includes SAT-solvers, QBF-solvers, etc.
Definition at line 70 of file Options.h.
Referenced by getTPDirName().
const string Options::VERSION = string(`1.1.0`) [static]
The version of the tool as string.
Definition at line 63 of file Options.h.
Referenced by parse().
The documentation for this class was generated from the following files:
src/Options.h
src/Options.cpp