VarManager Class Reference
Stores and maintains all Boolean variables that have (ever) been created.
#include <VarManager.h>
Public Member Functions
void initFromAig (aiger *aig, const vector< bool > &refs)
Initializes the VarManager from the AIGER input file structure.
void clear ()
Completely clears the VarManager. All variables are gone then.
int createFreshTmpVar ()
Creates and returns a fresh variable of type VarInfo::TMP.
int createFreshTmpVar (const string &name)
Creates and returns a fresh named variable of type VarInfo::TMP.
int createFreshTemplParam ()
Creates and returns a fresh variable of type VarInfo::TEMPL_PARAMS.
int createFreshTemplParam (const string &name)
Creates and returns a fresh named variable of type VarInfo::TEMPL_PARAMS.
int createFreshPrevVar ()
Creates and returns a fresh variable of type VarInfo::PREV.
int createFreshPrevVar (const string &name)
Creates and returns a fresh named variable of type VarInfo::PREV.
const VarInfo & getInfo (int var_in_cnf) const
Returns additional information to a CNF variable.
int aigLitToCnfLit (unsigned aig_lit) const
Takes an AIGER literal and returns the corresponding CNF-literal.
const vector< int > & getVarsOfType (VarInfo::VarKind var_kind) const
Returns the CNF representation of all variables of a given kind.
vector< int > getAllNonTempVars () const
Returns the CNF representation of all variables that are not of type VarInfo::TMP.
int getPresErrorStateVar () const
Returns the present-state variable saying that we have a safety error now.
int getNextErrorStateVar () const
Returns the next-state variable saying that we have a safety error next.
int getMaxCNFVar () const
Returns the maximum index of all CNF variables.
int getMaxAIGVar () const
Returns the maximum index of all AIGER variables.
string toString ()
Returns a string containing all (or most) information stored in this object.
Static Public Member Functions
static VarManager & instance ()
Returns the one and only instance of this class.
static void push ()
Pushes the current state of this object onto a stack.
static void pop ()
Restores the VarManager to the last push and removes the data from the stack.
static void resetToLastPush ()
Restores the VarManager to the last push but does not pop the stack.
Protected Types
typedef map< int, VarInfo >
*
::const_iterator VarsConstIter
A type for a const-iterator over the variable map.
typedef map< int, VarInfo >
*
::iterator VarIter
A type for an iterator over the variable map.
Protected Attributes
map< int, VarInfo > vars_
All variables created so far.
int max_cnf_var_
The maximum index of all CNF variables.
int max_aig_var_
The maximum index of all AIGER variables.
vector< int > aig_to_cnf_lit_map_
A map from AIGER literals to CNF literals.
vector< int > inputs_
The CNF representation of all (uncontrollable) inputs (type VarManager::INPUT).
vector< int > ctrl_vars_
The CNF representation of all control signals (type VarManager::CTRL).
vector< int > pres_state_vars_
The CNF representation of all state variables (type VarManager::PRES_STATE).
vector< int > next_state_vars_
The CNF representation of all next-state variables (type VarManager::NEXT_STATE).
vector< int > tmp_vars_
The CNF representation of all temporary variables (type VarManager::TMP).
vector< int > templs_params_
The CNF representation of all parameters (type VarManager::TEMPL_PARAMS).
vector< int > prev_vars_
The CNF representation of all previous-step variables (type VarManager::PREV).
Private Member Functions
VarManager ()
Constructor.
virtual ~VarManager ()
Destructor.
VarManager (const VarManager &other)
Copy constructor.
VarManager & operator= (const VarManager &other)
Assignment operator.
Static Private Attributes
static vector< VarManager * > stack_
Detailed Description
Stores and maintains all Boolean variables that have (ever) been created.
This is mainly a container which stores all Boolean variables that have been created. It also provides methods to create new variables, to retrieve variables of different kinds, and to get additional information to variables.
This class is implemented as a Singleton. That is, you cannot instantiate objects of this class with the constructor. Use the method instance() to obtain the one and only instance of this class.
Definition at line 50 of file VarManager.h.
Member Typedef Documentation
map< int, VarInfo >::iterator VarManager::VarIter [protected]
A type for an iterator over the variable map.
Definition at line 335 of file VarManager.h.
map< int, VarInfo >::const_iterator VarManager::VarsConstIter [protected]
A type for a const-iterator over the variable map.
Definition at line 329 of file VarManager.h.
Constructor & Destructor Documentation
VarManager::VarManager () [private]
Constructor.
The constructor is disabled (set private) as this method is implemented as a Singleton. Use the method instance() to obtain the one and only instance of this class.
Definition at line 369 of file VarManager.cpp.
References templs_params_.
Referenced by instance(), and push().
VarManager::~VarManager () [private], [virtual]
Destructor.
The destructor is disabled (set private) as this method is implemented as a Singleton. One cannot instantiate objects of this class, so there is no need to be able to delete them.
Definition at line 375 of file VarManager.cpp.
VarManager::VarManager (const VarManager & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Definition at line 381 of file VarManager.cpp.
Member Function Documentation
int VarManager::aigLitToCnfLit (unsigned aig_lit) const
Takes an AIGER literal and returns the corresponding CNF-literal.
Parameters
aig_lit Some AIGER literal.
Returns
The corresponding CNF literal.
Definition at line 274 of file VarManager.cpp.
References aig_to_cnf_lit_map_, and MASSERT.
Referenced by AIG2CNF::initFromAig().
void VarManager::clear ()
Completely clears the VarManager. All variables are gone then.
Definition at line 203 of file VarManager.cpp.
References aig_to_cnf_lit_map_, ctrl_vars_, inputs_, max_aig_var_, max_cnf_var_, next_state_vars_, pres_state_vars_, prev_vars_, templs_params_, tmp_vars_, and vars_.
Referenced by initFromAig().
int VarManager::createFreshPrevVar ()
Creates and returns a fresh variable of type VarInfo::PREV.
Returns
The (CNF representation of the) newly created fresh previous-time-step variable.
Definition at line 251 of file VarManager.cpp.
Referenced by ParallelLearner::computePreviousTrans(), LearnSynthQBFInd::LearnSynthQBFInd(), and LearnSynthSAT::LearnSynthSAT().
int VarManager::createFreshPrevVar (const string & name)
Creates and returns a fresh named variable of type VarInfo::PREV.
Parameters
name The name of the newly created previous-time-step variable.
Returns
The (CNF representation of the) newly created fresh previous-time-step variable.
Definition at line 257 of file VarManager.cpp.
References max_cnf_var_, VarInfo::PREV, prev_vars_, and vars_.
int VarManager::createFreshTemplParam ()
Creates and returns a fresh variable of type VarInfo::TEMPL_PARAMS.
Returns
The (CNF representation of the) newly created fresh parameter variable.
Definition at line 235 of file VarManager.cpp.
Referenced by TemplateSynth::findWinRegCNFTempl().
int VarManager::createFreshTemplParam (const string & name)
Creates and returns a fresh named variable of type VarInfo::TEMPL_PARAMS.
Parameters
name The name of the newly created parameter variable.
Returns
The (CNF representation of the) newly created fresh parameter variable.
Definition at line 241 of file VarManager.cpp.
References max_cnf_var_, VarInfo::TEMPL_PARAMS, templs_params_, and vars_.
int VarManager::createFreshTmpVar ()
Creates and returns a fresh variable of type VarInfo::TMP.
Returns
The (CNF representation of the) newly created fresh temporary variable.
Definition at line 219 of file VarManager.cpp.
Referenced by ParallelLearner::computePreviousTrans(), TemplateSynth::findWinRegCNFTempl(), AIG2CNF::initFromAig(), LearnSynthQBFInd::LearnSynthQBFInd(), LearnSynthSAT::LearnSynthSAT(), and CNF::negate().
int VarManager::createFreshTmpVar (const string & name)
Creates and returns a fresh named variable of type VarInfo::TMP.
Parameters
name The name of the newly created temporary variable.
Returns
The (CNF representation of the) newly created fresh temporary variable.
Definition at line 225 of file VarManager.cpp.
References max_cnf_var_, VarInfo::TMP, tmp_vars_, and vars_.
vector< int > VarManager::getAllNonTempVars () const
Returns the CNF representation of all variables that are not of type VarInfo::TMP.
Returns
The CNF representation of all variables that are not of type VarInfo::TMP.
Definition at line 300 of file VarManager.cpp.
References ctrl_vars_, inputs_, next_state_vars_, pres_state_vars_, prev_vars_, and templs_params_.
Referenced by LearnSynthSAT::computeWinningRegionRG(), and LearnSynthSAT::computeWinningRegionRGRC().
const VarInfo & VarManager::getInfo (int var_in_cnf) const
Returns additional information to a CNF variable.
Parameters
var_in_cnf The CNF representation of the variable for which additional information is requested. It is an error if the requested variable does not exist.
Returns
Additional information to a CNF variable.
Definition at line 267 of file VarManager.cpp.
References MASSERT, and vars_.
Referenced by QBFCertImplExtractor::parseQBFCertAnswer(), LearnSynthQBFInc::restrictToStates(), LearnSynthQBF::restrictToStates(), and LearnSynthQBFInd::restrictToStates().
int VarManager::getMaxAIGVar () const
Returns the maximum index of all AIGER variables.
Returns
The maximum index of all AIGER variables. That is, if the value N is returned, then this means that there exists the AIGER-variables 1,2,3,...,N. The exists no AIGER-variable with index greater than N.
Definition at line 338 of file VarManager.cpp.
References max_aig_var_.
Referenced by QBFCertImplExtractor::parseQBFCertAnswer().
int VarManager::getMaxCNFVar () const
Returns the maximum index of all CNF variables.
Returns
The maximum index of all CNF variables. That is, if the value N is returned, then this means that there exists the CNF-variables 1,2,3,...,N. The exists no CNF-variable with index greater than N.
Definition at line 332 of file VarManager.cpp.
References max_cnf_var_.
Referenced by ParallelLearner::computePreviousTrans(), ExtQBFSolver::dumpQBF(), TemplateSynth::findWinRegCNFTempl(), DepQBFApi::initBloqqer(), DepQBFApiInc::initBloqqer(), DepQBFApi::initDepQBF(), DepQBFApiInc::initDepQBF(), LearnSynthQBFInd::LearnSynthQBFInd(), LearnSynthSAT::LearnSynthSAT(), DepQBFApiInc::startIncrementalSession(), Utils::swapPresentToNext(), and CNF::swapPresentToNext().
int VarManager::getNextErrorStateVar () const
Returns the next-state variable saying that we have a safety error next.
In the AIGER input file, the error is an output. It can depend on the current state and the input. In order to have a notion of safe and unsafe states, we 'latch' this error output and make it part of the state space. This is supposed to make the life of the synthesis algorithm easier.
Returns
The (CNF representation of the) next-state variable saying that we have a safety error in the next time step. This is the next-state copy of the variable returned by getPresErrorStateVar().
Definition at line 326 of file VarManager.cpp.
References next_state_vars_.
Referenced by TemplateSynth::findWinRegCNFTempl(), and AIG2CNF::initFromAig().
int VarManager::getPresErrorStateVar () const
Returns the present-state variable saying that we have a safety error now.
In the AIGER input file, the error is an output. It can depend on the current state and the input. In order to have a notion of safe and unsafe states, we 'latch' this error output and make it part of the state space. This is supposed to make the life of the synthesis algorithm easier.
Returns
The (CNF representation of the) present-state variable saying that we have a safety error now.
Definition at line 320 of file VarManager.cpp.
References pres_state_vars_.
Referenced by LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), TemplateSynth::findWinRegCNFTempl(), AIG2CNF::initFromAig(), LearnSynthQBFInc::restrictToStates(), LearnSynthQBF::restrictToStates(), and LearnSynthQBFInd::restrictToStates().
const vector< int > & VarManager::getVarsOfType (VarInfo::VarKind var_kind) const
Returns the CNF representation of all variables of a given kind.
Parameters
var_kind The requested variable kind.
Returns
The CNF representation of all variables of the given kind.
Definition at line 281 of file VarManager.cpp.
References VarInfo::CTRL, ctrl_vars_, VarInfo::INPUT, inputs_, VarInfo::NEXT_STATE, next_state_vars_, VarInfo::PRES_STATE, pres_state_vars_, VarInfo::PREV, prev_vars_, VarInfo::TEMPL_PARAMS, templs_params_, and tmp_vars_.
Referenced by ClauseMinimizerQBF::ClauseMinimizerQBF(), LearnSynthQBF::computeCounterexampleSAT(), ParallelLearner::computePreviousTrans(), IFM13Synth::computeWinningRegion(), TemplateSynth::computeWinningRegion(), LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOneSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), DepQBFApi::debugCheckBloqqerModel(), DepQBFApiInc::debugCheckBloqqerModel(), ExtQBFSolver::dumpQBF(), ClauseExplorerSAT::exploreClauses(), Utils::extract(), Utils::extractNextAsPresent(), Utils::extractPresIn(), TemplateSynth::findWinRegCNFTempl(), CounterGenSAT::generalizeCounterexamples(), IFM13Explorer::IFM13Explorer(), IFM13Synth::IFM13Synth(), DepQBFApi::initBloqqer(), DepQBFApiInc::initBloqqer(), DepQBFApi::initDepQBF(), DepQBFApiInc::initDepQBF(), AIG2CNF::initFromAig(), DepQBFApi::isSatModel(), DepQBFApiInc::isSatModel(), LearnSynthQBFInd::LearnSynthQBFInd(), LearnSynthSAT::LearnSynthSAT(), QBFCertImplExtractor::parseQBFCertAnswer(), DepQBFApiInc::startIncrementalSession(), Utils::swapPresentToNext(), and CNF::swapPresentToNext().
void VarManager::initFromAig (aiger * aig, const vector< bool > & refs)
Initializes the VarManager from the AIGER input file structure.
That is, this method creates variables for all signals that occur in the AIGER circuit. An additional vector defines which signals of the AIGER circuit are actually going to be used.
Parameters
aig An AIGER structure defining a circuit. This is typically the content of the AIGER input file. We create variables for the signals occurring in this structure.
refs A vector defining which signals are actually going to be used. It maps AIGER literals to either true or false. If a literal is mapped to true, we will create a variable for it, otherwise not.
Definition at line 92 of file VarManager.cpp.
References aig_to_cnf_lit_map_, clear(), VarInfo::CTRL, ctrl_vars_, VarInfo::INPUT, inputs_, MASSERT, max_aig_var_, max_cnf_var_, VarInfo::NEXT_STATE, next_state_vars_, VarInfo::PRES_STATE, pres_state_vars_, VarInfo::TMP, tmp_vars_, StringUtils::toLowerCase(), and vars_.
Referenced by AIG2CNF::initFromAig().
VarManager & VarManager::instance () [static]
Returns the one and only instance of this class.
This class is implemented as a Singleton. That is, you cannot instantiate objects of this class with the constructor. Use this method to obtain the one and only instance of this class.
Returns
The one and only instance of this class.
Definition at line 41 of file VarManager.cpp.
References MASSERT, stack_, and VarManager().
Referenced by IFM13Synth::addBlockedState(), ClauseMinimizerQBF::ClauseMinimizerQBF(), CounterGenSAT::compressBored(), Utils::compressStateCNF(), LearnSynthQBF::computeCounterexampleSAT(), ParallelLearner::computePreviousTrans(), IFM13Synth::computeWinningRegion(), TemplateSynth::computeWinningRegion(), LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOneSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), DepQBFApi::debugCheckBloqqerModel(), DepQBFApiInc::debugCheckBloqqerModel(), ExtQBFSolver::dumpQBF(), ClauseExplorerSAT::exploreClauses(), Utils::extract(), Utils::extractNextAsPresent(), Utils::extractPresIn(), TemplateSynth::findWinRegCNFTempl(), CounterGenSAT::generalizeCounterexamples(), IFM13Explorer::IFM13Explorer(), IFM13Synth::IFM13Synth(), DepQBFApi::initBloqqer(), DepQBFApiInc::initBloqqer(), DepQBFApi::initDepQBF(), DepQBFApiInc::initDepQBF(), AIG2CNF::initFromAig(), DepQBFApi::isSatModel(), DepQBFApiInc::isSatModel(), LearnSynthQBFInd::LearnSynthQBFInd(), LearnSynthSAT::LearnSynthSAT(), main(), CNF::negate(), QBFCertImplExtractor::parseQBFCertAnswer(), LearnSynthQBFInc::restrictToStates(), LearnSynthQBF::restrictToStates(), LearnSynthQBFInd::restrictToStates(), LearnSynthQBFInc::run(), ParallelLearner::run(), LearnSynthQBF::run(), LearnSynthSAT::run(), LearnSynthQBFInd::run(), DepQBFApiInc::startIncrementalSession(), Utils::swapPresentToNext(), CNF::swapPresentToNext(), and ParallelLearner::triggerExplorerRestart().
VarManager& VarManager::operator= (const VarManager & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
void VarManager::pop () [static]
Restores the VarManager to the last push and removes the data from the stack.
Definition at line 82 of file VarManager.cpp.
References stack_.
Referenced by TemplateSynth::computeWinningRegion().
void VarManager::push () [static]
Pushes the current state of this object onto a stack.
The methods pop() and resetToLastPush() can then be used later to restore the pushed state again. This can be convenient for the following reason. Certain methods may create tons of temporary variables, which are not used after a certain point. All these temporary variables may slow down this class and may consume quite a bit of memory. The temporary variables can be discarded by calling a push() before and a pop() or resetToLastPush() after the code block that produces all the temporary variables. But there are other scenarios, of course.
Definition at line 55 of file VarManager.cpp.
References stack_, and VarManager().
Referenced by TemplateSynth::computeWinningRegion(), LearnSynthQBFInc::run(), ParallelLearner::run(), LearnSynthQBF::run(), LearnSynthSAT::run(), and LearnSynthQBFInd::run().
void VarManager::resetToLastPush () [static]
Restores the VarManager to the last push but does not pop the stack.
That is, you can call resetToLastPush() several times to restore the state of the VarManager. E.g.
VarManager::instance().push()
 // do something
VarManager::instance().resetToLastPush()
 // do something else
VarManager::instance().resetToLastPush()
 // and so on
 This is not possible with pop().
Definition at line 63 of file VarManager.cpp.
References aig_to_cnf_lit_map_, ctrl_vars_, inputs_, MASSERT, max_aig_var_, max_cnf_var_, next_state_vars_, pres_state_vars_, prev_vars_, stack_, templs_params_, tmp_vars_, and vars_.
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthQBFInc::recomputeCheckCNF(), LearnSynthQBF::recomputeCheckCNF(), LearnSynthQBFInd::recomputeCheckCNF(), and ParallelLearner::triggerExplorerRestart().
string VarManager::toString ()
Returns a string containing all (or most) information stored in this object.
This is mainly useful for debugging.
Returns
A string containing all (or most) information stored in this object.
Definition at line 344 of file VarManager.cpp.
References VarInfo::CTRL, VarInfo::getKind(), VarInfo::getLitInAIG(), VarInfo::getLitInCNF(), VarInfo::getName(), VarInfo::INPUT, VarInfo::NEXT_STATE, VarInfo::PRES_STATE, VarInfo::PREV, VarInfo::TEMPL_PARAMS, VarInfo::TMP, and vars_.
Member Data Documentation
vector<int> VarManager::aig_to_cnf_lit_map_ [protected]
A map from AIGER literals to CNF literals.
This map is implemented as a vector because the number of AIGER literals is defined by the input file and does not change.
Definition at line 284 of file VarManager.h.
Referenced by aigLitToCnfLit(), clear(), initFromAig(), and resetToLastPush().
vector<int> VarManager::ctrl_vars_ [protected]
The CNF representation of all control signals (type VarManager::CTRL).
Definition at line 294 of file VarManager.h.
Referenced by clear(), getAllNonTempVars(), getVarsOfType(), initFromAig(), and resetToLastPush().
vector<int> VarManager::inputs_ [protected]
The CNF representation of all (uncontrollable) inputs (type VarManager::INPUT).
Definition at line 289 of file VarManager.h.
Referenced by clear(), getAllNonTempVars(), getVarsOfType(), initFromAig(), and resetToLastPush().
int VarManager::max_aig_var_ [protected]
The maximum index of all AIGER variables.
That means: there exists the AIGER-variables 1,2,3,...,max_aig_var_. The exists no AIGER-variable with index greater than max_aig_var_.
Definition at line 276 of file VarManager.h.
Referenced by clear(), getMaxAIGVar(), initFromAig(), and resetToLastPush().
int VarManager::max_cnf_var_ [protected]
The maximum index of all CNF variables.
That means: there exists the CNF-variables 1,2,3,...,max_cnf_var_. The exists no CNF-variable with index greater than max_cnf_var_.
Definition at line 268 of file VarManager.h.
Referenced by clear(), createFreshPrevVar(), createFreshTemplParam(), createFreshTmpVar(), getMaxCNFVar(), initFromAig(), and resetToLastPush().
vector<int> VarManager::next_state_vars_ [protected]
The CNF representation of all next-state variables (type VarManager::NEXT_STATE).
pres_state_vars_ and next_state_vars_ have the same length. next_state_vars_ contains the next-state copies of all pres_state_vars_.
Definition at line 307 of file VarManager.h.
Referenced by clear(), getAllNonTempVars(), getNextErrorStateVar(), getVarsOfType(), initFromAig(), and resetToLastPush().
vector<int> VarManager::pres_state_vars_ [protected]
The CNF representation of all state variables (type VarManager::PRES_STATE).
Definition at line 299 of file VarManager.h.
Referenced by clear(), getAllNonTempVars(), getPresErrorStateVar(), getVarsOfType(), initFromAig(), and resetToLastPush().
vector<int> VarManager::prev_vars_ [protected]
The CNF representation of all previous-step variables (type VarManager::PREV).
Definition at line 322 of file VarManager.h.
Referenced by clear(), createFreshPrevVar(), getAllNonTempVars(), getVarsOfType(), and resetToLastPush().
vector< VarManager * > VarManager::stack_ [static], [private]
A stack for the instances of this object.
This is a singleton. However, we allow push() and pop(), so we store the stack of VarManager configurations on a stack. The current VarManager is always located at the top of the stack (the end of the vector).
Definition at line 384 of file VarManager.h.
Referenced by instance(), pop(), push(), and resetToLastPush().
vector<int> VarManager::templs_params_ [protected]
The CNF representation of all parameters (type VarManager::TEMPL_PARAMS).
Definition at line 317 of file VarManager.h.
Referenced by clear(), createFreshTemplParam(), getAllNonTempVars(), getVarsOfType(), resetToLastPush(), and VarManager().
vector<int> VarManager::tmp_vars_ [protected]
The CNF representation of all temporary variables (type VarManager::TMP).
Definition at line 312 of file VarManager.h.
Referenced by clear(), createFreshTmpVar(), getVarsOfType(), initFromAig(), and resetToLastPush().
map<int, VarInfo> VarManager::vars_ [protected]
All variables created so far.
The variables are stored in a map where the key is the CNF-representation of the variable, and the value is a VarInfo object storing additional information to this variable.
Definition at line 260 of file VarManager.h.
Referenced by clear(), createFreshPrevVar(), createFreshTemplParam(), createFreshTmpVar(), getInfo(), initFromAig(), resetToLastPush(), and toString().
The documentation for this class was generated from the following files:
src/VarManager.h
src/VarManager.cpp