VarInfo Class Reference
Stores additional information to a variable.
#include <VarInfo.h>
Public Types
enum VarKind {
*
PRES_STATE,
NEXT_STATE,
INPUT,
CTRL,
*
TMP,
TEMPL_PARAMS,
PREV
 }
A type for the kind of variable.
Public Member Functions
VarInfo (VarKind var_kind, int lit_in_cnf, int lit_in_aig)
Constructor without name.
VarInfo (VarKind var_kind, int lit_in_cnf, int lit_in_aig, const string &name)
Constructor without name.
VarInfo (const VarInfo &other)
Copy constructor.
virtual VarInfo & operator= (const VarInfo &other)
Assignment operator.
virtual ~VarInfo ()
Destructor.
VarKind getKind () const
Returns the kind of this variable.
int getLitInCNF () const
Returns the index with which this variable occurs in the CNFs.
int getLitInAIG () const
Returns the index with which this variable occurs in the AIGER input file.
const string & getName () const
Returns the name of the variable.
void setKind (VarKind kind)
Sets the kind of the variable.
void setName (const string &name)
Sets the name of the variable.
Protected Attributes
VarKind var_kind_
The kind of the variable.
int lit_in_cnf_
The index with which this variable occurs in the CNFs.
int lit_in_aig_
The index with which this variable occurs in the AIGER input file.
string name_
The name of the variable.
Detailed Description
Stores additional information to a variable.
At the moment, a variable has a kind, a name (optional), an index with which id appears in the AIGER input file, and an index with which is appears in CNF formulas. This class is mainly a container for all this information without any intelligence.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.1.0
Definition at line 46 of file VarInfo.h.
Member Enumeration Documentation
enum VarInfo::VarKind
A type for the kind of variable.
Enumerator:
PRES_STATE
 The value for present-state variables.
NEXT_STATE
 The value for next-state variables.
INPUT
 The value for uncontrollable input variables.
CTRL
 The value for controllable variables.
TMP
 The value for temporary variables without any special meaning. These are usually Tseitin variables that are just abbreviations for some formulas.
TEMPL_PARAMS
 The value for template parameter variables. This kind is only used by TemplateSynth.
PREV
 The value for previous-time-step variables. This kind is used for the previous-state copy of state variables but also inputs and control signals. At the moment, it is mainly used for optimization RG and RC in LearnSynthSAT and LearnSynthQBFInd.
Definition at line 53 of file VarInfo.h.
Constructor & Destructor Documentation
VarInfo::VarInfo (VarKind var_kind, int lit_in_cnf, int lit_in_aig)
Constructor without name.
Parameters
var_kind The kind of the variable.
lit_in_cnf The index with which this variable occurs in the CNFs.
lit_in_aig The index with which this variable occurs in the AIGER input file.
Definition at line 33 of file VarInfo.cpp.
VarInfo::VarInfo (VarKind var_kind, int lit_in_cnf, int lit_in_aig, const string & name)
Constructor without name.
Parameters
var_kind The kind of the variable.
lit_in_cnf The index with which this variable occurs in the CNFs.
lit_in_aig The index with which this variable occurs in the AIGER input file.
name The name of the variable.
Definition at line 43 of file VarInfo.cpp.
VarInfo::VarInfo (const VarInfo & other)
Copy constructor.
Makes a copy of the VarInfo.
Parameters
other The source for creating the copy.
Definition at line 53 of file VarInfo.cpp.
VarInfo::~VarInfo () [virtual]
Destructor.
Definition at line 73 of file VarInfo.cpp.
Member Function Documentation
VarInfo::VarKind VarInfo::getKind () const
Returns the kind of this variable.
Returns
The kind of this variable.
Definition at line 79 of file VarInfo.cpp.
References var_kind_.
Referenced by LearnSynthQBFInc::restrictToStates(), LearnSynthQBF::restrictToStates(), LearnSynthQBFInd::restrictToStates(), and VarManager::toString().
int VarInfo::getLitInAIG () const
Returns the index with which this variable occurs in the AIGER input file.
Returns
The index with which this variable occurs in the AIGER input file.
Definition at line 91 of file VarInfo.cpp.
References lit_in_aig_.
Referenced by CNFImplExtractor::insertIntoSpec(), LearningImplExtractor::LearningImplExtractor(), and VarManager::toString().
int VarInfo::getLitInCNF () const
Returns the index with which this variable occurs in the CNFs.
Returns
The index with which this variable occurs in the CNFs.
Definition at line 85 of file VarInfo.cpp.
References lit_in_cnf_.
Referenced by operator<(), and VarManager::toString().
const string & VarInfo::getName () const
Returns the name of the variable.
Returns
The name of the variable. If no name was set, the returned string is empty.
Definition at line 97 of file VarInfo.cpp.
References name_.
Referenced by LearningImplExtractor::LearningImplExtractor(), and VarManager::toString().
VarInfo & VarInfo::operator= (const VarInfo & other) [virtual]
Assignment operator.
Makes this object a copy of another object.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
Definition at line 63 of file VarInfo.cpp.
References lit_in_aig_, lit_in_cnf_, name_, and var_kind_.
void VarInfo::setKind (VarKind kind)
Sets the kind of the variable.
Parameters
kind The new kind of the variable.
Definition at line 103 of file VarInfo.cpp.
References var_kind_.
void VarInfo::setName (const string & name)
Sets the name of the variable.
Parameters
name The new name of the variable.
Definition at line 109 of file VarInfo.cpp.
References name_.
Member Data Documentation
int VarInfo::lit_in_aig_ [protected]
The index with which this variable occurs in the AIGER input file.
Definition at line 200 of file VarInfo.h.
Referenced by getLitInAIG(), and operator=().
int VarInfo::lit_in_cnf_ [protected]
The index with which this variable occurs in the CNFs.
Definition at line 195 of file VarInfo.h.
Referenced by getLitInCNF(), and operator=().
string VarInfo::name_ [protected]
The name of the variable.
This can be an empty string if the variable has no name.
Definition at line 207 of file VarInfo.h.
Referenced by getName(), operator=(), and setName().
VarKind VarInfo::var_kind_ [protected]
The kind of the variable.
Definition at line 190 of file VarInfo.h.
Referenced by getKind(), operator=(), and setKind().
The documentation for this class was generated from the following files:
src/VarInfo.h
src/VarInfo.cpp