Logger Class Reference
Prints messages of different kind, which can all be enabled and disabled.
#include <Logger.h>
Public Types
enum Logtype {
*
ERR = 0,
WRN = 1,
RES = 2,
INF = 3,
*
DBG = 4,
LOG = 5
 }
A type for the kind of message.
Public Member Functions
void enable (Logtype lt)
Enables the printing of a certain kind of message.
void disable (Logtype lt)
Disables the printing of a certain kind of message.
bool isEnabled (Logtype lt) const
Checks if a certain kind of message is enabled.
ostream & getOstream (Logtype lt)
Returns the output stream for a certain kind of message.
Static Public Member Functions
static Logger & instance ()
Returns the one and only instance of this class.
Protected Attributes
vector< ostream * > streams_
The output streams to be used for the different kinds of messages.
vector< bool > enabled_
The flags indicating which kind of message is enabled.
Static Protected Attributes
static Logger * instance_ = NULL
The one and only instance of this class.
Private Member Functions
Logger ()
Constructor.
virtual ~Logger ()
Destructor.
Logger (const Logger &other)
Copy constructor.
Logger & operator= (const Logger &other)
Assignment operator.
Detailed Description
Prints messages of different kind, which can all be enabled and disabled.
This utility class is able to print 6 different types of messages: ERRORs, WARNINGs RESULTs, INFOs, DEBUG messages and LOG messages. Every kind of message can be enabled and disabled. Do not directly print to stdout or stderr but use this class instead (except for special cases like printing messages before this Logger has been initialized).
This class is implemented as a Singleton. That is, you cannot instantiate objects of this class with the constructor. Use the method instance() to obtain the one and only instance of this class.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.1.0
Definition at line 52 of file Logger.h.
Member Enumeration Documentation
enum Logger::Logtype
A type for the kind of message.
Enumerator:
ERR
 The value for error messages. Use this kind for messages like 'could not open file'.
WRN
 The value for warnings. Use this kind for messages like 'pending signal'.
RES
 The value for printing results. Use this kind for messages like 'the spec is realizable'.
INF
 The value for printing additional information. Use this kind for messages like 'starting to compute a circuit ...'.
DBG
 The value for printing debug messages. Use this kind for messages like 'the aiger literal 4 corresponds to 12 in CNF'.
LOG
 The value for printing log messages. This is typically used for performance measures in messages like 'computing the winning region took 16 seconds'.
Definition at line 70 of file Logger.h.
Constructor & Destructor Documentation
Logger::Logger () [private]
Constructor.
The constructor is disabled (set private) as this method is implemented as a Singleton. Use the method instance to obtain the one and only instance of this class.
Definition at line 45 of file Logger.cpp.
References enabled_, and streams_.
Referenced by instance().
Logger::~Logger () [private], [virtual]
Destructor.
The destructor is disabled (set private) as this method is implemented as a Singleton. One cannot instantiate objects of this class, so there is no need to be able to delete them.
Definition at line 62 of file Logger.cpp.
References streams_.
Logger::Logger (const Logger & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void Logger::disable (Logtype lt)
Disables the printing of a certain kind of message.
If a message kind is disabled, all messaged of this type are discarded.
Parameters
lt The kind of message to disable.
Definition at line 73 of file Logger.cpp.
References enabled_.
Referenced by Options::initLogger().
void Logger::enable (Logtype lt)
Enables the printing of a certain kind of message.
If a message kind is disabled, all messaged of this type are discarded.
Parameters
lt The kind of message to enable.
Definition at line 79 of file Logger.cpp.
References enabled_.
Referenced by Options::initLogger().
ostream & Logger::getOstream (Logtype lt)
Returns the output stream for a certain kind of message.
Use this method to pipe arbitrary messages into the requested streams. See also the macros
L_ERR
L_WRN
L_RES
L_INF
L_DBG
L_LOG
which might be more convenient to use.
Note
This method does not check if the particular kind of message is enabled or disabled, i.e, it allows you to print messages although they are disabled.
Parameters
lt The kind of message for which the output stream is requested.
Returns
The output stream for this message.
Definition at line 91 of file Logger.cpp.
References MASSERT, and streams_.
Logger & Logger::instance () [static]
Returns the one and only instance of this class.
This class is implemented as a Singleton. That is, you cannot instantiate objects of this class with the constructor. Use this method to obtain the one and only instance of this class.
Returns
The one and only instance of this class.
Definition at line 36 of file Logger.cpp.
References instance_, Logger(), and MASSERT.
Referenced by LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), and LearnSynthQBF::computeWinningRegionOneSAT().
bool Logger::isEnabled (Logtype lt) const
Checks if a certain kind of message is enabled.
If a message kind is disabled, all messaged of this type are discarded.
Parameters
lt The kind of message in question.
Returns
True if this kind of message is enabled, false if it is disabled.
Definition at line 85 of file Logger.cpp.
References enabled_.
Referenced by LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), and LearnSynthQBF::computeWinningRegionOneSAT().
Logger& Logger::operator= (const Logger & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
Member Data Documentation
vector<bool> Logger::enabled_ [protected]
The flags indicating which kind of message is enabled.
The order in the array is as following:
enabled_[0] is true if errors are enabled.
enabled_[1] is true if warnings are enabled.
enabled_[2] is true if results are enabled.
enabled_[3] is true if infos are enabled.
enabled_[4] is true if debug messages are enabled.
enabled_[5] is true if log messages are enabled.
Definition at line 201 of file Logger.h.
Referenced by disable(), enable(), isEnabled(), and Logger().
Logger * Logger::instance_ = NULL [static], [protected]
The one and only instance of this class.
Definition at line 171 of file Logger.h.
Referenced by instance().
vector<ostream*> Logger::streams_ [protected]
The output streams to be used for the different kinds of messages.
The order in the array is as following:
streams_[0] is the output stream for errors (Logtype::ERR)
streams_[1] is the output stream for warnings (Logtype::WRN)
streams_[2] is the output stream for results (Logtype::RES)
streams_[3] is the output stream for infos (Logtype::INF)
streams_[4] is the output stream for debug messages (Logtype::DBG)
streams_[5] is the output stream for log messages (Logtype::LOG)
Definition at line 186 of file Logger.h.
Referenced by getOstream(), Logger(), and ~Logger().
The documentation for this class was generated from the following files:
src/Logger.h
src/Logger.cpp