IFMProofObligation Class Reference
A helper-class for IFM13Synth, representing an open proof obligation.
#include <IFMProofObligation.h>
Public Member Functions
IFMProofObligation (const vector< int > &state_cube, size_t state_level)
Constructor omitting the predecessor.
IFMProofObligation (const vector< int > &state_cube, size_t state_level, const vector< int > &pre_state_in_cube, const vector< int > &pre_ctrl_cube)
Constructor also setting a predecessor.
IFMProofObligation (const IFMProofObligation &other)
Copy constructor.
IFMProofObligation & operator= (const IFMProofObligation &other)
Assignment operator.
virtual ~IFMProofObligation ()
Destructor.
const vector< int > & getState () const
Returns the state in question in form of a full cube over the state variables.
size_t getLevel () const
Returns the level in question.
bool hasPre () const
Checks if a preprocessor was set.
const vector< int > & getPreStateInCube () const
Returns the predecessor together with the inputs of the transition.
const vector< int > & getPreCtrlCube () const
Returns the control values of the transition from the predecessor to the state.
void setPre (const vector< int > &pre_state_in_cube, const vector< int > &pre_ctrl_cube)
Sets the predecessor and the transition to the current state.
Protected Attributes
vector< int > state_cube_
A full cube over the state-variables. It represents the state in question.
size_t state_level_
The level of the proof obligation.
vector< int > pre_state_in_cube_
The predecessor of state_cube_ and the inputs of the transition.
vector< int > pre_ctrl_cube_
The control signal values of the transition to state_cube_.
Detailed Description
A helper-class for IFM13Synth, representing an open proof obligation.
This is a simple container without any intelligence. Basically, a proof obligation is a state together with a level. The intuitive meaning is that we need to check if the rank of the state is greater than the level or not. In addition, this class also stores information about the predecessor-state that was responsible for adding the current state as a proof obligation. This enables some optimizations.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 49 of file IFMProofObligation.h.
Constructor & Destructor Documentation
IFMProofObligation::IFMProofObligation (const vector< int > & state_cube, size_t state_level)
Constructor omitting the predecessor.
Parameters
state_cube A full cube over the state-variables. It represents the state in question.
state_level The level of the proof obligation (the proof obligation means: check if the rank of the state greater than this level or not).
Definition at line 33 of file IFMProofObligation.cpp.
IFMProofObligation::IFMProofObligation (const vector< int > & state_cube, size_t state_level, const vector< int > & pre_state_in_cube, const vector< int > & pre_ctrl_cube)
Constructor also setting a predecessor.
Parameters
state_cube A full cube over the state-variables. It represents the state in question.
state_level The level of the proof obligation (the proof obligation means: check if the rank of the state greater than this level or not).
pre_state_in_cube A full cube over the state variables and the uncontrollable inputs. It defines the predecessor of state_cube and the input that was used to go from this predecessor to the state_cube.
pre_ctrl_cube The control signal values (in form of a full cube) that were used to traverse from the predecessor to the current state.
Definition at line 41 of file IFMProofObligation.cpp.
IFMProofObligation::IFMProofObligation (const IFMProofObligation & other)
Copy constructor.
Makes a (deep) copy of the IFMProofObligation.
Parameters
other The source for creating the (deep) copy.
Definition at line 54 of file IFMProofObligation.cpp.
IFMProofObligation::~IFMProofObligation () [virtual]
Destructor.
Definition at line 74 of file IFMProofObligation.cpp.
Member Function Documentation
size_t IFMProofObligation::getLevel () const
Returns the level in question.
The proof obligation means: check if the rank of the state greater than this level or not.
Returns
The level in question.
Definition at line 86 of file IFMProofObligation.cpp.
References state_level_.
Referenced by IFM13Synth::recBlockCube(), and IFM13Explorer::recBlockCube().
const vector< int > & IFMProofObligation::getPreCtrlCube () const
Returns the control values of the transition from the predecessor to the state.
Returns
The control signal values (in form of a full cube) that were used to traverse from the predecessor to the current state.
Definition at line 104 of file IFMProofObligation.cpp.
References pre_ctrl_cube_.
Referenced by IFM13Synth::recBlockCube(), and IFM13Explorer::recBlockCube().
const vector< int > & IFMProofObligation::getPreStateInCube () const
Returns the predecessor together with the inputs of the transition.
Returns
A full cube over the state variables and the uncontrollable inputs. It defines the predecessor of state in question and the input that was used to go from this predecessor to the state in question.
Definition at line 98 of file IFMProofObligation.cpp.
References pre_state_in_cube_.
Referenced by IFM13Synth::recBlockCube(), and IFM13Explorer::recBlockCube().
const vector< int > & IFMProofObligation::getState () const
Returns the state in question in form of a full cube over the state variables.
Returns
The state in question in form of a full cube over the state variables.
Definition at line 80 of file IFMProofObligation.cpp.
References state_cube_.
Referenced by IFM13Synth::recBlockCube(), and IFM13Explorer::recBlockCube().
bool IFMProofObligation::hasPre () const
Checks if a preprocessor was set.
Returns
True if a predecessor was set (either via the constructor or with setPre() . The methods getPreStateInCube() and getPreCtrlCube() only return useful values if this method returns true.
Definition at line 92 of file IFMProofObligation.cpp.
References pre_ctrl_cube_.
Referenced by IFM13Synth::recBlockCube(), and IFM13Explorer::recBlockCube().
IFMProofObligation & IFMProofObligation::operator= (const IFMProofObligation & other)
Assignment operator.
Makes this object a deep copy of another object.
Parameters
other The source for creating the (deep) copy.
Returns
The result of the assignment, i.e, *this.
Definition at line 64 of file IFMProofObligation.cpp.
References pre_ctrl_cube_, pre_state_in_cube_, state_cube_, and state_level_.
void IFMProofObligation::setPre (const vector< int > & pre_state_in_cube, const vector< int > & pre_ctrl_cube)
Sets the predecessor and the transition to the current state.
Setting the predecessor can also be done with the right constructor. This method does the same thing, but after the object has been created.
Parameters
pre_state_in_cube A full cube over the state variables and the uncontrollable inputs. It defines the predecessor of state_cube and the input that was used to go from this predecessor to the state_cube.
pre_ctrl_cube The control signal values (in form of a full cube) that were used to traverse from the predecessor to the current state.
Definition at line 110 of file IFMProofObligation.cpp.
References MASSERT, pre_ctrl_cube_, and pre_state_in_cube_.
Member Data Documentation
vector<int> IFMProofObligation::pre_ctrl_cube_ [protected]
The control signal values of the transition to state_cube_.
The control signal values (in form of a full cube) that were used to traverse from the predecessor to the current state.
Definition at line 191 of file IFMProofObligation.h.
Referenced by getPreCtrlCube(), hasPre(), operator=(), and setPre().
vector<int> IFMProofObligation::pre_state_in_cube_ [protected]
The predecessor of state_cube_ and the inputs of the transition.
This is a full cube over the state variables and the uncontrollable inputs. It defines the predecessor of state_cube and the input that was used to go from this predecessor to the state_cube_.
Definition at line 183 of file IFMProofObligation.h.
Referenced by getPreStateInCube(), operator=(), and setPre().
vector<int> IFMProofObligation::state_cube_ [protected]
A full cube over the state-variables. It represents the state in question.
Definition at line 167 of file IFMProofObligation.h.
Referenced by getState(), and operator=().
size_t IFMProofObligation::state_level_ [protected]
The level of the proof obligation.
The proof obligation means: check if the rank of the state greater than this level or not.
Definition at line 174 of file IFMProofObligation.h.
Referenced by getLevel(), and operator=().
The documentation for this class was generated from the following files:
src/IFMProofObligation.h
src/IFMProofObligation.cpp