DepQBFApi Class Reference
Interfaces the DepQBF QBF-solver via its API.
#include <DepQBFApi.h>
Public Types
enum Quant { E,
A
 }
A type for the different kinds of quantifiers.
Public Member Functions
DepQBFApi (bool use_bloqqer=false)
Constructor.
virtual ~DepQBFApi ()
Destructor.
virtual bool isSat (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
Checks if a given QBF is satisfiable (with quantification over variable kinds).
virtual bool isSat (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
Checks if a given QBF is satisfiable (with quantification over variable sets).
virtual bool isSatModel (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf, vector< int > &model)
Checks satisfiability and extracts a model (quantifying over variable kinds).
virtual bool isSatModel (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf, vector< int > &model)
Checks satisfiability and extracts a model (quantifying over variable sets).
virtual void startIncrementalSession (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix)
Starts an incremental session with a quantifier prefix over variable kinds.
virtual void startIncrementalSession (const vector< pair< vector< int >, Quant > > &quantifier_prefix)
Starts an incremental session with a quantifier prefix over variable sets.
void doMinCores (bool min_cores=true)
Enables or disables the computation of MINIMAL unsatisfiable cores.
virtual void clearIncrementalSession ()
Closes a previously opened incremental session and frees all resources.
virtual void incAddVarAtInnermostQuant (int var)
Declares a new variable in the innermost quantifier nesting.
virtual void incAddCNF (const CNF &cnf)
Adds (conjuncts) a new CNF to the current incremental session.
virtual void incAddClause (const vector< int > &clause)
Adds (conjuncts) a new clause to the current incremental session.
virtual void incAddUnitClause (int lit)
Adds a new unit clause to the current incremental session.
virtual void incAdd2LitClause (int lit1, int lit2)
Adds a new clause consisting of 2 literals to the current incremental session.
virtual void incAdd3LitClause (int lit1, int lit2, int lit3)
Adds a new clause consisting of 3 literals to the current incremental session.
virtual void incAddCube (const vector< int > &cube)
Adds (conjuncts) a new cube to the current incremental session.
virtual void incAddNegCubeAsClause (const vector< int > &cube)
Adds the negation of a given cube (which is a clause) to the incremental session.
virtual void incPush ()
Stores the current state of the incremental session on a stack.
virtual void incPop ()
Restores the incremental session back to the point where incPush() was called.
virtual bool incIsSat ()
Checks if the QBF in the current incremental session is satisfiable.
virtual bool incIsSat (const vector< int > &assumptions)
Checks if the QBF in the incremental session is satisfiable under assumptions.
virtual bool incIsSatModelOrCore (const vector< int > &assumptions, vector< int > &model_or_core)
Checks if the incremental session is satisfiable and computes a model or core.
virtual bool incIsSatModel (const vector< int > &assumptions, vector< int > &model)
Checks if the incremental session is satisfiable and computes a model.
virtual bool incIsSatCore (const vector< int > &assumptions, vector< int > &core)
Checks if the incremental session is satisfiable and computes a core.
void debugDumpIncSolverState ()
Dumps the incremental solver state for debugging purposes.
Protected Member Functions
void initBloqqer (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
Initializes the pre-processor with a QBF (quantifying over variable kinds).
void initBloqqer (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
Initializes the pre-processor with a QBF (quantifying over variable sets).
void initDepQBF (QDPLL *solver, const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
Initializes a DepQBF instance with a QBF (quantifying over variable kinds).
void initDepQBF (QDPLL *solver, const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
Initializes a DepQBF instance with a QBF (quantifying over variable sets).
void extractCore (QDPLL *solver, vector< int > &core)
Extracts an unsatisfiable core after unsatisfiability has been shown.
void debugCheckBloqqerVerdict (int bloqqer_verdict, const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
A debug function to cross-check bloqqer verdicts (SAT or UNSAT).
void debugCheckBloqqerVerdict (int bloqqer_verdict, const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
A debug function to cross-check bloqqer verdicts (SAT or UNSAT).
void debugCheckBloqqerModel (const vector< int > &model, const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
A debug function to cross-check models produced by bloqqer.
void debugCheckBloqqerModel (const vector< int > &model, const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
A debug function to cross-check models produced by bloqqer.
void debugAssertIsDeclaredInc (int lit) const
Asserts that a literal has been declared in the current incremental session.
Protected Attributes
bool use_bloqqer_
A flag indicating whether or not the pre-processor bloqqer should be used.
bool min_cores_
A flag indicating whether or not unsatisfiable cores should be further minimized.
QDPLL * inc_solver_
The solver instance to use in the incremental session.
vector< int > inc_model_vars_
The variables for which a satisfying assignment can be constructed.
set< int > inc_decl_vars_
The variables which have been declared in the current incremental session.
Private Member Functions
DepQBFApi (const DepQBFApi &other)
Copy constructor.
DepQBFApi & operator= (const DepQBFApi &other)
Assignment operator.
Detailed Description
Interfaces the DepQBF QBF-solver via its API.
This class represents an interface to the QBF-solver DepQBF (see https://github.com/lonsing/depqbf). For a given Quantified Boolean formula (a CNF with a quantifier prefix), this class is able to determine satisfiability. Furthermore, in case of satisfiability, it can extract satisfying assignments for variables quantified existentially on the outermost level.
This interface to DepQBF can operated in two modes: with and without Bloqqer as pre-processor.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 54 of file DepQBFApi.h.
Member Enumeration Documentation
enum QBFSolver::Quant [inherited]
A type for the different kinds of quantifiers.
Enumerator
E
 The value for existential quantification.
A
 The value for universal quantification.
Definition at line 56 of file QBFSolver.h.
Constructor & Destructor Documentation
DepQBFApi::DepQBFApi (bool use_bloqqer = false)
Constructor.
Parameters
use_bloqqer True if bloqqer should be used as pre-processor, false if no pre-processing should be used. If this parameter is omitted, no pre-processing is used. At the moment, incremental solving is always done without any pre-processing.
Definition at line 44 of file DepQBFApi.cpp.
DepQBFApi::~DepQBFApi () [virtual]
Destructor.
Definition at line 53 of file DepQBFApi.cpp.
References clearIncrementalSession().
DepQBFApi::DepQBFApi (const DepQBFApi & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void DepQBFApi::clearIncrementalSession () [virtual]
Closes a previously opened incremental session and frees all resources.
If no incremental session is open, then this method has no effect at all.
Definition at line 404 of file DepQBFApi.cpp.
References inc_decl_vars_, inc_model_vars_, and inc_solver_.
Referenced by ~DepQBFApi().
void DepQBFApi::debugAssertIsDeclaredInc (int lit) const [protected]
Asserts that a literal has been declared in the current incremental session.
Asserts that a certain literal has been declared in the quantifier prefix of the current incremental session. This check is done in the debug mode only.
Parameters
lit The literal to check.
Definition at line 1028 of file DepQBFApi.cpp.
References DASSERT, and inc_decl_vars_.
Referenced by incAdd2LitClause(), incAdd3LitClause(), incAddClause(), incAddCNF(), incAddCube(), incAddNegCubeAsClause(), incAddUnitClause(), incIsSat(), incIsSatCore(), incIsSatModel(), and incIsSatModelOrCore().
void DepQBFApi::debugCheckBloqqerModel (const vector< int > & model, const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
A debug function to cross-check models produced by bloqqer.
DepQBF without preprocessing is used to check if the model found by bloqqer indeed satisfies the QBF. This method is used to debug bloqqer.
Parameters
model The satisfying assignment found by bloqqer. Negated variables in the vector are FALSE, unnegated ones are TRUE.
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Definition at line 935 of file DepQBFApi.cpp.
References CNF::addCube(), Utils::debugPrint(), ExtQBFSolver::dumpQBF(), VarManager::getVarsOfType(), VarManager::instance(), isSat(), L_ERR, and MASSERT.
void DepQBFApi::debugCheckBloqqerModel (const vector< int > & model, const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
A debug function to cross-check models produced by bloqqer.
DepQBF without preprocessing is used to check if the model found by bloqqer indeed satisfies the QBF. This method is used to debug bloqqer.
Parameters
model The satisfying assignment found by bloqqer. Negated variables in the vector are FALSE, unnegated ones are TRUE.
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Definition at line 982 of file DepQBFApi.cpp.
References CNF::addCube(), Utils::debugPrint(), ExtQBFSolver::dumpQBF(), isSat(), L_ERR, and MASSERT.
void DepQBFApi::debugCheckBloqqerVerdict (int bloqqer_verdict, const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
A debug function to cross-check bloqqer verdicts (SAT or UNSAT).
The QBF is also solved with DepQBF without pre-processing and the two verdicts are compared. This method is used to debug bloqqer.
Parameters
bloqqer_verdict The result returned by bloqqer. The value 10 means SAT, the value 20 means UNSAT.
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Definition at line 877 of file DepQBFApi.cpp.
References ExtQBFSolver::dumpQBF(), isSat(), L_ERR, and MASSERT.
Referenced by isSatModel().
void DepQBFApi::debugCheckBloqqerVerdict (int bloqqer_verdict, const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
A debug function to cross-check bloqqer verdicts (SAT or UNSAT).
The QBF is also solved with DepQBF without pre-processing and the two verdicts are compared. This method is used to debug bloqqer.
Parameters
bloqqer_verdict The result returned by bloqqer. The value 10 means SAT, the value 20 means UNSAT.
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Definition at line 906 of file DepQBFApi.cpp.
References ExtQBFSolver::dumpQBF(), isSat(), L_ERR, and MASSERT.
void DepQBFApi::debugDumpIncSolverState ()
Dumps the incremental solver state for debugging purposes.
Definition at line 695 of file DepQBFApi.cpp.
References inc_solver_, and MASSERT.
void DepQBFApi::doMinCores (bool min_cores = true)
Enables or disables the computation of MINIMAL unsatisfiable cores.
Parameters
min_cores A flag indicating if unsatisfiable cores returned by the solver should be minimized further by trying to drop one literal after the other. This makes the calls slower but produces potentially smaller cubes. If the parameter is skipped the computation of minimal cores is enabled.
Definition at line 398 of file DepQBFApi.cpp.
References min_cores_.
Referenced by LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), and ClauseMinimizerQBF::minimizeClausesInc().
void DepQBFApi::extractCore (QDPLL * solver, vector< int > & core) [protected]
Extracts an unsatisfiable core after unsatisfiability has been shown.
Parameters
solver The DepQBF solver instance to extract the core from.
core The vector into which the resulting unsatisfiable core will be stored. It is a subset of the used assumptions.
Definition at line 829 of file DepQBFApi.cpp.
References min_cores_, Utils::randomize(), and Utils::remove().
Referenced by incIsSatCore(), and incIsSatModelOrCore().
void DepQBFApi::incAdd2LitClause (int lit1, int lit2) [virtual]
Adds a new clause consisting of 2 literals to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
lit1 The first literal of the clause to add to the currently open incremental session.
lit2 The second literal of the clause to add to the currently open incremental session.
Definition at line 464 of file DepQBFApi.cpp.
References debugAssertIsDeclaredInc(), inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOnePool(), and LearnSynthQBFInc::computeWinningRegionOnePush().
void DepQBFApi::incAdd3LitClause (int lit1, int lit2, int lit3) [virtual]
Adds a new clause consisting of 3 literals to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
lit1 The first literal of the clause to add to the currently open incremental session.
lit2 The second literal of the clause to add to the currently open incremental session.
lit3 The third literal of the clause to add to the currently open incremental session.
Definition at line 475 of file DepQBFApi.cpp.
References debugAssertIsDeclaredInc(), inc_solver_, and MASSERT.
void DepQBFApi::incAddClause (const vector< int > & clause) [virtual]
Adds (conjuncts) a new clause to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
clause The clause which shall be conjuncted to the CNF in the currently open incremental session.
Definition at line 443 of file DepQBFApi.cpp.
References debugAssertIsDeclaredInc(), inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::computeAllBlockingClauses(), LearnSynthQBFInc::computeBlockingClause(), LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), and LearnSynthQBFInc::reduceExistingClauses().
void DepQBFApi::incAddCNF (const CNF & cnf) [virtual]
Adds (conjuncts) a new CNF to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
cnf A Boolean formula in CNF. It is conjuncted to the CNF in the currently open incremental session.
Definition at line 427 of file DepQBFApi.cpp.
References debugAssertIsDeclaredInc(), CNF::getClauses(), inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), ClauseMinimizerQBF::minimizeClausesInc(), LearningImplExtractor::runLearningQBFInc(), and ParExtractorQBFWorker::runQBF().
void DepQBFApi::incAddCube (const vector< int > & cube) [virtual]
Adds (conjuncts) a new cube to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
cube The cube which shall be conjuncted to the CNF in the currently open incremental session. All literals of the cube are added as unit clauses to the CNF of the currently open session.
Definition at line 488 of file DepQBFApi.cpp.
References debugAssertIsDeclaredInc(), inc_solver_, and MASSERT.
void DepQBFApi::incAddNegCubeAsClause (const vector< int > & cube) [virtual]
Adds the negation of a given cube (which is a clause) to the incremental session.
For instance, if the cube [2, -4, 8] is passed as argument, then this method adds the clauses [-2, 4, -8] to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
cube The cube (a conjunction of literals) to negate and add (conjunct) to the currently open incremental session.
Definition at line 500 of file DepQBFApi.cpp.
References debugAssertIsDeclaredInc(), inc_solver_, and MASSERT.
Referenced by LearningImplExtractor::runLearningQBFInc(), and ParExtractorQBFWorker::runQBF().
void DepQBFApi::incAddUnitClause (int lit) [virtual]
Adds a new unit clause to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
lit The (one and only) literal of the unit clause to add to the currently open incremental session.
Definition at line 455 of file DepQBFApi.cpp.
References debugAssertIsDeclaredInc(), inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), and ClauseMinimizerQBF::minimizeClausesInc().
void DepQBFApi::incAddVarAtInnermostQuant (int var) [virtual]
Declares a new variable in the innermost quantifier nesting.
Parameters
var The variable to declare in the innermost nesting.
Definition at line 416 of file DepQBFApi.cpp.
References inc_decl_vars_, inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::computeWinningRegionAllPush(), and LearnSynthQBFInc::computeWinningRegionOnePush().
bool DepQBFApi::incIsSat () [virtual]
Checks if the QBF in the current incremental session is satisfiable.
Returns
True if the QBF in the current incremental session is satisfiable, false otherwise.
Definition at line 526 of file DepQBFApi.cpp.
References inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::generalizeCounterexampleFurther(), and ClauseMinimizerQBF::minimizeClausesInc().
bool DepQBFApi::incIsSat (const vector< int > & assumptions) [virtual]
Checks if the QBF in the incremental session is satisfiable under assumptions.
Parameters
assumptions The assumptions under which the QBF in the current incremental session should be solved. The assumptions are interpreted as a cube of literals. Every literal is added temporarily as a unit clause to the QBF.
Returns
True if the QBF in the current incremental session is satisfiable under the assumptions, false otherwise.
Definition at line 539 of file DepQBFApi.cpp.
References debugAssertIsDeclaredInc(), inc_solver_, and MASSERT.
bool DepQBFApi::incIsSatCore (const vector< int > & assumptions, vector< int > & core) [virtual]
Checks if the incremental session is satisfiable and computes a core.
This method first checks if the QBF in the incremental session is satisfiable under a given set of assumptions. If no, then an unsatisfiable core is computed over the assumption variables.
Parameters
assumptions The assumptions under which the QBF in the current incremental session should be solved. The assumptions are interpreted as a cube of literals. Every literal is added temporarily as a unit clause to the QBF.
core If this method returns false, a subset of the passed assumptions is stored in this vector.
Returns
True if the QBF in the current incremental session is satisfiable under the assumptions, false otherwise.
Definition at line 656 of file DepQBFApi.cpp.
References debugAssertIsDeclaredInc(), extractCore(), inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::generalizeCounterexample(), ClauseMinimizerQBF::minimizeClausesInc(), LearningImplExtractor::runLearningQBFInc(), and ParExtractorQBFWorker::runQBF().
bool DepQBFApi::incIsSatModel (const vector< int > & assumptions, vector< int > & model) [virtual]
Checks if the incremental session is satisfiable and computes a model.
This method first checks if the QBF in the incremental session is satisfiable under a given set of assumptions. If yes, then a satisfying assignment for the variables quantified existentially on the outermost level is computed.
Parameters
assumptions The assumptions under which the QBF in the current incremental session should be solved. The assumptions are interpreted as a cube of literals. Every literal is added temporarily as a unit clause to the QBF.
model The vector into which the resulting model will be stored. In case of satisfiability a satisfying assignment (a cube of literals; negated ones are false, unnegated ones are true) is stored in this vector. Otherwise, this vector remains untouched.
Returns
True if the QBF in the current incremental session is satisfiable under the assumptions, false otherwise.
Definition at line 612 of file DepQBFApi.cpp.
References debugAssertIsDeclaredInc(), inc_model_vars_, inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::computeCounterexampleQBF(), LearnSynthQBFInc::computeCounterexampleQBFPool(), LearningImplExtractor::runLearningQBFInc(), and ParExtractorQBFWorker::runQBF().
bool DepQBFApi::incIsSatModelOrCore (const vector< int > & assumptions, vector< int > & model_or_core) [virtual]
Checks if the incremental session is satisfiable and computes a model or core.
This method first checks if the QBF in the incremental session is satisfiable under a given set of assumptions. If yes, then a satisfying assignment for the variables quantified existentially on the outermost level is computed. Otherwise, an unsatisfiable core is computed. An unsatisfiable core is a subset of the assumptions under which the QBF is still unsatisfiable.
Parameters
assumptions The assumptions under which the QBF in the current incremental session should be solved. The assumptions are interpreted as a cube of literals. Every literal is added temporarily as a unit clause to the QBF.
model_or_core The vector into which the resulting model or core will be stored. In case of satisfiability a satisfying assignment (a cube of literals; negated ones are false, unnegated ones are true) is stored in this vector. Otherwise, if this method returns false, a subset of the passed assumptions is stored in this vector.
Returns
True if the QBF in the current incremental session is satisfiable under the assumptions, false otherwise.
Definition at line 561 of file DepQBFApi.cpp.
References debugAssertIsDeclaredInc(), extractCore(), inc_model_vars_, inc_solver_, and MASSERT.
void DepQBFApi::incPop () [virtual]
Restores the incremental session back to the point where incPush() was called.
Definition at line 519 of file DepQBFApi.cpp.
References inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::computeWinningRegionAllPush(), and LearnSynthQBFInc::computeWinningRegionOnePush().
void DepQBFApi::incPush () [virtual]
Stores the current state of the incremental session on a stack.
The state can be restored later by calling incPop().
Definition at line 512 of file DepQBFApi.cpp.
References inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::computeWinningRegionAllPush(), and LearnSynthQBFInc::computeWinningRegionOnePush().
void DepQBFApi::initBloqqer (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
Initializes the pre-processor with a QBF (quantifying over variable kinds).
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Definition at line 702 of file DepQBFApi.cpp.
References QBFSolver::E, CNF::getClauses(), VarManager::getMaxCNFVar(), CNF::getNrOfClauses(), VarManager::getVarsOfType(), and VarManager::instance().
Referenced by isSat(), and isSatModel().
void DepQBFApi::initBloqqer (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
Initializes the pre-processor with a QBF (quantifying over variable sets).
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Definition at line 730 of file DepQBFApi.cpp.
References QBFSolver::E, CNF::getClauses(), and CNF::getNrOfClauses().
void DepQBFApi::initDepQBF (QDPLL * solver, const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
Initializes a DepQBF instance with a QBF (quantifying over variable kinds).
Parameters
solver The DepQBF solver instance to initialize.
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Definition at line 766 of file DepQBFApi.cpp.
References QBFSolver::E, CNF::getClauses(), VarManager::getMaxCNFVar(), VarManager::getVarsOfType(), and VarManager::instance().
Referenced by isSat(), isSatModel(), and startIncrementalSession().
void DepQBFApi::initDepQBF (QDPLL * solver, const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
Initializes a DepQBF instance with a QBF (quantifying over variable sets).
Parameters
solver The DepQBF solver instance to initialize.
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Definition at line 793 of file DepQBFApi.cpp.
References QBFSolver::E, and CNF::getClauses().
bool DepQBFApi::isSat (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [virtual]
Checks if a given QBF is satisfiable (with quantification over variable kinds).
The QBF consists of a quantifier prefix and a Boolean formula in CNF. The quantifier prefix assigns an existential or universal quantifier to every kind of variable.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 59 of file DepQBFApi.cpp.
References initBloqqer(), initDepQBF(), MASSERT, and use_bloqqer_.
Referenced by debugCheckBloqqerModel(), debugCheckBloqqerVerdict(), IFM13Synth::debugCheckInvariants(), and LearnSynthSAT::debugCheckWinReg().
bool DepQBFApi::isSat (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [virtual]
Checks if a given QBF is satisfiable (with quantification over variable sets).
The QBF consists of a quantifier prefix and a Boolean formula in CNF. The quantifier prefix assigns an existential or universal quantifier to different sets variable.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 91 of file DepQBFApi.cpp.
References initBloqqer(), initDepQBF(), MASSERT, and use_bloqqer_.
bool DepQBFApi::isSatModel (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf, vector< int > & model) [virtual]
Checks satisfiability and extracts a model (quantifying over variable kinds).
Just like isSat() , this method checks a quantified Boolean formula for satisfiability. If the QBF is satisfiable, this method also extracts a model (a satisfying assignment) for all variables which are quantified existentially on the outermost level. The model is provided as cube: negated variables in the cube are FALSE, unnegated ones are TRUE.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
model The resulting model in form of a cube in case of satisfiability. Negated variables in the cube are FALSE, unnegated ones are TRUE. If the formula is unsatisfiable (this method returns false) then this parameter is not modified.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 123 of file DepQBFApi.cpp.
References DASSERT, debugCheckBloqqerVerdict(), VarManager::getVarsOfType(), initBloqqer(), initDepQBF(), VarManager::instance(), MASSERT, and use_bloqqer_.
bool DepQBFApi::isSatModel (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf, vector< int > & model) [virtual]
Checks satisfiability and extracts a model (quantifying over variable sets).
Just like isSat() , this method checks a quantified Boolean formula for satisfiability. If the QBF is satisfiable, this method also extracts a model (a satisfying assignment) for all variables which are quantified existentially on the outermost level. The model is provided as cube: negated variables in the cube are FALSE, unnegated ones are TRUE.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
model The resulting model in form of a cube in case of satisfiability. Negated variables in the cube are FALSE, unnegated ones are TRUE. If the formula is unsatisfiable (this method returns false) then this parameter is not modified.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 218 of file DepQBFApi.cpp.
References DASSERT, debugCheckBloqqerVerdict(), initBloqqer(), initDepQBF(), MASSERT, and use_bloqqer_.
DepQBFApi& DepQBFApi::operator= (const DepQBFApi & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
void DepQBFApi::startIncrementalSession (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix) [virtual]
Starts an incremental session with a quantifier prefix over variable kinds.
Every DepQBFApi instance can only have one open incremental session. If you call this method twice, the old incremental session (if any) will be deleted (just like calling clearIncrementalSession()) and a new one will be opened.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
Definition at line 320 of file DepQBFApi.cpp.
References QBFSolver::E, VarManager::getMaxCNFVar(), VarManager::getVarsOfType(), inc_decl_vars_, inc_model_vars_, inc_solver_, initDepQBF(), and VarManager::instance().
Referenced by LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), ClauseMinimizerQBF::minimizeClausesInc(), LearningImplExtractor::runLearningQBFInc(), and ParExtractorQBFWorker::runQBF().
void DepQBFApi::startIncrementalSession (const vector< pair< vector< int >, Quant > > & quantifier_prefix) [virtual]
Starts an incremental session with a quantifier prefix over variable sets.
Every DepQBFApi instance can only have one open incremental session. If you call this method twice, the old incremental session (if any) will be deleted (just like calling clearIncrementalSession()) and a new one will be opened.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
Definition at line 359 of file DepQBFApi.cpp.
References QBFSolver::E, VarManager::getMaxCNFVar(), inc_decl_vars_, inc_model_vars_, inc_solver_, initDepQBF(), and VarManager::instance().
Member Data Documentation
set<int> DepQBFApi::inc_decl_vars_ [protected]
The variables which have been declared in the current incremental session.
This set is only used in debug mode to check if all the variables in the matrix of the QBF are mentioned in the quantifier prefix.
Definition at line 557 of file DepQBFApi.h.
Referenced by clearIncrementalSession(), debugAssertIsDeclaredInc(), incAddVarAtInnermostQuant(), and startIncrementalSession().
vector<int> DepQBFApi::inc_model_vars_ [protected]
The variables for which a satisfying assignment can be constructed.
Definition at line 549 of file DepQBFApi.h.
Referenced by clearIncrementalSession(), incIsSatModel(), incIsSatModelOrCore(), and startIncrementalSession().
QDPLL* DepQBFApi::inc_solver_ [protected]
The solver instance to use in the incremental session.
Definition at line 544 of file DepQBFApi.h.
Referenced by clearIncrementalSession(), debugDumpIncSolverState(), incAdd2LitClause(), incAdd3LitClause(), incAddClause(), incAddCNF(), incAddCube(), incAddNegCubeAsClause(), incAddUnitClause(), incAddVarAtInnermostQuant(), incIsSat(), incIsSatCore(), incIsSatModel(), incIsSatModelOrCore(), incPop(), incPush(), and startIncrementalSession().
bool DepQBFApi::min_cores_ [protected]
A flag indicating whether or not unsatisfiable cores should be further minimized.
If this flag is false, then we take the core as returned by the solver. If it is true, then we try to further minimize the core by trying to drop one remaining assumption after the other in a loop. This is then guaranteed to result in an unsatisfiable core which is a local minimum subset of the assumptions.
Definition at line 539 of file DepQBFApi.h.
Referenced by doMinCores(), and extractCore().
bool DepQBFApi::use_bloqqer_ [protected]
A flag indicating whether or not the pre-processor bloqqer should be used.
Definition at line 529 of file DepQBFApi.h.
Referenced by isSat(), and isSatModel().
The documentation for this class was generated from the following files:
src/DepQBFApi.h
src/DepQBFApi.cpp