LearnSynthQBF Class Reference
Implements a learning-based synthesis using a QBF solver.
#include <LearnSynthQBF.h>
Public Member Functions
LearnSynthQBF (CNFImplExtractor *impl_extractor)
Constructor.
virtual ~LearnSynthQBF ()
Destructor.
virtual bool run ()
Executes this back-end.
Protected Member Functions
bool computeWinningRegion ()
Computes the winning region and stores the result in winning_region_.
bool computeWinningRegionOne ()
Uses the standard method to compute the winning region.
bool computeWinningRegionOneSAT ()
Computes the winning region, using two SAT-solvers to compute counterexamples.
bool computeWinningRegionAll ()
Computes the winning region, always computing all counterexample generalizations.
bool computeCounterexampleQBF (vector< int > &ce)
Computes a counterexample-state using a QBF-solver.
bool computeCounterexampleSAT (vector< int > &ce)
Computes a counterexample-state using two competing SAT-solvers.
bool computeBlockingClause (vector< int > &ce, vector< int > &blocking_clause)
Computes a blocking clause for a counterexample.
bool computeAllBlockingClauses (vector< int > &ce, vector< vector< int > > &blocking_clauses)
Computes all minimal blocking clauses for a counterexample.
void reduceExistingClauses ()
Tries to drop literals from clauses in the winning region.
void recomputeCheckCNF (bool take_small_win=true)
Recomputes the CNF (of the QBF) that is used for computing counterexamples.
void recomputeGenCNF (bool take_small_win=true)
Recomputes the CNF (of the QBF) that is used for generalizing counterexamples.
void restrictToStates (vector< int > &vec) const
Restricts a vector of literals (a cube or clause) to state-variables only.
bool generalizeCounterexample (vector< int > &ce, bool check_sat=true) const
Generalizes a counterexample-state by dropping literals.
Protected Attributes
CNF winning_region_
The current over-approximation of the winning region.
CNF winning_region_large_
The current over-approximation of the winning region in an uncompressed form.
LearnStatisticsQBF statistics_
Stores and maintains statistics and performance measures.
QBFSolver * qbf_solver_
The QBF-solver used for all queries.
vector< pair< VarInfo::VarKind,
*
QBFSolver::Quant > > check_quant_
The quantifier prefix of the QBF for computing counterexamples.
CNF check_cnf_
The CNF matrix of the QBF for computing counterexamples.
vector< pair< VarInfo::VarKind,
*
QBFSolver::Quant > > gen_quant_
The quantifier prefix of the QBF for generalizing counterexamples.
CNF generalize_clause_cnf_
The CNF matrix of the QBF for generalizing counterexamples.
SatSolver * solver_i_
The SAT-solver for antagonist moves when using computeCounterexampleSAT().
SatSolver * solver_ctrl_
The SAT-solver for protagonist moves when using computeCounterexampleSAT().
vector< int > incremental_vars_to_keep_
A list of variables the SAT-solver should not optimize away.
bool solver_i_precise_
A flag indicating if solver_i_ is precise.
CNFImplExtractor * impl_extractor_
The engine to use for circuit extraction.
Private Member Functions
LearnSynthQBF (const LearnSynthQBF &other)
Copy constructor.
LearnSynthQBF & operator= (const LearnSynthQBF &other)
Assignment operator.
Detailed Description
Implements a learning-based synthesis using a QBF solver.
The computation of the winning region works as follows. We start with the initial guess that the winning region F is the set of all state states P. In a loop, we first compute a counterexample to the correctness of this guess in form of a state from which the antagonist (controlling the uncontrollable inputs i) can enforce to leave F. The state is represented as a cube over all state-variables. Next, this state-cube is generalized into a larger region of states by dropping literals as long as the cube contains only states that are winning for the antagonist (and hence must be removed or have already been removed from F). Finally, the generalized cube is removed from F. The next iteration checks for counterexample-state on the refined F. This is repeated until no more counterexample-states exist (then the specification is realizable and F is a winning region) or the initial state has been removed from F (in which case the specification is unrealizable).
This procedure is implemented in computeWinningRegionOne(). Some variants of this procedure are implemented in other methods of this class. The method computeWinningRegionOneSAT() uses two SAT solvers instead of a QBF solver to compute a counterexample-state. The method computeWinningRegionAll() computes (and excludes) not only one generalization of the counterexample but all generalizations. Command-line parameters (--mode) decide which of these methods to use.
Finally the QBFCertImplExtractor is used to extract a circuit.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.1.0
Definition at line 72 of file LearnSynthQBF.h.
Constructor & Destructor Documentation
LearnSynthQBF::LearnSynthQBF (CNFImplExtractor * impl_extractor)
Constructor.
Parameters
impl_extractor The engine to use for circuit extraction. It will be deleted by this class.
Definition at line 40 of file LearnSynthQBF.cpp.
References QBFSolver::A, check_quant_, VarInfo::CTRL, QBFSolver::E, gen_quant_, SatSolver::incAddCNF(), incremental_vars_to_keep_, VarInfo::INPUT, AIG2CNF::instance(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, solver_ctrl_, solver_i_, solver_i_precise_, SatSolver::startIncrementalSession(), and VarInfo::TMP.
LearnSynthQBF::~LearnSynthQBF () [virtual]
Destructor.
Definition at line 79 of file LearnSynthQBF.cpp.
References impl_extractor_, qbf_solver_, solver_ctrl_, and solver_i_.
LearnSynthQBF::LearnSynthQBF (const LearnSynthQBF & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
bool LearnSynthQBF::computeAllBlockingClauses (vector< int > & ce, vector< vector< int > > & blocking_clauses) [protected]
Computes all minimal blocking clauses for a counterexample.
This method is like computeBlockingClause(). However, instead of computing just one generalization of the counterexample (and the corresponding blocking clause) it computes all minimal generalizations (and corresponding blocking clauses). It does so using a simple hitting set tree algorithm as presented by `Raymond Reiter: A Theory of Diagnosis
from First Principles. Artif. Intell. 32(1): 57-95 (1987)`.
Parameters
ce The counterexample to block. It is a full or partial cube over the state variables.
blocking_clauses An empty vector. It is used to store the computed blocking clauses. The counterexample falsifies all blocking clauses in this vector.
Returns
False if one of the blocking clauses blocks the initial state. This means that the initial state is removed from the winning region, i.e., the specification is unrealizable. True is returned otherwise.
Definition at line 450 of file LearnSynthQBF.cpp.
References CNF::addClause(), Utils::containsInit(), generalize_clause_cnf_, generalizeCounterexample(), Utils::intersectionEmpty(), Utils::negateLiterals(), LearnStatisticsQBF::notifyAfterCubeMin(), LearnStatisticsQBF::notifyBeforeCubeMin(), LearnStatisticsQBF::notifyCubeMin(), Utils::remove(), statistics_, and Utils::swapPresentToNext().
Referenced by computeWinningRegionAll().
bool LearnSynthQBF::computeBlockingClause (vector< int > & ce, vector< int > & blocking_clause) [protected]
Computes a blocking clause for a counterexample.
A naive blocking clause would be the plain negation of the counterexample. However, in order to boost the overall performance of the algorithm, we generalize the counterexample before we negate it. This is done by dropping literals from the counterexample-cube as long as all states in the cube are counterexamples (or have already been removed from the winning region). The method also checks if the blocking clause blocks the initial state.
Parameters
ce The counterexample to block. It is a full or partial cube over the state variables.
blocking_clause An empty vector. It is used to store the computed blocking clause. The counterexample falsifies the blocking clause.
Returns
False if the blocking clause blocks the initial state. This means that the initial state is removed from the winning region, i.e., the specification is unrealizable. True is returned otherwise.
Definition at line 432 of file LearnSynthQBF.cpp.
References Utils::containsInit(), generalizeCounterexample(), L_DBG, Utils::negateLiterals(), LearnStatisticsQBF::notifyAfterCubeMin(), LearnStatisticsQBF::notifyBeforeCubeMin(), Utils::randomize(), and statistics_.
Referenced by computeWinningRegionOne(), and computeWinningRegionOneSAT().
bool LearnSynthQBF::computeCounterexampleQBF (vector< int > & ce) [protected]
Computes a counterexample-state using a QBF-solver.
'Counterexample' here means: counterexample to the correctness of the current guess of the winning region. A counterexample is simply a state (represented as cube over the state variables) from which the antagonist can enforce to leave the winning region. This method uses a single call to a QBF-solver in order to find such a state.
Parameters
ce An empty vector. The computed counterexample is stored in this vector in form of a cube over the state variables. The cube does not necessarily contain all state variables. If some state variables are irrelevant, then they may be omitted.
Returns
True if a counterexample was found, false if no counterexample exists.
Definition at line 333 of file LearnSynthQBF.cpp.
References check_cnf_, check_quant_, QBFSolver::isSatModel(), LearnStatisticsQBF::notifyAfterComputeCube(), LearnStatisticsQBF::notifyBeforeComputeCube(), qbf_solver_, restrictToStates(), and statistics_.
Referenced by computeWinningRegionAll(), and computeWinningRegionOne().
bool LearnSynthQBF::computeCounterexampleSAT (vector< int > & ce) [protected]
Computes a counterexample-state using two competing SAT-solvers.
'Counterexample' here means: counterexample to the correctness of the current guess of the winning region. A counterexample is simply a state (represented as cube over the state variables) from which the antagonist can enforce to leave the winning region. This method uses two competing SAT-solvers in order to find such a state. First, solver solver_i_ finds some input values i that could be chosen by the antagonist in order to leave the winning_region_. Next, solver_ctrl_ checks if there exists a response of the protagonist to chose control values c such that the winning region is not left. If no such response exists, then we have found a counterexample. Otherwise, we exclude the state-input combination found by solver_i_ and try again.
There is also an optimization which allows to use solver_i_ incrementally: The next state-copy of the winning region is updated only lazily.
Parameters
ce An empty vector. The computed counterexample is stored in this vector in form of a cube over the state variables. The cube does not necessarily contain all state variables. If some state variables are irrelevant, then they may be omitted.
Returns
True if a counterexample was found, false if no counterexample exists.
Definition at line 345 of file LearnSynthQBF.cpp.
References CNF::addCNF(), Utils::compressStateCNF(), VarInfo::CTRL, Utils::extract(), VarManager::getVarsOfType(), SatSolver::incAddClause(), SatSolver::incAddCNF(), SatSolver::incIsSatModelOrCore(), incremental_vars_to_keep_, VarInfo::INPUT, VarManager::instance(), AIG2CNF::instance(), L_DBG, MASSERT, CNF::negate(), LearnStatisticsQBF::notifyAfterComputeCube(), LearnStatisticsQBF::notifyBeforeComputeCube(), VarInfo::PRES_STATE, solver_ctrl_, solver_i_, solver_i_precise_, SatSolver::startIncrementalSession(), statistics_, CNF::swapPresentToNext(), and winning_region_.
Referenced by computeWinningRegionOneSAT().
bool LearnSynthQBF::computeWinningRegion () [protected]
Computes the winning region and stores the result in winning_region_.
Depending on the command-line parameters (--mode) this method calls one of
computeWinningRegionOne()
computeWinningRegionOneSAT()
computeWinningRegionAll()
Returns
True if the specification was realizable, false otherwise.
Definition at line 125 of file LearnSynthQBF.cpp.
References computeWinningRegionAll(), computeWinningRegionOne(), computeWinningRegionOneSAT(), and Options::instance().
Referenced by run().
bool LearnSynthQBF::computeWinningRegionAll () [protected]
Computes the winning region, always computing all counterexample generalizations.
The working principle is the same as for computeWinningRegionOne(). The only difference is that this method computes and excludes all counterexample generalizations instead of just one.
Returns
True if the specification was realizable, false otherwise.
Definition at line 267 of file LearnSynthQBF.cpp.
References CNF::addClauseAndSimplify(), check_cnf_, CNF::clear(), Utils::compressStateCNF(), computeAllBlockingClauses(), computeCounterexampleQBF(), VarInfo::CTRL, Logger::DBG, Utils::debugPrint(), generalize_clause_cnf_, CNF::getNrOfClauses(), CNF::getNrOfLits(), AIG2CNF::getSafeStates(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), Logger::instance(), AIG2CNF::instance(), Logger::isEnabled(), L_DBG, LearnStatisticsQBF::logStatistics(), VarInfo::PRES_STATE, recomputeCheckCNF(), recomputeGenCNF(), reduceExistingClauses(), statistics_, winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
bool LearnSynthQBF::computeWinningRegionOne () [protected]
Uses the standard method to compute the winning region.
This standard method works as follows. We start with the initial guess that the winning region F is the set of all state states P. In a loop, we first compute a counterexample to the correctness of this guess in form of a state from which the antagonist (controlling the uncontrollable inputs i) can enforce to leave F. The state is represented as a cube over all state-variables. Next, this state-cube is generalized into a larger region of states by dropping literals as long as the cube contains only states that are winning for the antagonist (and hence must be removed or have already been removed from F). Finally, the generalized cube is removed from F. The next iteration checks for counterexample-state on the refined F. This is repeated until no more counterexample-states exist (then the specification is realizable and F is a winning region) or the initial state has been removed from F (in which case the specification is unrealizable).
Returns
True if the specification was realizable, false otherwise.
Definition at line 135 of file LearnSynthQBF.cpp.
References CNF::addClauseAndSimplify(), check_cnf_, CNF::clear(), Utils::compressStateCNF(), computeBlockingClause(), computeCounterexampleQBF(), VarInfo::CTRL, Logger::DBG, Utils::debugPrint(), generalize_clause_cnf_, CNF::getNrOfClauses(), CNF::getNrOfLits(), AIG2CNF::getSafeStates(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), Logger::instance(), AIG2CNF::instance(), Logger::isEnabled(), L_DBG, LearnStatisticsQBF::logStatistics(), VarInfo::PRES_STATE, recomputeCheckCNF(), recomputeGenCNF(), statistics_, Utils::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
bool LearnSynthQBF::computeWinningRegionOneSAT () [protected]
Computes the winning region, using two SAT-solvers to compute counterexamples.
The working principle is the same as for computeWinningRegionOne(). The only difference is that counterexample-states (states from which the antagonist controlling the inputs i can enforce to leave the winning region) are computed using two competing SAT-solvers instead of a QBF-solver.
Returns
True if the specification was realizable, false otherwise.
Definition at line 204 of file LearnSynthQBF.cpp.
References CNF::addClauseAndSimplify(), check_cnf_, CNF::clear(), computeBlockingClause(), computeCounterexampleSAT(), VarInfo::CTRL, Logger::DBG, Utils::debugPrint(), generalize_clause_cnf_, CNF::getNrOfClauses(), CNF::getNrOfLits(), AIG2CNF::getSafeStates(), VarManager::getVarsOfType(), SatSolver::incAddClause(), VarInfo::INPUT, VarManager::instance(), Logger::instance(), AIG2CNF::instance(), Logger::isEnabled(), L_DBG, LearnStatisticsQBF::logStatistics(), VarInfo::PRES_STATE, recomputeGenCNF(), solver_ctrl_, solver_i_, statistics_, Utils::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegion().
bool LearnSynthQBF::generalizeCounterexample (vector< int > & ce, bool check_sat = true) const [protected]
Generalizes a counterexample-state by dropping literals.
This method generalizes a counterexample-state (a cube over the present-state variables) by dropping literals as long as all states in the cube are counterexamples (or have already been removed from the winning region). Optionally, this method also checks if the passed vector is a valid (generalization of a) counterexample.
Parameters
ce The counterexample to generalize (it will be overwritten by its own generalization). This is a complete or partial cube over the present state variables.
check_sat If set to true, then this method checks if the passed counterexample vector is indeed a valid (generalization of a) counterexample. If set to false, then this step is skipped. If this parameter is true and the passed vector is not a valid counterexample, then it will not be modified.
Returns
True if the passed vector is a valid (generalization of a) counterexample, or if the check was skipped by setting check_sat = false. False is returned only if the check was performed (check_sat = true) and the passed vector is not a valid counterexample.
Definition at line 627 of file LearnSynthQBF.cpp.
References CNF::addCube(), CNF::addNegCubeAsClause(), gen_quant_, generalize_clause_cnf_, QBFSolver::isSat(), qbf_solver_, Utils::remove(), Utils::sort(), and Utils::swapPresentToNext().
Referenced by computeAllBlockingClauses(), and computeBlockingClause().
LearnSynthQBF& LearnSynthQBF::operator= (const LearnSynthQBF & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
void LearnSynthQBF::recomputeCheckCNF (bool take_small_win = true) [protected]
Recomputes the CNF (of the QBF) that is used for computing counterexamples.
The CNF used for computing counterexamples is F & T & !F', where F is the winning_region_. The result is stored in check_cnf_. Since F is constantly updated with new clauses, check_cnf_ needs to be updated as well. In an old version, we updated the check_cnf_ in place, modifying only the clauses that need to be modified. This gives quite ugly code. Since this operation is not performance critical (compared to QBF-solving), we now recompute check_cnf_ completely in each iteration.
Parameters
take_small_win If this parameter is true (or omitted) the winning_region_ is used to compute the check_cnf_. Otherwise, the winning_region_large_ is used. The difference between these two winning region versions is as follows. From time to we remove redundant clauses (clauses implied by other clauses) from winning_region_ but not from winning_region_large_. Hence, winning_region_ is often smaller, but winning_region_large_ may contain clauses the solver may have to learn when using winning_region_.
Definition at line 565 of file LearnSynthQBF.cpp.
References CNF::addCNF(), check_cnf_, CNF::clear(), AIG2CNF::instance(), CNF::negate(), VarManager::resetToLastPush(), CNF::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegionAll(), and computeWinningRegionOne().
void LearnSynthQBF::recomputeGenCNF (bool take_small_win = true) [protected]
Recomputes the CNF (of the QBF) that is used for generalizing counterexamples.
The CNF used for generalizing counterexamples is F & T & F', where F is the winning_region_. The result is stored in generalize_clause_cnf_. Since F is constantly updated with new clauses, generalize_clause_cnf_ needs to be updated as well. In an old version, we updated the generalize_clause_cnf_ in place. This results in ugly code at some places (especially when the winning_region_ is compressed or simplified). Since this operation is not performance critical (compared to QBF-solving), we now recompute generalize_clause_cnf_ completely in each iteration.
Parameters
take_small_win If this parameter is true (or omitted) the winning_region_ is used to compute the generalize_clause_cnf_. Otherwise, the winning_region_large_ is used. The difference between these two winning region versions is as follows. From time to we remove redundant clauses (clauses implied by other clauses) from winning_region_ but not from winning_region_large_. Hence, winning_region_ is often smaller, but winning_region_large_ may contain clauses the solver may have to learn when using winning_region_.
Definition at line 588 of file LearnSynthQBF.cpp.
References CNF::addCNF(), CNF::clear(), generalize_clause_cnf_, AIG2CNF::instance(), CNF::swapPresentToNext(), winning_region_, and winning_region_large_.
Referenced by computeWinningRegionAll(), computeWinningRegionOne(), and computeWinningRegionOneSAT().
void LearnSynthQBF::reduceExistingClauses () [protected]
Tries to drop literals from clauses in the winning region.
This method examines all clauses (in winning_region_) that have already been computed and checks if more literals can be dropped. This is done in the same way as for dropping literals when generalizing a counterexample.
The intuition behind this method is that, even if a literal could not be dropped before, it could be dropped at a later point in time because the winning region has been refined in the meantime. However, in practice, typically only very few additional literals can be dropped, so this method often does not pay off.
Definition at line 532 of file LearnSynthQBF.cpp.
References CNF::addClauseAndSimplify(), CNF::addNegClauseAsCube(), gen_quant_, generalize_clause_cnf_, CNF::getClauses(), CNF::getNrOfClauses(), CNF::getNrOfLits(), QBFSolver::isSat(), L_DBG, LearnStatisticsQBF::notifyAfterCubeMin(), LearnStatisticsQBF::notifyBeforeCubeMin(), qbf_solver_, Utils::remove(), statistics_, winning_region_, and winning_region_large_.
Referenced by computeWinningRegionAll().
void LearnSynthQBF::restrictToStates (vector< int > & vec) const [protected]
Restricts a vector of literals (a cube or clause) to state-variables only.
That is, all literals that do not talk about present state variables are removed.
Parameters
vec The vector of literals (the cube or clause) to restricts to state-variables only.
Definition at line 608 of file LearnSynthQBF.cpp.
References VarManager::getInfo(), VarInfo::getKind(), VarManager::getPresErrorStateVar(), VarManager::instance(), and VarInfo::PRES_STATE.
Referenced by computeCounterexampleQBF().
bool LearnSynthQBF::run () [virtual]
Executes this back-end.
The computation of the winning region works as follows. We start with the initial guess that the winning region F is the set of all state states P. In a loop, we first compute a counterexample to the correctness of this guess in form of a state from which the antagonist (controlling the uncontrollable inputs i) can enforce to leave F. The state is represented as a cube over all state-variables. Next, this state-cube is generalized into a larger region of states by dropping literals as long as the cube contains only states that are winning for the antagonist (and hence must be removed or have already been removed from F). Finally, the generalized cube is removed from F. The next iteration checks for counterexample-state on the refined F. This is repeated until no more counterexample-states exist (then the specification is realizable and F is a winning region) or the initial state has been removed from F (in which case the specification is unrealizable).
Command-line parameters (--mode) are used to select different variants of this method. There is
the standard method as described above,
a variant which computes counterexamples using two SAT-solvers instead of a QBF solver,
a variant which computes and excludes all counterexample-generalizations instead of just one.
Returns
True if the specification was realizable, false otherwise.
Implements BackEnd.
Definition at line 92 of file LearnSynthQBF.cpp.
References computeWinningRegion(), Utils::debugCheckWinReg(), CNFImplExtractor::extractCircuit(), impl_extractor_, VarManager::instance(), Options::instance(), L_INF, L_RES, CNFImplExtractor::logStatistics(), LearnStatisticsQBF::logStatistics(), LearnStatisticsQBF::notifyWinRegEnd(), LearnStatisticsQBF::notifyWinRegStart(), VarManager::push(), statistics_, and winning_region_.
Member Data Documentation
CNF LearnSynthQBF::check_cnf_ [protected]
The CNF matrix of the QBF for computing counterexamples.
This CNF is always F & T & !F', where F is the winning_region_.
Definition at line 386 of file LearnSynthQBF.h.
Referenced by computeCounterexampleQBF(), computeWinningRegionAll(), computeWinningRegionOne(), computeWinningRegionOneSAT(), and recomputeCheckCNF().
vector<pair<VarInfo::VarKind, QBFSolver::Quant> > LearnSynthQBF::check_quant_ [protected]
The quantifier prefix of the QBF for computing counterexamples.
This quantifier prefix is always exists x,i: forall c: exists x',tmp:
Definition at line 379 of file LearnSynthQBF.h.
Referenced by computeCounterexampleQBF(), and LearnSynthQBF().
vector<pair<VarInfo::VarKind, QBFSolver::Quant> > LearnSynthQBF::gen_quant_ [protected]
The quantifier prefix of the QBF for generalizing counterexamples.
This quantifier prefix is always exists x: forall i: exists c,x',tmp:
Definition at line 394 of file LearnSynthQBF.h.
Referenced by generalizeCounterexample(), LearnSynthQBF(), and reduceExistingClauses().
CNF LearnSynthQBF::generalize_clause_cnf_ [protected]
The CNF matrix of the QBF for generalizing counterexamples.
This CNF is always F & T & F', where F is the winning_region_.
Definition at line 401 of file LearnSynthQBF.h.
Referenced by computeAllBlockingClauses(), computeWinningRegionAll(), computeWinningRegionOne(), computeWinningRegionOneSAT(), generalizeCounterexample(), recomputeGenCNF(), and reduceExistingClauses().
CNFImplExtractor* LearnSynthQBF::impl_extractor_ [protected]
The engine to use for circuit extraction.
It will be deleted by this class (in the destructor).
Definition at line 442 of file LearnSynthQBF.h.
Referenced by run(), and ~LearnSynthQBF().
vector<int> LearnSynthQBF::incremental_vars_to_keep_ [protected]
A list of variables the SAT-solver should not optimize away.
Definition at line 424 of file LearnSynthQBF.h.
Referenced by computeCounterexampleSAT(), and LearnSynthQBF().
QBFSolver* LearnSynthQBF::qbf_solver_ [protected]
The QBF-solver used for all queries.
The type of solver is selected with command-line arguments.
Definition at line 371 of file LearnSynthQBF.h.
Referenced by computeCounterexampleQBF(), generalizeCounterexample(), reduceExistingClauses(), and ~LearnSynthQBF().
SatSolver* LearnSynthQBF::solver_ctrl_ [protected]
The SAT-solver for protagonist moves when using computeCounterexampleSAT().
It stores the CNF F & T & !F', where F is the winning_region_. However, !F' is only updated lazily for performance reasons (this way, incremental solving can be exploited better).
Definition at line 419 of file LearnSynthQBF.h.
Referenced by computeCounterexampleSAT(), computeWinningRegionOneSAT(), LearnSynthQBF(), and ~LearnSynthQBF().
SatSolver* LearnSynthQBF::solver_i_ [protected]
The SAT-solver for antagonist moves when using computeCounterexampleSAT().
It stores the CNF F & T & !F', where F is the winning_region_. However, !F' is only updated lazily for performance reasons (this way, incremental solving can be exploited better).
Definition at line 410 of file LearnSynthQBF.h.
Referenced by computeCounterexampleSAT(), computeWinningRegionOneSAT(), LearnSynthQBF(), and ~LearnSynthQBF().
bool LearnSynthQBF::solver_i_precise_ [protected]
A flag indicating if solver_i_ is precise.
We update the next-state copy of the winning region in solver_i_ only lazily to better support incremental solving. If this flag is true, then this means that the next-state copy of the winning region is accurate in solver_i_. If this flag is false, then we must not trust any unsatisfiability verdicts coming from solver_i_ (but need to update the next-state copy of the winning region instead).
Definition at line 435 of file LearnSynthQBF.h.
Referenced by computeCounterexampleSAT(), and LearnSynthQBF().
LearnStatisticsQBF LearnSynthQBF::statistics_ [protected]
Stores and maintains statistics and performance measures.
Definition at line 364 of file LearnSynthQBF.h.
Referenced by computeAllBlockingClauses(), computeBlockingClause(), computeCounterexampleQBF(), computeCounterexampleSAT(), computeWinningRegionAll(), computeWinningRegionOne(), computeWinningRegionOneSAT(), reduceExistingClauses(), and run().
CNF LearnSynthQBF::winning_region_ [protected]
The current over-approximation of the winning region.
Only when computeWinningRegion() is done, this field will store the correct winning region.
Definition at line 347 of file LearnSynthQBF.h.
Referenced by computeCounterexampleSAT(), computeWinningRegionAll(), computeWinningRegionOne(), computeWinningRegionOneSAT(), recomputeCheckCNF(), recomputeGenCNF(), reduceExistingClauses(), and run().
CNF LearnSynthQBF::winning_region_large_ [protected]
The current over-approximation of the winning region in an uncompressed form.
This CNF is logically equivalent to winning_region_. However, winning_region_ is 'compressed' from time to time by removing redundant clauses (clauses that are implied by other clauses in the winning region). This field stores the uncompressed version of the winning region. Having the uncompressed winning region can be good because throwing away redundant clauses is not always beneficial. The CNF get smaller, but the solver may have to re-discover the removed clauses.
Definition at line 359 of file LearnSynthQBF.h.
Referenced by computeWinningRegionAll(), computeWinningRegionOne(), computeWinningRegionOneSAT(), recomputeCheckCNF(), recomputeGenCNF(), and reduceExistingClauses().
The documentation for this class was generated from the following files:
src/LearnSynthQBF.h
src/LearnSynthQBF.cpp