CNFImplExtractor Class Reference
An interface for all classes that can construct circuits from a CNF winning region.
#include <CNFImplExtractor.h>
Public Member Functions
CNFImplExtractor ()
Constructor.
virtual ~CNFImplExtractor ()
Destructor.
virtual void extractCircuit (const CNF &winning_region)
Extracts a circuit from the winning region.
virtual void extractCircuit (const CNF &winning_region, const CNF &neg_winning_region)
Extracts a circuit from the winning region and its negation.
virtual void logStatistics ()
Logs statistical information about circuit extraction.
Static Public Member Functions
static aiger * optimizeWithABC (aiger *circuit)
Optimizes a combinatorial AIGER circuit with ABC.
Protected Member Functions
virtual void run (const CNF &winning_region, const CNF &neg_winning_region)=0
Runs the circuit extractor.
virtual void logDetailedStatistics ()
Logs statistical information about circuit extraction.
size_t insertIntoSpec (aiger *standalone_circuit) const
Takes a circuit defining the control signals and inserts it into the spec.
Protected Attributes
double extraction_cpu_time_
The circuit extraction time in CPU-seconds.
size_t extraction_real_time_
Like extraction_cpu_time_ but real-time.
Private Member Functions
CNFImplExtractor (const CNFImplExtractor &other)
Copy constructor.
CNFImplExtractor & operator= (const CNFImplExtractor &other)
Assignment operator.
Detailed Description
An interface for all classes that can construct circuits from a CNF winning region.
This class is abstract, i.e., objects of this class cannot be instantiated. Instantiate one of the derived classes instead. Derived classes have to implement the run() method.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 48 of file CNFImplExtractor.h.
Constructor & Destructor Documentation
CNFImplExtractor::CNFImplExtractor ()
Constructor.
Definition at line 71 of file CNFImplExtractor.cpp.
CNFImplExtractor::~CNFImplExtractor () [virtual]
Destructor.
Definition at line 79 of file CNFImplExtractor.cpp.
CNFImplExtractor::CNFImplExtractor (const CNFImplExtractor & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void CNFImplExtractor::extractCircuit (const CNF & winning_region) [virtual]
Extracts a circuit from the winning region.
How this is done (interpolation, learning, etc.) depends on the concrete implementation of this abstract class. The result is written into the output file specified by the user.
Parameters
winning_region The winning region from which the circuit should be extracted. For circuit extraction we need both the winning region and its negation. The negation is computed inside this function. If you already have a negation, use the other circuit extraction method of this class.
Reimplemented in StoreImplExtractor.
Definition at line 85 of file CNFImplExtractor.cpp.
References Utils::compressStateCNF(), extraction_cpu_time_, extraction_real_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), CNF::negate(), run(), and Stopwatch::start().
Referenced by LoadSynth::run(), LearnSynthQBFInc::run(), TemplateSynth::run(), IFM13Synth::run(), LearnSynthQBF::run(), LearnSynthSAT::run(), LearnSynthQBFInd::run(), and ParallelLearner::run().
void CNFImplExtractor::extractCircuit (const CNF & winning_region, const CNF & neg_winning_region) [virtual]
Extracts a circuit from the winning region and its negation.
How this is done (interpolation, learning, etc.) depends on the concrete implementation of this abstract class. The result is written into the output file specified by the user.
Parameters
winning_region The winning region from which the circuit should be extracted.
neg_winning_region The negation of the winning region.
Definition at line 102 of file CNFImplExtractor.cpp.
References extraction_cpu_time_, extraction_real_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), run(), and Stopwatch::start().
size_t CNFImplExtractor::insertIntoSpec (aiger * standalone_circuit) const [protected]
Takes a circuit defining the control signals and inserts it into the spec.
This method takes as argument an aiger circuit of the following form:
The circuit is combinational, i.e., has no latches.
The inputs of the circuit are: the uncontrollable inputs from the spec (in the order in which they appear in the spec) followed by the state-signals (the output of the latches in the spec, in the order in which they appear in the spec).
The outputs of the circuit are the controllable inputs in the order in which they are defined in the spec.
Parameters
standalone_circuit A circuit defining the control signals.
Returns
The number of additional AND gates introduced into the spec.
Definition at line 149 of file CNFImplExtractor.cpp.
References VarInfo::CTRL, Options::getAigInFileName(), Options::getAigOutFileName(), VarManager::getInfo(), VarInfo::getLitInAIG(), VarManager::getMaxAIGVar(), VarManager::getPresErrorStateVar(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), Options::instance(), MASSERT, VarInfo::PRES_STATE, and StringUtils::toLowerCaseIn().
Referenced by ParExtractor::run(), LearningImplExtractor::run(), and QBFCertImplExtractor::run().
void CNFImplExtractor::logDetailedStatistics () [protected], [virtual]
Logs statistical information about circuit extraction.
Override this method to provide more detailed statistical information. Per default, the the method logStatistics logs the overall execution time, and then calls this method.
Reimplemented in LearningImplExtractor, ParExtractor, and QBFCertImplExtractor.
Definition at line 298 of file CNFImplExtractor.cpp.
Referenced by logStatistics().
void CNFImplExtractor::logStatistics () [virtual]
Logs statistical information about circuit extraction.
This method logs the overall execution time plus whatever detailed information is collected by the concrete implementation of this class.
Definition at line 290 of file CNFImplExtractor.cpp.
References extraction_cpu_time_, extraction_real_time_, L_LOG, and logDetailedStatistics().
Referenced by LoadSynth::run(), LearnSynthQBFInc::run(), TemplateSynth::run(), IFM13Synth::run(), LearnSynthQBF::run(), LearnSynthSAT::run(), LearnSynthQBFInd::run(), and ParallelLearner::run().
CNFImplExtractor& CNFImplExtractor::operator= (const CNFImplExtractor & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
aiger * CNFImplExtractor::optimizeWithABC (aiger * circuit) [static]
Optimizes a combinatorial AIGER circuit with ABC.
Note
The returned structure must be deleted by the caller.
Parameters
circuit The circuit to optimize.
Returns
The optimized version of the circuit. The returned aiger structure must be deleted by the caller.
Definition at line 112 of file CNFImplExtractor.cpp.
References Options::getTPDirName(), Options::getUniqueTmpFileName(), Options::instance(), and MASSERT.
Referenced by LearningImplExtractor::run(), QBFCertImplExtractor::run(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
virtual void CNFImplExtractor::run (const CNF & winning_region, const CNF & neg_winning_region) [protected], [pure virtual]
Runs the circuit extractor.
This is the workhorse of the circuit extractor. The methods extractCircuit mainly forward the call to this method.
Parameters
winning_region The winning region from which the circuit should be extracted.
neg_winning_region The negation of the winning region.
Implemented in QBFCertImplExtractor, LearningImplExtractor, StoreImplExtractor, ParExtractor, and InterpolImplExtractor.
Referenced by extractCircuit().
Member Data Documentation
double CNFImplExtractor::extraction_cpu_time_ [protected]
The circuit extraction time in CPU-seconds.
Definition at line 145 of file CNFImplExtractor.h.
Referenced by extractCircuit(), and logStatistics().
size_t CNFImplExtractor::extraction_real_time_ [protected]
Like extraction_cpu_time_ but real-time.
Definition at line 150 of file CNFImplExtractor.h.
Referenced by extractCircuit(), and logStatistics().
The documentation for this class was generated from the following files:
src/CNFImplExtractor.h
src/CNFImplExtractor.cpp