InterpolImplExtractor Class Reference
Supposed to extract circuits using interpolation; implemented in a separate branch.
#include <InterpolImplExtractor.h>
Public Member Functions
InterpolImplExtractor ()
Constructor.
virtual ~InterpolImplExtractor ()
Destructor.
virtual void run (const CNF &winning_region, const CNF &neg_winning_region)
Supposed to extract circuits using interpolation; implemented in a separate branch.
virtual void extractCircuit (const CNF &winning_region)
Extracts a circuit from the winning region.
virtual void extractCircuit (const CNF &winning_region, const CNF &neg_winning_region)
Extracts a circuit from the winning region and its negation.
virtual void logStatistics ()
Logs statistical information about circuit extraction.
Protected Member Functions
virtual void logDetailedStatistics ()
Logs statistical information about circuit extraction.
aiger * optimizeWithABC (aiger *circuit) const
Optimizes a combinatorial AIGER circuit with ABC.
size_t insertIntoSpec (aiger *standalone_circuit) const
Takes a circuit defining the control signals and inserts it into the spec.
Protected Attributes
double extraction_cpu_time_
The circuit extraction time in CPU-seconds.
size_t extraction_real_time_
Like extraction_cpu_time_ but real-time.
Private Member Functions
InterpolImplExtractor (const InterpolImplExtractor &other)
Copy constructor.
InterpolImplExtractor & operator= (const InterpolImplExtractor &other)
Assignment operator.
Detailed Description
Supposed to extract circuits using interpolation; implemented in a separate branch.
This class has been implemented in a separate branch by a student (Patrick Klapfl). It is not part of the release. Contact us if you would like to get the source code.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.1.0
Definition at line 46 of file InterpolImplExtractor.h.
Constructor & Destructor Documentation
InterpolImplExtractor::InterpolImplExtractor ()
Constructor.
Definition at line 34 of file InterpolImplExtractor.cpp.
References MASSERT.
InterpolImplExtractor::~InterpolImplExtractor () [virtual]
Destructor.
Definition at line 40 of file InterpolImplExtractor.cpp.
References MASSERT.
InterpolImplExtractor::InterpolImplExtractor (const InterpolImplExtractor & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void CNFImplExtractor::extractCircuit (const CNF & winning_region) [virtual], [inherited]
Extracts a circuit from the winning region.
How this is done (interpolation, learning, etc.) depends on the concrete implementation of this abstract class. The result is written into the output file specified by the user.
Parameters
winning_region The winning region from which the circuit should be extracted. For circuit extraction we need both the winning region and its negation. The negation is computed inside this function. If you already have a negation, use the other circuit extraction method of this class.
Reimplemented in StoreImplExtractor.
Definition at line 85 of file CNFImplExtractor.cpp.
References Utils::compressStateCNF(), CNFImplExtractor::extraction_cpu_time_, CNFImplExtractor::extraction_real_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), CNF::negate(), CNFImplExtractor::run(), and Stopwatch::start().
Referenced by LoadSynth::run(), LearnSynthQBFInc::run(), IFM13Synth::run(), TemplateSynth::run(), ParallelLearner::run(), LearnSynthQBF::run(), LearnSynthSAT::run(), and LearnSynthQBFInd::run().
void CNFImplExtractor::extractCircuit (const CNF & winning_region, const CNF & neg_winning_region) [virtual], [inherited]
Extracts a circuit from the winning region and its negation.
How this is done (interpolation, learning, etc.) depends on the concrete implementation of this abstract class. The result is written into the output file specified by the user.
Parameters
winning_region The winning region from which the circuit should be extracted.
neg_winning_region The negation of the winning region.
Definition at line 102 of file CNFImplExtractor.cpp.
References CNFImplExtractor::extraction_cpu_time_, CNFImplExtractor::extraction_real_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), CNFImplExtractor::run(), and Stopwatch::start().
size_t CNFImplExtractor::insertIntoSpec (aiger * standalone_circuit) const [protected], [inherited]
Takes a circuit defining the control signals and inserts it into the spec.
This method takes as argument an aiger circuit of the following form:
The circuit is combinational, i.e., has no latches.
The inputs of the circuit are: the uncontrollable inputs from the spec (in the order in which they appear in the spec) followed by the state-signals (the output of the latches in the spec, in the order in which they appear in the spec).
The outputs of the circuit are the controllable inputs in the order in which they are defined in the spec.
Parameters
standalone_circuit A circuit defining the control signals.
Returns
The number of additional AND gates introduced into the spec.
Definition at line 149 of file CNFImplExtractor.cpp.
References VarInfo::CTRL, Options::getAigInFileName(), Options::getAigOutFileName(), VarManager::getInfo(), VarInfo::getLitInAIG(), VarManager::getMaxAIGVar(), VarManager::getPresErrorStateVar(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), Options::instance(), MASSERT, VarInfo::PRES_STATE, and StringUtils::toLowerCaseIn().
Referenced by LearningImplExtractor::run(), and QBFCertImplExtractor::run().
void CNFImplExtractor::logDetailedStatistics () [protected], [virtual], [inherited]
Logs statistical information about circuit extraction.
Override this method to provide more detailed statistical information. Per default, the the method logStatistics logs the overall execution time, and then calls this method.
Reimplemented in LearningImplExtractor, and QBFCertImplExtractor.
Definition at line 298 of file CNFImplExtractor.cpp.
Referenced by CNFImplExtractor::logStatistics().
void CNFImplExtractor::logStatistics () [virtual], [inherited]
Logs statistical information about circuit extraction.
This method logs the overall execution time plus whatever detailed information is collected by the concrete implementation of this class.
Definition at line 290 of file CNFImplExtractor.cpp.
References CNFImplExtractor::extraction_cpu_time_, CNFImplExtractor::extraction_real_time_, L_LOG, and CNFImplExtractor::logDetailedStatistics().
Referenced by LoadSynth::run(), LearnSynthQBFInc::run(), IFM13Synth::run(), TemplateSynth::run(), ParallelLearner::run(), LearnSynthQBF::run(), LearnSynthSAT::run(), and LearnSynthQBFInd::run().
InterpolImplExtractor& InterpolImplExtractor::operator= (const InterpolImplExtractor & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
aiger * CNFImplExtractor::optimizeWithABC (aiger * circuit) const [protected], [inherited]
Optimizes a combinatorial AIGER circuit with ABC.
Note
The returned structure must be deleted by the caller.
Parameters
circuit The circuit to optimize.
Returns
The optimized version of the circuit. The returned aiger structure must be deleted by the caller.
Definition at line 112 of file CNFImplExtractor.cpp.
References Options::getTPDirName(), Options::getUniqueTmpFileName(), Options::instance(), and MASSERT.
Referenced by LearningImplExtractor::run(), and QBFCertImplExtractor::run().
void InterpolImplExtractor::run (const CNF & winning_region, const CNF & neg_winning_region) [virtual]
Supposed to extract circuits using interpolation; implemented in a separate branch.
Parameters
winning_region The winning region from which the circuit should be extracted.
neg_winning_region The negation of the winning region.
Implements CNFImplExtractor.
Definition at line 46 of file InterpolImplExtractor.cpp.
References MASSERT.
Member Data Documentation
double CNFImplExtractor::extraction_cpu_time_ [protected], [inherited]
The circuit extraction time in CPU-seconds.
Definition at line 145 of file CNFImplExtractor.h.
Referenced by CNFImplExtractor::extractCircuit(), and CNFImplExtractor::logStatistics().
size_t CNFImplExtractor::extraction_real_time_ [protected], [inherited]
Like extraction_cpu_time_ but real-time.
Definition at line 150 of file CNFImplExtractor.h.
Referenced by CNFImplExtractor::extractCircuit(), and CNFImplExtractor::logStatistics().
The documentation for this class was generated from the following files:
src/InterpolImplExtractor.h
src/InterpolImplExtractor.cpp