UnivExpander Class Reference
A utility class that can do universal expansion of given CNFs.
#include <UnivExpander.h>
Public Member Functions
UnivExpander ()
Constructor.
virtual ~UnivExpander ()
Destructor.
bool resetSolverIExp (CNF &win_reg, SatSolver *solver_i, bool limit_size=false)
Performs the reset of solver_i in LearnSynthSAT::computeWinningRegionPlainExp().
bool resetSolverIExp (CNF &win_reg, vector< SatSolver * > solvers, bool limit_size=false)
Same as the previous function but resets multiple solvers simultaneously.
void initSolverCExp (SatSolver *solver_c, const vector< int > &keep, size_t max_nr_of_signals_to_expand=1)
Initializes solver_c in LearnSynthSAT::computeWinningRegionPlainExp().
void addExpNxtClauseToC (const vector< int > &clause, SatSolver *solver_c)
Adds next-state clauses to solver_c after initialization with initSolverCExp().
void resetSolverCExp (SatSolver *solver_c)
Resets solver_c in LearnSynthSAT::computeWinningRegionPlainExp().
void extrExp (const CNF &nxt_win_reg, SatSolver *solver, const vector< int > to_exp) const
Initializes the solver for LearningImplExtractor::runLearningExp().
void setAbortCondition (volatile int *abort_if)
If the integer pointed to becomes != 0, the expansion aborts.
void cleanup ()
Destroys the stored data structures to save space.
Static Public Member Functions
static void univExpand (const CNF &orig, CNF &res, const vector< int > &vars_to_exp, const vector< int > &keep, float rate=1.1, const map< int, set< int > > *more_deps=NULL)
The standard method for universal expansion of certain variables.
Protected Member Functions
bool initSolverIData (bool limit_size=false)
A helper function for resetSolverIExp().
void simplifyTransAndsWithAbc ()
Simplifies the fully expanded AIGER graph using ABC.
bool shallAbort () const
Returns true of we call abort, and false otherwise.
void cleanupIData ()
Deletes all data structures that are needed for expansion in solver_i.
Protected Attributes
const vector< int > & s_
The list of present-state variables.
const vector< int > & i_
The list of (uncontrollable) input variables.
const vector< int > & c_
The list of control signals (controllable input variables).
const vector< int > & n_
The list of next-state variables.
vector< CNFAnd > i_trans_ands_
The expansion of the transition relation for resetSolverIExp().
int i_max_trans_var_
The maximum variable index occurring in i_trans_ands_.
vector< int > i_s_to_ren_n_
A map, renaming present-state vars to a renamed version of the next-state copy.
vector< vector< int > > i_rename_maps_
The rename maps resulting from the expansion of the transition relation.
vector< vector< int > > i_copy_maps_
Additional rename maps to be applied to i_rename_maps_.
vector< vector< int > > i_orig_prop_maps_
Additional rename maps to be applied to i_rename_maps_.
set< int > i_occ_
All the final copies of the next-state variables.
set< int > i_prev_occ_
The almost-final copies of the next-state variables.
set< int > i_occ_in_i_rename_maps_
All variables that occur (as values) in i_rename_maps_.
vector< vector< int > > c_rename_maps_
The rename maps for the next-state variables for adding clauses to solver_c.
CNF c_cnf_
The CNF to put into the solver when resetSolverCExp() is called.
vector< int > c_keep_
The CNF to put into the solver when resetSolverCExp() is called.
volatile int * abort_if_
If this pointer points to some integer that is not 0, expansion aborts.
Private Member Functions
UnivExpander (const UnivExpander &other)
Copy constructor.
UnivExpander & operator= (const UnivExpander &other)
Assignment operator.
Detailed Description
A utility class that can do universal expansion of given CNFs.
Universal expansion of a CNF with respect to certain variables is an expensive operation, especially if there are a lot of variables to expand. Hence, this operation must be implemented cleverly. For this reason, this class provides several implementations, each one tailored towards a specific application (expanding CTRL-signals in a conjuction of the transition relation with some CNF over the next-state variables, etc.)
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 71 of file UnivExpander.h.
Constructor & Destructor Documentation
UnivExpander::UnivExpander ()
Constructor.
Definition at line 95 of file UnivExpander.cpp.
UnivExpander::~UnivExpander () [virtual]
Destructor.
Definition at line 107 of file UnivExpander.cpp.
UnivExpander::UnivExpander (const UnivExpander & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void UnivExpander::addExpNxtClauseToC (const vector< int > & clause, SatSolver * solver_c)
Adds next-state clauses to solver_c after initialization with initSolverCExp().
After initSolverCExp() has been called to initialize solver_c, this method can be used to add next-state clauses to all expansions of the next-state variables.
Parameters
clause A clause over the current-state variables. It is added as clause over (all expansions of) the next state variables in solver_c.
solver_c The solver to which the next-state copies of this clause should be added.
Definition at line 932 of file UnivExpander.cpp.
References c_rename_maps_, and SatSolver::incAddClause().
Referenced by LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRCExp(), ClauseExplorerSAT::considerNewInfoFromOthers(), and ClauseExplorerSAT::exploreClauses().
void UnivExpander::cleanup ()
Destroys the stored data structures to save space.
Definition at line 1428 of file UnivExpander.cpp.
References c_cnf_, c_keep_, c_rename_maps_, cleanupIData(), and CNF::clear().
Referenced by ParallelLearner::run().
void UnivExpander::cleanupIData () [protected]
Deletes all data structures that are needed for expansion in solver_i.
These data structures can consume quite some memory, so we do not want to have them lying around uselessly.
Definition at line 2012 of file UnivExpander.cpp.
References i_copy_maps_, i_occ_, i_occ_in_i_rename_maps_, i_orig_prop_maps_, i_prev_occ_, i_rename_maps_, and i_trans_ands_.
Referenced by cleanup(), initSolverIData(), and resetSolverIExp().
void UnivExpander::extrExp (const CNF & nxt_win_reg, SatSolver * solver, const vector< int > to_exp) const
Initializes the solver for LearningImplExtractor::runLearningExp().
This method initializes the SAT solver for circuit extraction using universal expansion in order to use a SAT solver instead of a QBF solver. However, this approach appears to be very slow. The solver is filled with the CNF for T(x,i,c,x') & !W(x'), expanded over some but not all control signals.
Parameters
nxt_win_reg The next-state copy of the winning region, i.e., W(x').
solver The solver in which the expanded CNF should be put.
to_exp The set of control signals to expand.
Definition at line 954 of file UnivExpander.cpp.
References c_, CNF::getClauses(), VarManager::getMaxCNFVar(), AIG2CNF::getTrans(), i_, SatSolver::incAdd2LitClause(), SatSolver::incAdd3LitClause(), SatSolver::incAddClause(), SatSolver::incAddUnitClause(), VarManager::instance(), AIG2CNF::instance(), CNFAnd::l, MASSERT, n_, CNFAnd::r0, CNFAnd::r1, s_, and SatSolver::startIncrementalSession().
Referenced by LearningImplExtractor::runLearningExp().
void UnivExpander::initSolverCExp (SatSolver * solver_c, const vector< int > & keep, size_t max_nr_of_signals_to_expand = 1)
Initializes solver_c in LearnSynthSAT::computeWinningRegionPlainExp().
In LearnSynthSAT::computeWinningRegionPlainExp(), solver_c needs to check exists x: forall i: exists x',t: W(x) & T(x,i,c,x',t) & W(x') where W is the winning region (a CNF over the state variables x) and T is the transition relation with t being auxiliary variables. This method expands some of the input signals i in the transition relation T, and puts the resulting formula into solver_c. At the same time, this method also constructs a renaming map so clauses of W(x') can be added later on (using the method addExpNxtClauseToC()). This method is highly optimized for exactly this purpose. univExpand() could also be used in principle, but this method has more optimizations exploiting the structure of the transition relation.
Note
The newly created auxiliary variables are not registered in the VarManager for performance reasons (there may be zillions of new variables introduced during the expansion).
Parameters
solver_c The solver into which the expanded transition relation should be stored.
keep This method declares the current-state variables, the uncontrollable inputs, and the next-state variables (in their various copys) as reusable. If you also want other variables to be reusable (e.g. previous-state variables), then they can be enumerated in this vector.
max_nr_of_signals_to_expand For solver_c, expansion is very costly (more than for solver_i). Hence, we usually only expand a few input variables. This parameter defines the maximum number of input signals to expand. Low values are recommended.
Definition at line 655 of file UnivExpander.cpp.
References CNF::add1LitClause(), CNF::add2LitClause(), CNF::add3LitClause(), c_, c_cnf_, c_keep_, c_rename_maps_, CNF::clear(), CNF::getClauses(), VarManager::getMaxCNFVar(), AIG2CNF::getTmpDeps(), AIG2CNF::getTrans(), VarManager::getVarsOfType(), i_, SatSolver::incAdd2LitClause(), SatSolver::incAdd3LitClause(), SatSolver::incAddUnitClause(), VarManager::instance(), AIG2CNF::instance(), MASSERT, n_, VarInfo::PREV, s_, and SatSolver::startIncrementalSession().
Referenced by LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRCExp(), and ClauseExplorerSAT::exploreClauses().
bool UnivExpander::initSolverIData (bool limit_size = false) [protected]
A helper function for resetSolverIExp().
Some work in resetSolverIExp() needs to be done again and again when this method is called repeatedly. For instance, the expansion of the transition relation is always the same. This method performs these repeated tasks only once, and stores the resulting information in fields of this class. This way, they can then be reused by resetSolverIExp() whenever needed. All fields defined by this method start with 'i_'.
Parameters
limit_size If set to true, then this method aborts if the CNF size limit defined by Options::getSizeLimitForExpansion() is exceeded. This is supposed to prevent running out of memory during the expansion. If this flag is set to false, or omitted, then the size limit does not apply.
Returns
True if the size limit for the expansion has been exceeded during the initialization already. False if everything went OK.
Definition at line 1439 of file UnivExpander.cpp.
References c_, cleanupIData(), CNF::getClauses(), Utils::getCurrentMemUsage(), Options::getSizeLimitForExpansion(), AIG2CNF::getTmpDeps(), AIG2CNF::getTrans(), i_, i_copy_maps_, i_max_trans_var_, i_occ_, i_occ_in_i_rename_maps_, i_orig_prop_maps_, i_prev_occ_, i_rename_maps_, i_s_to_ren_n_, i_trans_ands_, Options::instance(), AIG2CNF::instance(), CNFAnd::l, MASSERT, n_, CNFAnd::r0, CNFAnd::r1, s_, shallAbort(), and simplifyTransAndsWithAbc().
Referenced by resetSolverIExp().
UnivExpander& UnivExpander::operator= (const UnivExpander & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
void UnivExpander::resetSolverCExp (SatSolver * solver_c)
Resets solver_c in LearnSynthSAT::computeWinningRegionPlainExp().
After many many iterations of LearnSynthSAT::computeWinningRegionPlainExp(), solver_c may contain many redundant clauses, which only slow down the solving process. So, from time to time, we may just reset the solver again (i.e., set it into the state after calling initSolverCExp) to get rid of all these redundant clauses.
Parameters
solver_c The solver to reset. After calling this method, solver_c will be in the same state as if initSolverCExp() had just been called.
Definition at line 947 of file UnivExpander.cpp.
References c_cnf_, c_keep_, SatSolver::incAddCNF(), and SatSolver::startIncrementalSession().
Referenced by LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRCExp(), and ClauseExplorerSAT::considerNewInfoFromOthers().
bool UnivExpander::resetSolverIExp (CNF & win_reg, SatSolver * solver_i, bool limit_size = false)
Performs the reset of solver_i in LearnSynthSAT::computeWinningRegionPlainExp().
In LearnSynthSAT::computeWinningRegionPlainExp(), solver_i needs to check exists x,i: forall c: exists x',t: W(x) & T(x,i,c,x',t) & !W(x') where W is the winning region (a CNF over the state variables x) and T is the transition relation with t being auxiliary variables. This method expands the control signals c of the above formula and puts the resulting formula into the SAT solver solver_i. This method is highly optimized for this purpose. For instance, the expansion of the transition relation is done only once and reused for different winning regions. univExpand() could also be used in principle, but this method has more optimizations exploiting the structure of the formula that needs to be expanded.
Note
The newly created auxiliary variables are not registered in the VarManager for performance reasons (there may be zillions of new variables introduced during the expansion).
Parameters
win_reg The winning region with which the solver should be initialized. This winning region is compressed (redundant clauses are removed) inside this function and, hence, modified.
solver_i The solver into which the expanded CNF should be stored.
limit_size If set to true, then this method aborts if the CNF size limit defined by Options::getSizeLimitForExpansion() is exceeded. This is supposed to prevent running out of memory during the expansion. If this flag is set to false, or omitted, then the size limit does not apply.
Returns
True if the size limit for the expansion has been exceeded. False if everything went OK (or nothing was checked because limit_size was set to false).
Definition at line 302 of file UnivExpander.cpp.
Referenced by LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRCExp(), ParallelLearner::triggerExplorerRestart(), and ParallelLearner::triggerInitialMode1Restart().
bool UnivExpander::resetSolverIExp (CNF & win_reg, vector< SatSolver * > solvers, bool limit_size = false)
Same as the previous function but resets multiple solvers simultaneously.
Parameters
win_reg The winning region with which the solver should be initialized. This winning region is compressed (redundant clauses are removed) inside this function and, hence, modified.
solvers The list of solvers into which the expanded CNF should be stored.
limit_size If set to true, then this method aborts if the CNF size limit defined by Options::getSizeLimitForExpansion() is exceeded. This is supposed to prevent running out of memory during the expansion. If this flag is set to false, or omitted, then the size limit does not apply.
Returns
True if the size limit for the expansion has been exceeded. False if everything went OK (or nothing was checked because limit_size was set to false).
Definition at line 309 of file UnivExpander.cpp.
References cleanupIData(), Utils::compressNextStateCNF(), CNF::getClauses(), Utils::getCurrentMemUsage(), Options::getSizeLimitForExpansion(), i_, i_copy_maps_, i_max_trans_var_, i_occ_in_i_rename_maps_, i_orig_prop_maps_, i_rename_maps_, i_trans_ands_, initSolverIData(), Options::instance(), AIG2CNF::instance(), MASSERT, n_, and s_.
void UnivExpander::setAbortCondition (volatile int * abort_if)
If the integer pointed to becomes != 0, the expansion aborts.
This is useful in the parallelization: if one thread already found a solution, it makes sense to abort the expansion (because the expansion can take quite long).
Parameters
abort_if A pointer to an integer. If this integer ever becomes != 0, the expansion aborts. If this pointer is NULL, we never abort.
Definition at line 1422 of file UnivExpander.cpp.
References abort_if_.
Referenced by ParallelLearner::ParallelLearner().
bool UnivExpander::shallAbort () const [protected]
Returns true of we call abort, and false otherwise.
This is useful in the parallelization: if one thread already found a solution, it makes sense to abort the expansion (because the expansion can take quite long).
See Also
setAbortCondition
Returns
true of we call abort, and false otherwise.
Definition at line 2004 of file UnivExpander.cpp.
References abort_if_.
Referenced by initSolverIData().
void UnivExpander::simplifyTransAndsWithAbc () [protected]
Simplifies the fully expanded AIGER graph using ABC.
This is a helper for initSolverIData(). If the transition relation is already fully expanded, then this method can be used to rewrite this expansion further to shring the formula. This method modifies i_trans_ands_, i_max_trans_var_, and i_rename_maps_.
Definition at line 1851 of file UnivExpander.cpp.
References Options::getTPDirName(), Options::getUniqueTmpFileName(), i_, i_copy_maps_, i_max_trans_var_, i_occ_, i_orig_prop_maps_, i_prev_occ_, i_rename_maps_, i_trans_ands_, Options::instance(), CNFAnd::l, L_DBG, MASSERT, CNFAnd::r0, CNFAnd::r1, and s_.
Referenced by initSolverIData().
void UnivExpander::univExpand (const CNF & orig, CNF & res, const vector< int > & vars_to_exp, const vector< int > & keep, float rate = 1.1, const map< int, set< int > > * more_deps = NULL) [static]
The standard method for universal expansion of certain variables.
Note
The newly created auxiliary variables are not registered in the VarManager for performance reasons (there may be zillions of new variables introduced during the expansion).
Parameters
orig The original CNF in which we perform universal expansion.
res An empty CNF. This is where the result will be stored.
vars_to_exp The list of variables to expand.
keep The list of variables that are quantified outside of the vars_to_exp and should hence not be renamed during the expansion.
rate A number between 0 and 1. It defines which fraction of the vars_to_exp should be expanded. Value 0.4 means that 40% of the vars_to_exp should be expanded. Use a value larger than 1 (or omit this parameter) if you want to be sure that every signal is expanded.
more_deps Additional dependencies that can be exploited during expansion. This map must map user-defined (temporary) variables to a set of other variables that define these variables. Don't include the dependencies of the temporary variables used to encode the transition relation, and don't include the dependencies of the next-state variables because they are automatically read from AIG2CNF. But if you have additional temporary variables, e.g., from Tseitin encoding some formula part then the expansion can benefit from dependency information (it needs to copy less). In any case: more_deps[i] must only contain variables in keep or vars_to_exp.
Definition at line 113 of file UnivExpander.cpp.
References CNF::appendVarsTo(), DASSERT, CNF::getClauses(), VarManager::getMaxCNFVar(), AIG2CNF::getTmpDepsTrans(), VarManager::instance(), AIG2CNF::instance(), and CNF::swapWith().
Member Data Documentation
volatile int* UnivExpander::abort_if_ [protected]
If this pointer points to some integer that is not 0, expansion aborts.
Definition at line 455 of file UnivExpander.h.
Referenced by setAbortCondition(), and shallAbort().
const vector<int>& UnivExpander::c_ [protected]
The list of control signals (controllable input variables).
This list is often used, so we keep it as a field to increase readability of the code.
Definition at line 318 of file UnivExpander.h.
Referenced by extrExp(), initSolverCExp(), and initSolverIData().
CNF UnivExpander::c_cnf_ [protected]
The CNF to put into the solver when resetSolverCExp() is called.
This CNF is computed by initSolverCExp() and contains the expanded transition relation for solver_c.
Definition at line 441 of file UnivExpander.h.
Referenced by cleanup(), initSolverCExp(), and resetSolverCExp().
vector<int> UnivExpander::c_keep_ [protected]
The CNF to put into the solver when resetSolverCExp() is called.
This CNF is computed by initSolverCExp() and contains the variables that should not be optimized away by the solver (because they will be needed in the incremental use of the solver).
Definition at line 450 of file UnivExpander.h.
Referenced by cleanup(), initSolverCExp(), and resetSolverCExp().
vector<vector<int> > UnivExpander::c_rename_maps_ [protected]
The rename maps for the next-state variables for adding clauses to solver_c.
c_rename_maps_[i] is the rename map for present-state variables to the i-th copy of the next state variables.
Definition at line 433 of file UnivExpander.h.
Referenced by addExpNxtClauseToC(), cleanup(), and initSolverCExp().
const vector<int>& UnivExpander::i_ [protected]
The list of (uncontrollable) input variables.
This list is often used, so we keep it as a field to increase readability of the code.
Definition at line 311 of file UnivExpander.h.
Referenced by extrExp(), initSolverCExp(), initSolverIData(), resetSolverIExp(), and simplifyTransAndsWithAbc().
vector<vector<int> > UnivExpander::i_copy_maps_ [protected]
Additional rename maps to be applied to i_rename_maps_.
For small benchmarks, this field is not used. For small benchmarks, all the renaming is stored in i_rename_maps_. However, for large benchmarks with many control signals, i_rename_maps_ can grow very large and eat up all our memory. For such cases, we do not build up i_rename_maps_ completely, but store the remaining renamings (to be applied to i_rename_maps_) in i_copy_maps_ and i_orig_prop_maps_.
Definition at line 393 of file UnivExpander.h.
Referenced by cleanupIData(), initSolverIData(), resetSolverIExp(), and simplifyTransAndsWithAbc().
int UnivExpander::i_max_trans_var_ [protected]
The maximum variable index occurring in i_trans_ands_.
That is, for resetSolverIExp(), i_max_trans_var_ + 1 is the next fresh CNF variable. All fields starting with 'i_' (like this one) are initialized by initSolverIData() and used by resetSolverIExp().
Definition at line 347 of file UnivExpander.h.
Referenced by initSolverIData(), resetSolverIExp(), and simplifyTransAndsWithAbc().
set<int> UnivExpander::i_occ_ [protected]
All the final copies of the next-state variables.
Definition at line 410 of file UnivExpander.h.
Referenced by cleanupIData(), initSolverIData(), and simplifyTransAndsWithAbc().
set<int> UnivExpander::i_occ_in_i_rename_maps_ [protected]
All variables that occur (as values) in i_rename_maps_.
Definition at line 425 of file UnivExpander.h.
Referenced by cleanupIData(), initSolverIData(), and resetSolverIExp().
vector<vector<int> > UnivExpander::i_orig_prop_maps_ [protected]
Additional rename maps to be applied to i_rename_maps_.
For small benchmarks, this field is not used. For small benchmarks, all the renaming is stored in i_rename_maps_. However, for large benchmarks with many control signals, i_rename_maps_ can grow very large and eat up all our memory. For such cases, we do not build up i_rename_maps_ completely, but store the remaining renamings (to be applied to i_rename_maps_) in i_copy_maps_ and i_orig_prop_maps_.
Definition at line 404 of file UnivExpander.h.
Referenced by cleanupIData(), initSolverIData(), resetSolverIExp(), and simplifyTransAndsWithAbc().
set<int> UnivExpander::i_prev_occ_ [protected]
The almost-final copies of the next-state variables.
This set is only used to overwrite renamings more efficiently. When we overwrite the renamings, then we need to update the last renaming map. The almost-final copies of the next-state variables are exactly the variables that are used as indices in the final rename map.
Definition at line 420 of file UnivExpander.h.
Referenced by cleanupIData(), initSolverIData(), and simplifyTransAndsWithAbc().
vector<vector<int> > UnivExpander::i_rename_maps_ [protected]
The rename maps resulting from the expansion of the transition relation.
i_rename_maps_[cnt] defines how to rename state variables to the obtain the renamed version of the next-state variables for expansion number cnt. i_rename_maps_[c1][c2] gives the c1'th renaming of the state variable with index (not value!) c2. We use the index to save memory. This rename map does not only do renaming, but also constant propagation. If a certain variable is renamed to 1, then it is set to TRUE. If it is renamed to -1, then it is set to FALSE. If there are n control signals, then this vector could contain 2^n rename maps, one for each expansion, in the worst case. For certain benchmarks, this rename map alone can consume all our memory (while i_trans_ands_ still stays small). Hence, if this i_rename_maps_ grows too large, we do not build it fully. Instead, we store further renamings (to be applied to i_rename_maps_) in i_copy_maps_ and i_orig_prop_maps_ and apply them only when needed.
Definition at line 382 of file UnivExpander.h.
Referenced by cleanupIData(), initSolverIData(), resetSolverIExp(), and simplifyTransAndsWithAbc().
vector<int> UnivExpander::i_s_to_ren_n_ [protected]
A map, renaming present-state vars to a renamed version of the next-state copy.
resetSolverIExp() gets the winning region, and needs to expand and negate the next-state copy of the winning region. This map does two renamings in one go: (1) it renames present state variables to their corresponding next-state copy, and (2) it further renames the next-state copy of state variables to the auxiliary variables defining them in the transition relation. Originally, the transition relation CNF has special clauses that do this renaming. We remove these clauses and do the renaming with a map. This is more efficient. Otherwise, the renaming-clauses of the transition relation would get copied many many many times, which increases the size of the expanded CNFs unnecessarily. All fields starting with 'i_' (like this one) are initialized by initSolverIData() and used by resetSolverIExp().
Definition at line 363 of file UnivExpander.h.
Referenced by initSolverIData().
vector<CNFAnd> UnivExpander::i_trans_ands_ [protected]
The expansion of the transition relation for resetSolverIExp().
We do not expand the transition relation again and again, but we do this only once and reuse it. The only thing we expand freshly each time is the next state copy of the (negation of the) winning region. All fields starting with 'i_' (like this one) are initialized by initSolverIData() and used by resetSolverIExp(). We store the expansion of the transition relation here as a list of AND gates. Storing it as CNF would waste memory (this expansion can be very big).
Definition at line 338 of file UnivExpander.h.
Referenced by cleanupIData(), initSolverIData(), resetSolverIExp(), and simplifyTransAndsWithAbc().
const vector<int>& UnivExpander::n_ [protected]
The list of next-state variables.
This list is often used, so we keep it as a field to increase readability of the code.
Definition at line 325 of file UnivExpander.h.
Referenced by extrExp(), initSolverCExp(), initSolverIData(), and resetSolverIExp().
const vector<int>& UnivExpander::s_ [protected]
The list of present-state variables.
This list is often used, so we keep it as a field to increase readability of the code.
Definition at line 304 of file UnivExpander.h.
Referenced by extrExp(), initSolverCExp(), initSolverIData(), resetSolverIExp(), and simplifyTransAndsWithAbc().
The documentation for this class was generated from the following files:
src/UnivExpander.h
src/UnivExpander.cpp