RareqsApi Class Reference
Interfaces the RAReQS QBF-solver via its API.
#include <RareqsApi.h>
Public Types
enum Quant { E,
A
 }
A type for the different kinds of quantifiers.
Public Member Functions
RareqsApi ()
Constructor.
virtual ~RareqsApi ()
Destructor.
virtual bool isSat (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
Checks if a given QBF is satisfiable (with quantification over variable kinds).
virtual bool isSat (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
Checks if a given QBF is satisfiable (with quantification over variable sets).
virtual bool isSatModel (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf, vector< int > &model)
Checks satisfiability and extracts a model (quantifying over variable kinds).
virtual bool isSatModel (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf, vector< int > &model)
Checks satisfiability and extracts a model (quantifying over variable sets).
Private Member Functions
RareqsApi (const RareqsApi &other)
Copy constructor.
RareqsApi & operator= (const RareqsApi &other)
Assignment operator.
Detailed Description
Interfaces the RAReQS QBF-solver via its API.
This class represents an interface to the QBF-solver RAReQS (see http://sat.inesc-id.pt/~mikolas/sw/areqs/). For a given Quantified Boolean formula (a CNF with a quantifier prefix), this class is able to determine satisfiability. Furthermore, in case of satisfiability, it can extract satisfying assignments for variables quantified existentially on the outermost level.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 49 of file RareqsApi.h.
Member Enumeration Documentation
enum QBFSolver::Quant [inherited]
A type for the different kinds of quantifiers.
Enumerator
E
 The value for existential quantification.
A
 The value for universal quantification.
Definition at line 56 of file QBFSolver.h.
Constructor & Destructor Documentation
RareqsApi::RareqsApi ()
Constructor.
Definition at line 57 of file RareqsApi.cpp.
RareqsApi::~RareqsApi () [virtual]
Destructor.
Definition at line 63 of file RareqsApi.cpp.
RareqsApi::RareqsApi (const RareqsApi & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
bool RareqsApi::isSat (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [virtual]
Checks if a given QBF is satisfiable (with quantification over variable kinds).
The QBF consists of a quantifier prefix and a Boolean formula in CNF. The quantifier prefix assigns an existential or universal quantifier to every kind of variable.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 69 of file RareqsApi.cpp.
References QBFSolver::E, CNF::getClauses(), VarManager::getVarsOfType(), and VarManager::instance().
bool RareqsApi::isSat (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [virtual]
Checks if a given QBF is satisfiable (with quantification over variable sets).
The QBF consists of a quantifier prefix and a Boolean formula in CNF. The quantifier prefix assigns an existential or universal quantifier to different sets variable.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 98 of file RareqsApi.cpp.
References QBFSolver::E, and CNF::getClauses().
bool RareqsApi::isSatModel (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf, vector< int > & model) [virtual]
Checks satisfiability and extracts a model (quantifying over variable kinds).
Just like isSat() , this method checks a quantified Boolean formula for satisfiability. If the QBF is satisfiable, this method also extracts a model (a satisfying assignment) for all variables which are quantified existentially on the outermost level. The model is provided as cube: negated variables in the cube are FALSE, unnegated ones are TRUE.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
model The resulting model in form of a cube in case of satisfiability. Negated variables in the cube are FALSE, unnegated ones are TRUE. If the formula is unsatisfiable (this method returns false) then this parameter is not modified.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 125 of file RareqsApi.cpp.
References QBFSolver::E, CNF::getClauses(), VarManager::getVarsOfType(), and VarManager::instance().
bool RareqsApi::isSatModel (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf, vector< int > & model) [virtual]
Checks satisfiability and extracts a model (quantifying over variable sets).
Just like isSat() , this method checks a quantified Boolean formula for satisfiability. If the QBF is satisfiable, this method also extracts a model (a satisfying assignment) for all variables which are quantified existentially on the outermost level. The model is provided as cube: negated variables in the cube are FALSE, unnegated ones are TRUE.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
model The resulting model in form of a cube in case of satisfiability. Negated variables in the cube are FALSE, unnegated ones are TRUE. If the formula is unsatisfiable (this method returns false) then this parameter is not modified.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 153 of file RareqsApi.cpp.
References QBFSolver::E, and CNF::getClauses().
RareqsApi& RareqsApi::operator= (const RareqsApi & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
The documentation for this class was generated from the following files:
src/RareqsApi.h
src/RareqsApi.cpp