LoadSynth Class Reference
A dummy back-end which loads the winning region from a file.
#include <LoadSynth.h>
Public Member Functions
LoadSynth (CNFImplExtractor *impl_extractor)
Constructor.
virtual ~LoadSynth ()
Destructor.
virtual bool run ()
Loads the winning region from a file and runs the circuit extractor.
Protected Attributes
CNFImplExtractor * impl_extractor_
The engine to use for circuit extraction.
Private Member Functions
LoadSynth (const LoadSynth &other)
Copy constructor.
LoadSynth & operator= (const LoadSynth &other)
Assignment operator.
Detailed Description
A dummy back-end which loads the winning region from a file.
This back-end is used to reduce the computation time when benchmarking relation determinization approaches. It loads the winning region from a file instead of computing it. The StoreImplExtractor can save the winning region into a file. We assume that this has been done before.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.1.0
Definition at line 50 of file LoadSynth.h.
Constructor & Destructor Documentation
LoadSynth::LoadSynth (CNFImplExtractor * impl_extractor)
Constructor.
Parameters
impl_extractor The engine to use for circuit extraction. It will be deleted by this class.
Definition at line 36 of file LoadSynth.cpp.
LoadSynth::~LoadSynth () [virtual]
Destructor.
Definition at line 44 of file LoadSynth.cpp.
References impl_extractor_.
LoadSynth::LoadSynth (const LoadSynth & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
LoadSynth& LoadSynth::operator= (const LoadSynth & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
bool LoadSynth::run () [virtual]
Loads the winning region from a file and runs the circuit extractor.
This method is used to reduce the computation time when benchmarking relation determinization approaches. It loads the winning region from a file instead of computing it. Then it runs the circuit extraction. The StoreImplExtractor can save the winning region into a file. We assume that this has been done before.
Returns
Always true.
Implements BackEnd.
Definition at line 51 of file LoadSynth.cpp.
References CNFImplExtractor::extractCircuit(), Options::getAigInFileNameOnly(), impl_extractor_, Options::instance(), and CNFImplExtractor::logStatistics().
Member Data Documentation
CNFImplExtractor* LoadSynth::impl_extractor_ [protected]
The engine to use for circuit extraction.
It will be deleted by this class (in the destructor).
Definition at line 86 of file LoadSynth.h.
Referenced by run(), and ~LoadSynth().
The documentation for this class was generated from the following files:
src/LoadSynth.h
src/LoadSynth.cpp