DepQBFApiInc Class Reference
Interfaces an experimental DepQBF-version via its API.
#include <DepQBFApiInc.h>
Public Types
enum Quant { E,
A
 }
A type for the different kinds of quantifiers.
Public Member Functions
DepQBFApiInc (bool use_bloqqer=false)
Constructor.
virtual ~DepQBFApiInc ()
Destructor.
virtual bool isSat (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
Checks if a given QBF is satisfiable (with quantification over variable kinds).
virtual bool isSat (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
Checks if a given QBF is satisfiable (with quantification over variable sets).
virtual bool isSatModel (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf, vector< int > &model)
Checks satisfiability and extracts a model (quantifying over variable kinds).
virtual bool isSatModel (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf, vector< int > &model)
Checks satisfiability and extracts a model (quantifying over variable sets).
virtual void startIncrementalSession (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix)
Starts an 'incremental' session with a quantifier prefix over variable kinds.
virtual void startIncrementalSession (const vector< pair< vector< int >, Quant > > &quantifier_prefix)
Starts an 'incremental' session with a quantifier prefix over variable sets.
virtual void clearIncrementalSession ()
Closes a previously opened incremental session and frees all resources.
virtual void incAddCNF (const CNF &cnf)
Adds (conjuncts) a new CNF to the current incremental session.
virtual void incAddClause (const vector< int > &clause)
Adds (conjuncts) a new clause to the current incremental session.
virtual void incAddCube (const vector< int > &cube)
Adds (conjuncts) a new cube to the current incremental session.
virtual bool incIsSat ()
Checks if the QBF in the current incremental session is satisfiable.
virtual bool incIsSat (const vector< int > &assumptions)
Checks if the QBF in the incremental session is satisfiable under assumptions.
virtual bool incIsSatModelOrCore (const vector< int > &assumptions, vector< int > &model_or_core)
Checks if the incremental session is satisfiable and computes a model or core.
Protected Member Functions
void initBloqqer (const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
Initializes the pre-processor with a QBF (quantifying over variable kinds).
void initBloqqer (const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
Initializes the pre-processor with a QBF (quantifying over variable sets).
void initDepQBF (QDPLL *solver, const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
Initializes a DepQBF instance with a QBF (quantifying over variable kinds).
void initDepQBF (QDPLL *solver, const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
Initializes a DepQBF instance with a QBF (quantifying over variable sets).
void extractCore (QDPLL *solver, vector< int > &core)
Extracts an unsatisfiable core after unsatisfiability has been shown.
void debugCheckBloqqerVerdict (int bloqqer_verdict, const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
A debug function to cross-check bloqqer verdicts (SAT or UNSAT).
void debugCheckBloqqerVerdict (int bloqqer_verdict, const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
A debug function to cross-check bloqqer verdicts (SAT or UNSAT).
void debugCheckBloqqerModel (const vector< int > &model, const vector< pair< VarInfo::VarKind, Quant > > &quantifier_prefix, const CNF &cnf)
A debug function to cross-check models produced by bloqqer.
void debugCheckBloqqerModel (const vector< int > &model, const vector< pair< vector< int >, Quant > > &quantifier_prefix, const CNF &cnf)
A debug function to cross-check models produced by bloqqer.
Protected Attributes
bool use_bloqqer_
A flag indicating whether or not the pre-processor bloqqer should be used.
bool min_cores_
A flag indicating whether or not unsatisfiable cores should be further minimized.
QDPLL * inc_solver_
The solver instance to use in the incremental session.
vector< int > inc_model_vars_
The variables for which a satisfying assignment can be constructed.
Private Member Functions
DepQBFApiInc (const DepQBFApiInc &other)
Copy constructor.
DepQBFApiInc & operator= (const DepQBFApiInc &other)
Assignment operator.
Detailed Description
Interfaces an experimental DepQBF-version via its API.
This class represents an interface to an experimental version of the QBF-solver DepQBF (see https://github.com/lonsing/depqbf). This version is not (yet) publicly available. In addition to the features of DepQBFApi, this interface to DepQBF can also compute unsatisfiable cores. Furthermore, it can use DepQBF incrementally in the sense that clauses that talk only about variables that are quantified existentially on the outermost quantifier block can be added without a need to restart the solver completely.
Otherwise, this class is equivalent to DepQBFApi.
Note
This class is experimental.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.0.0
Definition at line 55 of file DepQBFApiInc.h.
Member Enumeration Documentation
enum QBFSolver::Quant [inherited]
A type for the different kinds of quantifiers.
Enumerator:
E
 The value for existential quantification.
A
 The value for universal quantification.
Definition at line 56 of file QBFSolver.h.
Constructor & Destructor Documentation
DepQBFApiInc::DepQBFApiInc (bool use_bloqqer = false)
Constructor.
Parameters
use_bloqqer True if bloqqer should be used as pre-processor, false if no pre-processing should be used. If this parameter is omitted, no pre-processing is used.
Definition at line 42 of file DepQBFApiInc.cpp.
DepQBFApiInc::~DepQBFApiInc () [virtual]
Destructor.
Definition at line 51 of file DepQBFApiInc.cpp.
References clearIncrementalSession().
DepQBFApiInc::DepQBFApiInc (const DepQBFApiInc & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void DepQBFApiInc::clearIncrementalSession () [virtual]
Closes a previously opened incremental session and frees all resources.
If no incremental session is open, then this method has no effect at all.
Definition at line 370 of file DepQBFApiInc.cpp.
References inc_model_vars_, inc_solver_, and MASSERT.
Referenced by ~DepQBFApiInc().
void DepQBFApiInc::debugCheckBloqqerModel (const vector< int > & model, const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
A debug function to cross-check models produced by bloqqer.
DepQBF without preprocessing is used to check if the model found by bloqqer indeed satisfies the QBF. This method is used to debug bloqqer.
Parameters
model The satisfying assignment found by bloqqer. Negated variables in the vector are FALSE, unnegated ones are TRUE.
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Definition at line 744 of file DepQBFApiInc.cpp.
References CNF::addCube(), Utils::debugPrint(), ExtQBFSolver::dumpQBF(), VarManager::getVarsOfType(), VarManager::instance(), isSat(), L_ERR, and MASSERT.
void DepQBFApiInc::debugCheckBloqqerModel (const vector< int > & model, const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
A debug function to cross-check models produced by bloqqer.
DepQBF without preprocessing is used to check if the model found by bloqqer indeed satisfies the QBF. This method is used to debug bloqqer.
Parameters
model The satisfying assignment found by bloqqer. Negated variables in the vector are FALSE, unnegated ones are TRUE.
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Definition at line 791 of file DepQBFApiInc.cpp.
References CNF::addCube(), Utils::debugPrint(), ExtQBFSolver::dumpQBF(), isSat(), L_ERR, and MASSERT.
void DepQBFApiInc::debugCheckBloqqerVerdict (int bloqqer_verdict, const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
A debug function to cross-check bloqqer verdicts (SAT or UNSAT).
The QBF is also solved with DepQBF without pre-processing and the two verdicts are compared. This method is used to debug bloqqer.
Parameters
bloqqer_verdict The result returned by bloqqer. The value 10 means SAT, the value 20 means UNSAT.
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Definition at line 686 of file DepQBFApiInc.cpp.
References ExtQBFSolver::dumpQBF(), isSat(), L_ERR, and MASSERT.
Referenced by isSatModel().
void DepQBFApiInc::debugCheckBloqqerVerdict (int bloqqer_verdict, const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
A debug function to cross-check bloqqer verdicts (SAT or UNSAT).
The QBF is also solved with DepQBF without pre-processing and the two verdicts are compared. This method is used to debug bloqqer.
Parameters
bloqqer_verdict The result returned by bloqqer. The value 10 means SAT, the value 20 means UNSAT.
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Definition at line 715 of file DepQBFApiInc.cpp.
References ExtQBFSolver::dumpQBF(), isSat(), L_ERR, and MASSERT.
void DepQBFApiInc::extractCore (QDPLL * solver, vector< int > & core) [protected]
Extracts an unsatisfiable core after unsatisfiability has been shown.
Parameters
solver The DepQBF solver instance to extract the core from.
core The vector into which the resulting unsatisfiable core will be stored. It is a subset of the used assumptions.
Definition at line 638 of file DepQBFApiInc.cpp.
References MASSERT, min_cores_, Utils::randomize(), and Utils::remove().
Referenced by incIsSatModelOrCore().
void DepQBFApiInc::incAddClause (const vector< int > & clause) [virtual]
Adds (conjuncts) a new clause to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
clause The clause which shall be conjuncted to the CNF in the currently open incremental session.
Definition at line 402 of file DepQBFApiInc.cpp.
References inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::computeWinningRegionAll(), and LearnSynthQBFInc::computeWinningRegionOne().
void DepQBFApiInc::incAddCNF (const CNF & cnf) [virtual]
Adds (conjuncts) a new CNF to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
cnf A Boolean formula in CNF. It is conjuncted to the CNF in the currently open incremental session.
Definition at line 385 of file DepQBFApiInc.cpp.
References CNF::getClauses(), inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::computeAllBlockingClauses(), LearnSynthQBFInc::computeBlockingClause(), LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionOne(), and LearnSynthQBFInc::reduceExistingClauses().
void DepQBFApiInc::incAddCube (const vector< int > & cube) [virtual]
Adds (conjuncts) a new cube to the current incremental session.
Precondition
startIncrementalSession() must have been called before.
Parameters
cube The cube which shall be conjuncted to the CNF in the currently open incremental session. All literals of the cube are added as unit clauses to the CNF of the currently open session.
Definition at line 415 of file DepQBFApiInc.cpp.
References inc_solver_, and MASSERT.
bool DepQBFApiInc::incIsSat () [virtual]
Checks if the QBF in the current incremental session is satisfiable.
Returns
True if the QBF in the current incremental session is satisfiable, false otherwise.
Definition at line 430 of file DepQBFApiInc.cpp.
References inc_solver_, and MASSERT.
bool DepQBFApiInc::incIsSat (const vector< int > & assumptions) [virtual]
Checks if the QBF in the incremental session is satisfiable under assumptions.
Parameters
assumptions The assumptions under which the QBF in the current incremental session should be solved. The assumptions are interpreted as a cube of literals. Every literal is added temporarily as a unit clause to the QBF.
Returns
True if the QBF in the current incremental session is satisfiable under the assumptions, false otherwise.
Definition at line 447 of file DepQBFApiInc.cpp.
References inc_solver_, and MASSERT.
bool DepQBFApiInc::incIsSatModelOrCore (const vector< int > & assumptions, vector< int > & model_or_core) [virtual]
Checks if the incremental session is satisfiable and computes a model or core.
This method first checks if the QBF in the incremental session is satisfiable under a given set of assumptions. If yes, then a satisfying assignment for the variables quantified existentially on the outermost level is computed. Otherwise, an unsatisfiable core is computed. An unsatisfiable core is a subset of the assumptions under which the QBF is still unsatisfiable.
Parameters
assumptions The assumptions under which the QBF in the current incremental session should be solved. The assumptions are interpreted as a cube of literals. Every literal is added temporarily as a unit clause to the QBF.
model_or_core The vector into which the resulting model or core will be stored. In case of satisfiability a satisfying assignment (a cube of literals; negated ones are false, unnegated ones are true) is stored in this vector. Otherwise, if this method returns false, a subset of the passed assumptions is stored in this vector.
Returns
True if the QBF in the current incremental session is satisfiable under the assumptions, false otherwise.
Definition at line 466 of file DepQBFApiInc.cpp.
References extractCore(), inc_model_vars_, inc_solver_, and MASSERT.
Referenced by LearnSynthQBFInc::computeCounterexampleQBF(), and LearnSynthQBFInc::generalizeCounterexample().
void DepQBFApiInc::initBloqqer (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
Initializes the pre-processor with a QBF (quantifying over variable kinds).
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Definition at line 511 of file DepQBFApiInc.cpp.
References QBFSolver::E, CNF::getClauses(), VarManager::getMaxCNFVar(), CNF::getNrOfClauses(), VarManager::getVarsOfType(), and VarManager::instance().
Referenced by isSat(), and isSatModel().
void DepQBFApiInc::initBloqqer (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
Initializes the pre-processor with a QBF (quantifying over variable sets).
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Definition at line 539 of file DepQBFApiInc.cpp.
References QBFSolver::E, CNF::getClauses(), and CNF::getNrOfClauses().
void DepQBFApiInc::initDepQBF (QDPLL * solver, const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
Initializes a DepQBF instance with a QBF (quantifying over variable kinds).
Parameters
solver The DepQBF solver instance to initialize.
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Definition at line 575 of file DepQBFApiInc.cpp.
References QBFSolver::E, CNF::getClauses(), VarManager::getMaxCNFVar(), VarManager::getVarsOfType(), and VarManager::instance().
Referenced by isSat(), isSatModel(), and startIncrementalSession().
void DepQBFApiInc::initDepQBF (QDPLL * solver, const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [protected]
Initializes a DepQBF instance with a QBF (quantifying over variable sets).
Parameters
solver The DepQBF solver instance to initialize.
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Definition at line 602 of file DepQBFApiInc.cpp.
References QBFSolver::E, and CNF::getClauses().
bool DepQBFApiInc::isSat (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf) [virtual]
Checks if a given QBF is satisfiable (with quantification over variable kinds).
The QBF consists of a quantifier prefix and a Boolean formula in CNF. The quantifier prefix assigns an existential or universal quantifier to every kind of variable.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 57 of file DepQBFApiInc.cpp.
References initBloqqer(), initDepQBF(), MASSERT, and use_bloqqer_.
Referenced by debugCheckBloqqerModel(), and debugCheckBloqqerVerdict().
bool DepQBFApiInc::isSat (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf) [virtual]
Checks if a given QBF is satisfiable (with quantification over variable sets).
The QBF consists of a quantifier prefix and a Boolean formula in CNF. The quantifier prefix assigns an existential or universal quantifier to different sets variable.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 89 of file DepQBFApiInc.cpp.
References initBloqqer(), initDepQBF(), MASSERT, and use_bloqqer_.
bool DepQBFApiInc::isSatModel (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix, const CNF & cnf, vector< int > & model) [virtual]
Checks satisfiability and extracts a model (quantifying over variable kinds).
Just like isSat() , this method checks a quantified Boolean formula for satisfiability. If the QBF is satisfiable, this method also extracts a model (a satisfying assignment) for all variables which are quantified existentially on the outermost level. The model is provided as cube: negated variables in the cube are FALSE, unnegated ones are TRUE.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
cnf A Boolean formula in CNF.
model The resulting model in form of a cube in case of satisfiability. Negated variables in the cube are FALSE, unnegated ones are TRUE. If the formula is unsatisfiable (this method returns false) then this parameter is not modified.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 121 of file DepQBFApiInc.cpp.
References debugCheckBloqqerVerdict(), VarManager::getVarsOfType(), initBloqqer(), initDepQBF(), VarManager::instance(), MASSERT, and use_bloqqer_.
bool DepQBFApiInc::isSatModel (const vector< pair< vector< int >, Quant > > & quantifier_prefix, const CNF & cnf, vector< int > & model) [virtual]
Checks satisfiability and extracts a model (quantifying over variable sets).
Just like isSat() , this method checks a quantified Boolean formula for satisfiability. If the QBF is satisfiable, this method also extracts a model (a satisfying assignment) for all variables which are quantified existentially on the outermost level. The model is provided as cube: negated variables in the cube are FALSE, unnegated ones are TRUE.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
cnf A Boolean formula in CNF.
model The resulting model in form of a cube in case of satisfiability. Negated variables in the cube are FALSE, unnegated ones are TRUE. If the formula is unsatisfiable (this method returns false) then this parameter is not modified.
Returns
True if the QBF is satisfiable, false otherwise.
Implements QBFSolver.
Definition at line 211 of file DepQBFApiInc.cpp.
References debugCheckBloqqerVerdict(), initBloqqer(), initDepQBF(), MASSERT, and use_bloqqer_.
DepQBFApiInc& DepQBFApiInc::operator= (const DepQBFApiInc & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
void DepQBFApiInc::startIncrementalSession (const vector< pair< VarInfo::VarKind, Quant > > & quantifier_prefix) [virtual]
Starts an 'incremental' session with a quantifier prefix over variable kinds.
Here, 'incrementally' means that clauses that talk only about variables that are quantified existentially on the outermost quantifier block can be added without a need to restart the solver completely.
Every DepQBFApiInc instance can only have one open incremental session. If you call this method twice, the old incremental session (if any) will be deleted (just like calling clearIncrementalSession()) and a new one will be opened.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to every kind of variable that occurs in the cnf.
Definition at line 308 of file DepQBFApiInc.cpp.
References QBFSolver::E, VarManager::getMaxCNFVar(), VarManager::getVarsOfType(), inc_model_vars_, inc_solver_, initDepQBF(), VarManager::instance(), and MASSERT.
Referenced by LearnSynthQBFInc::computeAllBlockingClauses(), LearnSynthQBFInc::computeBlockingClause(), LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionOne(), and LearnSynthQBFInc::reduceExistingClauses().
void DepQBFApiInc::startIncrementalSession (const vector< pair< vector< int >, Quant > > & quantifier_prefix) [virtual]
Starts an 'incremental' session with a quantifier prefix over variable sets.
Here, 'incrementally' means that clauses that talk only about variables that are quantified existentially on the outermost quantifier block can be added without a need to restart the solver completely.
Every DepQBFApiInc instance can only have one open incremental session. If you call this method twice, the old incremental session (if any) will be deleted (just like calling clearIncrementalSession()) and a new one will be opened.
Parameters
quantifier_prefix The quantifier prefix as a vector of pairs. vector[0] is the leftmost (i.e., outermost) quantifier block. The pairs in the quantifier_prefix assign an existential or universal quantifier to different sets of variables occurring in the cnf.
Definition at line 339 of file DepQBFApiInc.cpp.
References QBFSolver::E, VarManager::getMaxCNFVar(), inc_model_vars_, inc_solver_, initDepQBF(), VarManager::instance(), and MASSERT.
Member Data Documentation
vector<int> DepQBFApiInc::inc_model_vars_ [protected]
The variables for which a satisfying assignment can be constructed.
Definition at line 427 of file DepQBFApiInc.h.
Referenced by clearIncrementalSession(), incIsSatModelOrCore(), and startIncrementalSession().
QDPLL* DepQBFApiInc::inc_solver_ [protected]
The solver instance to use in the incremental session.
Definition at line 422 of file DepQBFApiInc.h.
Referenced by clearIncrementalSession(), incAddClause(), incAddCNF(), incAddCube(), incIsSat(), incIsSatModelOrCore(), and startIncrementalSession().
bool DepQBFApiInc::min_cores_ [protected]
A flag indicating whether or not unsatisfiable cores should be further minimized.
If this flag is false, then we take the core as returned by the solver. If it is true, then we try to further minimize the core by trying to drop one remaining assumption after the other in a loop. This is then guaranteed to result in an unsatisfiable core which is a local minimum subset of the assumptions.
Definition at line 417 of file DepQBFApiInc.h.
Referenced by extractCore().
bool DepQBFApiInc::use_bloqqer_ [protected]
A flag indicating whether or not the pre-processor bloqqer should be used.
Definition at line 407 of file DepQBFApiInc.h.
Referenced by isSat(), and isSatModel().
The documentation for this class was generated from the following files:
src/DepQBFApiInc.h
src/DepQBFApiInc.cpp