AIG2CNF Class Reference
Transforms an AIGER specification into CNF.
#include <AIG2CNF.h>
Public Types
typedef map< int, set< VarInfo >
*
 >::const_iterator DepConstIter
A type for a const-iterator over the dependencies of temporary variables.
Public Member Functions
void initFromAig (aiger *aig)
Initializes this class from an aiger structure.
void clear ()
Clears all the CNFs constructed by initFromAig() .
const CNF & getTrans () const
Returns the transition relation in CNF.
const CNF & getTransEqT () const
Returns a CNF saying that the transition holds iff a certain literal is true.
int getT () const
Returns the literal assigned by getTransEqT() .
const CNF & getSafeStates () const
Returns a CNF representing the set of safe states.
const CNF & getUnsafeStates () const
Returns a CNF representing the set of unsafe states.
const CNF & getNextSafeStates () const
Returns a CNF saying that the next state is safe.
const CNF & getNextUnsafeStates () const
Returns a CNF saying that the next state is unsafe.
const CNF & getInitial () const
Returns a CNF representing the initial state.
const map< int, set< VarInfo > > & getTmpDeps () const
Returns dependencies of temporary variables in the transition relation.
const map< int, set< VarInfo > > & getTmpDepsTrans ()
Returns transitive dependencies of temporary variables in the transition relation.
Static Public Member Functions
static AIG2CNF & instance ()
Returns the one and only instance of this class.
Protected Attributes
CNF trans_
The transition relation in CNF.
CNF trans_eq_t_
A CNF saying that the transition holds iff t_ is true.
int t_
The literal assigned by trans_eq_t_ .
CNF safe_
A CNF representing the set of safe states.
CNF unsafe_
A CNF representing the set of unsafe states.
CNF next_safe_
A CNF saying that the next state is safe.
CNF next_unsafe_
A CNF saying that the next state is unsafe.
CNF initial_
A CNF representing the initial state.
map< int, set< VarInfo > > trans_tmp_deps_
The variables on which a temporary variable of the transition relation depends.
map< int, set< VarInfo > > trans_tmp_deps_trans_
Like trans_tmp_deps_, but stores (transitive) dependencies non non-temporary vars.
Private Member Functions
AIG2CNF ()
Constructor.
virtual ~AIG2CNF ()
Destructor.
AIG2CNF (const AIG2CNF &other)
Copy constructor.
AIG2CNF & operator= (const AIG2CNF &other)
Assignment operator.
Static Private Attributes
static AIG2CNF * instance_ = NULL
The one and only instance of this class.
Detailed Description
Transforms an AIGER specification into CNF.
This class creates CNF formulas representing the transition relation as well as the initial state, and the set of safe states from an AIGER specification. It does not parse the AIGER file itself, but expects that this has already been done with the AIGER utility tools (see http://fmv.jku.at/aiger/). This class then analyzes the resulting 'aiger' structure to build the corresponding CNFs. It is compatible with AIGER version 1.9.4. This class can parse AIGER structures that are compatible with input format for the synthesis competition (see http://www.syntcomp.org/). That is, the AIGER structure is expected to have exactly one output: This output signals that an error occurred. The synthesis problem addressed by this tool is to prevent the error-output form over becoming TRUE. Controllable inputs are identified via their name. If an input signal has a name that starts with 'controllable_', then it is considered as controllable.
The resulting transition relation is a CNF T(x,i,c,x') that talks about the current state bits x, the uncontrollable inputs i, the controllable inputs c, and the next state copies x' of the state bits x. The transition relation is
complete, i.e., forall x,i,c: exists x': T(x,i,c,x').
deterministic, i.e., forall x,i,c,x1',x2': (T(x,i,c,x1') AND T(x,i,c,x2')) implies (x1' = x2')
This means: for every state and input, the next state is uniquely defined.
There is only one initial state. It is the state where all state-bits are set to FALSE. (This may change with newer AIGER versions in the future).
The set of safe states is identified by one special state bit. This special state bit does not exist in the original AIGER file but is introduced by this class. This transformation (encoded in the transition relation) is supposed to make the life of the synthesis algorithms easier.
This class is implemented as a Singleton. That is, you cannot instantiate objects of this class with the constructor. Use the method instance() to obtain the one and only instance of this class.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.1.0
Definition at line 80 of file AIG2CNF.h.
Member Typedef Documentation
map< int, set< VarInfo > >::const_iterator AIG2CNF::DepConstIter
A type for a const-iterator over the dependencies of temporary variables.
Definition at line 279 of file AIG2CNF.h.
Constructor & Destructor Documentation
AIG2CNF::AIG2CNF () [private]
Constructor.
The constructor is disabled (set private) as this method is implemented as a Singleton. Use the method instance() to obtain the one and only instance of this class.
Definition at line 303 of file AIG2CNF.cpp.
Referenced by instance().
AIG2CNF::~AIG2CNF () [private], [virtual]
Destructor.
The destructor is disabled (set private) as this method is implemented as a Singleton. One cannot instantiate objects of this class, so there is no need to be able to delete them.
Definition at line 309 of file AIG2CNF.cpp.
AIG2CNF::AIG2CNF (const AIG2CNF & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void AIG2CNF::clear ()
Clears all the CNFs constructed by initFromAig() .
Definition at line 197 of file AIG2CNF.cpp.
References CNF::clear(), initial_, next_safe_, next_unsafe_, safe_, t_, trans_, trans_eq_t_, and unsafe_.
Referenced by initFromAig().
const CNF & AIG2CNF::getInitial () const
Returns a CNF representing the initial state.
There is exactly one initial state (this is a restriction imposed by the AIGER format which serves as input for our tool). Furthermore, the initial state is always characterized by having all state bits set to FALSE. However, this may change with future AIGER versions.
Returns
A CNF representing the initial state.
Definition at line 252 of file AIG2CNF.cpp.
References initial_.
const CNF & AIG2CNF::getNextSafeStates () const
Returns a CNF saying that the next state is safe.
The set of safe next states is actually characterized by one single state bit, namely the next states where the variable VarManager::instance().getNextErrorStateVar() is FALSE. The returned CNF asserts exactly this.
Returns
A CNF saying that the next state is safe.
Definition at line 240 of file AIG2CNF.cpp.
References next_safe_.
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), ClauseExplorerSAT::exploreClauses(), and CounterGenSAT::generalizeCounterexamples().
const CNF & AIG2CNF::getNextUnsafeStates () const
Returns a CNF saying that the next state is unsafe.
The set of unsafe next states is actually characterized by one single state bit, namely the next states where the variable VarManager::instance().getNextErrorStateVar() is TRUE. The returned CNF asserts exactly this.
Returns
A CNF saying that the next state is unsafe.
Definition at line 246 of file AIG2CNF.cpp.
References next_unsafe_.
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), and ClauseExplorerSAT::exploreClauses().
const CNF & AIG2CNF::getSafeStates () const
Returns a CNF representing the set of safe states.
The set of safe states is actually characterized by one single state bit, namely the states where the variable VarManager::instance().getPresErrorStateVar() is FALSE. The returned CNF asserts exactly this.
Returns
A CNF representing the set of safe states.
Definition at line 228 of file AIG2CNF.cpp.
References safe_.
Referenced by LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), LearnSynthQBF::computeWinningRegionOneSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), ClauseExplorerSAT::exploreClauses(), and CounterGenSAT::generalizeCounterexamples().
int AIG2CNF::getT () const
Returns the literal assigned by getTransEqT() .
The method getTransEqT() returns a CNF that asserts T(x,i,c,x') <-> l, where l is the literal returned by this method. This can be useful if you need the negated transition relation, if you want to use the the transition relation in some complicated formula, or if your formula should contain the transition relation several times (e.g. A & T | B & !T) .
Returns
The literal assigned by getTransEqT()
Definition at line 222 of file AIG2CNF.cpp.
References t_.
Referenced by TemplateSynth::findWinRegCNFTempl().
const map< int, set< VarInfo > > & AIG2CNF::getTmpDeps () const
Returns dependencies of temporary variables in the transition relation.
For each temporary variable that has been introduced when encoding the transition relation into CNF, the returned map stores on which other variables (state variables, inputs, or other temporary variables) a certain temporary CNF-variable depends on. This information can be useful in optimizations: For instance, if a certain temporary variable only depends on state-variables and uncontrollable inputs, the control signals can be allowed to depend on such a temporary variable during circuit extraction.
Returns
The dependencies of temporary variables in the transition relation as a map from temporary CNF variables to the set of other variables on which the respective variables depend.
Definition at line 258 of file AIG2CNF.cpp.
References trans_tmp_deps_.
Referenced by LearnSynthSAT::computeWinningRegionPlainDep2(), and LearningImplExtractor::insertMissingAndFromTrans().
const map< int, set< VarInfo > > & AIG2CNF::getTmpDepsTrans ()
Returns transitive dependencies of temporary variables in the transition relation.
For each temporary variable that has been introduced when encoding the transition relation into CNF, the returned map stores on which other non-temporary variables (state variables, or controllable or uncontrollable inputs) a certain temporary CNF-variable depends on. That is, in contrast to getTmpDeps, dependencies on other temporary variables are represented by taking their dependencies on state variables and (uncontrollable and controllable) inputs. This information can be useful in optimizations: For instance, if a certain temporary variable only depends on state-variables and uncontrollable inputs, the control signals can be allowed to depend on such a temporary variable during circuit extraction.
Returns
The transitive dependencies of temporary variables in the transition relation as a which the respective variables depend.
Definition at line 265 of file AIG2CNF.cpp.
References VarInfo::TMP, trans_tmp_deps_, and trans_tmp_deps_trans_.
Referenced by LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearningImplExtractor::LearningImplExtractor(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), and LearningImplExtractor::runLearningJiangSATTmpCtrlInc2().
const CNF & AIG2CNF::getTrans () const
Returns the transition relation in CNF.
The returned transition relation is a CNF T(x,i,c,x') that talks about the current state bits x, the uncontrollable inputs i, the controllable inputs c, and the next state copies x' of the state bits x. The transition relation is
complete, i.e., forall x,i,c: exists x': T(x,i,c,x').
deterministic, i.e., forall x,i,c,x1',x2': (T(x,i,c,x1') AND T(x,i,c,x2')) implies (x1' = x2')
This means: for every state and input, the next state is uniquely defined.
Returns
The transition relation in CNF.
Definition at line 210 of file AIG2CNF.cpp.
References trans_.
Referenced by ParallelLearner::computePreviousTrans(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), ClauseExplorerSAT::exploreClauses(), CounterGenSAT::generalizeCounterexamples(), LearnSynthQBFInd::LearnSynthQBFInd(), LearnSynthSAT::LearnSynthSAT(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), and LearningImplExtractor::runLearningJiangSATTmpCtrlInc2().
const CNF & AIG2CNF::getTransEqT () const
Returns a CNF saying that the transition holds iff a certain literal is true.
The returned CNF asserts T(x,i,c,x') <-> l, where l is the literal returned by getT() . This can be useful if you need the negated transition relation, if you want to use the the transition relation in some complicated formula, or if your formula should contain the transition relation several times (e.g. A & T | B & !T) .
Returns
A CNF saying that the transition holds iff a certain literal is true.
Definition at line 216 of file AIG2CNF.cpp.
References trans_eq_t_.
Referenced by TemplateSynth::findWinRegCNFTempl().
const CNF & AIG2CNF::getUnsafeStates () const
Returns a CNF representing the set of unsafe states.
The set of unsafe states is actually characterized by one single state bit, namely the states where the variable VarManager::instance().getPresErrorStateVar() is TRUE. The returned CNF asserts exactly this.
Returns
A CNF representing the set of unsafe states.
Definition at line 234 of file AIG2CNF.cpp.
References unsafe_.
void AIG2CNF::initFromAig (aiger * aig)
Initializes this class from an aiger structure.
This method actually builds the CNFs formulas representing the transition relation as well as the initial state, and the set of safe states from an AIGER specification. This is where all the magic happens. This method is called once in beginning before a back-end is started. The back-ends can then access the constructed CNFs. This method also initializes the VarManager with the correct sets of variables.
This method can parse AIGER structures that are compatible with input format for the synthesis competition (see http://www.syntcomp.org/). That is, the AIGER structure is expected to have exactly one output: This output signals that an error occurred. The synthesis problem addressed by this tool is to prevent the error-output form over becoming TRUE. Controllable inputs are identified via their name. If an input signal has a name that starts with 'controllable_', then it is considered as controllable.
The resulting transition relation is a CNF T(x,i,c,x') that talks about the current state bits x, the uncontrollable inputs i, the controllable inputs c, and the next state copies x' of the state bits x. The transition relation is
complete, i.e., forall x,i,c: exists x': T(x,i,c,x').
deterministic, i.e., forall x,i,c,x1',x2': (T(x,i,c,x1') AND T(x,i,c,x2')) implies (x1' = x2')
This means: for every state and input, the next state is uniquely defined.
There is only one initial state. It is the state where all state-bits are set to FALSE. (This may change with newer AIGER versions in the future).
The set of safe states is identified by one special state bit. This special state bit does not exist in the original AIGER file but is introduced by this class. This transformation (encoded in the transition relation) is supposed to make the life of the synthesis algorithms easier.
Precondition
aig != NULL
aig->num_outputs == 1
Parameters
aig The aiger structure as parsed by the AIGER utilities. The current implementation assumes version 1.9.4 of the AIGER utilities.
Definition at line 50 of file AIG2CNF.cpp.
References CNF::add1LitClause(), CNF::add2LitClause(), CNF::add3LitClause(), CNF::addClause(), VarManager::aigLitToCnfLit(), clear(), VarManager::createFreshTmpVar(), VarManager::getInfo(), VarManager::getNextErrorStateVar(), VarManager::getPresErrorStateVar(), VarManager::getVarsOfType(), VarManager::initFromAig(), initial_, instance(), next_safe_, VarInfo::NEXT_STATE, next_unsafe_, VarInfo::PRES_STATE, safe_, t_, trans_, trans_eq_t_, trans_tmp_deps_, and unsafe_.
Referenced by main().
AIG2CNF & AIG2CNF::instance () [static]
Returns the one and only instance of this class.
This class is implemented as a Singleton. That is, you cannot instantiate objects of this class with the constructor. Use this method to obtain the one and only instance of this class.
Returns
The one and only instance of this class.
Definition at line 41 of file AIG2CNF.cpp.
References AIG2CNF(), instance_, and MASSERT.
Referenced by CounterGenSAT::compressBored(), LearnSynthQBF::computeCounterexampleSAT(), ParallelLearner::computePreviousTrans(), LearnSynthQBFInc::computeWinningRegionAll(), LearnSynthQBF::computeWinningRegionAll(), LearnSynthQBFInd::computeWinningRegionAll(), LearnSynthQBFInc::computeWinningRegionAllPool(), LearnSynthQBFInc::computeWinningRegionAllPush(), LearnSynthQBFInc::computeWinningRegionOne(), LearnSynthQBF::computeWinningRegionOne(), LearnSynthQBFInd::computeWinningRegionOne(), LearnSynthQBFInc::computeWinningRegionOnePool(), LearnSynthQBFInc::computeWinningRegionOnePush(), LearnSynthQBF::computeWinningRegionOneSAT(), LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGRC(), IFM13Synth::debugCheckInvariants(), LearnSynthSAT::debugCheckWinReg(), Utils::debugCheckWinReg(), LearnSynthQBFInd::debugCheckWinRegReach(), ClauseExplorerSAT::exploreClauses(), TemplateSynth::findWinRegCNFTempl(), CounterGenSAT::generalizeCounterexamples(), IFM13Synth::getGenBlockTransSolver(), IFM13Explorer::getGenBlockTransSolver(), IFM13Synth::getGotoNextLowerSolver(), IFM13Explorer::getGotoNextLowerSolver(), IFM13Explorer::IFM13Explorer(), IFM13Synth::IFM13Synth(), initFromAig(), LearningImplExtractor::insertMissingAndFromTrans(), LearningImplExtractor::LearningImplExtractor(), LearnSynthQBF::LearnSynthQBF(), LearnSynthQBFInd::LearnSynthQBFInd(), LearnSynthSAT::LearnSynthSAT(), main(), ClauseMinimizerQBF::minimizeClauses(), LearnSynthQBFInc::recomputeCheckCNF(), LearnSynthQBF::recomputeCheckCNF(), LearnSynthQBFInd::recomputeCheckCNF(), LearnSynthQBFInc::recomputeGenCNF(), LearnSynthQBF::recomputeGenCNF(), LearnSynthQBFInd::recomputeGenCNF(), QBFCertImplExtractor::run(), ParallelLearner::run(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), LearningImplExtractor::runLearningQBF(), LearningImplExtractor::runLearningQBFInc(), and ParallelLearner::triggerExplorerRestart().
AIG2CNF& AIG2CNF::operator= (const AIG2CNF & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
Member Data Documentation
CNF AIG2CNF::initial_ [protected]
A CNF representing the initial state.
There is exactly one initial state (this is a restriction imposed by the AIGER format which serves as input for our tool). Furthermore, the initial state is always characterized by having all state bits set to FALSE. However, this may change with future AIGER versions.
Definition at line 360 of file AIG2CNF.h.
Referenced by clear(), getInitial(), and initFromAig().
AIG2CNF * AIG2CNF::instance_ = NULL [static], [private]
The one and only instance of this class.
Definition at line 426 of file AIG2CNF.h.
Referenced by instance().
CNF AIG2CNF::next_safe_ [protected]
A CNF saying that the next state is safe.
The set of safe next states is actually characterized by one single state bit, namely the next states where the variable VarManager::instance().getNextErrorStateVar() is FALSE. This CNF asserts exactly this.
Definition at line 341 of file AIG2CNF.h.
Referenced by clear(), getNextSafeStates(), and initFromAig().
CNF AIG2CNF::next_unsafe_ [protected]
A CNF saying that the next state is unsafe.
The set of unsafe next states is actually characterized by one single state bit, namely the next states where the variable VarManager::instance().getNextErrorStateVar() is TRUE. This CNF asserts exactly this.
Definition at line 350 of file AIG2CNF.h.
Referenced by clear(), getNextUnsafeStates(), and initFromAig().
CNF AIG2CNF::safe_ [protected]
A CNF representing the set of safe states.
The set of safe states is actually characterized by one single state bit, namely the states where the variable VarManager::instance().getPresErrorStateVar() is FALSE. This CNF asserts exactly this.
Definition at line 323 of file AIG2CNF.h.
Referenced by clear(), getSafeStates(), and initFromAig().
int AIG2CNF::t_ [protected]
The literal assigned by trans_eq_t_ .
The CNF trans_eq_t_ asserts T(x,i,c,x') <-> t_ .
Definition at line 314 of file AIG2CNF.h.
Referenced by clear(), getT(), and initFromAig().
CNF AIG2CNF::trans_ [protected]
The transition relation in CNF.
The transition relation is a CNF T(x,i,c,x') that talks about the current state bits x, the uncontrollable inputs i, the controllable inputs c, and the next state copies x' of the state bits x. The transition relation is
complete, i.e., forall x,i,c: exists x': T(x,i,c,x').
deterministic, i.e., forall x,i,c,x1',x2': (T(x,i,c,x1') AND T(x,i,c,x2')) implies (x1' = x2')
This means: for every state and input, the next state is uniquely defined.
Definition at line 296 of file AIG2CNF.h.
Referenced by clear(), getTrans(), and initFromAig().
CNF AIG2CNF::trans_eq_t_ [protected]
A CNF saying that the transition holds iff t_ is true.
This CNF asserts T(x,i,c,x') <-> t_ . This can be useful if you need the negated transition relation, if you want to use the the transition relation in some complicated formula, or if your formula should contain the transition relation several times (e.g. A & T | B & !T) .
Definition at line 306 of file AIG2CNF.h.
Referenced by clear(), getTransEqT(), and initFromAig().
map<int, set<VarInfo> > AIG2CNF::trans_tmp_deps_ [protected]
The variables on which a temporary variable of the transition relation depends.
For each temporary variable that has been introduced when encoding the transition relation into CNF, this map stores on which other variables (state variables, inputs, or other temporary variables) a certain temporary CNF-variable depends. This information can be useful in optimizations: For instance, if a certain temporary variable only depends on state-variables and uncontrollable inputs, the the control signals can be allowed to depend on such a temporary variable during circuit extraction.
Definition at line 372 of file AIG2CNF.h.
Referenced by getTmpDeps(), getTmpDepsTrans(), and initFromAig().
map<int, set<VarInfo> > AIG2CNF::trans_tmp_deps_trans_ [protected]
Like trans_tmp_deps_, but stores (transitive) dependencies non non-temporary vars.
This map stores essentially the same information as trans_tmp_deps_. However, it only contains (transitive) dependencies on state variables and (uncontrollable and controllable) inputs. Dependencies on other temporary variables are represented by taking their dependencies on state variables and (uncontrollable and controllable) inputs.
Definition at line 382 of file AIG2CNF.h.
Referenced by getTmpDepsTrans().
CNF AIG2CNF::unsafe_ [protected]
A CNF representing the set of unsafe states.
The set of unsafe states is actually characterized by one single state bit, namely the states where the variable VarManager::instance().getPresErrorStateVar() is TRUE. This CNF asserts exactly this.
Definition at line 332 of file AIG2CNF.h.
Referenced by clear(), getUnsafeStates(), and initFromAig().
The documentation for this class was generated from the following files:
src/AIG2CNF.h
src/AIG2CNF.cpp