IFM13Explorer Class Reference
Implements the method of IFM13Synth in a parallelized way.
#include <ParallelLearner.h>
Public Member Functions
IFM13Explorer (ParallelLearner &coordinator)
Constructor.
virtual ~IFM13Explorer ()
Destructor.
void exploreClauses ()
The work-horse of this class.
void notifyNewWinRegClause (const vector< int > &clause, int src)
Notifies this worker about a new winning region clause.
Protected Member Functions
void considerNewInfoFromOthers ()
Considers new winning region clauses that have been found by other threads.
size_t propagateBlockedStates (size_t max_level)
Propagates clauses forward and searches for equivalent clause sets.
bool recBlockCube (const vector< int > &state_cube, size_t level)
Analyzes the rank of the passed state.
void addBlockedTransition (const vector< int > &state_in_cube, size_t level)
Marks a state-input-pair as blocked.
void addBlockedState (const vector< int > &state_cube, size_t level)
Removes a state(-cube) from the frame R[level].
bool isBlocked (const vector< int > &state_cube, size_t level)
Checks if a state is contained in a certain frame.
void addLose (const vector< int > &state_cube)
Removes a state(-cube) from the current over-approximation of the winning region.
bool isLose (const vector< int > &state_cube)
Checks if a state satisfies the current over-approximation of the winning region.
void genAndBlockTrans (const vector< int > &state_in_cube, const vector< int > &ctrl_cube, size_t level)
Generalizes and excludes a blocked transition.
CNF & getR (size_t index)
Returns the frame R[index] in CNF.
CNF & getU (size_t index)
Returns the blocked transitions U[index] in CNF.
SatSolver * getGotoNextLowerSolver (size_t index)
Returns a solver with CNF: U[index] & T & R[index-1]'.
SatSolver * getGenBlockTransSolver (size_t index)
Returns a solver with CNF: T & R[index-1]'.
IFMProofObligation popMin (list< IFMProofObligation > &queue)
Takes a list of proof obligations and removes the element with lowest rank.
Protected Attributes
ParallelLearner & coordinator_
A reference to the coordinator.
CNF new_win_reg_clauses_
All new winning region clauses that have not been considered yet.
mutex new_win_reg_clauses_lock_
A lock that protects the new_win_reg_clauses_ from race-conditions.
vector< CNF > r_
The frames R[] of the algorithm. Each frame represents a set of states in CNF.
vector< CNF > u_
The blocked transitions U[] of the algorithm.
CNF win_
The current over-approximation of the winning region W (for the protagonist).
vector< SatSolver * > goto_next_lower_solvers_
The solvers storing the CNF: U[k] & T & R[k-1]'.
vector< SatSolver * > gen_block_trans_solvers_
The solvers storing the CNF: T & R[k-1]'.
SatSolver * goto_win_solver_
A solver that stores the CNF: T & W'.
vector< int > sin_
The vector of present- and next-state variables, and uncontrollable inputs.
vector< int > sicn_
The vector of present- and next-state variables, and all inputs.
vector< int > initial_state_cube_
The cube encoding the initial state.
int error_var_
The literal saying that we are in an unsafe state.
Private Member Functions
IFM13Explorer (const IFM13Explorer &other)
Copy constructor.
IFM13Explorer & operator= (const IFM13Explorer &other)
Assignment operator.
Detailed Description
Implements the method of IFM13Synth in a parallelized way.
This class basically implements the same method as IFM13Synth. It only has a few additional methods to communicate with other threads. Whenever it finds a new clause of the winning region (of the protagonist not the antagonist), it communicates this clause to all other worker-threads (via the ParallelLearner, which acts as a coordinator). On the other hand, it also considers refinements of the winning region done by other threads.
See Also
IFM13Synth
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.0.0
Definition at line 1266 of file ParallelLearner.h.
Constructor & Destructor Documentation
IFM13Explorer::IFM13Explorer (ParallelLearner & coordinator)
Constructor.
Parameters
coordinator A reference to the coordinator. All communication to other worker-threads is done via the coordinator.
Definition at line 1354 of file ParallelLearner.cpp.
References CNF::addCNF(), VarInfo::CTRL, gen_block_trans_solvers_, Options::getSATSolver(), VarManager::getVarsOfType(), goto_next_lower_solvers_, goto_win_solver_, SatSolver::incAddCNF(), initial_state_cube_, VarInfo::INPUT, VarManager::instance(), Options::instance(), AIG2CNF::instance(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, r_, sicn_, sin_, SatSolver::startIncrementalSession(), u_, and win_.
IFM13Explorer::~IFM13Explorer () [virtual]
Destructor.
Definition at line 1406 of file ParallelLearner.cpp.
References gen_block_trans_solvers_, goto_next_lower_solvers_, and goto_win_solver_.
IFM13Explorer::IFM13Explorer (const IFM13Explorer & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void IFM13Explorer::addBlockedState (const vector< int > & state_cube, size_t level) [protected]
Removes a state(-cube) from the frame R[level].
This method updates R[level] := R[level] & !state_cube. state_cube is a potentially incomplete state-cube. We also update the R-sets of all smaller levels in the same way for syntactic containment reasons (as described in the paper).
Parameters
state_cube The state-cube that should be removed from R[level]. The cube is potentially incomplete, i.e., can represent a larger set of states.
level The level in which the state should be blocked (i.e., removed form the corresponding frame R[level]).
Definition at line 1668 of file ParallelLearner.cpp.
References CNF::addClause(), Utils::contains(), error_var_, getGenBlockTransSolver(), getGotoNextLowerSolver(), getR(), SatSolver::incAddClause(), SatSolver::incIsSat(), r_, and Utils::swapPresentToNext().
Referenced by recBlockCube().
void IFM13Explorer::addBlockedTransition (const vector< int > & state_in_cube, size_t level) [protected]
Marks a state-input-pair as blocked.
The meaning is: we want to store the fact that a certain state-input pair is not helpful for the antagonist (the party controlling the inputs i) in trying to move from R[level] to R[level-1]. Hence, we update U[level] := U[level] & !state_in_cube. We also update the U-sets of all smaller levels in the same way for syntactic containment reasons (as described in the paper).
Parameters
state_in_cube The state-input pair as a cube over present state variables and uncontrollable inputs. The cube is potentially incomplete, i.e., can represent a larger set of state-input pairs.
level The level in which the transition should be blocked (i.e., the state-input pair should by marked as useless for the antagonist).
Definition at line 1653 of file ParallelLearner.cpp.
References CNF::addClauseAndSimplify(), getGotoNextLowerSolver(), getU(), and SatSolver::incAddClause().
Referenced by genAndBlockTrans().
void IFM13Explorer::addLose (const vector< int > & state_cube) [protected]
Removes a state(-cube) from the current over-approximation of the winning region.
This method updates W := W & !state_cube. state_cube is a potentially incomplete state-cube.
Parameters
state_cube The state-cube that should be removed from the current over-approximation of the winning region. The cube is potentially incomplete, i.e.,
Definition at line 1724 of file ParallelLearner.cpp.
References coordinator_, IFM, and ParallelLearner::notifyNewWinRegClause().
Referenced by recBlockCube().
void IFM13Explorer::considerNewInfoFromOthers () [protected]
Considers new winning region clauses that have been found by other threads.
Definition at line 1461 of file ParallelLearner.cpp.
References CNF::addCNF(), CNF::clear(), goto_win_solver_, SatSolver::incAddCNF(), new_win_reg_clauses_, new_win_reg_clauses_lock_, CNF::swapPresentToNext(), and win_.
Referenced by isLose(), and recBlockCube().
void IFM13Explorer::exploreClauses ()
The work-horse of this class.
It basically implements the same method as IFM13Synth. However, it also communicates with other threads: Whenever it finds a new clause of the winning region (of the protagonist not the antagonist), it communicates this clause to all other worker-threads (via the ParallelLearner, which acts as a coordinator). On the other hand, it also considers refinements of the winning region done by other threads. If it finds out that the specification is realizable or unrealizable, it sets the flag ParallelLearner::result_ accordingly. It also polls this flag regularly. If it has been set by some other thread, it quits.
Definition at line 1421 of file ParallelLearner.cpp.
References coordinator_, initial_state_cube_, IS_LOSE, L_DBG, L_LOG, propagateBlockedStates(), recBlockCube(), ParallelLearner::result_, UNKNOWN, and UNREALIZABLE.
Referenced by ParallelLearner::run().
void IFM13Explorer::genAndBlockTrans (const vector< int > & state_in_cube, const vector< int > & ctrl_cube, size_t level) [protected]
Generalizes and excludes a blocked transition.
Parameters
state_in_cube The state-input cube (the transition) that should be generalized and and blocked.
ctrl_cube The control signals that can be chosen by the protagonist in order to avoid ending up in R[level-1].
level The frame in which the transition should be blocked.
Returns
False if state_cube satisfies W, true otherwise.
Definition at line 1741 of file ParallelLearner.cpp.
References addBlockedTransition(), getGenBlockTransSolver(), SatSolver::incIsSatModelOrCore(), and MASSERT.
Referenced by recBlockCube().
SatSolver * IFM13Explorer::getGenBlockTransSolver (size_t index) [protected]
Returns a solver with CNF: T & R[index-1]'.
This solver is used to generalize blocked transitions. If the solver for this index does not yet exists, it is created.
Parameters
index The index of the requested solver.
Returns
A solver with CNF: T & R[index-1]'. getGenBlockTransSolver(0) returns NULL.
Definition at line 1782 of file ParallelLearner.cpp.
References gen_block_trans_solvers_, Options::instance(), AIG2CNF::instance(), and sicn_.
Referenced by addBlockedState(), genAndBlockTrans(), and propagateBlockedStates().
SatSolver * IFM13Explorer::getGotoNextLowerSolver (size_t index) [protected]
Returns a solver with CNF: U[index] & T & R[index-1]'.
This solver is used to search for moves the antagonist can make in order to reach R[index-1]. If the solver for this index does not yet exists, it is created.
Parameters
index The index of the requested solver.
Returns
A solver with CNF: U[index] & T & R[index-1]'. getGotoNextLowerSolver(0) returns NULL.
Definition at line 1770 of file ParallelLearner.cpp.
References goto_next_lower_solvers_, Options::instance(), AIG2CNF::instance(), and sicn_.
Referenced by addBlockedState(), addBlockedTransition(), propagateBlockedStates(), and recBlockCube().
CNF & IFM13Explorer::getR (size_t index) [protected]
Returns the frame R[index] in CNF.
If the frame with this index does not yet exists, it is created.
Parameters
index The index of the requested frame.
Returns
The frame R[index] in CNF.
Definition at line 1754 of file ParallelLearner.cpp.
References r_.
Referenced by addBlockedState(), isBlocked(), and propagateBlockedStates().
CNF & IFM13Explorer::getU (size_t index) [protected]
Returns the blocked transitions U[index] in CNF.
If the set of blocked transitions with this index does not yet exists, it is created. This function is actually only needed for debugging purposes.
Parameters
index The index of the requested set of blocked transitions.
Returns
The set U[index] of blocked transitions in CNF.
Definition at line 1762 of file ParallelLearner.cpp.
References u_.
Referenced by addBlockedTransition().
bool IFM13Explorer::isBlocked (const vector< int > & state_cube, size_t level) [protected]
Checks if a state is contained in a certain frame.
The passed state cube is complete, i.e., contains all state variables. Hence, containment can be (and is) checked syntactically. We simply check if state_cube satisfies all clauses of R[level].
Parameters
state_cube A full cube over the present state variables.
level The index i of a certain frame R[i].
Returns
False if state_cube satisfies R[level], true otherwise.
Definition at line 1718 of file ParallelLearner.cpp.
References getR(), and CNF::isSatBy().
Referenced by recBlockCube().
bool IFM13Explorer::isLose (const vector< int > & state_cube) [protected]
Checks if a state satisfies the current over-approximation of the winning region.
The passed state cube is complete, i.e., contains all state variables. Hence, containment can be (and is) checked syntactically. We simply check if state_cube satisfies all clauses of W (stored in win_).
Parameters
state_cube A full cube over the present state variables.
Returns
False if state_cube satisfies W, true otherwise.
Definition at line 1734 of file ParallelLearner.cpp.
References considerNewInfoFromOthers(), CNF::isSatBy(), and win_.
Referenced by recBlockCube().
void IFM13Explorer::notifyNewWinRegClause (const vector< int > & clause, int src)
Notifies this worker about a new winning region clause.
Parameters
clause The new clause that has been discovered.
src An integer number defining which kind of worker-thread discovered the clause. At the moment, this information is ignored.
Definition at line 1453 of file ParallelLearner.cpp.
References CNF::addClause(), new_win_reg_clauses_, and new_win_reg_clauses_lock_.
IFM13Explorer& IFM13Explorer::operator= (const IFM13Explorer & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
IFMProofObligation IFM13Explorer::popMin (list< IFMProofObligation > & queue) [protected]
Takes a list of proof obligations and removes the element with lowest rank.
Parameters
queue A list of proof obligations.
Returns
The element that has been removed from the list. It is always the element (among the elements) with minimal rank.
Definition at line 1794 of file ParallelLearner.cpp.
References MASSERT.
Referenced by recBlockCube().
size_t IFM13Explorer::propagateBlockedStates (size_t max_level) [protected]
Propagates clauses forward and searches for equivalent clause sets.
Similar to IC3, this method propagates clauses of frames forward. It also checks if two adjacent clauses sets become syntactically equal.
Parameters
max_level The maximum frame level until which propagation should be performed.
Returns
The number N returned by this method has the following meaning: N=0 means that no equal clause sets have been found. N > 0 means that R[N] = R[N-1].
Definition at line 1472 of file ParallelLearner.cpp.
References coordinator_, CNF::getClauses(), getGenBlockTransSolver(), getGotoNextLowerSolver(), getR(), SatSolver::incAddClause(), SatSolver::incIsSat(), CNF::removeDuplicates(), ParallelLearner::result_, Utils::swapPresentToNext(), CNF::swapWith(), and UNKNOWN.
Referenced by exploreClauses().
bool IFM13Explorer::recBlockCube (const vector< int > & state_cube, size_t level) [protected]
Analyzes the rank of the passed state.
There are two possible conclusions: (a) the rank of the state is > level, (b) the rank of the state is <= level. In order to analyze a certain state, this method may analyze some of its successor states first (using a queue of proof obligations internally). This method is always called for the initial state only.
Parameters
state_cube A full cube over the state variables, describing the state that should be analyzed.
level The level for the analysis (this method checks if the rank of the state is > level or <= level).
Returns
IS_GREATER (an alias for true) if the rank of the state is > level. IS_LOSE (an alias for false) otherwise.
Definition at line 1529 of file ParallelLearner.cpp.
References addBlockedState(), addLose(), considerNewInfoFromOthers(), Utils::containsInit(), coordinator_, VarInfo::CTRL, Utils::extract(), Utils::extractNextAsPresent(), Utils::extractPresIn(), genAndBlockTrans(), getGotoNextLowerSolver(), IFMProofObligation::getLevel(), IFMProofObligation::getPreCtrlCube(), IFMProofObligation::getPreStateInCube(), IFMProofObligation::getState(), goto_win_solver_, IFMProofObligation::hasPre(), SatSolver::incIsSatModelOrCore(), VarInfo::INPUT, IS_GREATER, IS_LOSE, isBlocked(), isLose(), popMin(), VarInfo::PRES_STATE, ParallelLearner::result_, sicn_, sin_, and UNKNOWN.
Referenced by exploreClauses().
Member Data Documentation
ParallelLearner& IFM13Explorer::coordinator_ [protected]
A reference to the coordinator.
All communication to other worker-threads is done via the coordinator.
Definition at line 1482 of file ParallelLearner.h.
Referenced by addLose(), exploreClauses(), propagateBlockedStates(), and recBlockCube().
int IFM13Explorer::error_var_ [protected]
The literal saying that we are in an unsafe state.
We cache it so that we do not have to get it from the VarManager every time. We may of lock the VarManager otherwise.
Definition at line 1566 of file ParallelLearner.h.
Referenced by addBlockedState().
vector<SatSolver*> IFM13Explorer::gen_block_trans_solvers_ [protected]
The solvers storing the CNF: T & R[k-1]'.
You should use getGenBlockTransSolver() to access these solvers. The reason is that this method initializes the solvers if they do not yet exist. gen_block_trans_solvers_[0] is always NULL.
Definition at line 1538 of file ParallelLearner.h.
Referenced by getGenBlockTransSolver(), IFM13Explorer(), and ~IFM13Explorer().
vector<SatSolver*> IFM13Explorer::goto_next_lower_solvers_ [protected]
The solvers storing the CNF: U[k] & T & R[k-1]'.
These solvers are used to search for moves the antagonist can make in order to reach R[k-1]. You should use getGotoNextLowerSolver() to access these solvers. The reason is that this method initializes the solvers if they do not yet exist. goto_next_lower_solvers_[0] is always NULL.
Definition at line 1529 of file ParallelLearner.h.
Referenced by getGotoNextLowerSolver(), IFM13Explorer(), and ~IFM13Explorer().
SatSolver* IFM13Explorer::goto_win_solver_ [protected]
A solver that stores the CNF: T & W'.
Definition at line 1543 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), IFM13Explorer(), recBlockCube(), and ~IFM13Explorer().
vector<int> IFM13Explorer::initial_state_cube_ [protected]
The cube encoding the initial state.
Definition at line 1558 of file ParallelLearner.h.
Referenced by exploreClauses(), and IFM13Explorer().
CNF IFM13Explorer::new_win_reg_clauses_ [protected]
All new winning region clauses that have not been considered yet.
Definition at line 1487 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), and notifyNewWinRegClause().
mutex IFM13Explorer::new_win_reg_clauses_lock_ [protected]
A lock that protects the new_win_reg_clauses_ from race-conditions.
Many worker-threads modify the new_win_reg_clauses_ (add new ones). This lock ensures that only one thread is modifying or reading the new_win_reg_clauses_ at one time.
Definition at line 1495 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), and notifyNewWinRegClause().
vector<CNF> IFM13Explorer::r_ [protected]
The frames R[] of the algorithm. Each frame represents a set of states in CNF.
You should use getR() to access the frames. The reason is that this method initializes frames if they do not yet exist.
Definition at line 1503 of file ParallelLearner.h.
Referenced by addBlockedState(), getR(), and IFM13Explorer().
vector<int> IFM13Explorer::sicn_ [protected]
The vector of present- and next-state variables, and all inputs.
Definition at line 1553 of file ParallelLearner.h.
Referenced by getGenBlockTransSolver(), getGotoNextLowerSolver(), IFM13Explorer(), and recBlockCube().
vector<int> IFM13Explorer::sin_ [protected]
The vector of present- and next-state variables, and uncontrollable inputs.
Definition at line 1548 of file ParallelLearner.h.
Referenced by IFM13Explorer(), and recBlockCube().
vector<CNF> IFM13Explorer::u_ [protected]
The blocked transitions U[] of the algorithm.
These sets are maintained only in debug mode. In release-mode they are only present inside the goto_next_lower_solvers_. You should use getU() to access the frames. The reason is that this method initializes elements if they do not yet exist.
Definition at line 1513 of file ParallelLearner.h.
Referenced by getU(), and IFM13Explorer().
CNF IFM13Explorer::win_ [protected]
The current over-approximation of the winning region W (for the protagonist).
Definition at line 1518 of file ParallelLearner.h.
Referenced by considerNewInfoFromOthers(), IFM13Explorer(), and isLose().
The documentation for this class was generated from the following files:
src/ParallelLearner.h
src/ParallelLearner.cpp