ParallelLearner Class Reference
The coordinator of the parallelized implementation.
#include <ParallelLearner.h>
Public Member Functions
ParallelLearner (size_t nr_of_threads, CNFImplExtractor *impl_extractor)
Constructor.
virtual ~ParallelLearner ()
Desctructor.
virtual bool run ()
Runs the back-end.
void notifyNewWinRegClause (const vector< int > &clause, int src)
Notifies all worker-threads that a new clause of the winning region is available.
void notifyNewUselessInputClause (const vector< int > &clause, int level)
Notifies all ClauseExplorerSAT-threads that a new U-clause is available.
void notifyNewCounterexample (const vector< int > &ce, const vector< int > &gen)
Adds a new counterexample to the ParallelLearner's database.
void triggerExplorerRestart ()
Computes a new restart point and notifies it to all ClauseExplorerSAT-instances.
void triggerInitialMode1Restart ()
The first restart is special because mode 0 threads are already allowed to work.
Public Attributes
PrevStateInfo psi_
A container with information about previous-state variables.
volatile int result_
An integer number containing the realizability verdict.
CNF winning_region_
The current version of the winning region.
mutex winning_region_lock_
A lock that protects the winning_region_ from race-conditions.
CNF unminimized_clauses_
All clauses of the winning region that have not yet been minimized.
mutex unminimized_clauses_lock_
A lock that protects the unminimized_clauses_ from race-conditions.
list< pair< vector< int >
*
, vector< int > > > counterexamples_
The counterexample-cubes together with their computed generalizations.
mutex counterexamples_lock_
A lock that protects the counterexamples_ from race-conditions.
mutex var_man_lock_
A lock that must be hold when the VarManager is modified.
Static Public Attributes
static mutex print_lock_
A lock used to synchronize the printing of debugging messages.
Protected Attributes
size_t nr_of_threads_
The number of threads to instantiate and execute.
vector< TemplExplorer * > templ_explorers_
The TemplExplorer-instances to execute in a separate thread.
vector< ClauseExplorerSAT * > clause_explorers_
The ClauseExplorerSAT-instances to execute in a separate thread.
vector< IFM13Explorer * > ifm_explorers_
The IFM13Explorer-instances to execute in a separate thread.
vector< ClauseMinimizerQBF * > clause_minimizers_
The ClauseMinimizerQBF-instances to execute in a separate thread.
vector< CounterGenSAT * > ce_generalizers_
The CounterGenSAT-instances to execute in a separate thread.
LearnStatisticsSAT statistics_
Stores and maintains statistics and performance measures.
CNFImplExtractor * impl_extractor_
The engine to use for circuit extraction.
vector< int > vars_to_keep_i_
The list of variables to keep in solver_i within the ClauseExplorerSAT.
UnivExpander expander_
The expander for eliminating universal quantifiers in our heuristic.
Private Member Functions
ParallelLearner (const ParallelLearner &other)
Copy constructor.
ParallelLearner & operator= (const ParallelLearner &other)
Assignment operator.
Detailed Description
The coordinator of the parallelized implementation.
This class implements a parallelized version of the learning-based synthesis methods. The idea is to combine various different techniques to refine an over-approximation of the winning region with new clauses. There is a lot of flexibility to play with. We can have threads discovering new clauses with SAT- or QBF-based learning techniques, we can have threads minimizing existing clauses with a QBF solver, etc. All threads share a common clause database. If (new or refined) clauses are discovered, they are communicated to all threads such that all of them can benefit from the new clauses in the next call. The threads performing actual work are implemented in other classes. This class is just the coordinator which starts the worker-threads and forwards information about new clauses to the worker-threads.
The parallel implementation has two advantages. First, it exploits hardware parallelism (modern CPUs have many cores), which means (potentially) shorter computation times. Second, it is an easy way of combining different methods. With one thread, one would have come up with points where to switch from one method to the other and back. Hence, it may also be useful to use the parallelized implementation even if only one core is available.
The question which methods we should combine how in order to achieve the best speed-up is not yet fully solved. This class is just one attempt, and can be seen as a playground for combining different methods.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 209 of file ParallelLearner.h.
Constructor & Destructor Documentation
ParallelLearner::ParallelLearner (size_t nr_of_threads, CNFImplExtractor * impl_extractor)
Constructor.
Parameters
nr_of_threads The number of threads to create. This does not have to be the number of cores in your CPU. It can also make sense to combine several methods running in several threads on one single core. The methods can complement each other and achieve a speedup compared to one single method in isolation.
impl_extractor The engine to use for circuit extraction. It will be deleted by this class.
Definition at line 251 of file ParallelLearner.cpp.
References ce_generalizers_, clause_explorers_, clause_minimizers_, VarInfo::CTRL, expander_, VarManager::getVarsOfType(), ifm_explorers_, VarInfo::INPUT, VarManager::instance(), MASSERT, VarInfo::PRES_STATE, psi_, result_, UnivExpander::setAbortCondition(), templ_explorers_, and vars_to_keep_i_.
ParallelLearner::~ParallelLearner () [virtual]
Desctructor.
Definition at line 364 of file ParallelLearner.cpp.
References ce_generalizers_, clause_explorers_, clause_minimizers_, ifm_explorers_, impl_extractor_, and templ_explorers_.
ParallelLearner::ParallelLearner (const ParallelLearner & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void ParallelLearner::notifyNewCounterexample (const vector< int > & ce, const vector< int > & gen)
Adds a new counterexample to the ParallelLearner's database.
A counterexample is a state-input combination with which the antagonist can enforce to leave the winning region. The counterexample is stored together with a generalization (some literals dropped) that has already been computed. This information can then be used by CounterGenSAT-threads. They take such a counterexample and compute all other generalizations (generalizations other than 'gen').
Parameters
ce This is a cube of the current-state variables and the uncontrollable inputs. With this state-input combination, the antagonist can enforce to leave the winning region. That is, there are no control-values such that the successor state is in the winning region again.
gen One generalization of the counterexample. This is a subset of the literals of ce such that no control-values can lead to a successor state inside the winning region.
Definition at line 549 of file ParallelLearner.cpp.
References ce_generalizers_, counterexamples_, and counterexamples_lock_.
Referenced by ClauseExplorerSAT::exploreClauses().
void ParallelLearner::notifyNewUselessInputClause (const vector< int > & clause, int level)
Notifies all ClauseExplorerSAT-threads that a new U-clause is available.
In essence, the ClauseExplorerSAT implements the same SAT-based learning method as LearnSynthSAT. It has just a few additional features which allow the implementation to communicate with others. A U-clause states that a certain state-input is useless for the antagonist in trying to leave the winning region (see LearnSynthSAT for details). If one ClauseExplorerSAT discovers such a clause, it communicates it to all other ClauseExplorerSAT-instances such that they can also benefit from it and do not need to re-discover the same fact again. For that to work, all ClauseExplorerSAT must be synchronized to a certain extend: All ClauseExplorerSAT must do solver restarts simultaneously. We pass the restart-level (the number of restarts done so far) as additional parameter so that every ClauseExplorerSAT-instances can then decide if this clause is helpful for him, or already out-dated.
Parameters
clause A new U-clause stating that a certain state-input is useless for the antagonist in trying to leave the winning region (see LearnSynthSAT for details).
level The restart level (the number of solver restarts that have already been performed. This information allows the receiver instance to decide whether or not this clause is useful for her (or if it is already out-dated).
Definition at line 534 of file ParallelLearner.cpp.
References clause_explorers_.
Referenced by ClauseExplorerSAT::exploreClauses().
void ParallelLearner::notifyNewWinRegClause (const vector< int > & clause, int src)
Notifies all worker-threads that a new clause of the winning region is available.
It also adds this clause to our global clause database winning_region_.
Parameters
clause The new clause that has been discovered.
src An integer number defining which kind of worker-thread discovered the clause. Some worker-threads may treat clauses from different sources in a special way.
Definition at line 498 of file ParallelLearner.cpp.
References CNF::addClause(), CNF::addClauseAndSimplify(), ce_generalizers_, clause_explorers_, clause_minimizers_, ifm_explorers_, MIN, templ_explorers_, unminimized_clauses_, unminimized_clauses_lock_, winning_region_, and winning_region_lock_.
Referenced by CounterGenSAT::bored(), ClauseExplorerSAT::exploreClauses(), CounterGenSAT::generalizeCounterexamples(), ClauseMinimizerQBF::minimizeClausesInc(), and ClauseMinimizerQBF::minimizeClausesNoInc().
ParallelLearner& ParallelLearner::operator= (const ParallelLearner & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
bool ParallelLearner::run () [virtual]
Runs the back-end.
This method mainly starts the worker-threads and waits until they are finished. The ParallelLearner itself does not do any work. It does not even run in an own thread. All the work is done in the worker-threads.
Returns
True if the specification was realizable, false otherwise.
Implements BackEnd.
Definition at line 391 of file ParallelLearner.cpp.
References CNF::addCNF(), ce_generalizers_, clause_explorers_, clause_minimizers_, UnivExpander::cleanup(), CNF::clear(), TemplExplorer::computeWinningRegion(), counterexamples_, Utils::debugCheckWinReg(), expander_, ClauseExplorerSAT::exploreClauses(), IFM13Explorer::exploreClauses(), CNFImplExtractor::extractCircuit(), CounterGenSAT::generalizeCounterexamples(), ifm_explorers_, impl_extractor_, VarManager::instance(), Options::instance(), AIG2CNF::instance(), L_INF, L_RES, CNFImplExtractor::logStatistics(), LearnStatisticsSAT::logStatistics(), MASSERT, LearnStatisticsSAT::mergeWith(), ClauseMinimizerQBF::minimizeClauses(), LearnStatisticsSAT::notifyWinRegEnd(), LearnStatisticsSAT::notifyWinRegStart(), nr_of_threads_, VarManager::push(), result_, statistics_, templ_explorers_, unminimized_clauses_, UNREALIZABLE, and winning_region_.
void ParallelLearner::triggerExplorerRestart ()
Computes a new restart point and notifies it to all ClauseExplorerSAT-instances.
The ClauseExplorerSAT update their next-state copy of the winning region only in a lazy manner. This allows them to use incremental SAT-solving more effectively. See LearnSynthSAT for a description. If no more solutions exists with one next-state copy of the winning region, it must be updated to the newest version. This is done by this method. A new next-state copy of the winning region is computed and communicated to all ClauseExplorerSAT-instances. It is absolutely important that all ClauseExplorerSAT instances work with the same next-state copy of the winning region. Otherwise, they could not exchange U-clauses (or rather, the U-clause discovered by one thread would not make sense for the other). See also notifyNewUselessInputClause().
Definition at line 560 of file ParallelLearner.cpp.
References clause_explorers_, Utils::compressStateCNF(), expander_, SatSolver::incAddCNF(), VarManager::instance(), AIG2CNF::instance(), L_LOG, CNF::negate(), UnivExpander::resetSolverIExp(), VarManager::resetToLastPush(), SatSolver::startIncrementalSession(), CNF::swapPresentToNext(), var_man_lock_, vars_to_keep_i_, winning_region_, and winning_region_lock_.
Referenced by ClauseExplorerSAT::exploreClauses().
void ParallelLearner::triggerInitialMode1Restart ()
The first restart is special because mode 0 threads are already allowed to work.
Definition at line 658 of file ParallelLearner.cpp.
References clause_explorers_, expander_, AIG2CNF::instance(), L_LOG, UnivExpander::resetSolverIExp(), and var_man_lock_.
Referenced by ClauseExplorerSAT::exploreClauses().
Member Data Documentation
vector<CounterGenSAT*> ParallelLearner::ce_generalizers_ [protected]
The CounterGenSAT-instances to execute in a separate thread.
Definition at line 440 of file ParallelLearner.h.
Referenced by notifyNewCounterexample(), notifyNewWinRegClause(), ParallelLearner(), run(), and ~ParallelLearner().
vector<ClauseExplorerSAT*> ParallelLearner::clause_explorers_ [protected]
The ClauseExplorerSAT-instances to execute in a separate thread.
Definition at line 425 of file ParallelLearner.h.
Referenced by notifyNewUselessInputClause(), notifyNewWinRegClause(), ParallelLearner(), run(), triggerExplorerRestart(), triggerInitialMode1Restart(), and ~ParallelLearner().
vector<ClauseMinimizerQBF*> ParallelLearner::clause_minimizers_ [protected]
The ClauseMinimizerQBF-instances to execute in a separate thread.
Definition at line 435 of file ParallelLearner.h.
Referenced by notifyNewWinRegClause(), ParallelLearner(), run(), and ~ParallelLearner().
list<pair<vector<int>, vector<int> > > ParallelLearner::counterexamples_
The counterexample-cubes together with their computed generalizations.
The first item of the pairs stored in this list is always the counterexample itself. The second item of the pair is the generalization that has already been computed.
A counterexample is a state-input combination with which the antagonist can enforce to leave the winning region. The generalization is a sub-cube of the counterexample. This information can then be used by CounterGenSAT-threads. They take such a counterexample and compute all other generalizations.
Definition at line 382 of file ParallelLearner.h.
Referenced by CounterGenSAT::generalizeCounterexamples(), notifyNewCounterexample(), and run().
mutex ParallelLearner::counterexamples_lock_
A lock that protects the counterexamples_ from race-conditions.
Many worker-threads modify the counterexamples_ (add new ones). This lock ensures that only one thread is modifying the counterexamples_ at one time.
Definition at line 390 of file ParallelLearner.h.
Referenced by CounterGenSAT::generalizeCounterexamples(), and notifyNewCounterexample().
UnivExpander ParallelLearner::expander_ [protected]
The expander for eliminating universal quantifiers in our heuristic.
Definition at line 464 of file ParallelLearner.h.
Referenced by ParallelLearner(), run(), triggerExplorerRestart(), and triggerInitialMode1Restart().
vector<IFM13Explorer*> ParallelLearner::ifm_explorers_ [protected]
The IFM13Explorer-instances to execute in a separate thread.
Definition at line 430 of file ParallelLearner.h.
Referenced by notifyNewWinRegClause(), ParallelLearner(), run(), and ~ParallelLearner().
CNFImplExtractor* ParallelLearner::impl_extractor_ [protected]
The engine to use for circuit extraction.
It will be deleted by this class (in the destructor).
Definition at line 454 of file ParallelLearner.h.
Referenced by run(), and ~ParallelLearner().
size_t ParallelLearner::nr_of_threads_ [protected]
The number of threads to instantiate and execute.
Definition at line 415 of file ParallelLearner.h.
Referenced by run().
mutex ParallelLearner::print_lock_ [static]
A lock used to synchronize the printing of debugging messages.
Debugging race conditions or other bugs in this implementation is tough. In order to prevent debugging messages from being interleaved strangely, this lock is used. It makes debug messages printed with the PLOG macro appear one after the other.
Definition at line 399 of file ParallelLearner.h.
PrevStateInfo ParallelLearner::psi_
A container with information about previous-state variables.
Definition at line 317 of file ParallelLearner.h.
Referenced by ParallelLearner().
volatile int ParallelLearner::result_
An integer number containing the realizability verdict.
There are three possible value.
UNKNOWN = 0: used as long as no thread has found a solution.
REALIZABLE = 1: used if some thread concludes that the spec must be realizable.
UNREALIZABLE = 2: used if some thread concludes that the spec must be unrealizable.
All worker-threads poll this flag from time to time. If the value is still UNKNOWN they continue to work. If they see that the values is not UNKNOWN anymore they stop assuming that some other thread has already found the solution. If one thread finds an answer to the realizability question it sets the flag (the winning_region_ must be precise enough then already).
Definition at line 335 of file ParallelLearner.h.
Referenced by CounterGenSAT::bored(), TemplExplorer::check(), CounterGenSAT::compressBored(), TemplExplorer::computeWinningRegion(), ClauseExplorerSAT::exploreClauses(), IFM13Explorer::exploreClauses(), CounterGenSAT::generalizeCounterexamples(), ClauseMinimizerQBF::minimizeClausesInc(), ClauseMinimizerQBF::minimizeClausesNoInc(), ParallelLearner(), IFM13Explorer::propagateBlockedStates(), IFM13Explorer::recBlockCube(), run(), and TemplExplorer::syntSAT().
LearnStatisticsSAT ParallelLearner::statistics_ [protected]
Stores and maintains statistics and performance measures.
Basically, this is a merge of the statistics from all worker-threads.
Definition at line 447 of file ParallelLearner.h.
Referenced by run().
vector<TemplExplorer*> ParallelLearner::templ_explorers_ [protected]
The TemplExplorer-instances to execute in a separate thread.
Definition at line 420 of file ParallelLearner.h.
Referenced by notifyNewWinRegClause(), ParallelLearner(), run(), and ~ParallelLearner().
CNF ParallelLearner::unminimized_clauses_
All clauses of the winning region that have not yet been minimized.
Whenever a clause is added to winning_region_, it is also added to this field. ClauseMinimizerQBF-instances then take clauses from unminimized_clauses_ and try to minimize them further. This is done to prevent that clauses are minimized twice or multiple times.
Definition at line 361 of file ParallelLearner.h.
Referenced by ClauseMinimizerQBF::minimizeClausesInc(), ClauseMinimizerQBF::minimizeClausesNoInc(), notifyNewWinRegClause(), and run().
mutex ParallelLearner::unminimized_clauses_lock_
A lock that protects the unminimized_clauses_ from race-conditions.
Many worker-threads refine the unminimized_clauses_ (add new clauses). This lock ensures that only one thread is modifying the unminimized_clauses_ at one time.
Definition at line 369 of file ParallelLearner.h.
Referenced by ClauseMinimizerQBF::minimizeClausesInc(), ClauseMinimizerQBF::minimizeClausesNoInc(), and notifyNewWinRegClause().
mutex ParallelLearner::var_man_lock_
A lock that must be hold when the VarManager is modified.
Sometimes (at the moment only when doing restarts in triggerExplorerRestart()) we need to modify the VarManager, e.g., if we create new variables. This lock is used to prevent race-conditions in these operations. It must be held whenever the VarManager is modified.
Definition at line 408 of file ParallelLearner.h.
Referenced by triggerExplorerRestart(), triggerInitialMode1Restart(), and ClauseExplorerSAT::waitUntilOngoingRestartDone().
vector<int> ParallelLearner::vars_to_keep_i_ [protected]
The list of variables to keep in solver_i within the ClauseExplorerSAT.
Definition at line 459 of file ParallelLearner.h.
Referenced by ParallelLearner(), and triggerExplorerRestart().
CNF ParallelLearner::winning_region_
The current version of the winning region.
All worker-threads discover or minimize clauses of the winning region. This is the current version of the winning region.
Definition at line 343 of file ParallelLearner.h.
Referenced by TemplExplorer::computeWinningRegion(), IFM13Explorer::exploreClauses(), ClauseMinimizerQBF::minimizeClausesNoInc(), notifyNewWinRegClause(), run(), and triggerExplorerRestart().
mutex ParallelLearner::winning_region_lock_
A lock that protects the winning_region_ from race-conditions.
Many worker-threads refine the winning_region_ (add new clauses). This lock ensures that only one thread is modifying the winning_region_ at one time.
Definition at line 351 of file ParallelLearner.h.
Referenced by TemplExplorer::computeWinningRegion(), IFM13Explorer::exploreClauses(), ClauseMinimizerQBF::minimizeClausesNoInc(), notifyNewWinRegClause(), and triggerExplorerRestart().
The documentation for this class was generated from the following files:
src/ParallelLearner.h
src/ParallelLearner.cpp