LearnStatisticsSAT Class Reference
Collects statistics and performance data for LearnSynthSAT.
#include <LearnStatisticsSAT.h>
Public Member Functions
LearnStatisticsSAT ()
Constructor.
virtual ~LearnStatisticsSAT ()
Destructor.
void notifyWinRegStart ()
Called before the computation of the winning region starts.
void notifyWinRegEnd ()
Called after the computation of the winning region is done.
void notifyBeforeComputeCandidate ()
Called before the SAT solver is called to compute a counterexample-candidate.
void notifyAfterComputeCandidate ()
Called after the SAT solver is done computing a counterexample-candidate.
void notifyRestart ()
Called whenever the incremental session of the solver is restarted.
void notifyBeforeCheckCandidate ()
Called before the SAT solver is called to check a counterexample-candidate.
void notifyAfterCheckCandidateFound (size_t from_size, size_t to_size)
Called after the SAT solver successfully checked a counterexample-candidate.
void notifyAfterCheckCandidateFailed ()
Called after the SAT solver unsuccessfully checked a counterexample-candidate.
void notifyBeforeRefine ()
Called before the SAT solver is called to refine the U-set.
void notifyAfterRefine (size_t from_size, size_t to_size)
Called after the SAT solver is done refining the U-set.
void mergeWith (const LearnStatisticsSAT &other)
Merges the data store in this object with statistics stored in another object.
void logStatistics () const
Writes the statistics to stdout as messages of type Logger::LOG.
Protected Attributes
PointInTime win_reg_start_time_
The time when the computation of the winning region was started.
double win_reg_cpu_time_
The winning region computation time in CPU-seconds.
size_t win_reg_real_time_
Like win_reg_cpu_time_ but real-time.
size_t nr_of_cand_comp_
The total number of candidate computations.
size_t nr_of_restarts_
The total number solver restarts (starting a new incremental session).
size_t nr_of_cand_checks_
The total number of candidate checks.
size_t nr_of_succ_checks_
The total number of successful candidate checks.
size_t sum_check_size_from_
The sum of the counterexample cube sizes (nr of literals) before minimization.
size_t sum_check_size_to_
The sum of the counterexample cube sizes (nr of literals) after minimization.
size_t nr_of_refines_
The number of refinements of the useless state-input pairs.
size_t sum_refine_size_from_
The sum of the useless state-input-cube sizes (nr of literals) before minimization.
size_t sum_refine_size_to_
The sum of the useless state-input-cube sizes (nr of literals) after minimization.
PointInTime cand_comp_start_time_
The time when the last computation of a counterexample-candidate was started.
double cand_comp_cpu_time_
The total candidate computation time in CPU-seconds.
size_t cand_comp_real_time_
Like cand_comp_cpu_time_ but real-time.
PointInTime cand_check_start_time_
The time when the last check of a counterexample-candidate was started.
double cand_check_cpu_time_
The total candidate checking time in CPU-seconds.
size_t cand_check_real_time_
Like cand_check_cpu_time_ but real-time.
PointInTime refine_start_time_
The time when the last useless state-input-cube generalization was started.
double refine_cpu_time_
The total useless state-input-cube generalization time in CPU-seconds.
size_t refine_real_time_
Like cand_check_cpu_time_ but real-time.
Private Member Functions
LearnStatisticsSAT (const LearnStatisticsSAT &other)
Copy constructor.
LearnStatisticsSAT & operator= (const LearnStatisticsSAT &other)
Assignment operator.
Detailed Description
Collects statistics and performance data for LearnSynthSAT.
This class collects statistics and performance data for the learning-based synthesis method implemented with two SAT solvers instead of a QBF-solver (implemented in the class LearnSynthSAT).
Definition at line 44 of file LearnStatisticsSAT.h.
Constructor & Destructor Documentation
LearnStatisticsSAT::LearnStatisticsSAT ()
Constructor.
Definition at line 34 of file LearnStatisticsSAT.cpp.
LearnStatisticsSAT::~LearnStatisticsSAT () [virtual]
Destructor.
Definition at line 57 of file LearnStatisticsSAT.cpp.
LearnStatisticsSAT::LearnStatisticsSAT (const LearnStatisticsSAT & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void LearnStatisticsSAT::logStatistics () const
Writes the statistics to stdout as messages of type Logger::LOG.
If messages of type Logger::LOG are disabled (see Logger), then nothing happens.
Definition at line 159 of file LearnStatisticsSAT.cpp.
References cand_check_cpu_time_, cand_check_real_time_, cand_comp_cpu_time_, cand_comp_real_time_, L_LOG, nr_of_cand_checks_, nr_of_cand_comp_, nr_of_refines_, nr_of_restarts_, nr_of_succ_checks_, refine_cpu_time_, refine_real_time_, sum_check_size_from_, sum_check_size_to_, sum_refine_size_from_, sum_refine_size_to_, win_reg_cpu_time_, and win_reg_real_time_.
Referenced by LearnSynthSAT::run(), and ParallelLearner::run().
void LearnStatisticsSAT::mergeWith (const LearnStatisticsSAT & other)
Merges the data store in this object with statistics stored in another object.
This is done by summing all (corresponding) execution times and iteration counters.
Parameters
other The source object that should be merged into this object.
Definition at line 137 of file LearnStatisticsSAT.cpp.
References cand_check_cpu_time_, cand_check_real_time_, cand_comp_cpu_time_, cand_comp_real_time_, nr_of_cand_checks_, nr_of_cand_comp_, nr_of_refines_, nr_of_restarts_, nr_of_succ_checks_, refine_cpu_time_, refine_real_time_, sum_check_size_from_, sum_check_size_to_, sum_refine_size_from_, sum_refine_size_to_, win_reg_cpu_time_, and win_reg_real_time_.
Referenced by ParallelLearner::run().
void LearnStatisticsSAT::notifyAfterCheckCandidateFailed ()
Called after the SAT solver unsuccessfully checked a counterexample-candidate.
This method just reads out the Stopwatch and stores the execution time.
Definition at line 113 of file LearnStatisticsSAT.cpp.
References cand_check_cpu_time_, cand_check_real_time_, cand_check_start_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), and nr_of_cand_checks_.
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::exploreClauses(), and CounterGenSAT::generalizeCounterexamples().
void LearnStatisticsSAT::notifyAfterCheckCandidateFound (size_t from_size, size_t to_size)
Called after the SAT solver successfully checked a counterexample-candidate.
This method just reads out the Stopwatch and stores the execution time. Furthermore, it stores the results of generalizing the counterexample.
Parameters
from_size The size of the counterexample (number of literals in the cube) before minimization (by computing an unsatisfiable core).
to_size The size of the counterexample (number of literals in the cube) after minimization (by computing an unsatisfiable core).
Definition at line 102 of file LearnStatisticsSAT.cpp.
References cand_check_cpu_time_, cand_check_real_time_, cand_check_start_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), nr_of_cand_checks_, nr_of_succ_checks_, sum_check_size_from_, and sum_check_size_to_.
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::exploreClauses(), and CounterGenSAT::generalizeCounterexamples().
void LearnStatisticsSAT::notifyAfterComputeCandidate ()
Called after the SAT solver is done computing a counterexample-candidate.
This method just reads out the Stopwatch and stores the execution time.
Definition at line 82 of file LearnStatisticsSAT.cpp.
References cand_comp_cpu_time_, cand_comp_real_time_, cand_comp_start_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), and nr_of_cand_comp_.
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), and ClauseExplorerSAT::exploreClauses().
void LearnStatisticsSAT::notifyAfterRefine (size_t from_size, size_t to_size)
Called after the SAT solver is done refining the U-set.
This method just reads out the Stopwatch and stores the execution time. Furthermore, it stores the results of generalizing the useless state-input cube.
Parameters
from_size The size of the useless state-input cube (number of literals in the cube) before minimization (by computing an unsatisfiable core).
to_size The size of the useless state-input cube (number of literals in the cube) after minimization (by computing an unsatisfiable core).
Definition at line 127 of file LearnStatisticsSAT.cpp.
References Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), nr_of_refines_, refine_cpu_time_, refine_real_time_, refine_start_time_, sum_refine_size_from_, and sum_refine_size_to_.
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRecy(), and ClauseExplorerSAT::exploreClauses().
void LearnStatisticsSAT::notifyBeforeCheckCandidate ()
Called before the SAT solver is called to check a counterexample-candidate.
This method just starts a Stopwatch.
Definition at line 96 of file LearnStatisticsSAT.cpp.
References cand_check_start_time_, and Stopwatch::start().
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), ClauseExplorerSAT::exploreClauses(), and CounterGenSAT::generalizeCounterexamples().
void LearnStatisticsSAT::notifyBeforeComputeCandidate ()
Called before the SAT solver is called to compute a counterexample-candidate.
This method just starts a Stopwatch.
Definition at line 76 of file LearnStatisticsSAT.cpp.
References cand_comp_start_time_, and Stopwatch::start().
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), and ClauseExplorerSAT::exploreClauses().
void LearnStatisticsSAT::notifyBeforeRefine ()
Called before the SAT solver is called to refine the U-set.
Refining the U-set means computing an unsatisfiable core of a state-input cube that is useless for the antagonist in trying to break out of the winning region. This method just starts a Stopwatch.
Definition at line 121 of file LearnStatisticsSAT.cpp.
References refine_start_time_, and Stopwatch::start().
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRecy(), and ClauseExplorerSAT::exploreClauses().
void LearnStatisticsSAT::notifyRestart ()
Called whenever the incremental session of the solver is restarted.
This method is called to count the number of performed restarts.
Definition at line 90 of file LearnStatisticsSAT.cpp.
References nr_of_restarts_.
Referenced by LearnSynthSAT::computeWinningRegionPlain(), LearnSynthSAT::computeWinningRegionPlainDep(), LearnSynthSAT::computeWinningRegionPlainDep2(), LearnSynthSAT::computeWinningRegionPlainExp(), LearnSynthSAT::computeWinningRegionRG(), LearnSynthSAT::computeWinningRegionRGExp(), LearnSynthSAT::computeWinningRegionRGRC(), LearnSynthSAT::computeWinningRegionRGRCExp(), LearnSynthSAT::computeWinningRegionRGRecy(), and ClauseExplorerSAT::considerNewInfoFromOthers().
void LearnStatisticsSAT::notifyWinRegEnd ()
Called after the computation of the winning region is done.
This method just reads out the Stopwatch and stores the execution time.
Definition at line 69 of file LearnStatisticsSAT.cpp.
References Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), win_reg_cpu_time_, win_reg_real_time_, and win_reg_start_time_.
Referenced by LearnSynthSAT::run(), and ParallelLearner::run().
void LearnStatisticsSAT::notifyWinRegStart ()
Called before the computation of the winning region starts.
This method just starts a Stopwatch.
Definition at line 63 of file LearnStatisticsSAT.cpp.
References Stopwatch::start(), and win_reg_start_time_.
Referenced by LearnSynthSAT::run(), and ParallelLearner::run().
LearnStatisticsSAT& LearnStatisticsSAT::operator= (const LearnStatisticsSAT & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
Member Data Documentation
double LearnStatisticsSAT::cand_check_cpu_time_ [protected]
The total candidate checking time in CPU-seconds.
Definition at line 250 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), notifyAfterCheckCandidateFailed(), and notifyAfterCheckCandidateFound().
size_t LearnStatisticsSAT::cand_check_real_time_ [protected]
Like cand_check_cpu_time_ but real-time.
Definition at line 255 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), notifyAfterCheckCandidateFailed(), and notifyAfterCheckCandidateFound().
PointInTime LearnStatisticsSAT::cand_check_start_time_ [protected]
The time when the last check of a counterexample-candidate was started.
Definition at line 245 of file LearnStatisticsSAT.h.
Referenced by notifyAfterCheckCandidateFailed(), notifyAfterCheckCandidateFound(), and notifyBeforeCheckCandidate().
double LearnStatisticsSAT::cand_comp_cpu_time_ [protected]
The total candidate computation time in CPU-seconds.
Definition at line 235 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyAfterComputeCandidate().
size_t LearnStatisticsSAT::cand_comp_real_time_ [protected]
Like cand_comp_cpu_time_ but real-time.
Definition at line 240 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyAfterComputeCandidate().
PointInTime LearnStatisticsSAT::cand_comp_start_time_ [protected]
The time when the last computation of a counterexample-candidate was started.
Definition at line 230 of file LearnStatisticsSAT.h.
Referenced by notifyAfterComputeCandidate(), and notifyBeforeComputeCandidate().
size_t LearnStatisticsSAT::nr_of_cand_checks_ [protected]
The total number of candidate checks.
Definition at line 187 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), notifyAfterCheckCandidateFailed(), and notifyAfterCheckCandidateFound().
size_t LearnStatisticsSAT::nr_of_cand_comp_ [protected]
The total number of candidate computations.
Definition at line 177 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyAfterComputeCandidate().
size_t LearnStatisticsSAT::nr_of_refines_ [protected]
The number of refinements of the useless state-input pairs.
Definition at line 211 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyAfterRefine().
size_t LearnStatisticsSAT::nr_of_restarts_ [protected]
The total number solver restarts (starting a new incremental session).
Definition at line 182 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyRestart().
size_t LearnStatisticsSAT::nr_of_succ_checks_ [protected]
The total number of successful candidate checks.
Definition at line 192 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyAfterCheckCandidateFound().
double LearnStatisticsSAT::refine_cpu_time_ [protected]
The total useless state-input-cube generalization time in CPU-seconds.
Definition at line 265 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyAfterRefine().
size_t LearnStatisticsSAT::refine_real_time_ [protected]
Like cand_check_cpu_time_ but real-time.
Definition at line 270 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyAfterRefine().
PointInTime LearnStatisticsSAT::refine_start_time_ [protected]
The time when the last useless state-input-cube generalization was started.
Definition at line 260 of file LearnStatisticsSAT.h.
Referenced by notifyAfterRefine(), and notifyBeforeRefine().
size_t LearnStatisticsSAT::sum_check_size_from_ [protected]
The sum of the counterexample cube sizes (nr of literals) before minimization.
This is tracked to assess the effectiveness of the minimization (=generalization).
Definition at line 199 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyAfterCheckCandidateFound().
size_t LearnStatisticsSAT::sum_check_size_to_ [protected]
The sum of the counterexample cube sizes (nr of literals) after minimization.
This is tracked to assess the effectiveness of the minimization (=generalization).
Definition at line 206 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyAfterCheckCandidateFound().
size_t LearnStatisticsSAT::sum_refine_size_from_ [protected]
The sum of the useless state-input-cube sizes (nr of literals) before minimization.
This is tracked to assess the effectiveness of the minimization (=generalization).
Definition at line 218 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyAfterRefine().
size_t LearnStatisticsSAT::sum_refine_size_to_ [protected]
The sum of the useless state-input-cube sizes (nr of literals) after minimization.
This is tracked to assess the effectiveness of the minimization (=generalization).
Definition at line 225 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyAfterRefine().
double LearnStatisticsSAT::win_reg_cpu_time_ [protected]
The winning region computation time in CPU-seconds.
Definition at line 167 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyWinRegEnd().
size_t LearnStatisticsSAT::win_reg_real_time_ [protected]
Like win_reg_cpu_time_ but real-time.
Definition at line 172 of file LearnStatisticsSAT.h.
Referenced by logStatistics(), mergeWith(), and notifyWinRegEnd().
PointInTime LearnStatisticsSAT::win_reg_start_time_ [protected]
The time when the computation of the winning region was started.
Definition at line 162 of file LearnStatisticsSAT.h.
Referenced by notifyWinRegEnd(), and notifyWinRegStart().
The documentation for this class was generated from the following files:
src/LearnStatisticsSAT.h
src/LearnStatisticsSAT.cpp