ClauseMinimizerQBF Class Reference
Uses a QBF solver to minimize existing winning region clauses further.
#include <ParallelLearner.h>
Public Member Functions
ClauseMinimizerQBF (size_t instance_nr, ParallelLearner &coordinator, PrevStateInfo &psi)
Constructor.
virtual ~ClauseMinimizerQBF ()
Destructor.
void minimizeClauses ()
The work-horse of this class.
void notifyNewWinRegClause (const vector< int > &clause, int src)
Notifies this worker about a new winning region clause.
Protected Member Functions
void minimizeClausesInc ()
Implements minimizeClauses() with incremental QBF solving.
void minimizeClausesNoInc ()
Implements minimizeClauses() with non-incremental QBF solving.
Protected Attributes
ParallelLearner & coordinator_
A reference to the coordinator.
vector< pair< vector< int >
*
, QBFSolver::Quant > > gen_quant_
The quantifier prefix of the QBF for generalizing clauses.
QBFSolver * qbf_solver_
The QBF-solver used for the generalization queries.
DepQBFApi * inc_qbf_solver_
An interface to DepQBF for incremental QBF solving.
SatSolver * sat_solver_
A SatSolver to check if minimized clauses are already implied by others.
CNF new_win_reg_clauses_
All new winning region clauses that have not been considered yet.
mutex new_win_reg_clauses_lock_
A lock that protects the new_win_reg_clauses_ from race-conditions.
const PrevStateInfo & psi_
Information about the previous states if optimization RG is enabled.
Private Member Functions
ClauseMinimizerQBF (const ClauseMinimizerQBF &other)
Copy constructor.
ClauseMinimizerQBF & operator= (const ClauseMinimizerQBF &other)
Assignment operator.
Detailed Description
Uses a QBF solver to minimize existing winning region clauses further.
This class is very simple: it just takes clauses from the winning region and tries to minimize them further using a QBF solver. The minimization is done in the very same way in LearnSynthQBF.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 1146 of file ParallelLearner.h.
Constructor & Destructor Documentation
ClauseMinimizerQBF::ClauseMinimizerQBF (size_t instance_nr, ParallelLearner & coordinator, PrevStateInfo & psi)
Constructor.
Parameters
instance_nr A unique instance number. It is used to bring in some asymmetry between the different ClauseMinimizerQBF-instances: depending on the instance number, the instance selects a different Solver to use.
coordinator A reference to the coordinator. All communication to other worker-threads is done via the coordinator.
psi A container for previous-state information (needed when optimization RG is enabled).
Definition at line 1502 of file ParallelLearner.cpp.
References QBFSolver::A, VarInfo::CTRL, QBFSolver::E, gen_quant_, VarManager::getVarsOfType(), inc_qbf_solver_, VarInfo::INPUT, VarManager::instance(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, VarInfo::PREV, psi_, sat_solver_, SatSolver::startIncrementalSession(), VarInfo::TMP, and PrevStateInfo::use_ind_.
ClauseMinimizerQBF::~ClauseMinimizerQBF () [virtual]
Destructor.
Definition at line 1534 of file ParallelLearner.cpp.
References inc_qbf_solver_, qbf_solver_, and sat_solver_.
ClauseMinimizerQBF::ClauseMinimizerQBF (const ClauseMinimizerQBF & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void ClauseMinimizerQBF::minimizeClauses ()
The work-horse of this class.
It takes clauses from the winning region and tries to minimize them further using a QBF-solver. The minimization is done in the very same way in LearnSynthQBF. In every iteration, this method also considers all new incoming clauses found by others. If it finds out that the specification is realizable or unrealizable, it sets the flag ParallelLearner::result_ accordingly. It also polls this flag regularly. If it has been set by some other thread, it quits.
Definition at line 1547 of file ParallelLearner.cpp.
References inc_qbf_solver_, minimizeClausesInc(), and minimizeClausesNoInc().
Referenced by ParallelLearner::run().
void ClauseMinimizerQBF::minimizeClausesInc () [protected]
Implements minimizeClauses() with incremental QBF solving.
Definition at line 1564 of file ParallelLearner.cpp.
References CNF::clear(), Utils::containsInit(), coordinator_, DepQBFApi::doMinCores(), gen_quant_, CNF::getNrOfClauses(), inc_qbf_solver_, SatSolver::incAddCNF(), DepQBFApi::incAddCNF(), DepQBFApi::incAddUnitClause(), DepQBFApi::incIsSat(), SatSolver::incIsSat(), DepQBFApi::incIsSatCore(), AIG2CNF::instance(), MASSERT, MIN, Utils::negateLiterals(), new_win_reg_clauses_, new_win_reg_clauses_lock_, ParallelLearner::notifyNewWinRegClause(), PrevStateInfo::presentToPrevious(), PrevStateInfo::prev_safe_, PrevStateInfo::prev_trans_or_initial_, psi_, Utils::randomize(), Utils::remove(), CNF::removeSomeClause(), ParallelLearner::result_, sat_solver_, DepQBFApi::startIncrementalSession(), CNF::swapPresentToNext(), UNKNOWN, ParallelLearner::unminimized_clauses_, ParallelLearner::unminimized_clauses_lock_, UNREALIZABLE, and PrevStateInfo::use_ind_.
Referenced by minimizeClauses().
void ClauseMinimizerQBF::minimizeClausesNoInc () [protected]
Implements minimizeClauses() with non-incremental QBF solving.
Definition at line 1674 of file ParallelLearner.cpp.
References CNF::addClause(), CNF::addCNF(), CNF::addNegClauseAsCube(), Utils::containsInit(), coordinator_, PrevStateInfo::current_state_is_initial_, gen_quant_, CNF::getNrOfClauses(), AIG2CNF::instance(), QBFSolver::isSat(), SatSolver::isSat(), MIN, Utils::negateLiterals(), ParallelLearner::notifyNewWinRegClause(), PrevStateInfo::presentToPrevious(), PrevStateInfo::prev_trans_or_initial_, psi_, qbf_solver_, Utils::randomize(), Utils::remove(), CNF::removeSmallest(), ParallelLearner::result_, sat_solver_, Utils::swapPresentToNext(), CNF::swapPresentToNext(), UNKNOWN, ParallelLearner::unminimized_clauses_, ParallelLearner::unminimized_clauses_lock_, UNREALIZABLE, PrevStateInfo::use_ind_, ParallelLearner::winning_region_, and ParallelLearner::winning_region_lock_.
Referenced by minimizeClauses().
void ClauseMinimizerQBF::notifyNewWinRegClause (const vector< int > & clause, int src)
Notifies this worker about a new winning region clause.
Parameters
clause The new clause that has been discovered.
src An integer number defining which kind of worker-thread discovered the clause. At the moment, this information is ignored.
Definition at line 1556 of file ParallelLearner.cpp.
References CNF::addClause(), new_win_reg_clauses_, and new_win_reg_clauses_lock_.
ClauseMinimizerQBF& ClauseMinimizerQBF::operator= (const ClauseMinimizerQBF & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
Member Data Documentation
ParallelLearner& ClauseMinimizerQBF::coordinator_ [protected]
A reference to the coordinator.
All communication to other worker-threads is done via the coordinator.
Definition at line 1208 of file ParallelLearner.h.
Referenced by minimizeClausesInc(), and minimizeClausesNoInc().
vector<pair<vector<int>, QBFSolver::Quant> > ClauseMinimizerQBF::gen_quant_ [protected]
The quantifier prefix of the QBF for generalizing clauses.
This quantifier prefix is always exists x: forall i: exists c,x',tmp:
Definition at line 1216 of file ParallelLearner.h.
Referenced by ClauseMinimizerQBF(), minimizeClausesInc(), and minimizeClausesNoInc().
DepQBFApi* ClauseMinimizerQBF::inc_qbf_solver_ [protected]
An interface to DepQBF for incremental QBF solving.
Definition at line 1228 of file ParallelLearner.h.
Referenced by ClauseMinimizerQBF(), minimizeClauses(), minimizeClausesInc(), and ~ClauseMinimizerQBF().
CNF ClauseMinimizerQBF::new_win_reg_clauses_ [protected]
All new winning region clauses that have not been considered yet.
Definition at line 1238 of file ParallelLearner.h.
Referenced by minimizeClausesInc(), and notifyNewWinRegClause().
mutex ClauseMinimizerQBF::new_win_reg_clauses_lock_ [protected]
A lock that protects the new_win_reg_clauses_ from race-conditions.
Many worker-threads modify the new_win_reg_clauses_ (add new ones). This lock ensures that only one thread is modifying or reading the new_win_reg_clauses_ at one time.
Definition at line 1246 of file ParallelLearner.h.
Referenced by minimizeClausesInc(), and notifyNewWinRegClause().
const PrevStateInfo& ClauseMinimizerQBF::psi_ [protected]
Information about the previous states if optimization RG is enabled.
Definition at line 1251 of file ParallelLearner.h.
Referenced by ClauseMinimizerQBF(), minimizeClausesInc(), and minimizeClausesNoInc().
QBFSolver* ClauseMinimizerQBF::qbf_solver_ [protected]
The QBF-solver used for the generalization queries.
The type of solver is selected with command-line arguments.
Definition at line 1223 of file ParallelLearner.h.
Referenced by minimizeClausesNoInc(), and ~ClauseMinimizerQBF().
SatSolver* ClauseMinimizerQBF::sat_solver_ [protected]
A SatSolver to check if minimized clauses are already implied by others.
Definition at line 1233 of file ParallelLearner.h.
Referenced by ClauseMinimizerQBF(), minimizeClausesInc(), minimizeClausesNoInc(), and ~ClauseMinimizerQBF().
The documentation for this class was generated from the following files:
src/ParallelLearner.h
src/ParallelLearner.cpp