IFM13Synth Class Reference
Implements the SAT-based synthesis method published at IFM'13.
#include <IFM13Synth.h>
Public Member Functions
IFM13Synth (CNFImplExtractor *impl_extractor)
Constructor.
virtual ~IFM13Synth ()
Destructor.
virtual bool run ()
Executes the back-end (which is implemented as described in the IFM'13 paper).
Protected Member Functions
bool computeWinningRegion ()
Computes the set of states from which the specification can be fulfilled.
size_t propagateBlockedStates (size_t max_level)
Propagates clauses forward and searches for equivalent clause sets.
bool recBlockCube (const vector< int > &state_cube, size_t level)
Analyzes the rank of the passed state.
void addBlockedTransition (const vector< int > &state_in_cube, size_t level)
Marks a state-input-pair as blocked.
void addBlockedState (const vector< int > &state_cube, size_t level)
Removes a state(-cube) from the frame R[level].
bool isBlocked (const vector< int > &state_cube, size_t level)
Checks if a state is contained in a certain frame.
void addLose (const vector< int > &state_cube)
Removes a state(-cube) from the current over-approximation of the winning region.
bool isLose (const vector< int > &state_cube)
Checks if a state satisfies the current over-approximation of the winning region.
void genAndBlockTrans (const vector< int > &state_in_cube, const vector< int > &ctrl_cube, size_t level)
Generalizes and excludes a blocked transition.
CNF & getR (size_t index)
Returns the frame R[index] in CNF.
CNF & getU (size_t index)
Returns the blocked transitions U[index] in CNF.
SatSolver * getGotoNextLowerSolver (size_t index)
Returns a solver with CNF: U[index] & T & R[index-1]'.
SatSolver * getGenBlockTransSolver (size_t index)
Returns a solver with CNF: T & R[index-1]'.
IFMProofObligation popMin (list< IFMProofObligation > &queue)
Takes a list of proof obligations and removes the element with lowest rank.
void debugPrintRs () const
A debugging utility to print all frames.
void debugCheckInvariants (size_t k)
A debugging utility check invariants of the data structures.
Protected Attributes
vector< CNF > r_
The frames R[] of the algorithm. Each frame represents a set of states in CNF.
vector< CNF > u_
The blocked transitions U[] of the algorithm.
CNF win_
The current over-approximation of the winning region W (for the protagonist).
vector< SatSolver * > goto_next_lower_solvers_
The solvers storing the CNF: U[k] & T & R[k-1]'.
vector< SatSolver * > gen_block_trans_solvers_
The solvers storing the CNF: T & R[k-1]'.
SatSolver * goto_win_solver_
A solver that stores the CNF: T & W'.
CNF winning_region_
The final winning region as computed by computeWinningRegion.
CNF neg_winning_region_
The negated winning region as computed by computeWinningRegion.
vector< int > sin_
The vector of present- and next-state variables, and uncontrollable inputs.
vector< int > sicn_
The vector of present- and next-state variables, and all inputs.
CNFImplExtractor * impl_extractor_
The engine to use for circuit extraction.
Private Member Functions
IFM13Synth (const IFM13Synth &other)
Copy constructor.
IFM13Synth & operator= (const IFM13Synth &other)
Assignment operator.
Detailed Description
Implements the SAT-based synthesis method published at IFM'13.
This class is a re-implementation of the SAT-based synthesis method published in the paper: `Andreas Morgenstern, Manuel Gesell, Klaus Schneider: Solving Games Using
Incremental Induction, IFM 2013, pages 177-191`. It is based on the description given in the paper with only a few additional optimizations following the paper `Niklas Een, Alan Mishchenko, Robert K. Brayton: Efficient implementation of property
directed reachability, FMCAD 2011, pages 125-134`. All these optimizations are clearly marked in the source code. In order to understand the code in this class, you should read the IFM'13 paper first. After that, you will find a one-to-one correspondence between the functions described in the paper and the methods of this class.
The IFM'13 publication only describes how to determine realizability, but not how extract a winning region from this computation. Our implementation also extracts a winning region (the set R[i] such that R[i] = R[i-1]).
Note
This is not the original implementation of the IFM'13 paper, it is a re-implementation. The re-implementation is based on the paper only. The original implementation may contain more optimizations.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 65 of file IFM13Synth.h.
Constructor & Destructor Documentation
IFM13Synth::IFM13Synth (CNFImplExtractor * impl_extractor)
Constructor.
Parameters
impl_extractor The engine to use for circuit extraction. It will be deleted by this class.
Definition at line 54 of file IFM13Synth.cpp.
References CNF::addCNF(), VarInfo::CTRL, gen_block_trans_solvers_, Options::getSATSolver(), VarManager::getVarsOfType(), goto_next_lower_solvers_, goto_win_solver_, SatSolver::incAddCNF(), VarInfo::INPUT, VarManager::instance(), Options::instance(), AIG2CNF::instance(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, r_, sicn_, sin_, SatSolver::startIncrementalSession(), u_, and win_.
IFM13Synth::~IFM13Synth () [virtual]
Destructor.
Definition at line 103 of file IFM13Synth.cpp.
References gen_block_trans_solvers_, goto_next_lower_solvers_, goto_win_solver_, and impl_extractor_.
IFM13Synth::IFM13Synth (const IFM13Synth & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void IFM13Synth::addBlockedState (const vector< int > & state_cube, size_t level) [protected]
Removes a state(-cube) from the frame R[level].
This method updates R[level] := R[level] & !state_cube. state_cube is a potentially incomplete state-cube. We also update the R-sets of all smaller levels in the same way for syntactic containment reasons (as described in the paper).
Parameters
state_cube The state-cube that should be removed from R[level]. The cube is potentially incomplete, i.e., can represent a larger set of states.
level The level in which the state should be blocked (i.e., removed form the corresponding frame R[level]).
Definition at line 351 of file IFM13Synth.cpp.
References CNF::addClause(), getGenBlockTransSolver(), getGotoNextLowerSolver(), getR(), SatSolver::incAddClause(), SatSolver::incIsSat(), VarManager::instance(), r_, and Utils::swapPresentToNext().
Referenced by recBlockCube().
void IFM13Synth::addBlockedTransition (const vector< int > & state_in_cube, size_t level) [protected]
Marks a state-input-pair as blocked.
The meaning is: we want to store the fact that a certain state-input pair is not helpful for the antagonist (the party controlling the inputs i) in trying to move from R[level] to R[level-1]. Hence, we update U[level] := U[level] & !state_in_cube. We also update the U-sets of all smaller levels in the same way for syntactic containment reasons (as described in the paper).
Parameters
state_in_cube The state-input pair as a cube over present state variables and uncontrollable inputs. The cube is potentially incomplete, i.e., can represent a larger set of state-input pairs.
level The level in which the transition should be blocked (i.e., the state-input pair should by marked as useless for the antagonist).
Definition at line 336 of file IFM13Synth.cpp.
References CNF::addClauseAndSimplify(), getGotoNextLowerSolver(), getU(), and SatSolver::incAddClause().
Referenced by genAndBlockTrans().
void IFM13Synth::addLose (const vector< int > & state_cube) [protected]
Removes a state(-cube) from the current over-approximation of the winning region.
This method updates W := W & !state_cube. state_cube is a potentially incomplete state-cube.
Parameters
state_cube The state-cube that should be removed from the current over-approximation of the winning region. The cube is potentially incomplete, i.e.,
Definition at line 405 of file IFM13Synth.cpp.
References CNF::addClauseAndSimplify(), goto_win_solver_, SatSolver::incAddClause(), Utils::swapPresentToNext(), and win_.
Referenced by recBlockCube().
bool IFM13Synth::computeWinningRegion () [protected]
Computes the set of states from which the specification can be fulfilled.
Returns
True if the specification is realizable, false otherwise.
Definition at line 145 of file IFM13Synth.cpp.
References debugCheckInvariants(), getR(), VarManager::getVarsOfType(), VarManager::instance(), IS_LOSE, L_DBG, L_LOG, neg_winning_region_, CNF::negate(), VarInfo::PRES_STATE, propagateBlockedStates(), recBlockCube(), and winning_region_.
Referenced by run().
void IFM13Synth::debugCheckInvariants (size_t k) [protected]
A debugging utility check invariants of the data structures.
The checks are only performed in debug-mode. In release-mode, this function does nothing.
Parameters
k The maximum level up until which the invariants should be checked.
Definition at line 502 of file IFM13Synth.cpp.
References QBFSolver::A, CNF::addCNF(), CNF::clear(), VarInfo::CTRL, QBFSolver::E, getR(), Options::getSATSolver(), getU(), VarInfo::INPUT, Options::instance(), AIG2CNF::instance(), DepQBFApi::isSat(), SatSolver::isSat(), MASSERT, CNF::negate(), VarInfo::NEXT_STATE, VarInfo::PRES_STATE, CNF::swapPresentToNext(), VarInfo::TMP, and win_.
Referenced by computeWinningRegion().
void IFM13Synth::debugPrintRs () const [protected]
A debugging utility to print all frames.
Do this for small examples only.
Definition at line 492 of file IFM13Synth.cpp.
References L_DBG, and r_.
void IFM13Synth::genAndBlockTrans (const vector< int > & state_in_cube, const vector< int > & ctrl_cube, size_t level) [protected]
Generalizes and excludes a blocked transition.
Parameters
state_in_cube The state-input cube (the transition) that should be generalized and and blocked.
ctrl_cube The control signals that can be chosen by the protagonist in order to avoid ending up in R[level-1].
level The frame in which the transition should be blocked.
Returns
False if state_cube satisfies W, true otherwise.
Definition at line 422 of file IFM13Synth.cpp.
References addBlockedTransition(), getGenBlockTransSolver(), SatSolver::incIsSatModelOrCore(), and MASSERT.
Referenced by recBlockCube().
SatSolver * IFM13Synth::getGenBlockTransSolver (size_t index) [protected]
Returns a solver with CNF: T & R[index-1]'.
This solver is used to generalize blocked transitions. If the solver for this index does not yet exists, it is created.
Parameters
index The index of the requested solver.
Returns
A solver with CNF: T & R[index-1]'. getGenBlockTransSolver(0) returns NULL.
Definition at line 463 of file IFM13Synth.cpp.
References gen_block_trans_solvers_, Options::instance(), AIG2CNF::instance(), and sicn_.
Referenced by addBlockedState(), genAndBlockTrans(), and propagateBlockedStates().
SatSolver * IFM13Synth::getGotoNextLowerSolver (size_t index) [protected]
Returns a solver with CNF: U[index] & T & R[index-1]'.
This solver is used to search for moves the antagonist can make in order to reach R[index-1]. If the solver for this index does not yet exists, it is created.
Parameters
index The index of the requested solver.
Returns
A solver with CNF: U[index] & T & R[index-1]'. getGotoNextLowerSolver(0) returns NULL.
Definition at line 451 of file IFM13Synth.cpp.
References goto_next_lower_solvers_, Options::instance(), AIG2CNF::instance(), and sicn_.
Referenced by addBlockedState(), addBlockedTransition(), propagateBlockedStates(), and recBlockCube().
CNF & IFM13Synth::getR (size_t index) [protected]
Returns the frame R[index] in CNF.
If the frame with this index does not yet exists, it is created.
Parameters
index The index of the requested frame.
Returns
The frame R[index] in CNF.
Definition at line 435 of file IFM13Synth.cpp.
References r_.
Referenced by addBlockedState(), computeWinningRegion(), debugCheckInvariants(), isBlocked(), and propagateBlockedStates().
CNF & IFM13Synth::getU (size_t index) [protected]
Returns the blocked transitions U[index] in CNF.
If the set of blocked transitions with this index does not yet exists, it is created. This function is actually only needed for debugging purposes.
Parameters
index The index of the requested set of blocked transitions.
Returns
The set U[index] of blocked transitions in CNF.
Definition at line 443 of file IFM13Synth.cpp.
References u_.
Referenced by addBlockedTransition(), and debugCheckInvariants().
bool IFM13Synth::isBlocked (const vector< int > & state_cube, size_t level) [protected]
Checks if a state is contained in a certain frame.
The passed state cube is complete, i.e., contains all state variables. Hence, containment can be (and is) checked syntactically. We simply check if state_cube satisfies all clauses of R[level].
Parameters
state_cube A full cube over the present state variables.
level The index i of a certain frame R[i].
Returns
False if state_cube satisfies R[level], true otherwise.
Definition at line 399 of file IFM13Synth.cpp.
References getR(), and CNF::isSatBy().
Referenced by recBlockCube().
bool IFM13Synth::isLose (const vector< int > & state_cube) [protected]
Checks if a state satisfies the current over-approximation of the winning region.
The passed state cube is complete, i.e., contains all state variables. Hence, containment can be (and is) checked syntactically. We simply check if state_cube satisfies all clauses of W (stored in win_).
Parameters
state_cube A full cube over the present state variables.
Returns
False if state_cube satisfies W, true otherwise.
Definition at line 416 of file IFM13Synth.cpp.
References CNF::isSatBy(), and win_.
Referenced by recBlockCube().
IFM13Synth& IFM13Synth::operator= (const IFM13Synth & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
IFMProofObligation IFM13Synth::popMin (list< IFMProofObligation > & queue) [protected]
Takes a list of proof obligations and removes the element with lowest rank.
Parameters
queue A list of proof obligations.
Returns
The element that has been removed from the list. It is always the element (among the elements) with minimal rank.
Definition at line 475 of file IFM13Synth.cpp.
References MASSERT.
Referenced by recBlockCube().
size_t IFM13Synth::propagateBlockedStates (size_t max_level) [protected]
Propagates clauses forward and searches for equivalent clause sets.
Similar to IC3, this method propagates clauses of frames forward. It also checks if two adjacent clauses sets become syntactically equal.
Parameters
max_level The maximum frame level until which propagation should be performed.
Returns
The number N returned by this method has the following meaning: N=0 means that no equal clause sets have been found. N > 0 means that R[N] = R[N-1].
Definition at line 177 of file IFM13Synth.cpp.
References CNF::getClauses(), getGenBlockTransSolver(), getGotoNextLowerSolver(), getR(), SatSolver::incAddClause(), SatSolver::incIsSat(), CNF::removeDuplicates(), Utils::swapPresentToNext(), and CNF::swapWith().
Referenced by computeWinningRegion().
bool IFM13Synth::recBlockCube (const vector< int > & state_cube, size_t level) [protected]
Analyzes the rank of the passed state.
There are two possible conclusions: (a) the rank of the state is > level, (b) the rank of the state is <= level. In order to analyze a certain state, this method may analyze some of its successor states first (using a queue of proof obligations internally). This method is always called for the initial state only.
Parameters
state_cube A full cube over the state variables, describing the state that should be analyzed.
level The level for the analysis (this method checks if the rank of the state is > level or <= level).
Returns
IS_GREATER (an alias for true) if the rank of the state is > level. IS_LOSE (an alias for false) otherwise.
Definition at line 229 of file IFM13Synth.cpp.
References addBlockedState(), addLose(), Utils::containsInit(), VarInfo::CTRL, Utils::extract(), Utils::extractNextAsPresent(), Utils::extractPresIn(), genAndBlockTrans(), getGotoNextLowerSolver(), IFMProofObligation::getLevel(), IFMProofObligation::getPreCtrlCube(), IFMProofObligation::getPreStateInCube(), IFMProofObligation::getState(), goto_win_solver_, IFMProofObligation::hasPre(), SatSolver::incIsSatModelOrCore(), VarInfo::INPUT, IS_GREATER, IS_LOSE, isBlocked(), isLose(), popMin(), VarInfo::PRES_STATE, sicn_, and sin_.
Referenced by computeWinningRegion().
bool IFM13Synth::run () [virtual]
Executes the back-end (which is implemented as described in the IFM'13 paper).
This method is the workhorse of this class. It implements the SAT-based synthesis method published in the paper: `Andreas Morgenstern, Manuel Gesell, Klaus Schneider: Solving
Games Using Incremental Induction, IFM 2013, pages 177-191`. It is based on the description given in the paper with only a few additional optimizations following the paper `Niklas Een, Alan Mishchenko, Robert K. Brayton: Efficient implementation of
property directed reachability, FMCAD 2011, pages 125-134`. All these optimizations are clearly marked in the source code. In order to understand the code in this class, you should read the IFM'13 paper first. After that, you will find a one-to-one correspondence between the functions described in the paper and the methods of this class.
The IFM'13 publication only describes how to determine realizability, but not how extract a winning region from this computation. Our implementation also extracts a winning region (the set R[i] such that R[i] = R[i-1]).
Returns
True if the specification was realizable, false otherwise.
Implements BackEnd.
Definition at line 121 of file IFM13Synth.cpp.
References computeWinningRegion(), Utils::debugCheckWinReg(), CNFImplExtractor::extractCircuit(), impl_extractor_, Options::instance(), L_INF, L_RES, CNFImplExtractor::logStatistics(), neg_winning_region_, and winning_region_.
Member Data Documentation
vector<SatSolver*> IFM13Synth::gen_block_trans_solvers_ [protected]
The solvers storing the CNF: T & R[k-1]'.
You should use getGenBlockTransSolver() to access these solvers. The reason is that this method initializes the solvers if they do not yet exist. gen_block_trans_solvers_[0] is always NULL.
Definition at line 333 of file IFM13Synth.h.
Referenced by getGenBlockTransSolver(), IFM13Synth(), and ~IFM13Synth().
vector<SatSolver*> IFM13Synth::goto_next_lower_solvers_ [protected]
The solvers storing the CNF: U[k] & T & R[k-1]'.
These solvers are used to search for moves the antagonist can make in order to reach R[k-1]. You should use getGotoNextLowerSolver() to access these solvers. The reason is that this method initializes the solvers if they do not yet exist. goto_next_lower_solvers_[0] is always NULL.
Definition at line 324 of file IFM13Synth.h.
Referenced by getGotoNextLowerSolver(), IFM13Synth(), and ~IFM13Synth().
SatSolver* IFM13Synth::goto_win_solver_ [protected]
A solver that stores the CNF: T & W'.
Definition at line 338 of file IFM13Synth.h.
Referenced by addLose(), IFM13Synth(), recBlockCube(), and ~IFM13Synth().
CNFImplExtractor* IFM13Synth::impl_extractor_ [protected]
The engine to use for circuit extraction.
It will be deleted by this class (in the destructor).
Definition at line 365 of file IFM13Synth.h.
Referenced by run(), and ~IFM13Synth().
CNF IFM13Synth::neg_winning_region_ [protected]
The negated winning region as computed by computeWinningRegion.
Definition at line 348 of file IFM13Synth.h.
Referenced by computeWinningRegion(), and run().
vector<CNF> IFM13Synth::r_ [protected]
The frames R[] of the algorithm. Each frame represents a set of states in CNF.
You should use getR() to access the frames. The reason is that this method initializes frames if they do not yet exist.
Definition at line 298 of file IFM13Synth.h.
Referenced by addBlockedState(), debugPrintRs(), getR(), and IFM13Synth().
vector<int> IFM13Synth::sicn_ [protected]
The vector of present- and next-state variables, and all inputs.
Definition at line 358 of file IFM13Synth.h.
Referenced by getGenBlockTransSolver(), getGotoNextLowerSolver(), IFM13Synth(), and recBlockCube().
vector<int> IFM13Synth::sin_ [protected]
The vector of present- and next-state variables, and uncontrollable inputs.
Definition at line 353 of file IFM13Synth.h.
Referenced by IFM13Synth(), and recBlockCube().
vector<CNF> IFM13Synth::u_ [protected]
The blocked transitions U[] of the algorithm.
These sets are maintained only in debug mode. In release-mode they are only present inside the goto_next_lower_solvers_. You should use getU() to access the frames. The reason is that this method initializes elements if they do not yet exist.
Definition at line 308 of file IFM13Synth.h.
Referenced by getU(), and IFM13Synth().
CNF IFM13Synth::win_ [protected]
The current over-approximation of the winning region W (for the protagonist).
Definition at line 313 of file IFM13Synth.h.
Referenced by addLose(), debugCheckInvariants(), IFM13Synth(), and isLose().
CNF IFM13Synth::winning_region_ [protected]
The final winning region as computed by computeWinningRegion.
Definition at line 343 of file IFM13Synth.h.
Referenced by computeWinningRegion(), and run().
The documentation for this class was generated from the following files:
src/IFM13Synth.h
src/IFM13Synth.cpp