EPRSynthesizer Class Reference
Implements a synthesis method based on reduction to EPR.
#include <EPRSynthesizer.h>
Public Member Functions
EPRSynthesizer ()
Constructor.
virtual ~EPRSynthesizer ()
Destructor.
virtual bool run ()
Executes the back-end (constructs an EPR formula an passes it to iProver).
Protected Member Functions
void addClause (const string &clause, string comment=``)
A helper that adds a clause to the EPR formula in TPTP format.
unsigned neg (unsigned aig_lit)
A helper to negate an AIGER literal.
Protected Attributes
ostringstream tptp_query_
The EPR formula in TPTP format.
size_t next_clause_nr_
A monotonic counter to assign unique IDs to clauses.
string path_to_iprover_
The path to the iProver executable.
string in_file_name_
The name of the input file (containing the EPR formula) that is solved by iProver.
string out_file_name_
The name of the file containing the response from iProver.
Private Member Functions
EPRSynthesizer (const EPRSynthesizer &other)
Copy constructor.
EPRSynthesizer & operator= (const EPRSynthesizer &other)
Assignment operator.
Detailed Description
Implements a synthesis method based on reduction to EPR.
EPR (Effectively Propositional Logic) is a subset of first-order logic. EPR formulas are of the form exists A: forall B: F, where A and B are sets of domain variables, and F is a function-free formula in CNF. F can contain predicates over the variables of A and B. These predicates are implicitly existentially quantified.
This class creates the following EPR formula: forall x,i,x': (I(x) => W(x)) AND (W(x) => P(x)) AND (W(x) AND T(x,i,C(x,i),x') => W(x')) Here, x,i, and x' are actually domain variables (and not Boolean variables), but there is a one-to-one mapping. W is a fresh predicate over the state variables. It represents the winning region. C(x,i) is a set of predicates, one for each control signal. These predicates represent the implementation of the control signals. The challenging part in constructing this EPR formula is actually an efficient encoding of the transition relation T in EPR. In the AIGER representation (and also in the CNF representation) the transition relation T uses many temporary variables. The problem is that they are all quantified existentially, which means that they have to be skolemized with predicates to get a valid EPR formula. We analyze the structure of the AIGER graph in order to find out the minimal dependencies for all these predicates. This is supposed to increase the performance. Then the class uses iProver (http://www.cs.man.ac.uk/~korovink/iprover/) to solve the formula. iProver cannot only give a YES/No answer for the satisfiability question. It can also construct functions for the predicates. That is, iProver gives us the winning region together with implementations for all control signals. It solves the synthesis problem completely (and does not only compute a winning region).
Todo
Todo : At the moment we only construct the formula, and parse back the answer to the realizability question. Parsing back the implementation for the controllable signals remains to be done. (The iProver page promises to release a new version with more output formats soon.)
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.1.0
Definition at line 73 of file EPRSynthesizer.h.
Constructor & Destructor Documentation
EPRSynthesizer::EPRSynthesizer ()
Constructor.
Definition at line 41 of file EPRSynthesizer.cpp.
References Options::getTPDirName(), Options::getUniqueTmpFileName(), in_file_name_, Options::instance(), out_file_name_, and path_to_iprover_.
EPRSynthesizer::~EPRSynthesizer () [virtual]
Destructor.
Definition at line 49 of file EPRSynthesizer.cpp.
EPRSynthesizer::EPRSynthesizer (const EPRSynthesizer & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void EPRSynthesizer::addClause (const string & clause, string comment = ``) [protected]
A helper that adds a clause to the EPR formula in TPTP format.
The clause is assigned a unique ID, and is added to the tptp_query_ in a nicely formatted form, together with an optional comment.
Parameters
clause A string representation of the clause to add.
comment A comment (useful for debugging). This parameter is optional.
Definition at line 332 of file EPRSynthesizer.cpp.
References next_clause_nr_, and tptp_query_.
Referenced by run().
unsigned EPRSynthesizer::neg (unsigned aig_lit) [protected]
A helper to negate an AIGER literal.
Parameters
aig_lit An AIGER literal.
Returns
The negation of the passed AIGER literal.
Definition at line 344 of file EPRSynthesizer.cpp.
Referenced by run().
EPRSynthesizer& EPRSynthesizer::operator= (const EPRSynthesizer & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
bool EPRSynthesizer::run () [virtual]
Executes the back-end (constructs an EPR formula an passes it to iProver).
This method is the workhorse of this class. It constructs the following EPR formula in TPTP format: forall x,i,x': (I(x) => W(x)) AND (W(x) => P(x)) AND (W(x) AND T(x,i,C(x,i),x') => W(x')) Here, x,i, and x' are actually domain variables (and not Boolean variables), but there is a one-to-one mapping. W is a fresh predicate over the state variables. It represents the winning region. C(x,i) is a set of predicates, one for each control signal. These predicates represent the implementation of the control signals. The challenging part in constructing this EPR formula is actually an efficient encoding of the transition relation T in EPR. In the AIGER representation (and also in the CNF representation) the transition relation T uses many temporary variables. The problem is that they are all quantified existentially, which means that they have to be skolemized with predicates to get a valid EPR formula. We analyze the structure of the AIGER graph in order to find out the minimal dependencies for all these predicates. This is supposed to increase the performance. After constructing the EPR formula this method then calls iProver (http://www.cs.man.ac.uk/~korovink/iprover/) to solve it. iProver cannot only give a YES/No answer for the satisfiability question. It can also construct functions for the predicates. That is, iProver gives us the winning region together with implementations for all control signals. It solves the synthesis problem completely (and does not only compute a winning region).
Todo
Todo : At the moment we only construct the formula, and parse back the answer to the realizability question. Parsing back the implementation for the controllable signals remains to be done. (The iProver page promises to release a new version with more output formats soon.)
Returns
True if the specification was realizable, false otherwise.
Implements BackEnd.
Definition at line 55 of file EPRSynthesizer.cpp.
References addClause(), Options::getAigInFileName(), in_file_name_, Options::instance(), L_ERR, L_RES, MASSERT, neg(), out_file_name_, path_to_iprover_, FileUtils::readFile(), StringUtils::toLowerCase(), tptp_query_, and FileUtils::writeFile().
Member Data Documentation
string EPRSynthesizer::in_file_name_ [protected]
The name of the input file (containing the EPR formula) that is solved by iProver.
Definition at line 160 of file EPRSynthesizer.h.
Referenced by EPRSynthesizer(), and run().
size_t EPRSynthesizer::next_clause_nr_ [protected]
A monotonic counter to assign unique IDs to clauses.
Definition at line 150 of file EPRSynthesizer.h.
Referenced by addClause().
string EPRSynthesizer::out_file_name_ [protected]
The name of the file containing the response from iProver.
Definition at line 165 of file EPRSynthesizer.h.
Referenced by EPRSynthesizer(), and run().
string EPRSynthesizer::path_to_iprover_ [protected]
The path to the iProver executable.
Definition at line 155 of file EPRSynthesizer.h.
Referenced by EPRSynthesizer(), and run().
ostringstream EPRSynthesizer::tptp_query_ [protected]
The EPR formula in TPTP format.
Definition at line 145 of file EPRSynthesizer.h.
Referenced by addClause(), and run().
The documentation for this class was generated from the following files:
src/EPRSynthesizer.h
src/EPRSynthesizer.cpp