LearningExtractorStatistics Class Reference
A class to collect performance measures for the LearningImplExtractor.
#include <LearningExtractorStatistics.h>
Public Member Functions
LearningExtractorStatistics ()
Constructor.
virtual ~LearningExtractorStatistics ()
Destructor.
void notifyBeforeCtrlSignal ()
Called before the computation of the next control signal.
void notifyAfterCtrlSignal ()
Called after the computation of the next control signal is done.
void notifyBeforeClauseComp ()
Called before the computation of the next counterexample situation.
void notifyAfterClauseComp ()
Called after the computation of the next counterexample situation is done.
void notifyBeforeClauseMin ()
Called before the generalization of the next counterexample situation.
void notifyAfterClauseMin (size_t size_from, size_t size_to)
Called after the generalization of the next counterexample situation is done.
void notifyBeforeABC (size_t nr_of_and_gates)
Called before optimizing the resulting circuit with ABC.
void notifyAfterABC (size_t nr_of_and_gates)
Called after optimizing the resulting circuit with ABC is done.
void notifyFinalSize (size_t nr_of_new_and_gates)
Logs the number of new AND gates that have been added to the specification.
void logStatistics (bool include_details=true) const
Writes the statistics to stdout as messages of type Logger::LOG.
Protected Attributes
PointInTime abc_start_time_
The time when the circuit optimization with ABC was started.
double abc_cpu_time_
The time for optimizing the circuit with ABC in CPU-seconds.
size_t abc_real_time_
Like abc_cpu_time_ but real-time.
PointInTime clause_comp_start_time_
The time when the computation of a counterexample-situation was started.
PointInTime clause_min_start_time_
The time when the generalization of a counterexample-situation was started.
PointInTime ctrl_signal_start_time_
The time when the computation of the next control signal was started.
vector< size_t > nr_of_clause_computations_
The number of counterexample-situations that had to be computed per control signal.
vector< size_t > sum_clause_size_from_
The sum of the clause size before generalization per control signal.
vector< size_t > sum_clause_size_to_
The sum of the clause size after generalization per control signal.
vector< double > sum_clause_comp_cpu_time_
The total counterexample computation time per control signal.
vector< size_t > sum_clause_comp_real_time_
Like sum_clause_comp_cpu_time_ but real-time.
vector< double > sum_clause_min_cpu_time_
The total counterexample generalization time per control signal.
vector< size_t > sum_clause_min_real_time_
Like sum_clause_min_cpu_time_ but real-time.
vector< double > ctrl_signal_cpu_time_
The total time per control signal.
vector< size_t > ctrl_signal_real_time_
Like ctrl_signal_cpu_time_ but real-time.
size_t size_before_abc_
The circuit size before optimization with ABC.
size_t size_after_abc_
The circuit size after optimization with ABC.
size_t size_final_
The number of new AND gates that have been added to the specification.
Private Member Functions
LearningExtractorStatistics (const LearningExtractorStatistics &other)
Copy constructor.
LearningExtractorStatistics & operator= (const LearningExtractorStatistics &other)
Assignment operator.
Detailed Description
A class to collect performance measures for the LearningImplExtractor.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
This class collects statistics and performance data for the learning-based synthesis circuit extraction method implemented using QBF or SAT solving (implemented in the class LearningImplExtractor).
Definition at line 47 of file LearningExtractorStatistics.h.
Constructor & Destructor Documentation
LearningExtractorStatistics::LearningExtractorStatistics ()
Constructor.
Definition at line 35 of file LearningExtractorStatistics.cpp.
References VarInfo::CTRL, ctrl_signal_cpu_time_, ctrl_signal_real_time_, VarManager::getVarsOfType(), VarManager::instance(), nr_of_clause_computations_, sum_clause_comp_cpu_time_, sum_clause_comp_real_time_, sum_clause_min_cpu_time_, sum_clause_min_real_time_, sum_clause_size_from_, and sum_clause_size_to_.
LearningExtractorStatistics::~LearningExtractorStatistics () [virtual]
Destructor.
Definition at line 55 of file LearningExtractorStatistics.cpp.
LearningExtractorStatistics::LearningExtractorStatistics (const LearningExtractorStatistics & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
void LearningExtractorStatistics::logStatistics (bool include_details = true) const
Writes the statistics to stdout as messages of type Logger::LOG.
If messages of type Logger::LOG are disabled (see Logger), then nothing happens.
Parameters
include_details True if more detailed information should be printed, false if only basic statistics and performance measures should be printed. If this parameter is omitted, then detailed info will be printed.
Definition at line 131 of file LearningExtractorStatistics.cpp.
References abc_real_time_, ctrl_signal_cpu_time_, ctrl_signal_real_time_, L_LOG, nr_of_clause_computations_, size_after_abc_, size_before_abc_, size_final_, sum_clause_comp_cpu_time_, sum_clause_comp_real_time_, sum_clause_min_cpu_time_, sum_clause_min_real_time_, sum_clause_size_from_, and sum_clause_size_to_.
Referenced by LearningImplExtractor::logDetailedStatistics().
void LearningExtractorStatistics::notifyAfterABC (size_t nr_of_and_gates)
Called after optimizing the resulting circuit with ABC is done.
This method just reads out the Stopwatch and stores the execution time. It also logs the circuit size after optimization.
Parameters
nr_of_and_gates The number of AND gates in the AIGER circuit after optimization with ABC.
Definition at line 117 of file LearningExtractorStatistics.cpp.
References abc_cpu_time_, abc_real_time_, abc_start_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), and size_after_abc_.
Referenced by LearningImplExtractor::run(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void LearningExtractorStatistics::notifyAfterClauseComp ()
Called after the computation of the next counterexample situation is done.
This method just reads out the Stopwatch and stores the execution time.
Definition at line 87 of file LearningExtractorStatistics.cpp.
References clause_comp_start_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), nr_of_clause_computations_, sum_clause_comp_cpu_time_, and sum_clause_comp_real_time_.
Referenced by LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), LearningImplExtractor::runLearningQBF(), LearningImplExtractor::runLearningQBFInc(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void LearningExtractorStatistics::notifyAfterClauseMin (size_t size_from, size_t size_to)
Called after the generalization of the next counterexample situation is done.
This method just reads out the Stopwatch and stores the execution time. It also logs the reduction of the clause size.
Parameters
size_from The size of the clause before the generalization.
size_to The size of the clause after the generalization.
Definition at line 101 of file LearningExtractorStatistics.cpp.
References clause_min_start_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), sum_clause_min_cpu_time_, sum_clause_min_real_time_, sum_clause_size_from_, and sum_clause_size_to_.
Referenced by LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), LearningImplExtractor::runLearningQBF(), LearningImplExtractor::runLearningQBFInc(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void LearningExtractorStatistics::notifyAfterCtrlSignal ()
Called after the computation of the next control signal is done.
This method just reads out the Stopwatch and stores the execution time.
Definition at line 74 of file LearningExtractorStatistics.cpp.
References ctrl_signal_cpu_time_, ctrl_signal_real_time_, ctrl_signal_start_time_, Stopwatch::getCPUTimeSec(), and Stopwatch::getRealTimeSec().
Referenced by LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), LearningImplExtractor::runLearningQBF(), LearningImplExtractor::runLearningQBFInc(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void LearningExtractorStatistics::notifyBeforeABC (size_t nr_of_and_gates)
Called before optimizing the resulting circuit with ABC.
This method just starts a Stopwatch and logs the circuit size before optimization.
Parameters
nr_of_and_gates The number of AND gates in the AIGER circuit before optimization with ABC.
Definition at line 110 of file LearningExtractorStatistics.cpp.
References abc_start_time_, size_before_abc_, and Stopwatch::start().
Referenced by LearningImplExtractor::run(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void LearningExtractorStatistics::notifyBeforeClauseComp ()
Called before the computation of the next counterexample situation.
This method just starts a Stopwatch.
Definition at line 81 of file LearningExtractorStatistics.cpp.
References clause_comp_start_time_, and Stopwatch::start().
Referenced by LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), LearningImplExtractor::runLearningQBF(), LearningImplExtractor::runLearningQBFInc(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void LearningExtractorStatistics::notifyBeforeClauseMin ()
Called before the generalization of the next counterexample situation.
This method just starts a Stopwatch.
Definition at line 95 of file LearningExtractorStatistics.cpp.
References clause_min_start_time_, and Stopwatch::start().
Referenced by LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), LearningImplExtractor::runLearningQBF(), LearningImplExtractor::runLearningQBFInc(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void LearningExtractorStatistics::notifyBeforeCtrlSignal ()
Called before the computation of the next control signal.
This method just starts a Stopwatch.
Definition at line 61 of file LearningExtractorStatistics.cpp.
References ctrl_signal_start_time_, nr_of_clause_computations_, Stopwatch::start(), sum_clause_comp_cpu_time_, sum_clause_comp_real_time_, sum_clause_min_cpu_time_, sum_clause_min_real_time_, sum_clause_size_from_, and sum_clause_size_to_.
Referenced by LearningImplExtractor::runLearningExp(), LearningImplExtractor::runLearningJiangSAT(), LearningImplExtractor::runLearningJiangSATInc1(), LearningImplExtractor::runLearningJiangSATInc2(), LearningImplExtractor::runLearningJiangSATTmp(), LearningImplExtractor::runLearningJiangSATTmpCtrl(), LearningImplExtractor::runLearningJiangSATTmpCtrlInc2(), LearningImplExtractor::runLearningQBF(), LearningImplExtractor::runLearningQBFInc(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void LearningExtractorStatistics::notifyFinalSize (size_t nr_of_new_and_gates)
Logs the number of new AND gates that have been added to the specification.
Parameters
nr_of_new_and_gates The number of new AND gates that have been added to the specification.
Definition at line 125 of file LearningExtractorStatistics.cpp.
References size_final_.
Referenced by LearningImplExtractor::run().
LearningExtractorStatistics& LearningExtractorStatistics::operator= (const LearningExtractorStatistics & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
Member Data Documentation
double LearningExtractorStatistics::abc_cpu_time_ [protected]
The time for optimizing the circuit with ABC in CPU-seconds.
Definition at line 157 of file LearningExtractorStatistics.h.
Referenced by notifyAfterABC().
size_t LearningExtractorStatistics::abc_real_time_ [protected]
Like abc_cpu_time_ but real-time.
Definition at line 162 of file LearningExtractorStatistics.h.
Referenced by logStatistics(), and notifyAfterABC().
PointInTime LearningExtractorStatistics::abc_start_time_ [protected]
The time when the circuit optimization with ABC was started.
Definition at line 152 of file LearningExtractorStatistics.h.
Referenced by notifyAfterABC(), and notifyBeforeABC().
PointInTime LearningExtractorStatistics::clause_comp_start_time_ [protected]
The time when the computation of a counterexample-situation was started.
Definition at line 167 of file LearningExtractorStatistics.h.
Referenced by notifyAfterClauseComp(), and notifyBeforeClauseComp().
PointInTime LearningExtractorStatistics::clause_min_start_time_ [protected]
The time when the generalization of a counterexample-situation was started.
Definition at line 172 of file LearningExtractorStatistics.h.
Referenced by notifyAfterClauseMin(), and notifyBeforeClauseMin().
vector<double> LearningExtractorStatistics::ctrl_signal_cpu_time_ [protected]
The total time per control signal.
ctrl_signal_cpu_time_[i] contains the total time for computing the output function of control signal i. This should be roughly sum_clause_comp_cpu_time_[i] + sum_clause_min_cpu_time_[i].
Definition at line 238 of file LearningExtractorStatistics.h.
Referenced by LearningExtractorStatistics(), logStatistics(), and notifyAfterCtrlSignal().
vector<size_t> LearningExtractorStatistics::ctrl_signal_real_time_ [protected]
Like ctrl_signal_cpu_time_ but real-time.
Definition at line 243 of file LearningExtractorStatistics.h.
Referenced by LearningExtractorStatistics(), logStatistics(), and notifyAfterCtrlSignal().
PointInTime LearningExtractorStatistics::ctrl_signal_start_time_ [protected]
The time when the computation of the next control signal was started.
Definition at line 177 of file LearningExtractorStatistics.h.
Referenced by notifyAfterCtrlSignal(), and notifyBeforeCtrlSignal().
vector<size_t> LearningExtractorStatistics::nr_of_clause_computations_ [protected]
The number of counterexample-situations that had to be computed per control signal.
nr_of_clause_computations_[i] contains the number of counterexample-situations that had to be computed during the computation of an output function for control signal i.
Definition at line 185 of file LearningExtractorStatistics.h.
Referenced by LearningExtractorStatistics(), logStatistics(), notifyAfterClauseComp(), and notifyBeforeCtrlSignal().
size_t LearningExtractorStatistics::size_after_abc_ [protected]
The circuit size after optimization with ABC.
Definition at line 253 of file LearningExtractorStatistics.h.
Referenced by logStatistics(), and notifyAfterABC().
size_t LearningExtractorStatistics::size_before_abc_ [protected]
The circuit size before optimization with ABC.
Definition at line 248 of file LearningExtractorStatistics.h.
Referenced by logStatistics(), and notifyBeforeABC().
size_t LearningExtractorStatistics::size_final_ [protected]
The number of new AND gates that have been added to the specification.
Definition at line 258 of file LearningExtractorStatistics.h.
Referenced by logStatistics(), and notifyFinalSize().
vector<double> LearningExtractorStatistics::sum_clause_comp_cpu_time_ [protected]
The total counterexample computation time per control signal.
sum_clause_comp_cpu_time_[i] contains the total counterexample computation time for control signal i.
Definition at line 211 of file LearningExtractorStatistics.h.
Referenced by LearningExtractorStatistics(), logStatistics(), notifyAfterClauseComp(), and notifyBeforeCtrlSignal().
vector<size_t> LearningExtractorStatistics::sum_clause_comp_real_time_ [protected]
Like sum_clause_comp_cpu_time_ but real-time.
Definition at line 216 of file LearningExtractorStatistics.h.
Referenced by LearningExtractorStatistics(), logStatistics(), notifyAfterClauseComp(), and notifyBeforeCtrlSignal().
vector<double> LearningExtractorStatistics::sum_clause_min_cpu_time_ [protected]
The total counterexample generalization time per control signal.
sum_clause_min_cpu_time_[i] contains the total counterexample minimization time for control signal i.
Definition at line 224 of file LearningExtractorStatistics.h.
Referenced by LearningExtractorStatistics(), logStatistics(), notifyAfterClauseMin(), and notifyBeforeCtrlSignal().
vector<size_t> LearningExtractorStatistics::sum_clause_min_real_time_ [protected]
Like sum_clause_min_cpu_time_ but real-time.
Definition at line 229 of file LearningExtractorStatistics.h.
Referenced by LearningExtractorStatistics(), logStatistics(), notifyAfterClauseMin(), and notifyBeforeCtrlSignal().
vector<size_t> LearningExtractorStatistics::sum_clause_size_from_ [protected]
The sum of the clause size before generalization per control signal.
sum_clause_size_from_[i] contains the sum of the clause sizes before generalization that had to be computed during the computation of an output function for control signal i.
Definition at line 194 of file LearningExtractorStatistics.h.
Referenced by LearningExtractorStatistics(), logStatistics(), notifyAfterClauseMin(), and notifyBeforeCtrlSignal().
vector<size_t> LearningExtractorStatistics::sum_clause_size_to_ [protected]
The sum of the clause size after generalization per control signal.
sum_clause_size_to_[i] contains the sum of the clause sizes after generalization that had to be computed during the computation of an output function for control signal i.
Definition at line 203 of file LearningExtractorStatistics.h.
Referenced by LearningExtractorStatistics(), logStatistics(), notifyAfterClauseMin(), and notifyBeforeCtrlSignal().
The documentation for this class was generated from the following files:
src/LearningExtractorStatistics.h
src/LearningExtractorStatistics.cpp