ParExtractor Class Reference
A parallelized version of the LearningImplExtractor.
#include <ParExtractor.h>
Public Member Functions
ParExtractor (size_t nr_of_threads)
Constructor.
virtual ~ParExtractor ()
Destructor.
virtual void run (const CNF &winning_region, const CNF &neg_winning_region)
Runs this circuit extractor.
bool allWaiting ()
Returns true if all worker threads are done and waiting for others to finish.
void killThemAll ()
Gives all worker threads the command to terminate.
virtual void extractCircuit (const CNF &winning_region)
Extracts a circuit from the winning region.
virtual void extractCircuit (const CNF &winning_region, const CNF &neg_winning_region)
Extracts a circuit from the winning region and its negation.
virtual void logStatistics ()
Logs statistical information about circuit extraction.
Static Public Member Functions
static aiger * optimizeWithABC (aiger *circuit)
Optimizes a combinatorial AIGER circuit with ABC.
Public Attributes
volatile int extr_command_
An integer number encoding the current command to the circuit extractor workers.
Protected Member Functions
void logDetailedStatistics ()
Logs the detailed statistics collected by the fastest worker.
size_t insertIntoSpec (aiger *standalone_circuit) const
Takes a circuit defining the control signals and inserts it into the spec.
Protected Attributes
size_t nr_of_threads_
The number of threads to instantiate and execute.
size_t nr_of_new_ands_
The final number of new AND gates (just for the statistics).
vector< ParExtractorWorker * > extractors_
The worker threads.
vector< pthread_t > extractor_pthreads_
A set of pthread objects we may have to kill if they do not terminate.
double extraction_cpu_time_
The circuit extraction time in CPU-seconds.
size_t extraction_real_time_
Like extraction_cpu_time_ but real-time.
Private Member Functions
ParExtractor (const ParExtractor &other)
Copy constructor.
ParExtractor & operator= (const ParExtractor &other)
Assignment operator.
Detailed Description
A parallelized version of the LearningImplExtractor.
This class implements a parallelized version of the LearningImplExtractor. Take a look at the comments in the LearningImplExtractor to see what it does. The parallelization is very simple at this point. It is merely a portfolio parallelization where different methods run in different threads. Closer interaction is left for future work.
Author
Robert Koenighofer (robert.koenighofer@iaik.tugraz.at)
Version
1.2.0
Definition at line 55 of file ParExtractor.h.
Constructor & Destructor Documentation
ParExtractor::ParExtractor (size_t nr_of_threads)
Constructor.
Parameters
nr_of_threads The number of threads to create. This does not have to be the number of cores in your CPU. It can also make sense to combine several methods running in several threads on one single core. The methods can complement each other and achieve a speedup compared to one single method in isolation.
Definition at line 61 of file ParExtractor.cpp.
ParExtractor::~ParExtractor () [virtual]
Destructor.
Definition at line 70 of file ParExtractor.cpp.
References extractors_.
ParExtractor::ParExtractor (const ParExtractor & other) [private]
Copy constructor.
The copy constructor is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Member Function Documentation
bool ParExtractor::allWaiting ()
Returns true if all worker threads are done and waiting for others to finish.
Returns
True if all worker threads are done and waiting for others to finish.
Definition at line 153 of file ParExtractor.cpp.
References extractors_.
Referenced by ParExtractorWorker::waitForOthersToFinish().
void CNFImplExtractor::extractCircuit (const CNF & winning_region) [virtual], [inherited]
Extracts a circuit from the winning region.
How this is done (interpolation, learning, etc.) depends on the concrete implementation of this abstract class. The result is written into the output file specified by the user.
Parameters
winning_region The winning region from which the circuit should be extracted. For circuit extraction we need both the winning region and its negation. The negation is computed inside this function. If you already have a negation, use the other circuit extraction method of this class.
Reimplemented in StoreImplExtractor.
Definition at line 85 of file CNFImplExtractor.cpp.
References Utils::compressStateCNF(), CNFImplExtractor::extraction_cpu_time_, CNFImplExtractor::extraction_real_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), CNF::negate(), CNFImplExtractor::run(), and Stopwatch::start().
Referenced by LoadSynth::run(), LearnSynthQBFInc::run(), TemplateSynth::run(), IFM13Synth::run(), LearnSynthQBF::run(), LearnSynthSAT::run(), LearnSynthQBFInd::run(), and ParallelLearner::run().
void CNFImplExtractor::extractCircuit (const CNF & winning_region, const CNF & neg_winning_region) [virtual], [inherited]
Extracts a circuit from the winning region and its negation.
How this is done (interpolation, learning, etc.) depends on the concrete implementation of this abstract class. The result is written into the output file specified by the user.
Parameters
winning_region The winning region from which the circuit should be extracted.
neg_winning_region The negation of the winning region.
Definition at line 102 of file CNFImplExtractor.cpp.
References CNFImplExtractor::extraction_cpu_time_, CNFImplExtractor::extraction_real_time_, Stopwatch::getCPUTimeSec(), Stopwatch::getRealTimeSec(), CNFImplExtractor::run(), and Stopwatch::start().
size_t CNFImplExtractor::insertIntoSpec (aiger * standalone_circuit) const [protected], [inherited]
Takes a circuit defining the control signals and inserts it into the spec.
This method takes as argument an aiger circuit of the following form:
The circuit is combinational, i.e., has no latches.
The inputs of the circuit are: the uncontrollable inputs from the spec (in the order in which they appear in the spec) followed by the state-signals (the output of the latches in the spec, in the order in which they appear in the spec).
The outputs of the circuit are the controllable inputs in the order in which they are defined in the spec.
Parameters
standalone_circuit A circuit defining the control signals.
Returns
The number of additional AND gates introduced into the spec.
Definition at line 149 of file CNFImplExtractor.cpp.
References VarInfo::CTRL, Options::getAigInFileName(), Options::getAigOutFileName(), VarManager::getInfo(), VarInfo::getLitInAIG(), VarManager::getMaxAIGVar(), VarManager::getPresErrorStateVar(), VarManager::getVarsOfType(), VarInfo::INPUT, VarManager::instance(), Options::instance(), MASSERT, VarInfo::PRES_STATE, and StringUtils::toLowerCaseIn().
Referenced by run(), LearningImplExtractor::run(), and QBFCertImplExtractor::run().
void ParExtractor::killThemAll ()
Gives all worker threads the command to terminate.
Definition at line 138 of file ParExtractor.cpp.
References extr_command_, EXTR_STOP, and extractor_pthreads_.
Referenced by ParExtractorWorker::waitForOthersToFinish().
void ParExtractor::logDetailedStatistics () [protected], [virtual]
Logs the detailed statistics collected by the fastest worker.
Reimplemented from CNFImplExtractor.
Definition at line 165 of file ParExtractor.cpp.
References extractors_, L_LOG, and nr_of_new_ands_.
void CNFImplExtractor::logStatistics () [virtual], [inherited]
Logs statistical information about circuit extraction.
This method logs the overall execution time plus whatever detailed information is collected by the concrete implementation of this class.
Definition at line 290 of file CNFImplExtractor.cpp.
References CNFImplExtractor::extraction_cpu_time_, CNFImplExtractor::extraction_real_time_, L_LOG, and CNFImplExtractor::logDetailedStatistics().
Referenced by LoadSynth::run(), LearnSynthQBFInc::run(), TemplateSynth::run(), IFM13Synth::run(), LearnSynthQBF::run(), LearnSynthSAT::run(), LearnSynthQBFInd::run(), and ParallelLearner::run().
ParExtractor& ParExtractor::operator= (const ParExtractor & other) [private]
Assignment operator.
The assignment operator is disabled (set private) and not implemented.
Parameters
other The source for creating the copy.
Returns
The result of the assignment, i.e, *this.
aiger * CNFImplExtractor::optimizeWithABC (aiger * circuit) [static], [inherited]
Optimizes a combinatorial AIGER circuit with ABC.
Note
The returned structure must be deleted by the caller.
Parameters
circuit The circuit to optimize.
Returns
The optimized version of the circuit. The returned aiger structure must be deleted by the caller.
Definition at line 112 of file CNFImplExtractor.cpp.
References Options::getTPDirName(), Options::getUniqueTmpFileName(), Options::instance(), and MASSERT.
Referenced by LearningImplExtractor::run(), QBFCertImplExtractor::run(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), and ParExtractorWorker::runSATDep().
void ParExtractor::run (const CNF & winning_region, const CNF & neg_winning_region) [virtual]
Runs this circuit extractor.
Parameters
winning_region The winning region from which the circuit should be extracted.
neg_winning_region The negation of the winning region.
Implements CNFImplExtractor.
Definition at line 84 of file ParExtractor.cpp.
References extractor_pthreads_, extractors_, CNFImplExtractor::insertIntoSpec(), MASSERT, nr_of_new_ands_, nr_of_threads_, ParExtractorWorker::runSAT(), and ParExtractorQBFWorker::startQBF().
Member Data Documentation
volatile int ParExtractor::extr_command_
An integer number encoding the current command to the circuit extractor workers.
There are two possible value.
EXTR_GO = 0: means that the circuit extractor threads should continue.
EXTR_STOP = 1: means that the circuit extractor threads should stop.
All worker-threads poll this flag from time to time. If the value is still EXTR_GO they continue to work. If they see that the values is EXTR_STOP they stop, assuming that some other thread has already found the solution. If one thread finds a solution, it sets this flag to EXTR_STOP.
Definition at line 108 of file ParExtractor.h.
Referenced by killThemAll(), ParExtractorQBFWorker::runQBF(), ParExtractorWorker::runSAT(), ParExtractorWorker::runSATDep(), and ParExtractorWorker::waitForOthersToFinish().
double CNFImplExtractor::extraction_cpu_time_ [protected], [inherited]
The circuit extraction time in CPU-seconds.
Definition at line 145 of file CNFImplExtractor.h.
Referenced by CNFImplExtractor::extractCircuit(), and CNFImplExtractor::logStatistics().
size_t CNFImplExtractor::extraction_real_time_ [protected], [inherited]
Like extraction_cpu_time_ but real-time.
Definition at line 150 of file CNFImplExtractor.h.
Referenced by CNFImplExtractor::extractCircuit(), and CNFImplExtractor::logStatistics().
vector<pthread_t> ParExtractor::extractor_pthreads_ [protected]
A set of pthread objects we may have to kill if they do not terminate.
Definition at line 135 of file ParExtractor.h.
Referenced by killThemAll(), and run().
vector<ParExtractorWorker*> ParExtractor::extractors_ [protected]
The worker threads.
Definition at line 130 of file ParExtractor.h.
Referenced by allWaiting(), logDetailedStatistics(), run(), and ~ParExtractor().
size_t ParExtractor::nr_of_new_ands_ [protected]
The final number of new AND gates (just for the statistics).
Definition at line 125 of file ParExtractor.h.
Referenced by logDetailedStatistics(), and run().
size_t ParExtractor::nr_of_threads_ [protected]
The number of threads to instantiate and execute.
Definition at line 120 of file ParExtractor.h.
Referenced by run().
The documentation for this class was generated from the following files:
src/ParExtractor.h
src/ParExtractor.cpp