src/MiniSatApi.cpp File Reference
Contains the definition of the class MiniSatApi.
#include `MiniSatApi.h`
*
#include `core/Solver.h`
*
#include `Utils.h`
*
#include `CNF.h`
*
Functions
Lit c2m (Solver &s, int lit)
Transforms a CNF literal to the corresponding literal used by MiniSat.
int m2c (Lit lit)
void randModel (Solver &solver, const vec< Lit > &assumptions, vector< int > &model)
A helper to randomize a satisfying assignment after it has been computed.
Detailed Description
Contains the definition of the class MiniSatApi.
Definition in file MiniSatApi.cpp.
Function Documentation
Lit c2m (Solver & s, int lit) [inline]
Transforms a CNF literal to the corresponding literal used by MiniSat.
In our CNF we use -7 to denote the negation of the literal 7. MiniSat toggles the least significant bit to encode negation. Hence we need utility functions to transform literals between the two notations. This function is the inverse function of m2c().
Parameters
s The solver instance in which the literal should be used.
lit The CNF literal to transform into the corresponding literal used by MiniSat.
Returns
The corresponding literal used by MiniSat.
Definition at line 61 of file MiniSatApi.cpp.
Referenced by MiniSatApi::incAdd2LitClause(), MiniSatApi::incAdd3LitClause(), MiniSatApi::incAddClause(), MiniSatApi::incAddCNF(), MiniSatApi::incAddCube(), MiniSatApi::incAddNegCubeAsClause(), MiniSatApi::incAddUnitClause(), MiniSatApi::incIsSat(), MiniSatApi::incIsSatModelOrCore(), MiniSatApi::incPush(), MiniSatApi::isSat(), MiniSatApi::isSatModelOrCore(), and randModel().
int m2c (Lit lit) [inline]
In our CNF we use -7 to denote the negation of the literal 7. MiniSat toggles the least significant bit to encode negation. Hence we need utility functions to transform literals between the two notations. This function is the inverse function of c2m().
Parameters
lit The MiniSat literal to transform.
Returns
The corresponding CNF-literal.
Definition at line 83 of file MiniSatApi.cpp.
Referenced by MiniSatApi::incIsSatModelOrCore(), and MiniSatApi::isSatModelOrCore().
void randModel (Solver & solver, const vec< Lit > & assumptions, vector< int > & model)
A helper to randomize a satisfying assignment after it has been computed.
This is done by flipping values of variables randomly and then checking if the modified assignment is still satisfies the formula. This is expensive. However, changing the decision heuristic to a random one seems even more expensive in first experiments. This method is not declared in the header file because this would require to include all the MiniSat internals in the header file.
Parameters
solver The solver containing the CNF for which the satisfying assignment has been computed.
assumptions Additional assumptions under which the CNF should be solved. This can be an empty vector if there are no assumptions.
model The satisfying assignment that has been found and should now be randomized. It will be modified in place, i.e., this vector will contain the randomized model after this method is done.
Definition at line 108 of file MiniSatApi.cpp.
References c2m().
Referenced by MiniSatApi::incIsSatModelOrCore(), and MiniSatApi::isSatModelOrCore().